import {privatePageTitleIntentSchema,privatePageTitlePreparedSchema,privatePageTitleLocalRequestSchema,privatePageTitleLocalResponseSchema,privatePageRenameRequestSchema,privatePageRenameResponseSchema,privatePageMetadataReadRequestSchema,privatePageMetadataReadResponseSchema,type PrivatePageTitlePrepared} from '@greiva/protocol/private-page-metadata';
import {NativeWorkspaceError,type NativeWorkspaceStore} from './native-workspace-store.js';
function immutable<T>(value:T):T{if(value&&typeof value==='object'){for(const child of Object.values(value))immutable(child);Object.freeze(value);}return value;}
// Captured native repository only; network/metadata synchronization is composed
// separately. A local snapshot is never a server sync receipt.
export class NativeWorkspaceTitle {
  constructor(private readonly store:NativeWorkspaceStore,readonly pageId:string){}
  private protocol<T>(work:()=>T):T{this.store.assertActive();try{return work();}catch{this.store.assertActive();throw new NativeWorkspaceError('protocol');}}
  private binding(value:{workspaceId:string;workspaceEpoch:string;pageId:string}){if(value.workspaceId!==this.store.context.workspaceId||value.workspaceEpoch!==this.store.context.streamEpoch||value.pageId!==this.pageId)throw Error();}
  private prepared(candidate:unknown){const value=privatePageTitlePreparedSchema.parse(candidate),request=privatePageRenameRequestSchema.parse(JSON.parse(value.wire));if(value.pageId!==this.pageId||request.clientId!==this.store.context.clientId||request.operationId!==value.operationId)throw Error();return value;}
  async enqueue(candidate:unknown):Promise<void>{const intent=this.protocol(()=>privatePageTitleIntentSchema.parse(candidate));await this.store.pageCommand(this.pageId,'title_enqueue',{intent});}
  async prepare():Promise<PrivatePageTitlePrepared|null>{const value=await this.store.pageCommand(this.pageId,'title_prepare');return this.protocol(()=>value===null?null:immutable(this.prepared(value)));}
  async load(candidate:unknown={}){const request=this.protocol(()=>privatePageTitleLocalRequestSchema.parse(candidate)),value=await this.store.pageCommand(this.pageId,'title_load',request);
    return this.protocol(()=>{const snapshot=privatePageTitleLocalResponseSchema.parse(value);if(snapshot.pageId!==this.pageId||Object.entries(this.store.context).some(([key,value])=>snapshot.context[key as keyof typeof snapshot.context]!==value)||snapshot.operations.length>request.limit||snapshot.conflicts.length>request.limit||snapshot.operations.some(entry=>request.afterOperation!==null&&BigInt(entry.sequence)<=BigInt(request.afterOperation))||snapshot.conflicts.some(entry=>request.afterConflict!==null&&entry.record.id<=request.afterConflict))throw Error();for(const entry of snapshot.operations)if(entry.wire!==null){const wire=privatePageRenameRequestSchema.parse(JSON.parse(entry.wire));if(wire.clientId!==this.store.context.clientId||wire.operationId!==entry.intent.operationId||wire.title!==entry.intent.title)throw Error();}return immutable(snapshot);});
  }
  async acknowledge(candidate:unknown,candidateResponse:unknown):Promise<void>{const {prepared,response}=this.protocol(()=>{const prepared=this.prepared(candidate),response=privatePageRenameResponseSchema.parse(candidateResponse);this.binding(response);if(response.operationId!==prepared.operationId)throw Error();return{prepared,response};});await this.store.pageCommand(this.pageId,'title_ack',{sequence:prepared.sequence,wire:prepared.wire,response});}
  async receive(candidateRequest:unknown,candidateResponse:unknown):Promise<void>{const {request,response}=this.protocol(()=>{const request=privatePageMetadataReadRequestSchema.parse(candidateRequest),response=privatePageMetadataReadResponseSchema.parse(candidateResponse);this.binding(response);if(request.clientId!==this.store.context.clientId||response.conflicts.length>request.limit||response.conflicts.some(entry=>request.afterConflict!==null&&entry.id<=request.afterConflict))throw Error();return{request,response};});await this.store.pageCommand(this.pageId,'title_receive',{request,response});}
}
