import {privateDatabaseViewWriteRequestSchema,privateDatabaseViewWriteResponseSchema,privateDatabaseViewIntentSchema,privateDatabaseViewEnqueuedSchema,privateDatabaseViewPreparedSchema,privateDatabaseViewBlockedSchema,privateDatabaseViewQueueRequestSchema,privateDatabaseViewQueueSchema} from '@greiva/protocol/private-database-view';
import {privateDatabaseRecordUpdateIntentSchema,privateDatabaseRecordUpdatePreparedSchema,privateDatabaseRecordUpdateEnqueuedSchema,privateDatabaseRecordUpdateQueueRequestSchema,privateDatabaseRecordUpdateQueueSchema,privateDatabaseRecordCreateIntentSchema,privateDatabaseRecordCreatePreparedSchema,privateDatabaseRecordCreateBlockedSchema,privateDatabaseRecordCreateQueueRequestSchema,privateDatabaseRecordCreateQueueSchema,privateDatabaseRecordWriteResponseSchema,privateDatabaseRecordWriteRequestSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseSourceIntentSchema,privateDatabaseSourcePreparedSchema,privateDatabaseSourceQueueRequestSchema,privateDatabaseSourceQueueSchema,privateDatabaseSourceCreateRequestSchema,privateDatabaseSourceCreateResponseSchema} from '@greiva/protocol/private-database-source';
import {privateDatabaseChangesRequestSchema,parsePrivateDatabaseChangesResponse,privateDatabaseChangesLocalProgressSchema} from '@greiva/protocol/private-database-changes';
import {idSchema} from '@greiva/shared';
import {parseDatabaseRecord,parseDatabaseRecordConflict,parseDatabaseViewSnapshot,parseDatabaseViewConflict} from '@greiva/domain';
import {privateDatabaseViewReadRequestSchema,privateDatabaseViewReadResponseSchema,privateDatabaseViewLocalLoadRequestSchema,privateDatabaseViewLocalLoadSchema,privateDatabaseViewLocalListRequestSchema,privateDatabaseViewLocalListSchema} from '@greiva/protocol/private-database-view';
import {privateDatabaseRecordReadRequestSchema,privateDatabaseRecordReadResponseSchema,privateDatabaseRecordLocalLoadRequestSchema,privateDatabaseRecordLocalLoadSchema,privateDatabaseRecordLocalListRequestSchema,privateDatabaseRecordLocalListSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseSourceReadRequestSchema,privateDatabaseSourceReadResponseSchema,privateDatabaseSourceLocalLoadSchema,privateDatabaseSourceLocalListSchema,privateDatabaseSourceLocalListRequestSchema} from '@greiva/protocol/private-database-source';
import {NativeWorkspaceTitle} from './native-workspace-title.js';
import {parseOperationPayload,pushOperationSchema,taskSchema,relationSchema} from '@greiva/protocol';
import {workspaceStructuredSnapshotSchema} from '@greiva/protocol/workspace';
import {privateLocalPageCatalogRequestSchema,privateLocalPageCatalogResponseSchema} from '@greiva/protocol/private-page-catalog';
import {privatePageChangesLocalRequestSchema,privatePageChangesLocalResponseSchema,privatePageChangesRequestSchema,privatePageChangesResponseSchema} from '@greiva/protocol/private-page-changes';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {workspaceLocalHandleSchema,workspaceLocalContextSchema,type WorkspacePushRequest,type WorkspacePullResponse,verifyWorkspacePushResponse} from '@greiva/protocol/workspace';
import {privatePageLocalLoadSchema,privatePagePreparedSchema,privatePageBootstrapRequestSchema,privatePageAppendRequestSchema,type PrivatePagePrepared,type PrivatePageReadRequest,type PrivatePageReadResponse} from '@greiva/protocol/private-page';
import {pageBase64,pageUpdateBytes,type PrivateWorkspaceConnection,type WorkspaceSyncContext,type WorkspaceSessionStore,type PageSessionStore,type PageSyncContext,type PageReceipt} from '@greiva/sync';
export type NativeWorkspaceInvoke=(command:string,args?:Record<string,unknown>)=>Promise<unknown>;
export class NativeWorkspaceError extends Error {
  constructor(readonly stage:'configuration'|'closed'|'protocol'|'storage'){super(`Native workspace ${stage}`);this.name='NativeWorkspaceError';}
}
function same(one:WorkspaceSyncContext,two:WorkspaceSyncContext){return Object.entries(one).every(([key,value])=>two[key as keyof WorkspaceSyncContext]===value);}
function immutable<T>(value:T):T{if(value&&typeof value==='object'){Object.freeze(value);for(const child of Object.values(value))immutable(child);}return value;}
// Fixed app-owned paths and local handles are repository binding, not a native
// JWT grant. This adapter requires the trusted verified connection composition;
// no Web fallback, credential disk writes or offline grant is introduced.
export class NativeWorkspaceStore implements WorkspaceSessionStore {
  readonly context:WorkspaceSyncContext;
  private closed=false;private closeWork:Promise<void>|null=null;
  private databaseSessions=new Set<{close():void;signal:AbortSignal}>();
  private constructor(private readonly connection:PrivateWorkspaceConnection,private readonly handle:string,context:WorkspaceSyncContext,private readonly lease:AbortSignal,private readonly invokePort:NativeWorkspaceInvoke){this.context=Object.freeze({...context});lease.addEventListener('abort',this.invalidated,{once:true});}
  private invalidated=()=>{void this.close().catch(()=>{});};
  static async open(connection:PrivateWorkspaceConnection,invokePort:NativeWorkspaceInvoke=invoke):Promise<NativeWorkspaceStore>{
    if(invokePort===invoke && !isTauri())throw new NativeWorkspaceError('configuration');
    const context=connection.context,lease=connection.generationSignal;if(!context || !lease || lease.aborted)throw new NativeWorkspaceError('closed');
    const contextResult=workspaceLocalContextSchema.safeParse(context);if(!contextResult.success)throw new NativeWorkspaceError('protocol');const captured=contextResult.data;let value:unknown;
    try{value=await invokePort('workspace_open',{context:captured});}catch{throw new NativeWorkspaceError(lease.aborted?'closed':'storage');}
    const parsed=workspaceLocalHandleSchema.safeParse(value);if(!parsed.success)throw new NativeWorkspaceError('protocol');
    const close=async()=>{try{await invokePort('workspace_close',{handle:parsed.data.handle});}catch{/* do not expose private causes or adopt another handle */}};
    if(lease.aborted || connection.generationSignal!==lease || !connection.context || !same(captured,connection.context)){await close();throw new NativeWorkspaceError('closed');}
    if(!same(captured,parsed.data.context)){await close();throw new NativeWorkspaceError('protocol');}
    return new NativeWorkspaceStore(connection,parsed.data.handle,captured,lease,invokePort);
  }
  private check(context:WorkspaceSyncContext=this.context){
    if(this.closed || this.lease.aborted || this.connection.generationSignal!==this.lease || !this.connection.context)throw new NativeWorkspaceError('closed');
    if(!same(this.context,context) || !same(this.context,this.connection.context))throw new NativeWorkspaceError('protocol');
  }
  close():Promise<void>{
    if(this.closeWork)return this.closeWork;this.closed=true;for(const session of this.databaseSessions)session.close();this.databaseSessions.clear();this.lease.removeEventListener('abort',this.invalidated);
    const invokePort=this.invokePort;this.closeWork=Promise.resolve().then(()=>invokePort('workspace_close',{handle:this.handle})).then(()=>{},()=>{throw new NativeWorkspaceError('storage');});return this.closeWork;
  }
  private async execute(request:Record<string,unknown>):Promise<unknown>{
    this.check();const invokePort=this.invokePort;let result:unknown;
    try{const captured=JSON.parse(JSON.stringify(request)) as unknown;result=await invokePort('workspace_execute',{handle:this.handle,request:captured});}catch{this.check();throw new NativeWorkspaceError('storage');}
    this.check();return result;
  }
  async acknowledge(context:WorkspaceSyncContext,_prepared:WorkspacePushRequest,response:ReturnType<typeof verifyWorkspacePushResponse>,wire:string){this.check(context);await this.execute({command:'ack',wire,response});}
  async applyPull(context:WorkspaceSyncContext,request:unknown,response:WorkspacePullResponse){this.check(context);await this.execute({command:'pull',request,response});}
  async snapshot():Promise<unknown>{const value=await this.execute({command:'snapshot'});try{if(!value || typeof value!=='object' || !('context' in value) || !same(this.context,workspaceLocalContextSchema.parse(value.context)))throw Error();this.check();return value;}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async prepare():Promise<string|null>{const value=await this.execute({command:'prepare'});if(value!==null && typeof value!=='string')throw new NativeWorkspaceError('protocol');this.check();return value;}
  page(pageId:string):NativeWorkspacePage {
    const parsed=idSchema.safeParse(pageId);if(!parsed.success)throw new NativeWorkspaceError('protocol');this.check();return new NativeWorkspacePage(this,pageId);
  }
  assertActive(){this.check();}
  async databaseViewEnqueue(candidate:unknown){this.check();let intent:ReturnType<typeof privateDatabaseViewIntentSchema.parse>;try{intent=privateDatabaseViewIntentSchema.parse(candidate);if(intent.source.workspaceId!==this.context.workspaceId)throw Error();immutable(intent);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_view_enqueue',intent});try{const value=privateDatabaseViewEnqueuedSchema.parse(raw);if(value.viewId!==intent.intent.viewId||(value.status==='queued'&&value.operationId!==intent.operationId)||(value.status==='busy'&&value.operationId===intent.operationId))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseViewPrepare(){this.check();const raw=await this.execute({command:'database_view_prepare'});if(raw===null)return null;try{if((raw as {status?:unknown}).status==='blocked'){const value=privateDatabaseViewBlockedSchema.parse(raw);this.check();return immutable(value);}const value=privateDatabaseViewPreparedSchema.parse(raw),request=privateDatabaseViewWriteRequestSchema.parse(JSON.parse(value.wire));if(request.clientId!==this.context.clientId)throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseViewAcknowledge(candidate:unknown,candidateReply:unknown){this.check();let value:ReturnType<typeof privateDatabaseViewPreparedSchema.parse>,reply:ReturnType<typeof privateDatabaseViewWriteResponseSchema.parse>;try{value=privateDatabaseViewPreparedSchema.parse(candidate);const request=privateDatabaseViewWriteRequestSchema.parse(JSON.parse(value.wire));reply=privateDatabaseViewWriteResponseSchema.parse(candidateReply);if(request.clientId!==this.context.clientId||reply.workspaceId!==this.context.workspaceId||reply.workspaceEpoch!==this.context.streamEpoch||reply.clientId!==this.context.clientId||reply.sourceId!==value.sourceId||reply.schemaVersion!==request.intent.schemaVersion||reply.operationId!==value.operationId||reply.snapshot.view.id!==value.viewId||(request.intent.kind==='create'?(reply.result.status!=='applied'||reply.snapshot.version!==1||!sameSettings(reply.snapshot.view,request.intent.settings)):reply.snapshot.version<request.intent.baseVersion))throw Error();immutable(value);immutable(reply);}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_view_ack',sequence:value.sequence,wire:value.wire,response:reply});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseViewQueue(candidate:unknown={}){this.check();let request:ReturnType<typeof privateDatabaseViewQueueRequestSchema.parse>;try{request=privateDatabaseViewQueueRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_view_queue',...request});try{const value=privateDatabaseViewQueueSchema.parse(raw);if(!same(this.context,value.context)||value.operations.length>request.limit||(request.pendingOnly&&value.operations.some(row=>row.response!==null))||value.operations.some(row=>request.after!==null&&BigInt(row.sequence)<=BigInt(request.after)))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseRecordUpdateEnqueue(candidate:unknown){this.check();let intent:ReturnType<typeof privateDatabaseRecordUpdateIntentSchema.parse>;try{intent=privateDatabaseRecordUpdateIntentSchema.parse(candidate);if(intent.source.workspaceId!==this.context.workspaceId)throw Error();immutable(intent);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_record_update_enqueue',intent});try{const value=privateDatabaseRecordUpdateEnqueuedSchema.parse(raw);if(value.recordId!==intent.intent.recordId||(value.status==='queued'&&value.operationId!==intent.operationId)||(value.status==='busy'&&value.operationId===intent.operationId))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseRecordUpdatePrepare(){this.check();const raw=await this.execute({command:'database_record_update_prepare'});if(raw===null)return null;try{const value=privateDatabaseRecordUpdatePreparedSchema.parse(raw),request=privateDatabaseRecordWriteRequestSchema.parse(JSON.parse(value.wire));if(request.clientId!==this.context.clientId)throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseRecordUpdateAcknowledge(candidate:unknown,candidateReply:unknown){this.check();let value:ReturnType<typeof privateDatabaseRecordUpdatePreparedSchema.parse>,reply:ReturnType<typeof privateDatabaseRecordWriteResponseSchema.parse>;try{value=privateDatabaseRecordUpdatePreparedSchema.parse(candidate);const request=privateDatabaseRecordWriteRequestSchema.parse(JSON.parse(value.wire));reply=privateDatabaseRecordWriteResponseSchema.parse(candidateReply);if(request.intent.kind!=='update'||request.clientId!==this.context.clientId||reply.workspaceId!==this.context.workspaceId||reply.workspaceEpoch!==this.context.streamEpoch||reply.clientId!==this.context.clientId||reply.sourceId!==value.sourceId||reply.schemaVersion!==request.intent.schemaVersion||reply.operationId!==value.operationId||reply.record.id!==value.recordId||reply.record.pageId!==value.pageId||reply.record.version<request.intent.baseVersion)throw Error();immutable(value);immutable(reply);}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_record_update_ack',sequence:value.sequence,wire:value.wire,response:reply});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseRecordUpdateQueue(candidate:unknown={}){this.check();let request:ReturnType<typeof privateDatabaseRecordUpdateQueueRequestSchema.parse>;try{request=privateDatabaseRecordUpdateQueueRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_record_update_queue',...request});try{const value=privateDatabaseRecordUpdateQueueSchema.parse(raw);if(!same(this.context,value.context)||value.operations.length>request.limit||(request.pendingOnly&&value.operations.some(row=>row.response!==null))||value.operations.some(row=>request.after!==null&&BigInt(row.sequence)<=BigInt(request.after)))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseRecordCreateEnqueue(candidate:unknown){this.check();let intent:ReturnType<typeof privateDatabaseRecordCreateIntentSchema.parse>;try{intent=privateDatabaseRecordCreateIntentSchema.parse(candidate);if(intent.source.workspaceId!==this.context.workspaceId)throw Error();immutable(intent);}catch{throw new NativeWorkspaceError('protocol');}const value=await this.execute({command:'database_record_create_enqueue',intent});if(value!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseRecordCreatePrepare(){this.check();const raw=await this.execute({command:'database_record_create_prepare'});if(raw===null)return null;try{if(raw&&typeof raw==='object'&&'status' in raw){const blocked=privateDatabaseRecordCreateBlockedSchema.parse(raw);this.check();return immutable(blocked);}const value=privateDatabaseRecordCreatePreparedSchema.parse(raw),request=privateDatabaseRecordWriteRequestSchema.parse(JSON.parse(value.wire));if(request.clientId!==this.context.clientId)throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseRecordCreateAcknowledge(candidate:unknown,candidateReply:unknown){this.check();let value:ReturnType<typeof privateDatabaseRecordCreatePreparedSchema.parse>,reply:ReturnType<typeof privateDatabaseRecordWriteResponseSchema.parse>;try{value=privateDatabaseRecordCreatePreparedSchema.parse(candidate);const request=privateDatabaseRecordWriteRequestSchema.parse(JSON.parse(value.wire));reply=privateDatabaseRecordWriteResponseSchema.parse(candidateReply);const keys=Object.keys(request.intent.values);if(request.clientId!==this.context.clientId||reply.workspaceId!==this.context.workspaceId||reply.workspaceEpoch!==this.context.streamEpoch||reply.clientId!==this.context.clientId||reply.sourceId!==value.sourceId||reply.schemaVersion!==request.intent.schemaVersion||reply.operationId!==value.operationId||reply.result.status!=='applied'||reply.record.id!==value.recordId||reply.record.pageId!==value.pageId||reply.record.version!==1||Object.keys(reply.record.values).length!==keys.length||keys.some(key=>reply.record.values[key]!==request.intent.values[key]))throw Error();immutable(value);immutable(reply);}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_record_create_ack',sequence:value.sequence,wire:value.wire,response:reply});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseRecordCreateQueue(candidate:unknown={}){this.check();let request:ReturnType<typeof privateDatabaseRecordCreateQueueRequestSchema.parse>;try{request=privateDatabaseRecordCreateQueueRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_record_create_queue',...request});try{const value=privateDatabaseRecordCreateQueueSchema.parse(raw);if(!same(this.context,value.context)||value.operations.length>request.limit||(request.pendingOnly&&value.operations.some(row=>row.response!==null))||value.operations.some(row=>request.after!==null&&BigInt(row.sequence)<=BigInt(request.after)))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseSourceEnqueue(candidate:unknown){this.check();let intent:ReturnType<typeof privateDatabaseSourceIntentSchema.parse>;try{intent=privateDatabaseSourceIntentSchema.parse(candidate);if(intent.source.workspaceId!==this.context.workspaceId)throw Error();immutable(intent);}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_source_enqueue',intent});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseSourcePrepare(){this.check();const raw=await this.execute({command:'database_source_prepare'});if(raw===null)return null;try{const prepared=privateDatabaseSourcePreparedSchema.parse(raw),request=privateDatabaseSourceCreateRequestSchema.parse(JSON.parse(prepared.wire));if(request.clientId!==this.context.clientId||request.source.workspaceId!==this.context.workspaceId)throw Error();this.check();return immutable(prepared);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseSourceAcknowledge(candidate:unknown,candidateReply:unknown){this.check();let prepared:ReturnType<typeof privateDatabaseSourcePreparedSchema.parse>,reply:ReturnType<typeof privateDatabaseSourceCreateResponseSchema.parse>;try{prepared=privateDatabaseSourcePreparedSchema.parse(candidate);const request=privateDatabaseSourceCreateRequestSchema.parse(JSON.parse(prepared.wire));reply=privateDatabaseSourceCreateResponseSchema.parse(candidateReply);if(request.clientId!==this.context.clientId||request.source.workspaceId!==this.context.workspaceId||reply.clientId!==this.context.clientId||reply.workspaceId!==this.context.workspaceId||reply.workspaceEpoch!==this.context.streamEpoch||reply.operationId!==prepared.operationId||reply.snapshot.version!==1||JSON.stringify(reply.snapshot.source)!==JSON.stringify(request.source))throw Error();immutable(prepared);immutable(reply);}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_source_ack',sequence:prepared.sequence,wire:prepared.wire,response:reply});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseSourceQueue(candidate:unknown={}){this.check();let request:ReturnType<typeof privateDatabaseSourceQueueRequestSchema.parse>;try{request=privateDatabaseSourceQueueRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const raw=await this.execute({command:'database_source_queue',...request});try{const value=privateDatabaseSourceQueueSchema.parse(raw);if(!same(this.context,value.context)||value.operations.length>request.limit||(request.pendingOnly&&value.operations.some(row=>row.response!==null))||value.operations.some(row=>request.after!==null&&BigInt(row.sequence)<=BigInt(request.after)))throw Error();this.check();return immutable(value);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  databaseRecordWrites(){this.check();const create=this.databaseRecordCreatePrepare.bind(this),update=this.databaseRecordUpdatePrepare.bind(this),createQueue=this.databaseRecordCreateQueue.bind(this),updateQueue=this.databaseRecordUpdateQueue.bind(this),createAck=this.databaseRecordCreateAcknowledge.bind(this),updateAck=this.databaseRecordUpdateAcknowledge.bind(this);return this.trackDatabase(this.connection.openDatabaseRecordWrites({prepare:kind=>kind==='create'?create():update(),queue:(kind,request)=>kind==='create'?createQueue(request):updateQueue(request),acknowledge:(kind,prepared,response)=>kind==='create'?createAck(prepared,response):updateAck(prepared,response)}));}
  databaseSourceWrites(){this.check();return this.trackDatabase(this.connection.openDatabaseSourceWrites({prepare:this.databaseSourcePrepare.bind(this),acknowledge:this.databaseSourceAcknowledge.bind(this)}));}
  databaseSources(){this.check();return this.trackDatabase(this.connection.openDatabaseSources({receive:this.databaseSourceReceive.bind(this)}));}
  private trackDatabase<T extends {close():void;signal:AbortSignal}>(session:T):T{this.check();this.databaseSessions.add(session);session.signal.addEventListener('abort',()=>this.databaseSessions.delete(session),{once:true});return session;}
  async databaseContents(sourceId:string){this.check();const cached=await this.databaseSourceLoad(sourceId);this.check();if(!cached.snapshot)throw new NativeWorkspaceError('protocol');return this.trackDatabase(this.connection.openDatabaseContents(cached.snapshot.source,{receiveRecord:(id,request,response)=>this.databaseRecordReceive(sourceId,id,request,response),receiveView:(id,request,response)=>this.databaseViewReceive(sourceId,id,request,response)}));}
  async databaseChanges(sourceId:string){this.check();const cached=await this.databaseSourceLoad(sourceId);this.check();if(!cached.snapshot)throw new NativeWorkspaceError('protocol');return this.trackDatabase(this.connection.openDatabaseChanges(cached.snapshot.source,{load:()=>this.databaseChangesLoad(sourceId),receive:(request,response)=>this.databaseChangesReceive(sourceId,request,response)}));}
  async databaseChangesLoad(sourceId:string){this.check();const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');const value=await this.execute({command:'database_changes_load',sourceId});try{const saved=privateDatabaseChangesLocalProgressSchema.parse(value);if(!same(this.context,saved.context)||saved.sourceId!==sourceId||saved.schemaVersion!==source.snapshot.source.schemaVersion)throw Error();this.check();return immutable(saved);}catch{this.check();throw new NativeWorkspaceError('protocol');}}
  async databaseChangesReceive(sourceId:string,candidateRequest:unknown,candidateResponse:unknown):Promise<void>{this.check();let request:ReturnType<typeof privateDatabaseChangesRequestSchema.parse>;try{request=privateDatabaseChangesRequestSchema.parse(candidateRequest);if(request.clientId!==this.context.clientId)throw Error();immutable(request);}catch{throw new NativeWorkspaceError('protocol');}const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');let response:ReturnType<typeof parsePrivateDatabaseChangesResponse>;try{response=parsePrivateDatabaseChangesResponse(source.snapshot.source,candidateResponse);if(response.clientId!==this.context.clientId||response.workspaceEpoch!==this.context.streamEpoch||response.events.length>request.limit||BigInt(response.readOrder)-BigInt(response.afterOrder)>BigInt(request.limit))throw Error();}catch{throw new NativeWorkspaceError('protocol');}const result=await this.execute({command:'database_changes_receive',sourceId,request,response});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();}
  async databaseViewReceive(sourceId:string,viewId:string,candidateRequest:unknown,candidateResponse:unknown):Promise<void>{
    this.check();let request:ReturnType<typeof privateDatabaseViewReadRequestSchema.parse>,response:ReturnType<typeof privateDatabaseViewReadResponseSchema.parse>;
    try{if(idSchema.parse(viewId)!==viewId.toLowerCase())throw Error();request=privateDatabaseViewReadRequestSchema.parse(candidateRequest);response=privateDatabaseViewReadResponseSchema.parse(candidateResponse);if(request.clientId!==this.context.clientId||response.clientId!==this.context.clientId||response.workspaceId!==this.context.workspaceId||response.workspaceEpoch!==this.context.streamEpoch||response.sourceId!==sourceId||response.snapshot.view.id!==viewId||response.conflicts.length>request.limit||response.conflicts.some(item=>request.afterConflict!==null&&item.id<=request.afterConflict!))throw Error();immutable(request);immutable(response);}catch{throw new NativeWorkspaceError('protocol');}
    const cached=await this.databaseSourceLoad(sourceId);try{if(!cached.snapshot||cached.snapshot.source.schemaVersion!==response.schemaVersion)throw Error();parseDatabaseViewSnapshot(cached.snapshot.source,response.snapshot);for(const conflict of response.conflicts)parseDatabaseViewConflict(cached.snapshot.source,conflict);}catch{throw new NativeWorkspaceError('protocol');}
    const result=await this.execute({command:'database_view_receive',sourceId,viewId,request,response});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();
  }
  async databaseViewLoad(sourceId:string,viewId:string,candidate:unknown={afterConflict:null,limit:20}){
    this.check();let request:ReturnType<typeof privateDatabaseViewLocalLoadRequestSchema.parse>;try{if(idSchema.parse(viewId)!==viewId.toLowerCase())throw Error();request=privateDatabaseViewLocalLoadRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'database_view_load',sourceId,viewId,...request});try{const result=privateDatabaseViewLocalLoadSchema.parse(value);if(!same(this.context,result.context)||result.sourceId!==sourceId||result.schemaVersion!==source.snapshot.source.schemaVersion||result.conflicts.length>request.limit||result.conflicts.some(row=>request.afterConflict!==null&&row.id<=request.afterConflict!))throw Error();if(result.snapshot){if(result.snapshot.view.id!==viewId)throw Error();parseDatabaseViewSnapshot(source.snapshot.source,result.snapshot);for(const conflict of result.conflicts)parseDatabaseViewConflict(source.snapshot.source,conflict);}this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async databaseViewList(sourceId:string,candidate:unknown={after:null,limit:50}){
    this.check();let request:ReturnType<typeof privateDatabaseViewLocalListRequestSchema.parse>;try{request=privateDatabaseViewLocalListRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'database_view_list',sourceId,...request});try{const result=privateDatabaseViewLocalListSchema.parse(value);if(!same(this.context,result.context)||result.sourceId!==sourceId||result.schemaVersion!==source.snapshot.source.schemaVersion||result.views.length>request.limit||result.views.some(row=>request.after!==null&&row.id<=request.after!))throw Error();this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async databaseRecordReceive(sourceId:string,recordId:string,candidateRequest:unknown,candidateResponse:unknown):Promise<void>{
    this.check();let request:ReturnType<typeof privateDatabaseRecordReadRequestSchema.parse>,response:ReturnType<typeof privateDatabaseRecordReadResponseSchema.parse>;
    try{if(idSchema.parse(recordId)!==recordId.toLowerCase())throw Error();request=privateDatabaseRecordReadRequestSchema.parse(candidateRequest);response=privateDatabaseRecordReadResponseSchema.parse(candidateResponse);if(request.clientId!==this.context.clientId||response.clientId!==this.context.clientId||response.workspaceId!==this.context.workspaceId||response.workspaceEpoch!==this.context.streamEpoch||response.sourceId!==sourceId||response.record.id!==recordId||response.record.pageId!==request.pageId||response.conflicts.length>request.limit||response.conflicts.some(item=>request.afterConflict!==null&&item.id<=request.afterConflict!))throw Error();immutable(request);immutable(response);}catch{throw new NativeWorkspaceError('protocol');}
    const cached=await this.databaseSourceLoad(sourceId);try{if(!cached.snapshot||cached.snapshot.source.schemaVersion!==response.schemaVersion)throw Error();parseDatabaseRecord(cached.snapshot.source,response.record);for(const conflict of response.conflicts)parseDatabaseRecordConflict(cached.snapshot.source,conflict);}catch{throw new NativeWorkspaceError('protocol');}
    const result=await this.execute({command:'database_record_receive',sourceId,recordId,request,response});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();
  }
  async databaseRecordLoad(sourceId:string,recordId:string,candidate:unknown={afterConflict:null,limit:20}){
    this.check();let request:ReturnType<typeof privateDatabaseRecordLocalLoadRequestSchema.parse>;try{if(idSchema.parse(recordId)!==recordId.toLowerCase())throw Error();request=privateDatabaseRecordLocalLoadRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'database_record_load',sourceId,recordId,...request});try{const result=privateDatabaseRecordLocalLoadSchema.parse(value);if(!same(this.context,result.context)||result.sourceId!==sourceId||result.schemaVersion!==source.snapshot.source.schemaVersion||result.conflicts.length>request.limit||result.conflicts.some(row=>request.afterConflict!==null&&row.id<=request.afterConflict!))throw Error();if(result.record){if(result.record.id!==recordId)throw Error();parseDatabaseRecord(source.snapshot.source,result.record);for(const conflict of result.conflicts)parseDatabaseRecordConflict(source.snapshot.source,conflict);}this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async databaseRecordList(sourceId:string,candidate:unknown={after:null,limit:50}){
    this.check();let request:ReturnType<typeof privateDatabaseRecordLocalListRequestSchema.parse>;try{request=privateDatabaseRecordLocalListRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}const source=await this.databaseSourceLoad(sourceId);if(!source.snapshot)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'database_record_list',sourceId,...request});try{const result=privateDatabaseRecordLocalListSchema.parse(value);if(!same(this.context,result.context)||result.sourceId!==sourceId||result.schemaVersion!==source.snapshot.source.schemaVersion||result.records.length>request.limit||result.records.some(row=>request.after!==null&&row.id<=request.after!))throw Error();this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async databaseSourceReceive(sourceId:string,candidateRequest:unknown,candidateResponse:unknown):Promise<void>{
    this.check();let request:ReturnType<typeof privateDatabaseSourceReadRequestSchema.parse>,response:ReturnType<typeof privateDatabaseSourceReadResponseSchema.parse>;
    try{if(idSchema.parse(sourceId)!==sourceId.toLowerCase())throw Error();request=privateDatabaseSourceReadRequestSchema.parse(candidateRequest);response=privateDatabaseSourceReadResponseSchema.parse(candidateResponse);if(request.clientId!==this.context.clientId||response.clientId!==this.context.clientId||response.workspaceId!==this.context.workspaceId||response.workspaceEpoch!==this.context.streamEpoch||response.snapshot.source.id!==sourceId)throw Error();immutable(request);immutable(response);}catch{throw new NativeWorkspaceError('protocol');}
    const result=await this.execute({command:'database_source_receive',sourceId,request,response});if(result!==null)throw new NativeWorkspaceError('protocol');this.check();
  }
  async databaseSourceLoad(sourceId:string){
    this.check();try{if(idSchema.parse(sourceId)!==sourceId.toLowerCase())throw Error();}catch{throw new NativeWorkspaceError('protocol');}
    const value=await this.execute({command:'database_source_load',sourceId});try{const result=privateDatabaseSourceLocalLoadSchema.parse(value);if(!same(this.context,result.context)||(result.snapshot!==null&&result.snapshot.source.id!==sourceId))throw Error();this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async databaseSourceList(candidate:unknown={after:null,limit:50}){
    this.check();let request:ReturnType<typeof privateDatabaseSourceLocalListRequestSchema.parse>;try{request=privateDatabaseSourceLocalListRequestSchema.parse(candidate);}catch{throw new NativeWorkspaceError('protocol');}
    const value=await this.execute({command:'database_source_list',...request});try{const result=privateDatabaseSourceLocalListSchema.parse(value);if(!same(this.context,result.context)||result.sources.length>request.limit||result.sources.some(row=>request.after!==null&&row.source.id<=request.after!))throw Error();this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async changesLoad(candidate:unknown={afterPage:null,limit:50}){
    const parsed=privatePageChangesLocalRequestSchema.safeParse(candidate);if(!parsed.success)throw new NativeWorkspaceError('protocol');const request=parsed.data;
    const value=await this.execute({command:'changes_load',...request});try{const result=privatePageChangesLocalResponseSchema.parse(value);if(!same(this.context,result.context)||result.pages.length>request.limit||result.pages.some(row=>request.afterPage!==null&&row.metadata.id<=request.afterPage!))throw Error();this.check();return immutable(result);}catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async changesReceive(candidateRequest:unknown,candidateResponse:unknown):Promise<void>{
    let request:ReturnType<typeof privatePageChangesRequestSchema.parse>,response:ReturnType<typeof privatePageChangesResponseSchema.parse>;
    this.check();try{request=privatePageChangesRequestSchema.parse(candidateRequest);response=privatePageChangesResponseSchema.parse(candidateResponse);if(request.clientId!==this.context.clientId||response.workspaceId!==this.context.workspaceId||response.workspaceEpoch!==this.context.streamEpoch||response.events.length>request.limit)throw Error();immutable(request);immutable(response);}catch{throw new NativeWorkspaceError('protocol');}
    await this.execute({command:'changes_receive',request,response});this.check();
  }
  async structuredSnapshot(){
    const value=await this.execute({command:'snapshot'});
    try{const result=workspaceStructuredSnapshotSchema.parse(value);if(!same(this.context,result.context)||result.snapshot.clientId!==this.context.clientId)throw Error();this.check();return immutable(result.snapshot);}
    catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  title(pageId:string):NativeWorkspaceTitle{const parsed=idSchema.safeParse(pageId);if(!parsed.success)throw new NativeWorkspaceError('protocol');this.check();return new NativeWorkspaceTitle(this,pageId);}
  async mutate(candidate:unknown):Promise<void>{
    let operation:ReturnType<typeof pushOperationSchema.parse>;
    try{operation=pushOperationSchema.parse(candidate);parseOperationPayload(operation);if(operation.clientId!==this.context.clientId)throw Error();}catch{throw new NativeWorkspaceError('protocol');}
    const value=await this.execute({command:'mutate',operation});
    try{const entity=operation.entityType==='task'?taskSchema.parse(value):relationSchema.parse(value);if(entity.id!==operation.entityId)throw Error();this.check();}
    catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  async hasPage(candidate:string):Promise<boolean>{
    const pageId=idSchema.safeParse(candidate);if(!pageId.success)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'page_exists',pageId:pageId.data});if(typeof value!=='boolean')throw new NativeWorkspaceError('protocol');this.check();return value;
  }
  async listPages(candidate:unknown={after:null,limit:50}) {
    const request=privateLocalPageCatalogRequestSchema.safeParse(candidate);if(!request.success)throw new NativeWorkspaceError('protocol');
    const value=await this.execute({command:'page_list',...request.data});
    try{const result=privateLocalPageCatalogResponseSchema.parse(value);if(!same(this.context,result.context) || result.pages.length>request.data.limit || result.pages.some(page=>request.data.after!==null && page.metadata.id<=request.data.after!))throw Error();
      for(const page of result.pages){Object.freeze(page.metadata);Object.freeze(page);}Object.freeze(result.pages);Object.freeze(result.context);this.check();return Object.freeze(result);
    }catch{this.check();throw new NativeWorkspaceError('protocol');}
  }
  assertConnection(connection:PrivateWorkspaceConnection){if(connection!==this.connection)throw new NativeWorkspaceError('protocol');this.check();}
  async pageCommand(pageId:string,command:string,fields:Record<string,unknown>={}):Promise<unknown>{return this.execute({...fields,command,pageId});}
}
export class NativeWorkspacePage implements PageSessionStore {
  constructor(private readonly store:NativeWorkspaceStore,readonly pageId:string){}
  private check(context:PageSyncContext){if(context.pageId!==this.pageId || context.documentName!=='page:'+this.pageId || context.editorSchemaVersion!==1 || !same(this.store.context,context))throw new NativeWorkspaceError('protocol');}
  async create(title:string,update:Uint8Array):Promise<void>{this.store.assertActive();
    const bytes=Uint8Array.from(update);try{privatePageBootstrapRequestSchema.parse({protocolVersion:1,clientId:this.store.context.clientId,editorSchemaVersion:1,title,initialUpdate:pageBase64(bytes)});pageUpdateBytes(pageBase64(bytes));}catch{throw new NativeWorkspaceError('protocol');}
    await this.store.pageCommand(this.pageId,'page_create',{title,update:Array.from(bytes)});this.store.assertActive();
  }
  async append(update:Uint8Array):Promise<void>{this.store.assertActive();
    const bytes=Uint8Array.from(update);try{privatePageAppendRequestSchema.parse({protocolVersion:1,clientId:this.store.context.clientId,editorSchemaVersion:1,update:pageBase64(bytes)});pageUpdateBytes(pageBase64(bytes));}catch{throw new NativeWorkspaceError('protocol');}
    await this.store.pageCommand(this.pageId,'page_append',{update:Array.from(bytes)});this.store.assertActive();
  }
  async load(){
    const candidate=await this.store.pageCommand(this.pageId,'page_load');try{const value=privatePageLocalLoadSchema.parse(candidate);if(value.page.metadata.id!==this.pageId || value.page.metadata.yDocId!=='page:'+this.pageId)throw Error();for(const bytes of value.page.updates)pageUpdateBytes(pageBase64(Uint8Array.from(bytes)));this.store.assertActive();return value;}catch{this.store.assertActive();throw new NativeWorkspaceError('protocol');}
  }
  async prepare():Promise<PrivatePagePrepared|null>{const value=await this.store.pageCommand(this.pageId,'page_prepare');if(value===null){this.store.assertActive();return null;}try{const prepared=privatePagePreparedSchema.parse(value);if(prepared.pageId!==this.pageId)throw Error();this.store.assertActive();return Object.freeze(prepared);}catch{this.store.assertActive();throw new NativeWorkspaceError('protocol');}}
  async acknowledge(context:PageSyncContext,prepared:PrivatePagePrepared,response:PageReceipt){this.check(context);if(prepared.pageId!==this.pageId)throw new NativeWorkspaceError('protocol');await this.store.pageCommand(this.pageId,'page_ack',{sequence:prepared.sequence,wire:prepared.wire,response});}
  async receive(context:PageSyncContext,_request:PrivatePageReadRequest,response:PrivatePageReadResponse,_update:Uint8Array){this.check(context);await this.store.pageCommand(this.pageId,'page_receive',{response});}
}

function sameSettings(view:Record<string,unknown>,settings:Record<string,unknown>):boolean{return Object.entries(settings).every(([key,value])=>sameSettingsValue(view[key],value));}
function sameSettingsValue(a:unknown,b:unknown):boolean{if(a===b)return true;if(Array.isArray(a)||Array.isArray(b))return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((value,index)=>sameSettingsValue(value,b[index]));if(!a||!b||typeof a!=='object'||typeof b!=='object')return false;const left=a as Record<string,unknown>,right=b as Record<string,unknown>;return Object.keys(left).length===Object.keys(right).length&&Object.keys(left).every(key=>Object.hasOwn(right,key)&&sameSettingsValue(left[key],right[key]));}