import {privateDatabaseViewIntentSchema,privateDatabaseViewQueueSchema,privateDatabaseViewEnqueuedSchema,privateDatabaseViewBlockedSchema,privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
import {DatabaseViewWriteSessionError,type DatabaseViewWriteSyncSession,type PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,NativeWorkspaceError} from './native-workspace-store.js';
type Intent=ReturnType<typeof privateDatabaseViewIntentSchema.parse>;
type Queue=ReturnType<typeof privateDatabaseViewQueueSchema.parse>;
type Enqueued=ReturnType<typeof privateDatabaseViewEnqueuedSchema.parse>;
type Reply=ReturnType<typeof privateDatabaseViewWriteResponseSchema.parse>;
type Blocked=ReturnType<typeof privateDatabaseViewBlockedSchema.parse>;
export type PrivateDatabaseViewSendResult=Readonly<{status:'empty'}|{status:'blocked';blocked:Blocked}|{status:'ack';response:Reply}>;
export type PrivateDatabaseViewWriteState=Readonly<{phase:'opening'|'ready'|'closed';busy:boolean;data:Queue|null;queueFresh:boolean;error:'protocol'|'storage'|'transport'|null;retryEnqueue:boolean;retryAck:boolean;lastEnqueue:Readonly<{attemptOperationId:string;result:Enqueued}>|null;lastSend:PrivateDatabaseViewSendResult|null}>;
export class PrivateDatabaseViewWriteError extends Error {constructor(readonly stage:'closed'|'busy'|'protocol'|'storage'|'transport'){super(`Private database View write ${stage}`);this.name='PrivateDatabaseViewWriteError';}}
function frozen<T>(value:T):T{if(value&&typeof value==='object'){for(const child of Object.values(value))frozen(child);Object.freeze(value);}return value;}
export class PrivateDatabaseViewWriteSession {
 private phase:PrivateDatabaseViewWriteState['phase']='opening';private busy=false;private data:Queue|null=null;private fresh=false;private error:PrivateDatabaseViewWriteState['error']=null;
 private pendingEnqueue:Intent|null=null;private lastEnqueue:PrivateDatabaseViewWriteState['lastEnqueue']=null;private lastSend:PrivateDatabaseViewSendResult|null=null;
 private readonly sync:DatabaseViewWriteSyncSession;private readonly lease:AbortSignal;private readonly detach:()=>void;
 private readonly enqueueStore:NativeWorkspaceStore['databaseViewEnqueue'];private readonly load:NativeWorkspaceStore['databaseViewQueue'];
 private listeners=new Set<(state:PrivateDatabaseViewWriteState)=>void>();private tail:Promise<void>=Promise.resolve();private closeWork:Promise<void>|null=null;
 private constructor(private readonly connection:PrivateWorkspaceConnection,private readonly store:NativeWorkspaceStore){
  store.assertConnection(connection);const lease=connection.generationSignal;if(!lease||lease.aborted)throw new PrivateDatabaseViewWriteError('closed');this.lease=lease;this.enqueueStore=store.databaseViewEnqueue.bind(store);this.load=store.databaseViewQueue.bind(store);this.sync=store.databaseViewWrites();
  const invalidated=()=>{void this.close();};lease.addEventListener('abort',invalidated,{once:true});this.sync.signal.addEventListener('abort',invalidated,{once:true});this.detach=()=>{lease.removeEventListener('abort',invalidated);this.sync.signal.removeEventListener('abort',invalidated);};
 }
 static async open(connection:PrivateWorkspaceConnection,store:NativeWorkspaceStore):Promise<PrivateDatabaseViewWriteSession>{let runtime:PrivateDatabaseViewWriteSession|undefined;try{runtime=new PrivateDatabaseViewWriteSession(connection,store);await runtime.read(null);runtime.check();runtime.phase='ready';return runtime;}catch(error){const failure=runtime?runtime.failure(error):new PrivateDatabaseViewWriteError(error instanceof NativeWorkspaceError?(error.stage==='configuration'?'protocol':error.stage):error instanceof PrivateDatabaseViewWriteError?error.stage:'protocol');await runtime?.close();throw failure;}}
 private check(){if(this.phase==='closed'||this.lease.aborted||this.sync.signal.aborted)throw new PrivateDatabaseViewWriteError('closed');try{this.store.assertConnection(this.connection);}catch{throw new PrivateDatabaseViewWriteError('closed');}}
 private failure(error:unknown):PrivateDatabaseViewWriteError{if(this.phase==='closed'||this.lease.aborted||this.sync.signal.aborted)return new PrivateDatabaseViewWriteError('closed');if(error instanceof PrivateDatabaseViewWriteError)return error;if(error instanceof DatabaseViewWriteSessionError)return new PrivateDatabaseViewWriteError(error.stage);if(error instanceof NativeWorkspaceError)return new PrivateDatabaseViewWriteError(error.stage==='configuration'?'protocol':error.stage);return new PrivateDatabaseViewWriteError('protocol');}
 get snapshot():PrivateDatabaseViewWriteState{return Object.freeze({phase:this.phase,busy:this.busy,data:this.data,queueFresh:this.fresh,error:this.error,retryEnqueue:this.pendingEnqueue!==null,retryAck:this.sync.retryAck,lastEnqueue:this.lastEnqueue,lastSend:this.lastSend});}
 subscribe(listener:(state:PrivateDatabaseViewWriteState)=>void){this.listeners.add(listener);try{listener(this.snapshot);}catch{/* Observations never interrupt storage. */}return()=>{this.listeners.delete(listener);};}
 private publish(){for(const listener of this.listeners)try{listener(this.snapshot);}catch{/* Observations never interrupt storage. */}}
 private run<T>(work:()=>Promise<T>):Promise<T>{this.check();if(this.phase!=='ready'||this.busy)throw new PrivateDatabaseViewWriteError('busy');this.busy=true;this.error=null;this.fresh=false;const result=Promise.resolve().then(async()=>{try{this.check();const result=await work();this.check();return result;}catch(error){const failure=this.failure(error);if(failure.stage==='closed')void this.close();else this.error=failure.stage==='busy'?'protocol':failure.stage;throw failure;}finally{this.busy=false;this.publish();}});this.tail=result.then(()=>{},()=>{});this.publish();return result;}
 private async read(after:string|null){const value=await this.load({pendingOnly:true,after,limit:100});this.check();this.data=value;this.fresh=true;}
 private available(){if(this.pendingEnqueue||this.sync.retryAck)throw new PrivateDatabaseViewWriteError('busy');}
 async reload(more=false){this.check();const after=more?this.data?.nextAfter??null:null;if(more&&after===null)return;return this.run(()=>this.read(after));}
 private async save(intent:Intent):Promise<Enqueued>{this.pendingEnqueue=intent;const result=await this.enqueueStore(intent);this.check();this.lastEnqueue=frozen({attemptOperationId:intent.operationId,result});if(result.status==='busy')this.pendingEnqueue=null;await this.read(null);this.pendingEnqueue=null;return result;}
 async enqueue(candidate:unknown){this.check();this.available();let intent:Intent;try{intent=frozen(privateDatabaseViewIntentSchema.parse(candidate));if(intent.source.workspaceId!==this.store.context.workspaceId)throw Error();}catch{throw new PrivateDatabaseViewWriteError('protocol');}return this.run(()=>this.save(intent));}
 async retryEnqueue(){return this.run(async()=>{if(!this.pendingEnqueue)throw new PrivateDatabaseViewWriteError('protocol');return this.save(this.pendingEnqueue);});}
 async send(){this.check();this.available();return this.run(async()=>{this.lastSend=null;const reply=await this.sync.send();this.check();this.lastSend=frozen(reply===null?{status:'empty'}:'status' in reply?{status:'blocked',blocked:reply}:{status:'ack',response:reply});await this.read(null);return reply;});}
 async retryAck(){this.check();if(this.pendingEnqueue)throw new PrivateDatabaseViewWriteError('busy');return this.run(async()=>{const reply=await this.sync.retry();this.check();this.lastSend=frozen({status:'ack',response:reply});await this.read(null);return reply;});}
 close():Promise<void>{if(this.closeWork)return this.closeWork;this.closeWork=this.tail.then(()=>{this.listeners.clear();});this.phase='closed';this.busy=false;this.fresh=false;this.data=null;this.error=null;this.pendingEnqueue=null;this.lastEnqueue=null;this.lastSend=null;this.detach();this.sync.close();this.publish();return this.closeWork;}
}
