import {privateDatabaseRecordCreateIntentSchema,privateDatabaseRecordUpdateIntentSchema,privateDatabaseRecordCreateQueueSchema,privateDatabaseRecordUpdateQueueSchema,privateDatabaseRecordUpdateEnqueuedSchema,privateDatabaseRecordCreateBlockedSchema,privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {DatabaseRecordWriteSessionError,type DatabaseRecordWriteKind,type DatabaseRecordWriteSyncSession,type PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,NativeWorkspaceError} from './native-workspace-store.js';
type CreateIntent=ReturnType<typeof privateDatabaseRecordCreateIntentSchema.parse>;
type UpdateIntent=ReturnType<typeof privateDatabaseRecordUpdateIntentSchema.parse>;
type CreateQueue=ReturnType<typeof privateDatabaseRecordCreateQueueSchema.parse>;
type UpdateQueue=ReturnType<typeof privateDatabaseRecordUpdateQueueSchema.parse>;
type Enqueued=ReturnType<typeof privateDatabaseRecordUpdateEnqueuedSchema.parse>;
type Reply=ReturnType<typeof privateDatabaseRecordWriteResponseSchema.parse>;
type Blocked=ReturnType<typeof privateDatabaseRecordCreateBlockedSchema.parse>;
type Pending={kind:'create';intent:CreateIntent}|{kind:'update';intent:UpdateIntent};
type Local=Readonly<{create:CreateQueue;update:UpdateQueue}>;
export type PrivateDatabaseRecordSendResult=Readonly<{kind:DatabaseRecordWriteKind;status:'empty'}|{kind:'create';status:'blocked';blocked:Blocked}|{kind:DatabaseRecordWriteKind;status:'ack';response:Reply}>;
export type PrivateDatabaseRecordWriteState=Readonly<{phase:'opening'|'ready'|'closed';busy:boolean;data:Local|null;queueFresh:Readonly<Record<DatabaseRecordWriteKind,boolean>>;error:'protocol'|'storage'|'transport'|null;retryEnqueue:boolean;retryEnqueueKind:DatabaseRecordWriteKind|null;retryAck:boolean;retryAckKind:DatabaseRecordWriteKind|null;lastEnqueue:Readonly<{kind:DatabaseRecordWriteKind;attemptOperationId:string;result:Enqueued}>|null;lastSend:PrivateDatabaseRecordSendResult|null}>;
export class PrivateDatabaseRecordWriteError extends Error {constructor(readonly stage:'closed'|'busy'|'protocol'|'storage'|'transport'){super(`Private database Record write ${stage}`);this.name='PrivateDatabaseRecordWriteError';}}
function frozen<T>(value:T):T{if(value&&typeof value==='object'){for(const child of Object.values(value))frozen(child);Object.freeze(value);}return value;}
export class PrivateDatabaseRecordWriteSession {
 private phase:PrivateDatabaseRecordWriteState['phase']='opening';private busy=false;private data:Local|null=null;private fresh={create:false,update:false};private error:PrivateDatabaseRecordWriteState['error']=null;
 private pendingEnqueue:Pending|null=null;private lastEnqueue:PrivateDatabaseRecordWriteState['lastEnqueue']=null;private lastSend:PrivateDatabaseRecordSendResult|null=null;
 private readonly sync:DatabaseRecordWriteSyncSession;private readonly lease:AbortSignal;private readonly detach:()=>void;
 private readonly enqueueCreateStore:NativeWorkspaceStore['databaseRecordCreateEnqueue'];private readonly enqueueUpdateStore:NativeWorkspaceStore['databaseRecordUpdateEnqueue'];private readonly loadCreate:NativeWorkspaceStore['databaseRecordCreateQueue'];private readonly loadUpdate:NativeWorkspaceStore['databaseRecordUpdateQueue'];
 private listeners=new Set<(state:PrivateDatabaseRecordWriteState)=>void>();private tail:Promise<void>=Promise.resolve();private closeWork:Promise<void>|null=null;
 private constructor(private readonly connection:PrivateWorkspaceConnection,private readonly store:NativeWorkspaceStore){
  store.assertConnection(connection);const lease=connection.generationSignal;if(!lease||lease.aborted)throw new PrivateDatabaseRecordWriteError('closed');this.lease=lease;this.enqueueCreateStore=store.databaseRecordCreateEnqueue.bind(store);this.enqueueUpdateStore=store.databaseRecordUpdateEnqueue.bind(store);this.loadCreate=store.databaseRecordCreateQueue.bind(store);this.loadUpdate=store.databaseRecordUpdateQueue.bind(store);this.sync=store.databaseRecordWrites();
  const invalidated=()=>{void this.close();};lease.addEventListener('abort',invalidated,{once:true});this.sync.signal.addEventListener('abort',invalidated,{once:true});this.detach=()=>{lease.removeEventListener('abort',invalidated);this.sync.signal.removeEventListener('abort',invalidated);};
 }
 static async open(connection:PrivateWorkspaceConnection,store:NativeWorkspaceStore):Promise<PrivateDatabaseRecordWriteSession>{let runtime:PrivateDatabaseRecordWriteSession|undefined;try{runtime=new PrivateDatabaseRecordWriteSession(connection,store);await runtime.readBoth();runtime.check();runtime.phase='ready';return runtime;}catch(error){const failure=runtime?runtime.failure(error):new PrivateDatabaseRecordWriteError(error instanceof NativeWorkspaceError?(error.stage==='configuration'?'protocol':error.stage):error instanceof PrivateDatabaseRecordWriteError?error.stage:'protocol');await runtime?.close();throw failure;}}
 private check(){if(this.phase==='closed'||this.lease.aborted||this.sync.signal.aborted)throw new PrivateDatabaseRecordWriteError('closed');try{this.store.assertConnection(this.connection);}catch{throw new PrivateDatabaseRecordWriteError('closed');}}
 private failure(error:unknown):PrivateDatabaseRecordWriteError{if(this.phase==='closed'||this.lease.aborted||this.sync.signal.aborted)return new PrivateDatabaseRecordWriteError('closed');if(error instanceof PrivateDatabaseRecordWriteError)return error;if(error instanceof DatabaseRecordWriteSessionError)return new PrivateDatabaseRecordWriteError(error.stage);if(error instanceof NativeWorkspaceError)return new PrivateDatabaseRecordWriteError(error.stage==='configuration'?'protocol':error.stage);return new PrivateDatabaseRecordWriteError('protocol');}
 get snapshot():PrivateDatabaseRecordWriteState{return Object.freeze({phase:this.phase,busy:this.busy,data:this.data,queueFresh:Object.freeze({...this.fresh}),error:this.error,retryEnqueue:this.pendingEnqueue!==null,retryEnqueueKind:this.pendingEnqueue?.kind??null,retryAck:this.sync.retryAck,retryAckKind:this.sync.retryKind,lastEnqueue:this.lastEnqueue,lastSend:this.lastSend});}
 subscribe(listener:(state:PrivateDatabaseRecordWriteState)=>void){this.listeners.add(listener);try{listener(this.snapshot);}catch{/* Observations never interrupt storage. */}return()=>{this.listeners.delete(listener);};}
 private publish(){for(const listener of this.listeners)try{listener(this.snapshot);}catch{/* Observations never interrupt storage. */}}
 private run<T>(work:()=>Promise<T>):Promise<T>{this.check();if(this.phase!=='ready'||this.busy)throw new PrivateDatabaseRecordWriteError('busy');this.busy=true;this.error=null;this.fresh={create:false,update:false};const result=Promise.resolve().then(async()=>{try{this.check();const value=await work();this.check();return value;}catch(error){const failure=this.failure(error);if(failure.stage==='closed')void this.close();else this.error=failure.stage==='busy'?'protocol':failure.stage;throw failure;}finally{this.busy=false;this.publish();}});this.tail=result.then(()=>{},()=>{});this.publish();return result;}
 private async readBoth(){const [create,update]=await Promise.allSettled([this.loadCreate({pendingOnly:true,after:null,limit:100}),this.loadUpdate({pendingOnly:true,after:null,limit:100})] as const);this.check();if(create.status==='rejected')throw create.reason;if(update.status==='rejected')throw update.reason;this.data=frozen({create:create.value,update:update.value});this.fresh={create:true,update:true};}
 private async readOne(kind:DatabaseRecordWriteKind,after:string){const prior=this.data;if(!prior)throw new PrivateDatabaseRecordWriteError('protocol');if(kind==='create'){const value=await this.loadCreate({pendingOnly:true,after,limit:100});this.check();this.data=frozen({...prior,create:value});}else{const value=await this.loadUpdate({pendingOnly:true,after,limit:100});this.check();this.data=frozen({...prior,update:value});}this.fresh={...this.fresh,[kind]:true};}
 private available(){if(this.pendingEnqueue||this.sync.retryAck)throw new PrivateDatabaseRecordWriteError('busy');}
 async reload(kind?:DatabaseRecordWriteKind,more=false){this.check();if(kind!==undefined&&kind!=='create'&&kind!=='update')throw new PrivateDatabaseRecordWriteError('protocol');if(!more)return this.run(()=>this.readBoth());if(!kind)throw new PrivateDatabaseRecordWriteError('protocol');const after=this.data?.[kind].nextAfter??null;if(after===null)return;return this.run(()=>this.readOne(kind,after));}
 private async save(pending:Pending):Promise<Enqueued>{this.pendingEnqueue=pending;const result=pending.kind==='create'?(await this.enqueueCreateStore(pending.intent),{status:'queued' as const,operationId:pending.intent.operationId,recordId:pending.intent.intent.recordId}):await this.enqueueUpdateStore(pending.intent);this.check();this.lastEnqueue=frozen({kind:pending.kind,attemptOperationId:pending.intent.operationId,result});if(result.status==='busy')this.pendingEnqueue=null;await this.readBoth();this.pendingEnqueue=null;return result;}
 async enqueueCreate(candidate:unknown){this.check();this.available();let intent:CreateIntent;try{intent=frozen(privateDatabaseRecordCreateIntentSchema.parse(candidate));if(intent.source.workspaceId!==this.store.context.workspaceId)throw Error();}catch{throw new PrivateDatabaseRecordWriteError('protocol');}return this.run(()=>this.save({kind:'create',intent}));}
 async enqueueUpdate(candidate:unknown){this.check();this.available();let intent:UpdateIntent;try{intent=frozen(privateDatabaseRecordUpdateIntentSchema.parse(candidate));if(intent.source.workspaceId!==this.store.context.workspaceId)throw Error();}catch{throw new PrivateDatabaseRecordWriteError('protocol');}return this.run(()=>this.save({kind:'update',intent}));}
 async retryEnqueue(){return this.run(async()=>{if(!this.pendingEnqueue)throw new PrivateDatabaseRecordWriteError('protocol');return this.save(this.pendingEnqueue);});}
 async send(kind:DatabaseRecordWriteKind){this.check();this.available();return this.run(async()=>{this.lastSend=null;const reply=await this.sync.send(kind);this.check();this.lastSend=frozen(reply===null?{kind,status:'empty'}:'status' in reply?{kind:'create',status:'blocked',blocked:reply}:{kind,status:'ack',response:reply});await this.readBoth();return reply;});}
 async retryAck(){this.check();if(this.pendingEnqueue)throw new PrivateDatabaseRecordWriteError('busy');return this.run(async()=>{const kind=this.sync.retryKind;if(!kind)throw new PrivateDatabaseRecordWriteError('protocol');const reply=await this.sync.retry();this.check();this.lastSend=frozen({kind,status:'ack',response:reply});await this.readBoth();return reply;});}
 close():Promise<void>{if(this.closeWork)return this.closeWork;this.closeWork=this.tail.then(()=>{this.listeners.clear();});this.phase='closed';this.busy=false;this.fresh={create:false,update:false};this.data=null;this.error=null;this.pendingEnqueue=null;this.lastEnqueue=null;this.lastSend=null;this.detach();this.sync.close();this.publish();return this.closeWork;}
}
