import {test,expect,type Page} from '@playwright/test';
type Fixture={snapshot:()=>{pages:{id:string;title:string;wires:string[]}[];reads:string[];sent:string[];composing:boolean};durable:()=>Promise<void>;refreshLocal:()=>Promise<void>;loseAck:()=>void;loseCreateReply:()=>void;failStorage:()=>void;failCatalog:()=>void;holdOpen:()=>void;resume:()=>void;seedPagination:()=>Promise<void>;seedRemote:()=>string;structuredSnapshot:()=>{data:import('@greiva/protocol').StructuredSnapshot;sent:string[]};rejectStructured:()=>void;loseStructuredAck:()=>void;loseStructuredMutationReply:()=>void;failStructuredStorage:()=>void;restoreStructuredStorage:()=>void;seedConflict:()=>Promise<void>};
declare global{interface Window{workspaceTest:Fixture}}
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const values:string[]=[];errors.set(page,values);page.on('pageerror',error=>values.push(error.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function login(page:Page){await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('認証を確認しました');await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeEnabled();}
async function create(page:Page,title='私のPage'){await page.getByLabel('新しいPageのタイトル',{exact:true}).fill(title);await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toBeVisible();}
test('WORKSPACE-SCREEN: login/create/keyboard edit/logout/relogin preserve unsent Page; ACK retry and native/browser boundaries',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('saved text');await page.evaluate(()=>window.workspaceTest.durable());const before=await page.evaluate(()=>window.workspaceTest.snapshot().pages);
 await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(body).toHaveCount(0);await login(page);await page.getByRole('complementary',{name:'Page一覧'}).getByRole('button',{name:'私のPage',exact:true}).click();await expect(body).toContainText('saved text');expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages)).toEqual(before);await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.loseAck());await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期エラー');await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');await expect(page.getByRole('complementary',{name:'Page一覧'}).getByText(/未確認の更新/)).toHaveCount(0);expect(await page.getByLabel('Pageタイトル',{exact:true}).evaluate(element=>getComputedStyle(element).color)).toBe(await page.locator('main').evaluate(element=>getComputedStyle(element).color));const wires=await page.evaluate(()=>window.workspaceTest.snapshot().sent);expect(wires[0]).toBe(wires[1]);
 await info.attach('workspace-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0});
});
test('WORKSPACE-TASKS: explicit Task/Relation CRUD, typed date/status, keyboard focus and logout/re-login keep unsent records',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);const panel=page.getByRole('region',{name:'TaskとRelation',exact:true}),title=page.getByLabel('Taskタイトル',{exact:true}),sync=page.getByRole('button',{name:'TaskとRelationを同期',exact:true});
 await title.fill('abcd');await page.getByRole('combobox',{name:'Task状態',exact:true}).selectOption('in_progress');await page.getByLabel('Task期限',{exact:true}).fill('2028-02-29');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await expect(panel.getByText('abcd',{exact:true})).toBeVisible();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('未確認の更新 1件');await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');
 await page.getByRole('button',{name:'Taskを編集: abcd',exact:true}).click();await expect(title).toBeFocused();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.insertText('X');await expect(title).toHaveValue('abXcd');await page.getByRole('button',{name:'Taskの変更を保存',exact:true}).click();await title.fill('second');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');
 const snapshot=await page.evaluate(()=>window.workspaceTest.structuredSnapshot()),one=snapshot.data.tasks.find(row=>row.title==='abXcd')!,two=snapshot.data.tasks.find(row=>row.title==='second')!;await page.getByRole('combobox',{name:'Relationの元',exact:true}).selectOption('task:'+one.id);await page.getByRole('combobox',{name:'Relationの先',exact:true}).selectOption('task:'+two.id);await page.getByRole('button',{name:'Relationを端末に保存',exact:true}).click();await expect(panel.getByText('Task: abXcd → Task: second',{exact:true})).toBeVisible();const pending=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations);
 await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(panel).toHaveCount(0);await login(page);expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations)).toEqual(pending);await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('未確認の更新 1件');await sync.click();const relationId=(await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.relations[0]!.id;
 await page.getByRole('button',{name:'Relationを編集: '+relationId,exact:true}).click();await expect(page.getByRole('combobox',{name:'Relationの元',exact:true})).toBeFocused();await page.getByRole('combobox',{name:'Relationの先',exact:true}).selectOption('task:'+one.id);await page.getByRole('button',{name:'Relationの変更を保存',exact:true}).click();await sync.click();await page.getByRole('button',{name:'Relationを削除: '+relationId,exact:true}).click();await sync.click();await page.getByRole('button',{name:'Taskを削除: second',exact:true}).click();await sync.click();await expect(page.getByRole('button',{name:'Taskを編集: second',exact:true})).toHaveCount(0);expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.tasks.find(row=>row.id===two.id)!.deletedAt).not.toBeNull();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.getByLabel('Task期限',{exact:true})).toHaveCSS('color-scheme',info.project.name==='desktop'?'light':'dark');await info.attach('workspace-structured-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
});
test('WORKSPACE-TASKS: unknown mutation result, composition, failed draft and ACK loss preserve one intent and copyable input',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);const title=page.getByLabel('Taskタイトル',{exact:true}),save=page.getByRole('button',{name:'Taskを端末に保存',exact:true}),sync=page.getByRole('button',{name:'TaskとRelationを同期',exact:true});await title.fill('copy draft');await title.dispatchEvent('compositionstart');await expect(save).toBeDisabled();await expect(page.getByRole('button',{name:'接続を閉じる',exact:true})).toBeDisabled();await title.dispatchEvent('compositionend');await page.evaluate(()=>window.workspaceTest.failStructuredStorage());await save.click();await expect(page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true})).toBeVisible();await expect(title).toHaveValue('copy draft');await expect(title).toHaveAttribute('readonly','');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-task');await page.evaluate(()=>window.workspaceTest.restoreStructuredStorage());await page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true}).click();await expect(page.getByRole('button',{name:'Taskを編集: copy draft',exact:true})).toBeVisible();
 await title.fill('unknown reply');await page.evaluate(()=>window.workspaceTest.loseStructuredMutationReply());await save.click();const before=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.map(row=>row.operationId));await page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.map(row=>row.operationId))).toEqual(before);
 await page.evaluate(()=>window.workspaceTest.loseStructuredAck());await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('同期を確認できませんでした');await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');const wires=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().sent);expect(wires[0]).toBe(wires[1]);
});
test('WORKSPACE-TASKS: conflict exposes base/local/remote and records an explicit resolution as a new operation',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.getByLabel('Taskタイトル',{exact:true}).fill('base');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');await page.evaluate(()=>window.workspaceTest.seedConflict());const conflict=page.getByRole('region',{name:'TaskとRelationの競合',exact:true});await expect(conflict.getByText('base',{exact:true})).toBeVisible();await expect(conflict.getByText('local',{exact:true})).toBeVisible();await expect(conflict.getByText('remote',{exact:true})).toBeVisible();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('競合を確認してください');const before=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.length);await conflict.getByRole('button',{name:'この端末の値を選ぶ',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.length)).toBe(before+1);await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(conflict).toHaveCount(0);await expect(page.getByRole('button',{name:'Taskを編集: local',exact:true})).toBeVisible();expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.conflicts[0]!.resolvedBy).toBeTruthy();
});
test('WORKSPACE-TASKS: unsaved draft and rejected updates remain distinct from sync confirmation without server error text',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');await page.getByLabel('Taskタイトル',{exact:true}).fill('rejected task');await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('入力内容はまだ保存していません');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.rejectStructured());await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('拒否された更新があります');await expect(page.getByRole('region',{name:'拒否された更新',exact:true})).toContainText('Task: rejected task / 作成が拒否されました');expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.operations[0]!.status).toBe('rejected');await expect(page.locator('body')).not.toContainText('fixture-private-server');await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('拒否された更新があります');
});
test('WORKSPACE-SCREEN: remote selection checks local presence beyond first page and remote-only download remains unconfirmed',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.seedPagination());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'サーバーで見える次のPage',exact:true}).click();await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('一覧の次のPage');expect(await page.evaluate(()=>window.workspaceTest.snapshot().reads)).toEqual([]);
 await page.getByRole('button',{name:'端末一覧をさらに表示',exact:true}).click();await expect(page.getByRole('button',{name:'一覧の次のPage',exact:true})).toBeVisible();
 await page.evaluate(()=>window.workspaceTest.seedRemote());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'遠隔のPage',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.failCatalog());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await expect(page.getByText('一覧を取得できませんでした。表示中の一覧があれば、以前の取得結果です。')).toBeVisible();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');
});
test('WORKSPACE-SCREEN: close during native open suppresses late ready; production Web has no persistence fallback',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await page.evaluate(()=>window.workspaceTest.holdOpen());await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByText('端末のworkspaceを開いています…')).toBeVisible();await page.getByRole('button',{name:'接続を閉じる',exact:true}).click();await page.evaluate(()=>window.workspaceTest.resume());await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('ログインしていません');await expect(page.getByRole('complementary',{name:'Page一覧'})).toHaveCount(0);
 await page.goto('/workspace.html');await expect(page.getByRole('button',{name:'ログイン',exact:true})).toBeDisabled();await expect(page.getByText('端末への保存に対応したアプリで開いてください。')).toBeVisible();
});
test('WORKSPACE-SCREEN: status/catalog rendering preserves selection/composition and uncertain create retries one ID',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.loseCreateReply());await page.getByLabel('新しいPageのタイトル',{exact:true}).fill('one create');await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('button',{name:'同じPageの作成を再確認',exact:true})).toBeEnabled();await page.getByRole('button',{name:'同じPageの作成を再確認',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages.length)).toBe(1);
 const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('abcd');await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'端末一覧を更新',exact:true}).click();await expect(page.getByRole('button',{name:'端末一覧を更新',exact:true})).toBeEnabled();await body.focus();await page.keyboard.type('X');await expect(body).toContainText('abXcd');
 await body.dispatchEvent('compositionstart');await page.evaluate(()=>window.workspaceTest.refreshLocal());expect(await page.evaluate(()=>window.workspaceTest.snapshot().composing)).toBe(true);await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await body.dispatchEvent('compositionend');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeEnabled();
});
test('WORKSPACE-SCREEN: failed commit retains copyable draft and blocks destructive navigation without leaking causes',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);await page.evaluate(()=>window.workspaceTest.failStorage());const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.insertText('copy draft');await expect(page.getByLabel('端末の保存状態',{exact:true})).toContainText('保存できません');await expect(body).toContainText('copy draft');await expect(body).toHaveAttribute('contenteditable','false');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-email');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
