import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
type Fixture={resolveRemoteTitle:()=>string|null;changesSnapshot:()=>{state:import('../../apps/client/src/workspace/private-changes-session.js').PrivateChangesState|null;cached:unknown[];pulls:unknown[];receives:number};loseChangesReply:()=>void;failChangesTransport:()=>void;restoreChangesTransport:()=>void;holdChanges:()=>void;titleSnapshot:()=>{state:import('../../apps/client/src/workspace/private-title-session.js').PrivateTitleState|null;sent:string[];records:import('@greiva/protocol/private-page-metadata').PrivatePageTitleLocalResponse['operations']};loseTitleAck:()=>void;loseTitleMutationReply:()=>void;failTitleStorage:()=>void;restoreTitleStorage:()=>void;rejectTitle:()=>void;remoteTitle:(value:string)=>void;seedTitleCandidates:()=>void;refreshTitle:()=>Promise<void>|undefined;snapshot:()=>{pages:{id:string;title:string;wires:string[]}[];reads:string[];sent:string[];composing:boolean};durable:()=>Promise<void>;refreshLocal:()=>Promise<void>;loseAck:()=>void;loseCreateReply:()=>void;failStorage:()=>void;failCatalog:()=>void;holdOpen:()=>void;resume:()=>void;seedPagination:()=>Promise<void>;seedRemote:()=>string;structuredSnapshot:()=>{data:import('@greiva/protocol').StructuredSnapshot;sent:string[]};rejectStructured:()=>void;loseStructuredAck:()=>void;loseStructuredMutationReply:()=>void;failStructuredStorage:()=>void;restoreStructuredStorage:()=>void;seedConflict:()=>Promise<void>};
declare global{interface Window{workspaceTest:Fixture}}
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const values:string[]=[];errors.set(page,values);page.on('pageerror',error=>values.push(error.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function login(page:Page){await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('認証を確認しました');await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeEnabled();}
async function create(page:Page,title='私のPage'){await page.getByLabel('新しいPageのタイトル',{exact:true}).fill(title);await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toBeVisible();}
test('WORKSPACE-SCREEN: login/create/keyboard edit/logout/relogin preserve unsent Page; ACK retry and native/browser boundaries',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('saved text');await page.evaluate(()=>window.workspaceTest.durable());const before=await page.evaluate(()=>window.workspaceTest.snapshot().pages);
 await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(body).toHaveCount(0);await login(page);await page.getByRole('complementary',{name:'Page一覧'}).getByRole('button',{name:'私のPage',exact:true}).click();await expect(body).toContainText('saved text');expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages)).toEqual(before);await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.loseAck());await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期エラー');await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');await expect(page.getByRole('complementary',{name:'Page一覧'}).getByText(/未確認の更新/)).toHaveCount(0);expect(await page.getByLabel('Pageタイトル',{exact:true}).evaluate(element=>getComputedStyle(element).color)).toBe(await page.locator('main').evaluate(element=>getComputedStyle(element).color));const wires=await page.evaluate(()=>window.workspaceTest.snapshot().sent);expect(wires[0]).toBe(wires[1]);
 await info.attach('workspace-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0});
});
test('WORKSPACE-TASKS: explicit Task/Relation CRUD, typed date/status, keyboard focus and logout/re-login keep unsent records',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);const panel=page.getByRole('region',{name:'TaskとRelation',exact:true}),title=page.getByLabel('Taskタイトル',{exact:true}),sync=page.getByRole('button',{name:'TaskとRelationを同期',exact:true});
 await title.fill('abcd');await page.getByRole('combobox',{name:'Task状態',exact:true}).selectOption('in_progress');await page.getByLabel('Task期限',{exact:true}).fill('2028-02-29');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await expect(panel.getByText('abcd',{exact:true})).toBeVisible();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('未確認の更新 1件');await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');
 await page.getByRole('button',{name:'Taskを編集: abcd',exact:true}).click();await expect(title).toBeFocused();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.insertText('X');await expect(title).toHaveValue('abXcd');await page.getByRole('button',{name:'Taskの変更を保存',exact:true}).click();await title.fill('second');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');
 const snapshot=await page.evaluate(()=>window.workspaceTest.structuredSnapshot()),one=snapshot.data.tasks.find(row=>row.title==='abXcd')!,two=snapshot.data.tasks.find(row=>row.title==='second')!;await page.getByRole('combobox',{name:'Relationの元',exact:true}).selectOption('task:'+one.id);await page.getByRole('combobox',{name:'Relationの先',exact:true}).selectOption('task:'+two.id);await page.getByRole('button',{name:'Relationを端末に保存',exact:true}).click();await expect(panel.getByText('Task: abXcd → Task: second',{exact:true})).toBeVisible();const pending=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations);
 await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(panel).toHaveCount(0);await login(page);expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations)).toEqual(pending);await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('未確認の更新 1件');await sync.click();const relationId=(await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.relations[0]!.id;
 await page.getByRole('button',{name:'Relationを編集: '+relationId,exact:true}).click();await expect(page.getByRole('combobox',{name:'Relationの元',exact:true})).toBeFocused();await page.getByRole('combobox',{name:'Relationの先',exact:true}).selectOption('task:'+one.id);await page.getByRole('button',{name:'Relationの変更を保存',exact:true}).click();await sync.click();await page.getByRole('button',{name:'Relationを削除: '+relationId,exact:true}).click();await sync.click();await page.getByRole('button',{name:'Taskを削除: second',exact:true}).click();await sync.click();await expect(page.getByRole('button',{name:'Taskを編集: second',exact:true})).toHaveCount(0);expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.tasks.find(row=>row.id===two.id)!.deletedAt).not.toBeNull();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.getByLabel('Task期限',{exact:true})).toHaveCSS('color-scheme',info.project.name==='desktop'?'light':'dark');await info.attach('workspace-structured-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
});
test('WORKSPACE-TASKS: unknown mutation result, composition, failed draft and ACK loss preserve one intent and copyable input',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);const title=page.getByLabel('Taskタイトル',{exact:true}),save=page.getByRole('button',{name:'Taskを端末に保存',exact:true}),sync=page.getByRole('button',{name:'TaskとRelationを同期',exact:true});await title.fill('copy draft');await title.dispatchEvent('compositionstart');await expect(save).toBeDisabled();await expect(page.getByRole('button',{name:'接続を閉じる',exact:true})).toBeDisabled();await title.dispatchEvent('compositionend');await page.evaluate(()=>window.workspaceTest.failStructuredStorage());await save.click();await expect(page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true})).toBeVisible();await expect(title).toHaveValue('copy draft');await expect(title).toHaveAttribute('readonly','');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-task');await page.evaluate(()=>window.workspaceTest.restoreStructuredStorage());await page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true}).click();await expect(page.getByRole('button',{name:'Taskを編集: copy draft',exact:true})).toBeVisible();
 await title.fill('unknown reply');await page.evaluate(()=>window.workspaceTest.loseStructuredMutationReply());await save.click();const before=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.map(row=>row.operationId));await page.getByRole('button',{name:'同じ更新の保存を再確認',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.map(row=>row.operationId))).toEqual(before);
 await page.evaluate(()=>window.workspaceTest.loseStructuredAck());await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('同期を確認できませんでした');await sync.click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');const wires=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().sent);expect(wires[0]).toBe(wires[1]);
});
test('WORKSPACE-TASKS: conflict exposes base/local/remote and records an explicit resolution as a new operation',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.getByLabel('Taskタイトル',{exact:true}).fill('base');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');await page.evaluate(()=>window.workspaceTest.seedConflict());const conflict=page.getByRole('region',{name:'TaskとRelationの競合',exact:true});await expect(conflict.getByText('base',{exact:true})).toBeVisible();await expect(conflict.getByText('local',{exact:true})).toBeVisible();await expect(conflict.getByText('remote',{exact:true})).toBeVisible();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('競合を確認してください');const before=await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.length);await conflict.getByRole('button',{name:'この端末の値を選ぶ',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.structuredSnapshot().data.operations.length)).toBe(before+1);await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(conflict).toHaveCount(0);await expect(page.getByRole('button',{name:'Taskを編集: local',exact:true})).toBeVisible();expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.conflicts[0]!.resolvedBy).toBeTruthy();
});
test('WORKSPACE-TASKS: unsaved draft and rejected updates remain distinct from sync confirmation without server error text',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('取得した更新まで同期済み');await page.getByLabel('Taskタイトル',{exact:true}).fill('rejected task');await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('入力内容はまだ保存していません');await page.getByRole('button',{name:'Taskを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.rejectStructured());await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('拒否された更新があります');await expect(page.getByRole('region',{name:'拒否された更新',exact:true})).toContainText('Task: rejected task / 作成が拒否されました');expect((await page.evaluate(()=>window.workspaceTest.structuredSnapshot())).data.operations[0]!.status).toBe('rejected');await expect(page.locator('body')).not.toContainText('fixture-private-server');await page.getByRole('button',{name:'TaskとRelationを同期',exact:true}).click();await expect(page.getByLabel('TaskとRelationの同期状態')).toHaveText('拒否された更新があります');
});
test('WORKSPACE-SCREEN: remote selection checks local presence beyond first page and remote-only download remains unconfirmed',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.seedPagination());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'サーバーで見える次のPage',exact:true}).click();await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('一覧の次のPage');expect(await page.evaluate(()=>window.workspaceTest.snapshot().reads)).toEqual([]);
 await page.getByRole('button',{name:'端末一覧をさらに表示',exact:true}).click();await expect(page.getByRole('button',{name:'一覧の次のPage',exact:true})).toBeVisible();
 await page.evaluate(()=>window.workspaceTest.seedRemote());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'遠隔のPage',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.failCatalog());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await expect(page.getByText('一覧を取得できませんでした。表示中の一覧があれば、以前の取得結果です。')).toBeVisible();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');
});
test('WORKSPACE-SCREEN: close during native open suppresses late ready; production Web has no persistence fallback',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await page.evaluate(()=>window.workspaceTest.holdOpen());await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByText('端末のworkspaceを開いています…')).toBeVisible();await page.getByRole('button',{name:'接続を閉じる',exact:true}).click();await page.evaluate(()=>window.workspaceTest.resume());await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('ログインしていません');await expect(page.getByRole('complementary',{name:'Page一覧'})).toHaveCount(0);
 await page.goto('/workspace.html');await expect(page.getByRole('button',{name:'ログイン',exact:true})).toBeDisabled();await expect(page.getByText('端末への保存に対応したアプリで開いてください。')).toBeVisible();
});
test('WORKSPACE-SCREEN: status/catalog rendering preserves selection/composition and uncertain create retries one ID',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.loseCreateReply());await page.getByLabel('新しいPageのタイトル',{exact:true}).fill('one create');await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('button',{name:'同じPageの作成を再確認',exact:true})).toBeEnabled();await page.getByRole('button',{name:'同じPageの作成を再確認',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages.length)).toBe(1);
 const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('abcd');await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'端末一覧を更新',exact:true}).click();await expect(page.getByRole('button',{name:'端末一覧を更新',exact:true})).toBeEnabled();await body.focus();await page.keyboard.type('X');await expect(body).toContainText('abXcd');
 await body.dispatchEvent('compositionstart');await page.evaluate(()=>window.workspaceTest.refreshLocal());expect(await page.evaluate(()=>window.workspaceTest.snapshot().composing)).toBe(true);await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await body.dispatchEvent('compositionend');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeEnabled();
});
test('WORKSPACE-SCREEN: failed commit retains copyable draft and blocks destructive navigation without leaking causes',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);await page.evaluate(()=>window.workspaceTest.failStorage());const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.insertText('copy draft');await expect(page.getByLabel('端末の保存状態',{exact:true})).toContainText('保存できません');await expect(body).toContainText('copy draft');await expect(body).toHaveAttribute('contenteditable','false');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-email');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

async function titleReady(page:Page){await create(page,'title base');await page.getByRole('button',{name:'タイトルを送信・確認',exact:true}).click();await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('取得したタイトルを確認しました');}
test('WORKSPACE-CHANGES: explicit catalog keeps remote-only body distinction, authorized opening and retained cache after relogin',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.seedRemote());const panel=page.getByRole('region',{name:'保存済みのPage情報',exact:true}),status=page.getByLabel('Page情報の取得状態',{exact:true});expect((await page.evaluate(()=>window.workspaceTest.changesSnapshot())).pulls).toHaveLength(0);await expect(status).toHaveText('Page情報はまだ取得していません');await panel.getByRole('button',{name:'Page情報を取得',exact:true}).click();await expect(status).toHaveText('前回取得した範囲の末尾まで保存しました');await expect(panel.getByText('本文は未取得',{exact:true})).toBeVisible();expect((await page.evaluate(()=>window.workspaceTest.snapshot())).pages).toEqual([]);await panel.getByRole('button',{name:'遠隔のPage',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');await expect(panel.getByText('本文を端末に保存済み',{exact:true})).toBeVisible();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(panel).toHaveCount(0);await login(page);await expect(status).toHaveText('以前取得した情報を表示しています');await expect(panel.getByRole('button',{name:'遠隔のPage',exact:true})).toBeVisible();expect((await page.evaluate(()=>window.workspaceTest.changesSnapshot())).pulls).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await info.attach('workspace-changes-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
});
test('WORKSPACE-CHANGES: unknown native receipt preserves prior list and exact retry uses no new network, transport error retains cache',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>{window.workspaceTest.seedRemote();window.workspaceTest.loseChangesReply();});const panel=page.getByRole('region',{name:'保存済みのPage情報',exact:true}),status=page.getByLabel('Page情報の取得状態',{exact:true});await panel.getByRole('button',{name:'Page情報を取得',exact:true}).click();await expect(status).toHaveText('受信した情報の保存を再確認してください');await expect(panel.getByRole('button',{name:'遠隔のPage',exact:true})).toHaveCount(0);await expect(panel.getByRole('button',{name:'Page情報を取得',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'受信した情報の保存を再確認',exact:true}).click();await expect(status).toHaveText('前回取得した範囲の末尾まで保存しました');expect(await page.evaluate(()=>({pulls:window.workspaceTest.changesSnapshot().pulls.length,receives:window.workspaceTest.changesSnapshot().receives}))).toEqual({pulls:1,receives:2});await page.evaluate(()=>window.workspaceTest.failChangesTransport());await panel.getByRole('button',{name:'Page情報を取得',exact:true}).click();await expect(status).toHaveText('Page情報を取得できませんでした');await expect(panel.getByRole('button',{name:'遠隔のPage',exact:true})).toBeVisible();await expect(page.locator('body')).not.toContainText('fixture-private-changes');await expect(panel.getByRole('button',{name:'受信した情報の保存を再確認',exact:true})).toHaveCount(0);
});
test('WORKSPACE-CHANGES: late receipt preserves dirty IME composition, focus/selection and body node until explicit input ends',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true}),body=page.getByRole('textbox',{name:'Page本文',exact:true}),panel=page.getByRole('region',{name:'保存済みのPage情報',exact:true});await body.evaluate(element=>element.setAttribute('data-preserved-node','same'));await page.evaluate(()=>{window.workspaceTest.remoteTitle('remote received');window.workspaceTest.holdChanges();});await panel.getByRole('button',{name:'Page情報を取得',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.workspaceTest.changesSnapshot().pulls.length)).toBe(1);await input.fill('abXcd');await input.focus();await input.evaluate(element=>(element as HTMLInputElement).setSelectionRange(2,3));await input.dispatchEvent('compositionstart');await page.evaluate(()=>window.workspaceTest.resume());await expect(panel.getByRole('button',{name:'remote received',exact:true})).toBeVisible();await expect(input).toHaveValue('abXcd');await expect(input).toBeFocused();await expect(input).not.toHaveAttribute('readonly');expect(await input.evaluate(element=>({start:(element as HTMLInputElement).selectionStart,end:(element as HTMLInputElement).selectionEnd}))).toEqual({start:2,end:3});await expect(body).toHaveAttribute('data-preserved-node','same');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'受信したタイトルの表示を更新',exact:true})).toBeDisabled();await input.dispatchEvent('compositionend');await expect(input).toHaveValue('abXcd');await page.getByRole('button',{name:'タイトル入力を取り消す',exact:true}).click();await expect(input).toHaveValue('remote received');await expect(input).toBeFocused();await expect(body).toHaveAttribute('data-preserved-node','same');await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('WORKSPACE-CHANGES: another device resolution removes an actionable candidate without changing body sync state',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);await page.getByLabel('タイトルを編集',{exact:true}).fill('offline choice');await page.getByRole('button',{name:'タイトルを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.remoteTitle('remote choice'));await page.getByRole('button',{name:'タイトルを送信・確認',exact:true}).click();await expect(page.getByRole('button',{name:'取得したタイトルを選ぶ',exact:true})).toBeVisible();const resolvedBy=await page.evaluate(()=>window.workspaceTest.resolveRemoteTitle());expect(resolvedBy).not.toBeNull();await page.getByRole('button',{name:'Page情報を取得',exact:true}).click();await expect(page.getByRole('button',{name:'取得したタイトルを選ぶ',exact:true})).toHaveCount(0);expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.data!.conflicts[0]!.resolvedBy).toBe(resolvedBy);await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');
});
test('WORKSPACE-TITLE: keyboard save, offline rename, sidebar pending and relogin preserve title separately from body sync',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true});await input.fill('saved title');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await input.press('Enter');await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('未確認のタイトル変更 1件');await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('saved title');await expect(page.getByRole('complementary',{name:'Page一覧'})).toContainText('タイトル未確認 1件');await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');
 const ids=await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.map(row=>row.intent.operationId));await page.getByRole('button',{name:'ログアウト',exact:true}).click();await login(page);await expect(page.getByRole('complementary',{name:'Page一覧'})).toContainText('タイトル未確認 1件');await page.getByRole('complementary',{name:'Page一覧'}).getByRole('button',{name:'saved title',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.map(row=>row.intent.operationId))).toEqual(ids);await expect(input).toHaveValue('saved title');await page.getByRole('button',{name:'タイトルを送信・確認',exact:true}).click();await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('取得したタイトルを確認しました');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await info.attach('workspace-title-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
});
test('WORKSPACE-TITLE: composition, local refresh and dirty input preserve focus/selection and block navigation/submit',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true}),save=page.getByRole('button',{name:'タイトルを端末に保存',exact:true});await input.fill('abXcd');await input.focus();await input.evaluate(element=>(element as HTMLInputElement).setSelectionRange(2,3));await input.dispatchEvent('compositionstart');await page.evaluate(()=>window.workspaceTest.refreshTitle());await expect(input).toBeFocused();expect(await input.evaluate(element=>({start:(element as HTMLInputElement).selectionStart,end:(element as HTMLInputElement).selectionEnd}))).toEqual({start:2,end:3});await expect(input).toHaveValue('abXcd');await expect(input).not.toHaveAttribute('readonly');await expect(save).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await input.press('Enter');expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.length)).toBe(0);await input.dispatchEvent('compositionend');await expect(save).toBeEnabled();await expect(page.getByRole('button',{name:'タイトルを送信・確認',exact:true})).toBeDisabled();await save.click();await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('abXcd');
});
test('WORKSPACE-TITLE: unknown local save and failed storage preserve copyable draft and retry same operation',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true}),save=page.getByRole('button',{name:'タイトルを端末に保存',exact:true}),retry=page.getByRole('button',{name:'同じタイトルの保存を再確認',exact:true});await input.fill('copy title');await page.evaluate(()=>window.workspaceTest.failTitleStorage());await save.click();await expect(retry).toBeVisible();await expect(input).toHaveValue('copy title');await expect(input).toHaveAttribute('readonly','');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-title');await page.evaluate(()=>window.workspaceTest.restoreTitleStorage());await retry.click();await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('未確認のタイトル変更 1件');await input.fill('unknown title reply');await page.evaluate(()=>window.workspaceTest.loseTitleMutationReply());await save.click();const ids=await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.map(row=>row.intent.operationId));await retry.click();expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.map(row=>row.intent.operationId))).toEqual(ids);await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('未確認のタイトル変更 2件');
});
test('WORKSPACE-TITLE: lost HTTP ACK keeps pending and sends exact same immutable request on retry',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);await page.getByLabel('タイトルを編集',{exact:true}).fill('retained title');await page.getByRole('button',{name:'タイトルを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.loseTitleAck());const sync=page.getByRole('button',{name:'タイトルを送信・確認',exact:true});await sync.click();await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('タイトルを確認できませんでした');expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.pending).toBe(1);await sync.click();await expect(page.getByLabel('タイトルの確認状態',{exact:true})).toHaveText('取得したタイトルを確認しました');const wires=(await page.evaluate(()=>window.workspaceTest.titleSnapshot())).sent;expect(wires[0]).toBe(wires[1]);
});
test('WORKSPACE-TITLE: base/local/remote choices create new resolution and retain resolved history',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);await page.getByLabel('タイトルを編集',{exact:true}).fill('local title');await page.getByRole('button',{name:'タイトルを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.remoteTitle('remote title'));const sync=page.getByRole('button',{name:'タイトルを送信・確認',exact:true});await sync.click();const cf=page.getByRole('region',{name:'タイトルの競合候補',exact:true});await expect(cf.getByText('title base',{exact:true})).toBeVisible();await expect(cf.getByText('local title',{exact:true})).toBeVisible();await expect(cf.getByText('remote title',{exact:true})).toBeVisible();const before=await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.length);await cf.getByRole('button',{name:'このタイトル入力を選ぶ',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.length)).toBe(before+1);await sync.click();await expect(cf).toHaveCount(0);await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('local title');expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.data!.conflicts[0]!.resolvedBy).toBeTruthy();
});
test('WORKSPACE-TITLE: rejected resolution keeps candidate and original input without private server error text',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);await page.getByLabel('タイトルを編集',{exact:true}).fill('local rejection');await page.getByRole('button',{name:'タイトルを端末に保存',exact:true}).click();await page.evaluate(()=>window.workspaceTest.remoteTitle('remote rejection'));const sync=page.getByRole('button',{name:'タイトルを送信・確認',exact:true});await sync.click();const cf=page.getByRole('region',{name:'タイトルの競合候補',exact:true});await cf.getByRole('button',{name:'このタイトル入力を選ぶ',exact:true}).click();await page.evaluate(()=>window.workspaceTest.rejectTitle());await sync.click();await expect(cf).toBeVisible();await expect(page.getByRole('region',{name:'拒否されたタイトル変更',exact:true})).toContainText('local rejection');await expect(page.locator('body')).not.toContainText('fixture-private-title');const value=await page.evaluate(()=>window.workspaceTest.titleSnapshot());expect(value.state!.data!.conflicts[0]!.resolvedBy).toBeNull();expect(value.records.at(-1)!.response!.result.status).toBe('rejected');
});
test('WORKSPACE-TITLE: remote and local candidate pagination stays bounded and dirty cancellation restores latest saved title',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);await page.evaluate(()=>window.workspaceTest.seedTitleCandidates());await page.getByRole('button',{name:'タイトルを送信・確認',exact:true}).click();expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.data!.conflicts.length).toBe(100);await page.getByRole('button',{name:'タイトル候補の続きも確認',exact:true}).click();await page.getByRole('button',{name:'保存済み候補・履歴の続き',exact:true}).click();expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.data!.conflicts.length).toBe(1);await page.getByRole('button',{name:'候補・履歴を先頭へ',exact:true}).click();expect((await page.evaluate(()=>window.workspaceTest.titleSnapshot())).state!.data!.conflicts.length).toBe(100);const input=page.getByLabel('タイトルを編集',{exact:true});await input.fill('unsaved');await page.getByRole('button',{name:'タイトル入力を取り消す',exact:true}).click();await expect(input).toHaveValue('remote');await expect(input).toBeFocused();await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeEnabled();
});

test('WORKSPACE-HELP: unsigned-in offline local search, categories, related articles and manifest version do not send queries',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await page.getByLabel('メールアドレス',{exact:true}).fill('private-help@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('private-help-secret');const requests:string[]=[];page.on('request',request=>requests.push(request.url()));await page.context().setOffline(true);
 await page.getByRole('button',{name:'ヘルプ・アプリ情報',exact:true}).click();const dialog=page.getByRole('dialog',{name:'ヘルプ・アプリ情報',exact:true}),search=dialog.getByRole('searchbox',{name:'ヘルプ内を検索',exact:true});await expect(search).toBeFocused();await expect(dialog.getByLabel('アプリ版',{exact:true})).toHaveText('Greiva '+JSON.parse(readFileSync(new URL('../../apps/client/package.json',import.meta.url),'utf8')).version);
 await search.fill('private-help-secret');await expect(dialog.getByLabel('ヘルプ検索結果',{exact:true})).toHaveText('0件の記事');await expect(search).toHaveValue('private-help-secret');await search.fill('ＯＦＦＬＩＮＥ');await expect(dialog.getByRole('navigation',{name:'ヘルプの記事'}).getByRole('button',{name:'端末保存とサーバー同期の違い',exact:true})).toBeVisible();await search.press('Enter');await expect(dialog.getByRole('heading',{name:'接続プレビューを使い始める',exact:true})).toBeVisible();await dialog.getByRole('navigation',{name:'ヘルプの記事'}).getByRole('button',{name:'端末保存とサーバー同期の違い',exact:true}).click();await expect(dialog.getByRole('heading',{name:'端末保存とサーバー同期の違い',exact:true})).toBeFocused();await dialog.getByRole('region',{name:'関連するヘルプ'}).getByRole('button',{name:'保存エラー・保存結果不明に対処する',exact:true}).click();await expect(dialog.getByRole('heading',{name:'保存エラー・保存結果不明に対処する',exact:true})).toBeFocused();await dialog.getByRole('button',{name:'検索をクリア',exact:true}).click();await dialog.getByRole('combobox',{name:'ヘルプカテゴリ',exact:true}).selectOption('tasks');await expect(dialog.getByLabel('ヘルプ検索結果',{exact:true})).toHaveText('1件の記事');await dialog.getByRole('navigation',{name:'ヘルプの記事'}).getByRole('button',{name:'TaskとRelationを使う',exact:true}).click();await expect(dialog.getByRole('heading',{name:'TaskとRelationを使う',exact:true})).toBeFocused();expect(await dialog.evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);
 await info.attach('workspace-help-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});expect(requests).toEqual([]);await dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByLabel('パスワード',{exact:true})).toHaveValue('private-help-secret');await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('ログインしていません');
});
test('WORKSPACE-HELP: dirty title and Task drafts retain selection, focus and immutable unsent records',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true}),task=page.getByLabel('Taskタイトル',{exact:true}),launcher=page.getByRole('button',{name:'ヘルプ・アプリ情報',exact:true});await task.fill('private unsaved Task');await input.fill('abXcd');await input.focus();await input.evaluate(node=>(node as HTMLInputElement).setSelectionRange(2,3,'backward'));const before=await page.evaluate(()=>({title:window.workspaceTest.titleSnapshot().records,structured:window.workspaceTest.structuredSnapshot(),body:window.workspaceTest.snapshot()}));
 await launcher.click();const dialog=page.getByRole('dialog',{name:'ヘルプ・アプリ情報',exact:true});await dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true}).click();await expect(input).toBeFocused();await expect(input).toHaveValue('abXcd');await expect(task).toHaveValue('private unsaved Task');expect(await input.evaluate(node=>({start:(node as HTMLInputElement).selectionStart,end:(node as HTMLInputElement).selectionEnd,direction:(node as HTMLInputElement).selectionDirection}))).toEqual({start:2,end:3,direction:'backward'});expect(await page.evaluate(()=>({title:window.workspaceTest.titleSnapshot().records,structured:window.workspaceTest.structuredSnapshot(),body:window.workspaceTest.snapshot()}))).toEqual(before);await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await page.keyboard.insertText('Y');await expect(input).toHaveValue('abYcd');
});
test('WORKSPACE-HELP: Page body remains mounted and its selection returns without a sync or local mutation',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.insertText('saved text');await page.evaluate(()=>window.workspaceTest.durable());await body.evaluate(node=>{node.setAttribute('data-help-origin','same');const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);let text:Node|null;while((text=walker.nextNode()))if(text.textContent==='saved text'){const range=document.createRange();range.setStart(text,2);range.setEnd(text,5);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);break;}});const before=await page.evaluate(()=>window.workspaceTest.snapshot());expect(await page.evaluate(()=>window.getSelection()?.toString())).toBe('ved');await page.getByRole('button',{name:'ヘルプ・アプリ情報',exact:true}).click();await page.getByRole('button',{name:'ヘルプを閉じる',exact:true}).click();await expect(body).toBeFocused();await expect(body).toHaveAttribute('data-help-origin','same');expect(await page.evaluate(()=>window.getSelection()?.toString())).toBe('ved');expect(await page.evaluate(()=>window.workspaceTest.snapshot())).toEqual(before);
});
test('WORKSPACE-HELP: composition guards entry, Enter and Escape; keyboard dismissal returns to its launcher',async({page})=>{
 await page.goto('/private-workspace.fixture.html');const input=page.getByLabel('メールアドレス',{exact:true}),launcher=page.getByRole('button',{name:'ヘルプ・アプリ情報',exact:true});await input.focus();await input.dispatchEvent('compositionstart');await expect(launcher).toBeDisabled();await expect(input).toBeFocused();await input.dispatchEvent('compositionend');await expect(launcher).toBeEnabled();await launcher.focus();await launcher.press('Enter');const dialog=page.getByRole('dialog',{name:'ヘルプ・アプリ情報',exact:true}),search=dialog.getByRole('searchbox',{name:'ヘルプ内を検索',exact:true});await expect(search).toBeFocused();await search.dispatchEvent('compositionstart');await search.fill('保存');await search.press('Enter');await search.press('Escape');await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true})).toBeDisabled();await search.dispatchEvent('compositionend');await expect(dialog.getByRole('heading',{name:'接続プレビューを使い始める',exact:true})).toBeVisible();await search.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(launcher).toBeFocused();
});
test('WORKSPACE-HELP: contextual unknown title-save guidance leaves exact retry and copyable draft untouched',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await titleReady(page);const input=page.getByLabel('タイトルを編集',{exact:true});await input.fill('unknown saved title');await page.evaluate(()=>window.workspaceTest.loseTitleMutationReply());await page.getByRole('button',{name:'タイトルを端末に保存',exact:true}).click();const retry=page.getByRole('button',{name:'同じタイトルの保存を再確認',exact:true});await expect(retry).toBeEnabled();const before=await page.evaluate(()=>window.workspaceTest.titleSnapshot());await page.getByRole('button',{name:'端末保存に失敗したときの説明を読む',exact:true}).click();const dialog=page.getByRole('dialog',{name:'ヘルプ・アプリ情報',exact:true});await expect(dialog.getByRole('heading',{name:'保存エラー・保存結果不明に対処する',exact:true})).toBeFocused();await expect(dialog.getByRole('article',{name:'ヘルプ本文'})).toContainText('同じタイトルの保存を再確認');await info.attach('workspace-help-storage-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true}).click();await expect(input).toHaveValue('unknown saved title');expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot())).toEqual(before);await expect(retry).toBeEnabled();await retry.click();expect(await page.evaluate(()=>window.workspaceTest.titleSnapshot().records.map(row=>row.intent.operationId))).toEqual(before.records.map(row=>row.intent.operationId));
});
test('WORKSPACE-HELP: metadata context explains cached progress without fetching or acknowledging pending body',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.insertText('unsent body');await page.evaluate(()=>window.workspaceTest.durable());const before=await page.evaluate(()=>({changes:window.workspaceTest.changesSnapshot(),body:window.workspaceTest.snapshot()}));await page.getByRole('button',{name:'Page情報の使い方を読む',exact:true}).click();const dialog=page.getByRole('dialog',{name:'ヘルプ・アプリ情報',exact:true});await expect(dialog.getByRole('heading',{name:'Page情報と本文を取得する',exact:true})).toBeFocused();await expect(dialog.getByRole('article',{name:'ヘルプ本文'})).toContainText('本文や未送信タイトルの同期完了を表しません');await dialog.getByRole('button',{name:'ヘルプを閉じる',exact:true}).click();expect(await page.evaluate(()=>({changes:window.workspaceTest.changesSnapshot(),body:window.workspaceTest.snapshot()}))).toEqual(before);await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
});
