import {test,expect,type Page} from '@playwright/test';
type Fixture={snapshot:()=>{pages:{id:string;title:string;wires:string[]}[];reads:string[];sent:string[];composing:boolean};durable:()=>Promise<void>;refreshLocal:()=>Promise<void>;loseAck:()=>void;loseCreateReply:()=>void;failStorage:()=>void;failCatalog:()=>void;holdOpen:()=>void;resume:()=>void;seedPagination:()=>Promise<void>;seedRemote:()=>string};
declare global{interface Window{workspaceTest:Fixture}}
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const values:string[]=[];errors.set(page,values);page.on('pageerror',error=>values.push(error.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function login(page:Page){await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('認証を確認しました');await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeEnabled();}
async function create(page:Page,title='私のPage'){await page.getByLabel('新しいPageのタイトル',{exact:true}).fill(title);await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toBeVisible();}
test('WORKSPACE-SCREEN: login/create/keyboard edit/logout/relogin preserve unsent Page; ACK retry and native/browser boundaries',async({page},info)=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('saved text');await page.evaluate(()=>window.workspaceTest.durable());const before=await page.evaluate(()=>window.workspaceTest.snapshot().pages);
 await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect(body).toHaveCount(0);await login(page);await page.getByRole('complementary',{name:'Page一覧'}).getByRole('button',{name:'私のPage',exact:true}).click();await expect(body).toContainText('saved text');expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages)).toEqual(before);await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.loseAck());await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期エラー');await page.getByRole('button',{name:'同期する',exact:true}).click();await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('サーバーと同期済み');await expect(page.getByRole('complementary',{name:'Page一覧'}).getByText(/未確認の更新/)).toHaveCount(0);expect(await page.getByLabel('Pageタイトル',{exact:true}).evaluate(element=>getComputedStyle(element).color)).toBe(await page.locator('main').evaluate(element=>getComputedStyle(element).color));const wires=await page.evaluate(()=>window.workspaceTest.snapshot().sent);expect(wires[0]).toBe(wires[1]);
 await info.attach('workspace-'+info.project.name,{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0});
});
test('WORKSPACE-SCREEN: remote selection checks local presence beyond first page and remote-only download remains unconfirmed',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.seedPagination());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'サーバーで見える次のPage',exact:true}).click();await expect(page.getByLabel('Pageタイトル',{exact:true})).toHaveValue('一覧の次のPage');expect(await page.evaluate(()=>window.workspaceTest.snapshot().reads)).toEqual([]);
 await page.getByRole('button',{name:'端末一覧をさらに表示',exact:true}).click();await expect(page.getByRole('button',{name:'一覧の次のPage',exact:true})).toBeVisible();
 await page.evaluate(()=>window.workspaceTest.seedRemote());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await page.getByRole('button',{name:'遠隔のPage',exact:true}).click();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');await expect(page.getByLabel('同期状態',{exact:true})).toHaveText('同期はまだ確認していません');
 await page.evaluate(()=>window.workspaceTest.failCatalog());await page.getByRole('button',{name:'サーバー一覧を取得',exact:true}).click();await expect(page.getByText('一覧を取得できませんでした。表示中の一覧があれば、以前の取得結果です。')).toBeVisible();await expect(page.getByRole('textbox',{name:'Page本文',exact:true})).toContainText('remote text');
});
test('WORKSPACE-SCREEN: close during native open suppresses late ready; production Web has no persistence fallback',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await page.evaluate(()=>window.workspaceTest.holdOpen());await page.getByRole('textbox',{name:'メールアドレス',exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.getByRole('button',{name:'workspaceを開く',exact:true}).click();await expect(page.getByText('端末のworkspaceを開いています…')).toBeVisible();await page.getByRole('button',{name:'接続を閉じる',exact:true}).click();await page.evaluate(()=>window.workspaceTest.resume());await expect(page.getByLabel('認証状態',{exact:true})).toHaveText('ログインしていません');await expect(page.getByRole('complementary',{name:'Page一覧'})).toHaveCount(0);
 await page.goto('/workspace.html');await expect(page.getByRole('button',{name:'ログイン',exact:true})).toBeDisabled();await expect(page.getByText('端末への保存に対応したアプリで開いてください。')).toBeVisible();
});
test('WORKSPACE-SCREEN: status/catalog rendering preserves selection/composition and uncertain create retries one ID',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await page.evaluate(()=>window.workspaceTest.loseCreateReply());await page.getByLabel('新しいPageのタイトル',{exact:true}).fill('one create');await page.getByRole('button',{name:'新しいPageを作成',exact:true}).click();await expect(page.getByRole('button',{name:'同じPageの作成を再確認',exact:true})).toBeEnabled();await page.getByRole('button',{name:'同じPageの作成を再確認',exact:true}).click();expect(await page.evaluate(()=>window.workspaceTest.snapshot().pages.length)).toBe(1);
 const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.type('abcd');await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'端末一覧を更新',exact:true}).click();await expect(page.getByRole('button',{name:'端末一覧を更新',exact:true})).toBeEnabled();await body.focus();await page.keyboard.type('X');await expect(body).toContainText('abXcd');
 await body.dispatchEvent('compositionstart');await page.evaluate(()=>window.workspaceTest.refreshLocal());expect(await page.evaluate(()=>window.workspaceTest.snapshot().composing)).toBe(true);await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await body.dispatchEvent('compositionend');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeEnabled();
});
test('WORKSPACE-SCREEN: failed commit retains copyable draft and blocks destructive navigation without leaking causes',async({page})=>{
 await page.goto('/private-workspace.fixture.html');await login(page);await create(page);await page.evaluate(()=>window.workspaceTest.failStorage());const body=page.getByRole('textbox',{name:'Page本文',exact:true});await body.click();await page.keyboard.insertText('copy draft');await expect(page.getByLabel('端末の保存状態',{exact:true})).toContainText('保存できません');await expect(body).toContainText('copy draft');await expect(body).toHaveAttribute('contenteditable','false');await expect(page.getByRole('button',{name:'ログアウト',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新しいPageを作成',exact:true})).toBeDisabled();await expect(page.locator('body')).not.toContainText('fixture-private-email');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
