import { test,expect } from '@playwright/test';
import { newId } from '@greiva/shared';
test('STEP6-E2E: Task and Relation pointer/keyboard CRUD persist with pending operations after renderer/store restart', async ({page}) => {
  test.setTimeout(60_000);
  const pageId = newId(); await page.goto(`/?page=${pageId}`);
  const panel = page.getByRole('region',{name:'TaskとRelation'});
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 0件');
  await page.getByRole('button',{name:'接続を一時停止'}).click();
  await panel.getByLabel('Taskの名前').fill('offline task');
  await panel.getByLabel('Taskの状態',{exact:true}).selectOption('in_progress');
  await panel.getByLabel('期限').fill('2028-02-29');
  await panel.getByLabel('Taskの名前').press('Enter');
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 1件');
  await expect(panel.getByLabel('Taskの名前')).toBeFocused();
  await panel.getByRole('button',{name:'offline taskを編集'}).click();
  await panel.getByLabel('Taskの名前').fill('edited offline task');
  await panel.getByLabel('期限').fill('');
  await panel.getByRole('button',{name:'変更を保存',exact:true}).click();
  await expect(panel.getByLabel('保存したTask')).toContainText('edited offline task');
  await panel.getByRole('button',{name:'Relationを追加',exact:true}).click();
  await expect(panel.getByLabel('保存したRelation')).toContainText('edited offline task');
  await panel.getByRole('button',{name:'Relationを編集',exact:true}).click();
  await panel.getByLabel('関連元').selectOption({label:'Task: edited offline task'});
  await panel.getByRole('button',{name:'Relationの変更を保存'}).click();
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 4件');
  await panel.screenshot({path:`${process.env.GREIVA_EVIDENCE_DIR ?? 'tests/evidence/runs/latest'}/structured-local.png`});
  const device = await page.evaluate(() => localStorage.getItem('greiva-test-device'));
  const before = await page.request.post('/__greiva_test_store',{data:{device,command:'structured-snapshot'}});
  const initial = (await before.json()).value;
  expect(initial.operations.map((operation:{status:string}) => operation.status)).toEqual(['pending','pending','pending','pending']);
  await page.request.post('/__greiva_test_store_control',{data:{device,command:'kill'}});
  await page.reload();
  await expect(panel.getByLabel('保存したTask')).toContainText('edited offline task');
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 4件');
  const after = (await (await page.request.post('/__greiva_test_store',{data:{device,command:'structured-snapshot'}})).json()).value;
  expect(after).toEqual(initial);
  await panel.getByRole('button',{name:'edited offline taskを削除'}).click();
  await expect(panel.getByLabel('保存したTask').getByRole('listitem')).toHaveCount(0);
  await panel.getByRole('button',{name:'Relationを削除',exact:true}).click();
  await expect(panel.getByLabel('保存したRelation').getByRole('listitem')).toHaveCount(0);
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 6件');
  const removed = (await (await page.request.post('/__greiva_test_store',{data:{device,command:'structured-snapshot'}})).json()).value;
  expect(removed.tasks[0].deletedAt).toMatch(/Z$/); expect(removed.relations[0].deletedAt).toMatch(/Z$/);
});
test('STEP6-WRITE-ERROR: failed queue commit retains the draft and permits a safe retry without duplicate Task',async ({page}) => {
  await page.goto(`/?page=${newId()}`);
  const panel = page.getByRole('region',{name:'TaskとRelation'});
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 0件');
  const device = await page.evaluate(() => localStorage.getItem('greiva-test-device'));
  await page.request.post('/__greiva_test_store_control',{data:{device,command:'structured-write-failure'}});
  await panel.getByLabel('Taskの名前').fill('preserve this draft');
  await panel.getByRole('button',{name:'Taskを追加',exact:true}).click();
  await expect(panel.getByRole('alert')).toContainText('Injected structured queue failure');
  await expect(panel.getByLabel('Taskの名前')).toHaveValue('preserve this draft');
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 0件');
  await expect(panel.getByLabel('保存したTask').getByRole('listitem')).toHaveCount(0);
  await page.request.post('/__greiva_test_store_control',{data:{device,command:'clear-structured-write-failure'}});
  await panel.getByRole('button',{name:'Taskを追加',exact:true}).click();
  await expect(panel.getByLabel('Taskの保存状態')).toContainText('送信待ち 1件');
  await expect(panel.getByRole('alert')).toHaveCount(0);
  await expect(panel.getByLabel('保存したTask').getByRole('listitem')).toHaveCount(1);
});
