import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as Y from '/workspace/node_modules/yjs/dist/yjs.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const target='01a10230-0000-7000-8000-000000000001';
function audit(path){const db=new DatabaseSync(path,{readOnly:true}),pages=[],tables={};assert.equal(db.prepare('pragma integrity_check').get().integrity_check,'ok');for(const p of db.prepare('select id,title from pages order by id').all()){const doc=new Y.Doc(),updates=db.prepare('select seq,update_bytes,digest from page_updates where page_id=? order by seq').all(p.id);for(const u of updates){assert.equal(sha(u.update_bytes),Buffer.from(u.digest).toString('hex'));Y.applyUpdate(doc,u.update_bytes);}const fragment=doc.getXmlFragment('body');pages.push({id:p.id,title:p.title,xml:fragment.toString(),rows:fragment.toArray().map(n=>n.toArray().map(t=>t.toString()).join('')),updates:updates.length,clocks:Array.from(Y.decodeStateVector(Y.encodeStateVector(doc))).sort(([a],[b])=>a-b)});doc.destroy();}for(const {name} of db.prepare("select name from sqlite_master where type='table' order by name").all()){if(['pages','page_updates','sqlite_sequence'].includes(name))continue;tables[name]=sha(JSON.stringify(db.prepare('select * from "'+name.replaceAll('"','""')+'"').all()));}db.close();return{pages,tables};}
const before=audit('/tmp/profile-before/greiva.sqlite'),after=audit('/tmp/profile-after/greiva.sqlite');assert.deepEqual(after.tables,before.tables);assert.equal(after.pages.length,before.pages.length);for(const p of before.pages.filter(p=>p.id!==target))assert.deepEqual(after.pages.find(q=>q.id===p.id),p);
const final=audit('/tmp/profile-final/greiva.sqlite');assert.deepEqual(final,after);
const b=before.pages.find(p=>p.id===target),a=after.pages.find(p=>p.id===target);assert.equal(a.rows.length,1000);assert.equal(a.title,b.title);assert.deepEqual(a.rows.slice(1),b.rows.slice(1));let index=0;while(index<b.rows[0].length&&b.rows[0][index]===a.rows[0][index])index++;assert.equal(a.rows[0],b.rows[0].slice(0,index)+'abc'+b.rows[0].slice(index));assert.equal(a.updates,b.updates+3);
const records=readFileSync('/tmp/profile-reports.jsonl','utf8').trim().split('\n').map(JSON.parse),runs=new Map();for(const r of records)runs.set(r.frontend.timeOrigin,r);
const summary=[];for(const r of runs.values()){const f=r.frontend,by=id=>f.records.find(p=>p.id===id),span=id=>r.nativeSpans.find(p=>p.id===id);assert.equal(by('yjs-restore').blocks,1000);assert.equal(by('editor-effect').blocks,1000);assert.equal(f.dom.handles,1000);const editorStart=by('editor-render').at;summary.push({timeOrigin:f.timeOrigin,lastReason:f.reason??'startup-v1',pageUpdates:by('yjs-restore').updates,pageBytes:by('yjs-restore').bytes,sqliteOpen:span('page_list-store-open').duration,pageQuery:span('page_load-query').duration,pageIpc:f.records.find(p=>p.id==='ipc'&&p.command==='page_load').duration,yjs:by('yjs-restore'),editorCreation:by('editor-effect').at-editorStart,editorTwoRaf:by('editor-two-raf').at-editorStart,editorTwoRafNavigation:by('editor-two-raf').at,tasksTwoRafNavigation:by('tasks-two-raf').at,tasks:by('tasks-two-raf').tasks,taskQuery:span('structured_snapshot-query').duration,longTasks:f.longTasks,save:f.dom.save??'UI screenshot confirmed; v1 selector typo'});}
const inputRun=[...runs.values()].find(r=>r.frontend.records.some(p=>p.id==='keydown'));
assert(inputRun);const input=inputRun.frontend.records,keys=input.filter(p=>p.id==='keydown');assert.deepEqual(keys.map(p=>p.key),['a','b','c']);assert(keys.every(p=>p.trusted&&!p.composing));assert(!input.some(p=>p.id==='compositionstart'));const inputTimings=keys.map(key=>{const frame=input.find(p=>p.id==='keydown-two-raf'&&p.start===key.start),append=input.find(p=>p.id==='ipc'&&p.command==='page_append'&&p.start>=key.start);assert(frame&&append);return{key:key.key,trusted:key.trusted,composing:key.composing,keydownToTwoRaf:frame.duration,appendIpc:append.duration,keydownToAppendResolved:append.at-key.start};});
assert.equal(summary.length,4);
const result={at:new Date().toISOString(),result:'Pass',execution:'Actual Windows WebView2 and Tauri IPC diagnostic derived from normal 0.6.17; Docker build and stopped SQLite audit',pageId:target,runs:summary,inputTimings,database:{beforeUpdates:b.updates,afterUpdates:a.updates,paragraphs:1000,insertion:{index,text:'abc'},other999ParagraphsUnchanged:true,otherPagesUnchanged:true,structuredTablesUnchanged:true,unchangedAfterTwoRestarts:true,structuredTableHashes:after.tables,allDigestsVerified:true,beforeBodySha256:sha(b.xml),afterBodySha256:sha(a.xml),beforeClocks:b.clocks,afterClocks:a.clocks},scope:'Diagnostic intervals and three spaced ASCII keys, not normal-product SLO, continuous typing, real Japanese IME, p95, cold OS boot, or Gate verdict.'};writeFileSync('/tmp/profile-audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify({result:result.result,runs:summary.length,keys:3,updates:a.updates,blocks:1000}));
