import {PrivateDatabaseViewWriteSession} from '../../apps/client/src/workspace/private-database-view-write-session.js';
import {PostgresPrivateDatabaseViewStore} from '../../apps/api/src/private-database-view-store.js';
import {prepareDatabaseViewResolution} from '@greiva/domain';
import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_vwrite_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-source-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'source-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'source-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'source-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit=false,lostHttp=false,failEnqueue=false,failQueue:string|null=null;const bodies:string[]=[];const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));if(String(input).endsWith('/views/write'))bodies.push(String(init?.body));const result=await fetch(input,init);if(lostHttp&&String(input).endsWith('/views/write')){lostHttp=false;throw Error('fixture lost HTTP response');}if(hold&&String(input).endsWith('/views/write')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command&&['database_view_ack'].includes((args?.request as {command:string}).command)){failCommit=false;throw Error('fixture commit result unknown');}if(failEnqueue&&command==='workspace_execute'&&(args?.request as {command?:string})?.command&&['database_view_enqueue'].includes((args?.request as {command:string}).command)){failEnqueue=false;throw Error('fixture lost enqueue response');}if(failQueue&&command==='workspace_execute'&&(args?.request as {command?:string;pendingOnly?:boolean})?.command===failQueue&&(args?.request as {pendingOnly?:boolean})?.pendingOnly===true){failQueue=null;throw Error('fixture lost queue read');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema);
 return{pool,schema,source,sources,context,auth,owner,bodies,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:()=>{failCommit=true;},unknownEnqueue:()=>{failEnqueue=true;},lostNextHttp:()=>{lostHttp=true;},writes:()=>store.databaseViewWrites(),viewRuntime:()=>PrivateDatabaseViewWriteSession.open(connection,store),unknownNextQueue:()=>{failQueue='database_view_queue';},blockCreate:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
type F=Awaited<ReturnType<typeof setup>>;
const property=(f:F,type:string)=>f.source.properties.find(p=>p.type===type)!.id;
function make(f:F){return{operationId:newId(),source:f.source,intent:{kind:'create' as const,sourceId:f.source.id,schemaVersion:1,viewId:newId(),baseVersion:null,settings:{name:'base',layout:'table' as const,visiblePropertyIds:[property(f,'name'),property(f,'text'),property(f,'number')],filter:null,sorts:[]}}};}
async function source(f:F){if((await f.store.databaseSourceLoad(f.source.id)).snapshot)return;await f.store.databaseSourceEnqueue({operationId:newId(),source:f.source});await f.store.databaseSourceWrites().send();}
async function ready(f:F){await source(f);const item=make(f);await f.store.databaseViewEnqueue(item);return item;}
async function created(f:F){const item=await ready(f),reply=await f.writes().send();if(!reply||'status' in reply)throw Error('Missing View creation');return{item,reply};}
const update=(f:F,snapshot:Awaited<ReturnType<typeof created>>['reply']['snapshot'],patch:Record<string,unknown>)=>({operationId:newId(),source:f.source,intent:{kind:'update' as const,sourceId:f.source.id,schemaVersion:1,viewId:snapshot.view.id,baseVersion:snapshot.version,patch}});
real('DB-VIEW-WRITE-PG: Source wait invokes no View HTTP; original create survives lost HTTP/native ACK and restart without Page dependency',async()=>{await isolated(async f=>{const item=make(f);await f.store.databaseSourceEnqueue({operationId:newId(),source:f.source});await f.store.databaseViewEnqueue(item);let sender=f.writes();expect(await sender.send()).toMatchObject({status:'blocked',reason:'source'});expect(f.bodies.length).toBe(0);await f.store.databaseSourceWrites().send();f.lostNextHttp();await expect(sender.send()).rejects.toMatchObject({stage:'transport'});expect((await f.store.databaseViewQueue()).pending).toBe(1);await f.reopen();sender=f.writes();f.unknownNextCommit();await expect(sender.send()).rejects.toMatchObject({stage:'storage'});expect(sender.retryAck).toBe(true);expect((await f.store.databaseViewQueue()).pending).toBe(0);expect(f.bodies[0]).toBe(f.bodies[1]);const calls=f.calls.length;await sender.retry();expect(f.calls.length).toBe(calls);await f.reopen();expect((await f.store.databaseViewLoad(f.source.id,item.intent.viewId)).snapshot!.view).toEqual({id:item.intent.viewId,sourceId:f.source.id,...item.intent.settings});expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_view_operations`)).rows[0].n).toBe('1');const saved=JSON.stringify((await f.pool.query(`SELECT request,result FROM "${f.schema}".private_database_view_operations`)).rows);expect(saved).not.toContain('auth-only@example.invalid');expect(saved).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_page_documents`)).rows[0].n).toBe('0');});});
real('DB-VIEW-WRITE-PG: all five settings original update survives lost HTTP/native ACK with exact arrays/filter/null and write proof',async()=>{await isolated(async f=>{const {reply}=await created(f),item=update(f,reply.snapshot,{name:'local',layout:'list',visiblePropertyIds:[property(f,'text'),property(f,'name')],filter:{kind:'predicate',propertyId:property(f,'number'),operator:'gte',value:0},sorts:[{propertyId:property(f,'text'),direction:'desc'}]});await f.store.databaseViewEnqueue(item);let sender=f.writes();f.lostNextHttp();await expect(sender.send()).rejects.toMatchObject({stage:'transport'});await f.reopen();sender=f.writes();f.unknownNextCommit();await expect(sender.send()).rejects.toMatchObject({stage:'storage'});const calls=f.calls.length;await sender.retry();expect(f.calls.length).toBe(calls);expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));const q=await f.store.databaseViewQueue();expect(q.operations[1]!.response).toMatchObject({operationId:item.operationId,snapshot:{version:2,view:item.intent.patch}});expect(q.pending).toBe(0);const clear=update(f,q.operations[1]!.response!.snapshot,{filter:null,sorts:[]});await f.store.databaseViewEnqueue(clear);const cleared=await f.writes().send();if(!cleared||'status' in cleared)throw Error('Missing cleared ACK');expect(cleared.snapshot.view.filter).toBeNull();});});
real('DB-VIEW-WRITE-PG: partial merge/name conflict and local/remote explicit choices cross actual HTTP and native atomic proof',async()=>{await isolated(async f=>{for(const choice of ['local','remote'] as const){const {reply}=await created(f),views=new PostgresPrivateDatabaseViewStore(f.pool,f.schema),remote=update(f,reply.snapshot,{name:'remote'});await views.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:remote.operationId,intent:remote.intent});const local=update(f,reply.snapshot,{name:'local',layout:'list'});await f.store.databaseViewEnqueue(local);const conflict=await f.writes().send();if(!conflict||'status' in conflict||conflict.result.status!=='conflict')throw Error('Missing original conflict');expect(conflict.snapshot.view.layout).toBe('list');const candidate=conflict.result.conflicts[0]!,item={operationId:newId(),source:f.source,intent:prepareDatabaseViewResolution(f.source,conflict.snapshot,candidate,choice)};await f.store.databaseViewEnqueue(item);const resolved=await f.writes().send();if(!resolved||'status' in resolved)throw Error('Missing choice ACK');expect(resolved.snapshot.version).toBe(choice==='local'?4:3);expect(resolved.snapshot.view.name).toBe(choice);await f.reopen();expect((await f.store.databaseViewLoad(f.source.id,reply.snapshot.view.id)).conflicts[0]!.resolvedBy).toBe(item.operationId);expect((await f.pool.query(`SELECT resolved_by FROM "${f.schema}".private_database_view_conflicts WHERE id=$1`,[candidate.id])).rows[0].resolved_by).toBe(item.operationId);}});});
real('DB-VIEW-WRITE-PG: stale choice remains original rejection, newer remote settings survive and candidate stays unresolved',async()=>{await isolated(async f=>{const {reply}=await created(f),views=new PostgresPrivateDatabaseViewStore(f.pool,f.schema),remote=update(f,reply.snapshot,{name:'remote'});await views.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:remote.operationId,intent:remote.intent});await f.store.databaseViewEnqueue(update(f,reply.snapshot,{name:'local'}));const conflict=await f.writes().send();if(!conflict||'status' in conflict||conflict.result.status!=='conflict')throw Error('Missing conflict');const item={operationId:newId(),source:f.source,intent:prepareDatabaseViewResolution(f.source,conflict.snapshot,conflict.result.conflicts[0]!,'local')};await f.store.databaseViewEnqueue(item);const newer=update(f,conflict.snapshot,{layout:'list'});await views.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:newer.operationId,intent:newer.intent});const runtime=await f.viewRuntime(),rejected=await runtime.send();if(!rejected||'status' in rejected)throw Error('Missing rejected ACK');expect(rejected.result).toEqual({status:'rejected',code:'resolution_stale'});expect(runtime.snapshot.lastSend).toMatchObject({status:'ack',response:{result:{status:'rejected'}}});const current=await f.store.databaseViewLoad(f.source.id,reply.snapshot.view.id);expect(current.snapshot!.view.layout).toBe('list');expect(current.conflicts[0]!.resolvedBy).toBeNull();await runtime.close();});});
real('DB-VIEW-WRITE-PG: replacement/Auth refresh/native close discard late committed reply; renewed sender reconciles durable original wire',async()=>{await isolated(async f=>{for(const boundary of ['replacement','refresh','native-close'] as const){const item=await ready(f),sender=f.writes(),hold=f.blockCreate(),work=sender.send();await hold.entered;if(boundary==='replacement')f.writes();if(boundary==='refresh'){await f.auth.refresh();await f.connection.bootstrap();}if(boundary==='native-close')await f.store.close();hold.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(sender.retryAck).toBe(false);await f.reopen();expect((await f.store.databaseViewQueue()).pending).toBe(1);const reply=await f.writes().send();if(!reply||'status' in reply)throw Error('Missing recovered ACK');expect(reply.snapshot.view.id).toBe(item.intent.viewId);expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));}});});
real('DB-VIEW-WRITE-PG: revoked device closes generation with durable pending and renewal can send same operation',async()=>{await isolated(async f=>{const item=await ready(f),sender=f.writes();await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=true WHERE id=$1`,[f.context.clientId]);await expect(sender.send()).rejects.toMatchObject({stage:'closed'});await expect(f.store.databaseViewQueue()).rejects.toMatchObject({stage:'closed'});await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=false WHERE id=$1`,[f.context.clientId]);await f.reconnect();expect((await f.store.databaseViewQueue()).pending).toBe(1);const reply=await f.writes().send();if(!reply||'status' in reply)throw Error();expect(reply.operationId).toBe(item.operationId);});});
real('DB-VIEW-RUNTIME-PG: unknown enqueue persists through local reload; exact retry and unknown ACK retry require no extra HTTP',async()=>{await isolated(async f=>{await source(f);const item=make(f),runtime=await f.viewRuntime(),before=f.calls.length;f.unknownEnqueue();await expect(runtime.enqueue(item)).rejects.toMatchObject({stage:'storage'});await runtime.reload();expect(runtime.snapshot).toMatchObject({retryEnqueue:true,data:{pending:1}});await runtime.retryEnqueue();expect(f.calls.length).toBe(before);f.unknownNextCommit();await expect(runtime.send()).rejects.toMatchObject({stage:'storage'});await runtime.reload();expect(runtime.snapshot).toMatchObject({retryAck:true,data:{pending:0}});const calls=f.calls.length;await runtime.retryAck();expect(f.calls.length).toBe(calls);expect(runtime.snapshot).toMatchObject({retryAck:false,lastSend:{status:'ack',response:{operationId:item.operationId}}});await runtime.close();expect((await f.store.databaseViewLoad(f.source.id,item.intent.viewId)).snapshot!.version).toBe(1);});});
real('DB-VIEW-RUNTIME-PG: known busy keeps first update, HTTP loss/restart keeps exact body, known ACK/list failure keeps original result',async()=>{await isolated(async f=>{const {reply}=await created(f),runtime=await f.viewRuntime(),item=update(f,reply.snapshot,{name:'first'});await runtime.enqueue(item);const attempt=update(f,reply.snapshot,{name:'unsaved'});expect(await runtime.enqueue(attempt)).toEqual({status:'busy',operationId:item.operationId,viewId:item.intent.viewId});expect(runtime.snapshot.retryEnqueue).toBe(false);f.lostNextHttp();await expect(runtime.send()).rejects.toMatchObject({stage:'transport'});expect(runtime.snapshot).toMatchObject({retryAck:false,queueFresh:false,data:{pending:1}});await runtime.close();await f.reopen();const recovered=await f.viewRuntime();f.unknownNextQueue();await expect(recovered.send()).rejects.toMatchObject({stage:'storage'});expect(recovered.snapshot).toMatchObject({retryAck:false,queueFresh:false,lastSend:{status:'ack',response:{snapshot:{view:{name:'first'}}}}});expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));await recovered.reload();expect(recovered.snapshot.data!.pending).toBe(0);await recovered.close();});});
real('DB-VIEW-RUNTIME-PG: Auth refresh closes private runtime during committed HTTP and reopening retrieves exact pending without old state',async()=>{await isolated(async f=>{const item=await ready(f),runtime=await f.viewRuntime(),hold=f.blockCreate(),work=runtime.send();await hold.entered;await f.auth.refresh();await f.connection.bootstrap();expect(runtime.snapshot).toMatchObject({phase:'closed',data:null,lastEnqueue:null,lastSend:null,retryEnqueue:false,retryAck:false});hold.release();await expect(work).rejects.toMatchObject({stage:'closed'});await runtime.close();await f.reopen();const recovered=await f.viewRuntime();expect(recovered.snapshot.data!.pending).toBe(1);const reply=await recovered.send();if(!reply||'status' in reply)throw Error();expect(reply.operationId).toBe(item.operationId);await recovered.close();});});
