import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema,prepareDatabaseResolution,prepareDatabaseViewResolution} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
import {PostgresPrivateDatabaseRecordStore} from '../../apps/api/src/private-database-record-store.js';
import {PostgresPrivateDatabaseViewStore} from '../../apps/api/src/private-database-view-store.js';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_cclient_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-content-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'content-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'content-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'content-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit:'record'|'view'|null=null;const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));const result=await fetch(input,init);if(hold&&String(input).endsWith('/read')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_'+failCommit+'_receive'){failCommit=null;throw Error('fixture commit result unknown');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),created=await sources.create(owner,context.workspaceId,{protocolVersion:1,clientId:context.clientId,operationId:newId(),source});
 const option=(source.properties.find(p=>p.type==='select') as {options:{id:string}[]}).options[0]!.id,pageId=newId(),recordId=newId(),viewId=newId(),pages=new PostgresPrivatePageStore(pool,schema),records=new PostgresPrivateDatabaseRecordStore(pool,schema),views=new PostgresPrivateDatabaseViewStore(pool,schema),writeRecord=async(intent:unknown)=>privateDatabaseRecordWriteResponseSchema.parse(await records.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent})),writeView=async(intent:unknown)=>privateDatabaseViewWriteResponseSchema.parse(await views.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent}));
 await pages.bootstrap(owner,context.workspaceId,pageId,{protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,title:'Page Name',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')});
 const recordBase={sourceId:source.id,schemaVersion:1,recordId,pageId},viewBase={sourceId:source.id,schemaVersion:1,viewId},initialRecord=await writeRecord({...recordBase,kind:'create',baseVersion:null,values:{[ids.text]:'base',[ids.number]:0,[ids.checkbox]:false,[ids.select]:option,[ids.date]:'2026-10-09'}}),initialView=await writeView({...viewBase,kind:'create',baseVersion:null,settings:{name:'base',layout:'table',visiblePropertyIds:[ids.name,ids.text,ids.number,ids.checkbox,ids.select,ids.date],filter:{kind:'predicate',propertyId:ids.number,operator:'gte',value:0},sorts:[{propertyId:ids.date,direction:'asc'},{propertyId:ids.text,direction:'desc'}]}});
 return{pool,schema,source,created,context,auth,owner,ids,pageId,recordId,viewId,recordBase,viewBase,initialRecord,initialView,writeRecord,writeView,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:(kind:'record'|'view')=>{failCommit=kind;},blockRead:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
real('DB-CONTENT-CLIENT-PG: signed HTTP catalogs/read commit typed Record/View snapshots; lost native returns retry exact response without network and restart retains values/settings',async()=>{await isolated(async f=>{const before=f.calls.length;await expect(f.store.databaseContents(f.source.id)).rejects.toMatchObject({stage:'protocol'});expect(f.calls).toHaveLength(before);await f.store.databaseSources().read(f.source.id);const session=await f.store.databaseContents(f.source.id),opened=f.calls.length;expect(f.calls).toHaveLength(opened);expect((await session.catalogRecords()).records.map(r=>r.id)).toEqual([f.recordId]);expect((await session.catalogViews()).views.map(r=>r.id)).toEqual([f.viewId]);expect((await f.store.databaseRecordList(f.source.id)).records).toEqual([]);expect((await f.store.databaseViewList(f.source.id)).views).toEqual([]);const request={protocolVersion:1,clientId:f.context.clientId,pageId:f.pageId};f.unknownNextCommit('record');await expect(session.readRecord(f.recordId,request)).rejects.toMatchObject({stage:'storage'});let calls=f.calls.length;await expect(session.readView(f.viewId)).rejects.toMatchObject({stage:'busy'});expect(await session.retry()).toMatchObject({record:f.initialRecord.record});expect(f.calls).toHaveLength(calls);f.unknownNextCommit('view');await expect(session.readView(f.viewId)).rejects.toMatchObject({stage:'storage'});calls=f.calls.length;await expect(session.catalogRecords()).rejects.toMatchObject({stage:'busy'});expect(await session.retry()).toMatchObject({snapshot:f.initialView.snapshot});expect(f.calls).toHaveLength(calls);await f.reopen();expect(session.signal.aborted).toBe(true);expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toEqual(f.initialRecord.record);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toEqual(f.initialView.snapshot);expect(await f.store.hasPage(f.pageId)).toBe(false);const ledgers=JSON.stringify((await f.pool.query(`SELECT request,result FROM "${f.schema}".private_database_record_operations UNION ALL SELECT request,result FROM "${f.schema}".private_database_view_operations`)).rows);expect(ledgers).not.toContain('auth-only@example.invalid');expect(ledgers).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);});});
real('DB-CONTENT-CLIENT-PG: actual server conflicts survive cache restart; read absence after remote resolution does not infer local resolution; denied Source retains saved data',async()=>{await isolated(async f=>{await f.store.databaseSources().read(f.source.id);let session=await f.store.databaseContents(f.source.id);const request={protocolVersion:1,clientId:f.context.clientId,pageId:f.pageId};await session.readRecord(f.recordId,request);await session.readView(f.viewId);await f.writeRecord({...f.recordBase,kind:'update',baseVersion:1,values:{[f.ids.text]:'remote'}});await f.writeView({...f.viewBase,kind:'update',baseVersion:1,patch:{name:'remote'}});const recordConflict=await f.writeRecord({...f.recordBase,kind:'update',baseVersion:1,values:{[f.ids.text]:'local'}}),viewConflict=await f.writeView({...f.viewBase,kind:'update',baseVersion:1,patch:{name:'local'}});if(recordConflict.result.status!=='conflict'||viewConflict.result.status!=='conflict')throw Error('Fixture conflict missing');const rc=recordConflict.result.conflicts[0]!,vc=viewConflict.result.conflicts[0]!;expect((await session.readRecord(f.recordId,request)).conflicts).toEqual([rc]);expect((await session.readView(f.viewId)).conflicts).toEqual([vc]);await f.reopen();expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).conflicts).toEqual([rc]);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).conflicts).toEqual([vc]);session=await f.store.databaseContents(f.source.id);await f.writeRecord(prepareDatabaseResolution(f.source,recordConflict.record,rc,'remote'));await f.writeView(prepareDatabaseViewResolution(f.source,viewConflict.snapshot,vc,'remote'));expect((await session.readRecord(f.recordId,request)).conflicts).toEqual([]);expect((await session.readView(f.viewId)).conflicts).toEqual([]);expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).conflicts).toEqual([rc]);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).conflicts).toEqual([vc]);await f.pool.query(`UPDATE "${f.schema}".private_database_sources SET deleted=true WHERE id=$1`,[f.source.id]);await expect(session.readView(f.viewId)).rejects.toMatchObject({stage:'closed'});expect(session.retryReceive).toBe(false);await expect(f.store.databaseViewLoad(f.source.id,f.viewId)).rejects.toMatchObject({stage:'closed'});await f.reconnect();expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record?.version).toBe(2);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot?.version).toBe(2);});});
real('DB-CONTENT-CLIENT-PG: replacement/Auth refresh/native close discard late signed read; closed native factories stop Source and content HTTP',async()=>{await isolated(async f=>{await f.store.databaseSources().read(f.source.id);let session=await f.store.databaseContents(f.source.id),block=f.blockRead(),work=session.readRecord(f.recordId,{protocolVersion:1,clientId:f.context.clientId,pageId:f.pageId});await block.entered;let replacement=await f.store.databaseContents(f.source.id);block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toBeNull();session=replacement;block=f.blockRead();const viewWork=session.readView(f.viewId);await block.entered;await f.auth.refresh();await f.connection.bootstrap();block.release();await expect(viewWork).rejects.toMatchObject({stage:'closed'});await f.reopen();expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toBeNull();session=await f.store.databaseContents(f.source.id);const sources=f.store.databaseSources();block=f.blockRead();work=session.readRecord(f.recordId,{protocolVersion:1,clientId:f.context.clientId,pageId:f.pageId});await block.entered;await f.store.close();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(sources.signal.aborted).toBe(true);const calls=f.calls.length;await expect(session.catalogViews()).rejects.toMatchObject({stage:'closed'});await expect(sources.read(f.source.id)).rejects.toMatchObject({stage:'closed'});expect(f.calls).toHaveLength(calls);await f.reopen();expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toBeNull();replacement=await f.store.databaseContents(f.source.id);await replacement.readView(f.viewId);f.connection.close();const closedCalls=f.calls.length;await expect(replacement.readView(f.viewId)).rejects.toMatchObject({stage:'closed'});expect(f.calls).toHaveLength(closedCalls);});});
