import {PostgresPrivateDatabaseRecordStore} from '../../apps/api/src/private-database-record-store.js';
import {prepareDatabaseResolution} from '@greiva/domain';
import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_rwrite_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-source-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'source-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'source-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'source-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit=false,lostHttp=false,failEnqueue=false;const bodies:string[]=[];const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));if(String(input).endsWith('/records/write'))bodies.push(String(init?.body));const result=await fetch(input,init);if(lostHttp&&String(input).endsWith('/records/write')){lostHttp=false;throw Error('fixture lost HTTP response');}if(hold&&String(input).endsWith('/records/write')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command&&['database_record_create_ack','database_record_update_ack'].includes((args?.request as {command:string}).command)){failCommit=false;throw Error('fixture commit result unknown');}if(failEnqueue&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_source_enqueue'){failEnqueue=false;throw Error('fixture lost enqueue response');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema);
 return{pool,schema,source,sources,context,auth,owner,bodies,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:()=>{failCommit=true;},unknownEnqueue:()=>{failEnqueue=true;},lostNextHttp:()=>{lostHttp=true;},writes:()=>store.databaseRecordWrites(),blockCreate:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
type F=Awaited<ReturnType<typeof setup>>;
const property=(f:F,type:string)=>f.source.properties.find(p=>p.type===type)!.id;
type Create=ReturnType<typeof make>;
function make(f:F){return{operationId:newId(),source:f.source,intent:{kind:'create' as const,sourceId:f.source.id,schemaVersion:1,recordId:newId(),pageId:newId(),baseVersion:null,values:{[property(f,'text')]:'base',[property(f,'number')]:1,[property(f,'checkbox')]:false,[property(f,'date')]:null}}};}
async function source(f:F){if((await f.store.databaseSourceLoad(f.source.id)).snapshot)return;await f.store.databaseSourceEnqueue({operationId:newId(),source:f.source});await f.store.databaseSourceWrites().send();}
async function page(f:F,id:string){const page=f.store.page(id);await page.create('Record Name',emptyPageUpdate());await f.connection.openPage(id,page).push(await page.prepare());}
async function ready(f:F){await source(f);const item=make(f);await page(f,item.intent.pageId);await f.store.databaseRecordCreateEnqueue(item);return item;}
async function created(f:F){const item=await ready(f),sender=f.writes(),reply=await sender.send('create');if(!reply||'status' in reply)throw Error('Missing Record creation ACK');return{item,reply};}
const update=(f:F,r:Awaited<ReturnType<typeof created>>['reply']['record'],values:Record<string,string|number|boolean|null>)=>({operationId:newId(),source:f.source,intent:{kind:'update' as const,sourceId:f.source.id,schemaVersion:1,recordId:r.id,pageId:r.pageId,baseVersion:r.version,values}});
real('DB-RECORD-WRITE-PG: Source/Page waits perform no Record HTTP; lost HTTP and unknown native create ACK reconcile original operation across restart',async()=>{await isolated(async f=>{const item=make(f);await f.store.databaseSourceEnqueue({operationId:newId(),source:f.source});await f.store.page(item.intent.pageId).create('Name',emptyPageUpdate());await f.store.databaseRecordCreateEnqueue(item);let sender=f.writes();expect(await sender.send('create')).toMatchObject({status:'blocked',reason:'source'});expect(f.bodies).toEqual([]);await f.store.databaseSourceWrites().send();expect(await sender.send('create')).toMatchObject({status:'blocked',reason:'page'});expect(f.bodies).toEqual([]);await f.connection.openPage(item.intent.pageId,f.store.page(item.intent.pageId)).push(await f.store.page(item.intent.pageId).prepare());f.lostNextHttp();await expect(sender.send('create')).rejects.toMatchObject({stage:'transport'});expect(sender.retryAck).toBe(false);expect((await f.store.databaseRecordCreateQueue()).pending).toBe(1);expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_records`)).rows[0].n).toBe('1');await f.reopen();sender=f.writes();f.unknownNextCommit();await expect(sender.send('create')).rejects.toMatchObject({stage:'storage'});expect(sender.retryAck).toBe(true);expect((await f.store.databaseRecordCreateQueue()).pending).toBe(0);expect(f.bodies[0]).toBe(f.bodies[1]);const count=f.calls.length;await sender.retry();expect(f.calls.length).toBe(count);await f.reopen();expect((await f.store.databaseRecordLoad(f.source.id,item.intent.recordId)).record!.values).toEqual(item.intent.values);expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_record_operations`)).rows[0].n).toBe('1');const saved=JSON.stringify((await f.pool.query(`SELECT request,result FROM "${f.schema}".private_database_record_operations`)).rows);expect(saved).not.toContain('auth-only@example.invalid');expect(saved).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);});});
real('DB-RECORD-WRITE-PG: original update wire survives lost HTTP/native ACK; explicit null/zero/false and exact write receipt remain durable',async()=>{await isolated(async f=>{const {reply}=await created(f),item=update(f,reply.record,{[property(f,'text')]:null,[property(f,'number')]:0,[property(f,'checkbox')]:false});await f.store.databaseRecordUpdateEnqueue(item);let sender=f.writes();f.lostNextHttp();await expect(sender.send('update')).rejects.toMatchObject({stage:'transport'});expect((await f.store.databaseRecordUpdateQueue()).pending).toBe(1);await f.reopen();sender=f.writes();f.unknownNextCommit();await expect(sender.send('update')).rejects.toMatchObject({stage:'storage'});expect(sender.retryAck).toBe(true);const count=f.calls.length;await sender.retry();expect(f.calls.length).toBe(count);expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));await f.reopen();const queue=await f.store.databaseRecordUpdateQueue();expect(queue.pending).toBe(0);expect(queue.operations[0]!.response).toMatchObject({operationId:item.operationId,result:{status:'applied'},record:{version:2,values:item.intent.values}});expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_record_operations`)).rows[0].n).toBe('2');});});
real('DB-RECORD-WRITE-PG: partial merge/three-value conflict and local/remote new-operation resolution cross actual HTTP and native proof atomically',async()=>{await isolated(async f=>{for(const choice of ['local','remote'] as const){const {reply}=await created(f),base=reply.record,records=new PostgresPrivateDatabaseRecordStore(f.pool,f.schema),remote=update(f,base,{[property(f,'text')]:'remote'});await records.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:remote.operationId,intent:remote.intent});const local=update(f,base,{[property(f,'text')]:'local',[property(f,'number')]:5});await f.store.databaseRecordUpdateEnqueue(local);let sender=f.writes();const conflict=await sender.send('update');if(!conflict||'status' in conflict||conflict.result.status!=='conflict')throw Error('Missing original conflict');expect(conflict.record.values[property(f,'number')]).toBe(5);const cf=conflict.result.conflicts[0]!,intent={operationId:newId(),source:f.source,intent:prepareDatabaseResolution(f.source,conflict.record,cf,choice)};await f.store.databaseRecordUpdateEnqueue(intent);sender=f.writes();const resolved=await sender.send('update');if(!resolved||'status' in resolved)throw Error('Missing resolution ACK');expect(resolved.result.status).toBe('applied');expect(resolved.record.version).toBe(choice==='local'?4:3);expect(resolved.record.values[property(f,'text')]).toBe(choice);await f.reopen();expect((await f.store.databaseRecordLoad(f.source.id,base.id)).conflicts[0]!.resolvedBy).toBe(intent.operationId);expect((await f.pool.query(`SELECT resolved_by FROM "${f.schema}".private_database_record_conflicts WHERE id=$1`,[cf.id])).rows[0].resolved_by).toBe(intent.operationId);}expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_record_operations`)).rows[0].n).toBe('8');});});
real('DB-RECORD-WRITE-PG: stale resolution is original known rejection; server/current history retained and candidate remains unresolved',async()=>{await isolated(async f=>{const {reply}=await created(f),base=reply.record,records=new PostgresPrivateDatabaseRecordStore(f.pool,f.schema),remote=update(f,base,{[property(f,'text')]:'remote'});await records.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:remote.operationId,intent:remote.intent});const local=update(f,base,{[property(f,'text')]:'local'});await f.store.databaseRecordUpdateEnqueue(local);const conflict=await f.writes().send('update');if(!conflict||'status' in conflict||conflict.result.status!=='conflict')throw Error('Missing conflict');const cf=conflict.result.conflicts[0]!,choice={operationId:newId(),source:f.source,intent:prepareDatabaseResolution(f.source,conflict.record,cf,'local')};await f.store.databaseRecordUpdateEnqueue(choice);const newer=update(f,conflict.record,{[property(f,'number')]:9});await records.write(f.owner,f.context.workspaceId,f.source.id,{protocolVersion:1,clientId:f.context.clientId,operationId:newer.operationId,intent:newer.intent});const rejected=await f.writes().send('update');if(!rejected||'status' in rejected)throw Error('Missing rejected ACK');expect(rejected.result).toEqual({status:'rejected',code:'resolution_stale'});await f.reopen();expect((await f.store.databaseRecordUpdateQueue()).pending).toBe(0);const current=await f.store.databaseRecordLoad(f.source.id,base.id);expect(current.record!.values[property(f,'number')]).toBe(9);expect(current.conflicts[0]!.resolvedBy).toBeNull();});});
real('DB-RECORD-WRITE-PG: replacement/Auth refresh/native close discard late committed HTTP; new captured sender reconciles exact original bytes',async()=>{await isolated(async f=>{for(const boundary of ['replacement','refresh','native-close'] as const){const item=await ready(f),sender=f.writes(),hold=f.blockCreate(),work=sender.send('create');await hold.entered;if(boundary==='replacement')f.writes();if(boundary==='refresh'){await f.auth.refresh();await f.connection.bootstrap();}if(boundary==='native-close')await f.store.close();hold.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(sender.retryAck).toBe(false);await f.reopen();expect((await f.store.databaseRecordCreateQueue()).pending).toBe(1);const reply=await f.writes().send('create');if(!reply||'status' in reply)throw Error('Missing reconciled ACK');expect(reply.record.id).toBe(item.intent.recordId);expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));expect((await f.store.databaseRecordCreateQueue()).pending).toBe(0);}expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_records`)).rows[0].n).toBe('3');});});
real('DB-RECORD-WRITE-PG: denied device closes old generation while retaining exact queued operation for renewed bootstrap',async()=>{await isolated(async f=>{const item=await ready(f),sender=f.writes();await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=true WHERE id=$1`,[f.context.clientId]);await expect(sender.send('create')).rejects.toMatchObject({stage:'closed'});await expect(f.store.databaseRecordCreateQueue()).rejects.toMatchObject({stage:'closed'});expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_records`)).rows[0].n).toBe('0');await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=false WHERE id=$1`,[f.context.clientId]);await f.reconnect();expect((await f.store.databaseRecordCreateQueue()).pending).toBe(1);const reply=await f.writes().send('create');if(!reply||'status' in reply)throw Error('Missing recovered ACK');expect(reply.operationId).toBe(item.operationId);expect((await f.store.databaseRecordCreateQueue()).pending).toBe(0);});});
