import {it,expect,vi} from 'vitest';
import pg from 'pg';
import {createServer} from 'node:net';
import {createHash} from 'node:crypto';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';
import {databaseSourceSchema} from '@greiva/domain';
import {privateDatabaseSourceCreateResponseSchema,privateDatabaseSourceReadResponseSchema,privateDatabaseSourceCatalogResponseSchema} from '@greiva/protocol/private-database-source';
import {installPrivateWorkspaceSchema,verifyPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {PostgresPrivateDatabaseSourceStore,PrivateDatabaseSourceInvalidRequest} from '../../apps/api/src/private-database-source-store.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';
import {PrivateTransactionUnavailable,PrivateTransactionInvalidRequest} from '../../apps/api/src/private-transactions.js';
import {PrivateWorkspaceAccessDenied} from '@greiva/application';
import {SessionVerificationError} from '../../apps/api/src/session-verifier.js';
import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
import {emptyPageUpdate} from '@greiva/sync';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {PostgresPrivatePageMetadataStore} from '../../apps/api/src/private-page-metadata-store.js';
import {PostgresPrivatePageChangesStore} from '../../apps/api/src/private-page-changes-store.js';
import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
const actor=(subjectId='source-owner')=>({subjectId,issuer:'https://project.fixture.invalid/auth/v1',expiresAt:Math.floor(Date.now()/1000)+300});
async function isolated(run:(pool:pg.Pool,schema:string)=>Promise<void>,upgrade=true){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,connectionTimeoutMillis:5000,statement_timeout:10000}),schema='greiva_private_source_'+newId().replaceAll('-','');try{await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await installPrivatePageMetadataSchema(pool,schema);await installPrivatePageChangesSchema(pool,schema);if(upgrade)await installPrivateDatabaseSourceSchema(pool,schema);await run(pool,schema);}finally{try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function fixture(pool:pg.Pool,schema:string){const owner=actor(),bootstrap=new PostgresPrivateBootstrapStore(pool,schema),binding=await bootstrap.bootstrap(owner,{clientId:newId()}),store=new PostgresPrivateDatabaseSourceStore(pool,schema);const source=(name='My DB')=>databaseSourceSchema.parse({id:newId(),workspaceId:binding.workspaceId,name,schemaVersion:1,properties:[{id:newId(),type:'name',name:'Name'},{id:newId(),type:'text',name:'Text'}]});const request=(definition=source(),operationId=newId())=>({protocolVersion:1 as const,clientId:binding.clientId,operationId,source:definition});const create=async(body=request())=>privateDatabaseSourceCreateResponseSchema.parse(await store.create(owner,binding.workspaceId,body)),catalog=async(cursor:string|null=null,limit=100)=>privateDatabaseSourceCatalogResponseSchema.parse(await store.catalog(owner,binding.workspaceId,{protocolVersion:1,clientId:binding.clientId,cursor,limit}));return{owner,bootstrap,binding,store,source,request,create,catalog};}
async function counts(pool:pg.Pool,schema:string){const result=await pool.query(`SELECT (SELECT count(*)::int FROM "${schema}".private_database_sources) AS sources,(SELECT count(*)::int FROM "${schema}".private_database_source_operations) AS operations,(SELECT COALESCE(max(head_order),0)::text FROM "${schema}".private_database_source_heads) AS head`);return result.rows[0];}

real('DB-SOURCE-PG: explicit five-to-six migration preserves metadata/config and rejects repeats without repair',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),before=(await pool.query(`SELECT encode(secret,'hex') AS key FROM "${schema}".private_structured_config`)).rows[0]!.key,fingerprint=createHash('sha256').update(before).digest('hex');await installPrivateDatabaseSourceSchema(pool,schema);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(6);expect(await f.bootstrap.bootstrap(f.owner,{clientId:f.binding.clientId})).toEqual(f.binding);expect(createHash('sha256').update((await pool.query(`SELECT encode(secret,'hex') AS key FROM "${schema}".private_structured_config`)).rows[0]!.key).digest('hex')).toBe(fingerprint);await expect(installPrivateDatabaseSourceSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(6);expect(await counts(pool,schema)).toEqual({sources:0,operations:0,head:'0'});},false);});
real('DB-SOURCE-PG: failed DDL rolls the whole upgrade back and readiness never repairs tables',async()=>{await isolated(async(pool,schema)=>{await pool.query(`CREATE TABLE "${schema}".private_database_sources(blocker integer)`);await expect(installPrivateDatabaseSourceSchema(pool,schema)).rejects.toThrow();expect((await pool.query(`SELECT version FROM "${schema}".private_schema_version`)).rows[0]!.version).toBe(5);expect((await pool.query(`SELECT to_regclass($1) AS relation`,[schema+'.private_database_source_heads'])).rows[0]!.relation).toBeNull();await pool.query(`DROP TABLE "${schema}".private_database_sources`);await installPrivateDatabaseSourceSchema(pool,schema);await pool.query(`ALTER TABLE "${schema}".private_database_source_operations RENAME TO missing_operations`);await expect(verifyPrivateWorkspaceSchema(pool,schema)).rejects.toThrow();expect((await pool.query(`SELECT to_regclass($1) AS relation`,[schema+'.private_database_source_operations'])).rows[0]!.relation).toBeNull();},false);});
real('DB-SOURCE-PG: create, active read and exact replay commit definition/head/receipt once',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),request=f.request(),reply=await f.create(request);expect(await f.create(request)).toEqual(reply);expect(privateDatabaseSourceReadResponseSchema.parse(await f.store.read(f.owner,f.binding.workspaceId,request.source.id,{protocolVersion:1,clientId:f.binding.clientId})).snapshot).toEqual(reply.snapshot);expect(await counts(pool,schema)).toEqual({sources:1,operations:1,head:'1'});await expect(f.create({...request,source:{...request.source,name:'changed request'}})).rejects.toMatchObject({code:'operation_id_reused'});await expect(f.create({...request,operationId:newId()})).rejects.toMatchObject({code:'source_id_reused'});expect(await counts(pool,schema)).toEqual({sources:1,operations:1,head:'1'});});});
real('DB-SOURCE-PG: strict/canonical requests and other owner/issuer/workspace/device cannot mutate or read',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),request=f.request(),reply=await f.create(request),other=actor('other-owner'),binding=await f.bootstrap.bootstrap(other,{clientId:newId()});for(const [session,workspaceId,clientId] of [[other,f.binding.workspaceId,f.binding.clientId],[{...f.owner,issuer:'https://other.fixture.invalid/auth/v1'},f.binding.workspaceId,f.binding.clientId],[f.owner,binding.workspaceId,binding.clientId],[f.owner,f.binding.workspaceId,newId()]] as const)await expect(f.store.read(session,workspaceId,reply.snapshot.source.id,{protocolVersion:1,clientId})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);for(const source of [{...request.source,id:'019AA000-0000-7000-8000-00000000000A'},{...request.source,schemaVersion:2},{...request.source,ownerEmail:'no-copy@example.invalid'}])await expect(f.store.create(f.owner,f.binding.workspaceId,{...f.request(),source})).rejects.toBeInstanceOf(PrivateDatabaseSourceInvalidRequest);await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[f.binding.clientId]);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);expect(await counts(pool,schema)).toEqual({sources:1,operations:1,head:'1'});});});
real('DB-SOURCE-PG: serial workspace head prevents parallel create/replay from missing a committed source',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();const blocker=await pool.connect();try{await blocker.query('BEGIN');await blocker.query(`SELECT head_order FROM "${schema}".private_database_source_heads WHERE workspace_id=$1 FOR UPDATE`,[f.binding.workspaceId]);const request=f.request(f.source('captured source')),a=f.create(request),b=f.create(request),other=f.create();await vi.waitFor(async()=>expect((await pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND position($1 in query)>0 AND query LIKE '%private_database_source_heads%'`,[schema])).rows[0]!.n).toBeGreaterThanOrEqual(3),{timeout:3000});request.source.name='mutated caller';await blocker.query('COMMIT');const [one,two,three]=await Promise.all([a,b,other]);expect(one).toEqual(two);expect(one.snapshot.source.name).toBe('captured source');expect([one.snapshot.creationOrder,three.snapshot.creationOrder].sort()).toEqual(['2','3']);expect((await f.catalog()).sources).toHaveLength(3);expect(await counts(pool,schema)).toEqual({sources:3,operations:3,head:'3'});}finally{try{await blocker.query('ROLLBACK');}finally{blocker.release();}}});});
real('DB-SOURCE-PG: catalog is bounded/signed/header-only and retains its observed head across new creation',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);for(let i=0;i<101;i++)await f.create();const first=await f.catalog();expect(first).toMatchObject({afterOrder:'0',throughOrder:'100',headOrder:'101',hasMore:true});expect(first.sources).toHaveLength(100);expect(first.sources[0]).not.toHaveProperty('source');expect(first.sources[0]).not.toHaveProperty('properties');await f.create();const next=await f.catalog(first.cursor);expect(next).toMatchObject({afterOrder:'100',throughOrder:'101',headOrder:'101',hasMore:false,cursor:null});expect(next.sources).toHaveLength(1);expect((await f.catalog()).headOrder).toBe('102');const device=await f.bootstrap.bootstrap(f.owner,{clientId:newId()});await expect(f.store.catalog(f.owner,f.binding.workspaceId,{protocolVersion:1,clientId:device.clientId,cursor:first.cursor,limit:100})).rejects.toBeInstanceOf(PrivateTransactionInvalidRequest);await expect(f.catalog(first.cursor!.slice(0,-1)+'!')).rejects.toThrow();});});
real('DB-SOURCE-PG: filtered deleted windows advance without returning definitions or acting as delete ACK',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);let request=f.request();for(let i=0;i<101;i++){request=f.request();await f.create(request);}await pool.query(`UPDATE "${schema}".private_database_sources SET deleted=true,definition='{"unreadable":"filtered"}'::jsonb WHERE creation_order<=100`);const first=await f.catalog();expect(first).toMatchObject({sources:[],throughOrder:'100',headOrder:'101',hasMore:true});expect((await f.catalog(first.cursor)).sources).toHaveLength(1);await pool.query(`UPDATE "${schema}".private_database_sources SET deleted=true WHERE id=$1`,[request.source.id]);await expect(f.create(request)).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);expect((await f.catalog()).sources).toEqual([]);});});
real('DB-SOURCE-PG: malformed lookahead/head/definition fails closed instead of showing an empty database',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();await f.create();await pool.query(`UPDATE "${schema}".private_database_sources SET definition=jsonb_set(definition,'{workspaceId}',to_jsonb($1::text)) WHERE creation_order=2`,[newId()]);await expect(f.catalog(null,1)).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await pool.query(`UPDATE "${schema}".private_database_source_heads SET head_order=3`);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);});});
real('DB-SOURCE-PG: failure after definition insertion rolls back source, counter and immutable result together',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),connect=pool.connect.bind(pool);let fired=false;const faultPool={connect:async()=>{const client=await connect(),query=client.query.bind(client);client.query=((...args:unknown[])=>{const sql=typeof args[0]==='string'?args[0]:'';if(!fired&&sql.includes('private_database_source_operations VALUES')){fired=true;return Promise.reject(Error('fixture-private-source-cause'));}return(query as (...args:unknown[])=>unknown)(...args);}) as typeof client.query;const release=client.release.bind(client);client.release=(...args:Parameters<typeof release>)=>{client.query=query;client.release=release;release(...args);};return client;}} as unknown as pg.Pool,store=new PostgresPrivateDatabaseSourceStore(faultPool,schema),request=f.request();await expect(store.create(f.owner,f.binding.workspaceId,request)).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect(fired).toBe(true);expect(await counts(pool,schema)).toEqual({sources:0,operations:0,head:'0'});await f.create(request);expect(await counts(pool,schema)).toEqual({sources:1,operations:1,head:'1'});});});
real('DB-SOURCE-PG: session expiry while waiting for the source head prevents every write',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();let clock=Date.now();const store=new PostgresPrivateDatabaseSourceStore(pool,schema,()=>clock),blocker=await pool.connect();try{await blocker.query('BEGIN');await blocker.query(`SELECT head_order FROM "${schema}".private_database_source_heads WHERE workspace_id=$1 FOR UPDATE`,[f.binding.workspaceId]);const result=store.create(f.owner,f.binding.workspaceId,f.request()).catch(error=>error);await vi.waitFor(async()=>expect((await pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND position($1 in query)>0 AND query LIKE '%private_database_source_heads%'`,[schema])).rows[0]!.n).toBeGreaterThan(0),{timeout:3000});clock=(f.owner.expiresAt+1)*1000;await blocker.query('COMMIT');expect(await result).toBeInstanceOf(SessionVerificationError);expect(await counts(pool,schema)).toEqual({sources:1,operations:1,head:'1'});}finally{try{await blocker.query('ROLLBACK');}finally{blocker.release();}}});});
real('DB-SOURCE-PG: actual protected runtime/JWKS signature gates routes and keeps Auth profile/token out of source storage',async()=>{await isolated(async(pool,schema)=>{const keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'source-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:async()=>new Response(JSON.stringify({keys:[jwk]}))});try{const token=await new SignJWT({sub:'signed-source-owner',iss:'https://project.fixture.invalid/auth/v1',aud:'authenticated',email:'auth-only@example.invalid',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'source-fixture'}).sign(keys.privateKey),post=(path:string,body:unknown,authorized=true)=>fetch(runtime.address+path,{method:'POST',headers:{'content-type':'application/json',...(authorized?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}),clientId=newId(),registered=await post('/v1/workspaces/bootstrap',{clientId});expect(registered.status).toBe(200);const binding=await registered.json(),source=databaseSourceSchema.parse({id:newId(),workspaceId:binding.workspaceId,name:'Runtime source',schemaVersion:1,properties:[{id:newId(),name:'Name',type:'name'}]}),path='/v1/workspaces/'+binding.workspaceId+'/databases',request={protocolVersion:1,clientId,operationId:newId(),source};expect((await post(path+'/create',request,false)).status).toBe(401);const created=await post(path+'/create',request);expect(created.status).toBe(200);const reply=privateDatabaseSourceCreateResponseSchema.parse(await created.json());expect(privateDatabaseSourceCreateResponseSchema.parse(await(await post(path+'/create',request)).json())).toEqual(reply);expect((await post(path+'/'+source.id+'/read',{protocolVersion:1,clientId})).status).toBe(200);expect((await post(path+'/catalog',{protocolVersion:1,clientId,cursor:null})).status).toBe(200);const reused=await post(path+'/create',{...request,source:{...source,name:'changed'}});expect(reused.status).toBe(409);expect(await reused.json()).toEqual({error:'operation_id_reused'});expect((await post(path+'/'+source.id+'/read',{protocolVersion:1,clientId:newId()})).status).toBe(403);const stored=JSON.stringify((await pool.query(`SELECT definition,request,result FROM "${schema}".private_database_sources JOIN "${schema}".private_database_source_operations ON source_id=id`)).rows);expect(stored).not.toContain('auth-only@example.invalid');expect(stored).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(6);}finally{await runtime.close();}});});
real('DB-SOURCE-PG: schema six retains Page bootstrap/title journal and structured stream behavior',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),id=newId(),pages=new PostgresPrivatePageStore(pool,schema),titles=new PostgresPrivatePageMetadataStore(pool,schema),changes=new PostgresPrivatePageChangesStore(pool,schema),structured=new PostgresPrivateStructuredStore(pool,schema);await pages.bootstrap(f.owner,f.binding.workspaceId,id,{protocolVersion:1,clientId:f.binding.clientId,editorSchemaVersion:1,title:'base',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')});await titles.rename(f.owner,f.binding.workspaceId,id,{protocolVersion:1,clientId:f.binding.clientId,operationId:newId(),baseVersion:0,title:'new'});expect(await changes.pull(f.owner,f.binding.workspaceId,{protocolVersion:1,clientId:f.binding.clientId})).toMatchObject({headOrder:'2',events:[{pageId:id,version:0},{pageId:id,version:1}]});expect(await structured.push(f.owner,f.binding.workspaceId,{protocolVersion:1,workspaceId:f.binding.workspaceId,clientId:f.binding.clientId,operations:[{operationId:newId(),clientId:f.binding.clientId,entityType:'task',entityId:newId(),kind:'create',baseVersion:null,payload:{title:'retained task',status:'todo',due:null}}]})).toMatchObject({results:[{status:'acknowledged'}]});expect((await f.catalog()).sources).toEqual([]);});});
