import {it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import pg from 'pg';import * as Y from 'yjs';import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {emptyPageUpdate,supabaseAuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {createSupabasePrivateApp} from '../../apps/api/src/supabase-private-app.js';import {PostgresPrivateAccessStore} from '../../apps/api/src/private-access-store.js';import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';import {PostgresPrivateTransactions} from '../../apps/api/src/private-transactions.js';import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';import {PostgresPrivatePageMetadataStore} from '../../apps/api/src/private-page-metadata-store.js';

it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1')('TITLE-CLIENT-PG: signed fixture HTTP and two native SQLite stores preserve offline chain/lost ACK, conflict resolution, late body metadata and revoked pending',async()=>{
  const directory=mkdtempSync(join(tmpdir(),'greiva-title-client-')),schema='greiva_private_'+newId().replaceAll('-',''),pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),projectUrl='https://project.fixture.invalid',keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'fixture',alg:'ES256'};
  const registries:WorkspaceRegistryDevice[]=[],auths:ReturnType<typeof supabaseAuthSession>[]=[],connections:PrivateWorkspaceConnection[]=[],stores:NativeWorkspaceStore[]=[];let app:Awaited<ReturnType<typeof createSupabasePrivateApp>>|undefined;
  try{
    await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await installPrivatePageMetadataSchema(pool,schema);
    app=await createSupabasePrivateApp({projectUrl,algorithm:'ES256'},new PostgresPrivateAccessStore(pool,schema),new PostgresPrivateBootstrapStore(pool,schema),async()=>new Response(JSON.stringify({keys:[jwk]})),new PostgresPrivateTransactions(pool,schema),new PostgresPrivateStructuredStore(pool,schema),new PostgresPrivatePageStore(pool,schema),new PostgresPrivatePageMetadataStore(pool,schema));await app.listen(0,'127.0.0.1');const apiUrl=await app.getUrl();
    const client=async(name:string)=>{const auth=supabaseAuthSession({projectUrl,algorithm:'ES256',publishableKey:'sb_publishable_fixture',apiUrl},async(input,init)=>{if(new URL(String(input)).origin!==projectUrl)return fetch(input,init);const token=await new SignJWT({sub:'owner',iss:projectUrl+'/auth/v1',aud:'authenticated',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(keys.privateKey);return new Response(JSON.stringify({access_token:token,refresh_token:'fixture-refresh',token_type:'bearer',user:{id:'owner'}}));});auths.push(auth);await auth.login('fixture@example.invalid','fixture-password');const connection=new PrivateWorkspaceConnection(auth,{apiUrl,clientId:newId()});connections.push(connection);await connection.bootstrap();const registry=new WorkspaceRegistryDevice(join(directory,name));registries.push(registry);const store=await NativeWorkspaceStore.open(connection,registry.invoke);stores.push(store);return{auth,connection,registry,store};};
    const one=await client('one'),two=await client('two'),id=newId(),firstPage=one.store.page(id),firstSession=one.connection.openPage(id,firstPage);await firstPage.create('base',emptyPageUpdate());const creation=await firstPage.prepare();expect(creation).not.toBeNull();await firstSession.push(creation!);const secondSession=two.connection.openPage(id,two.store.page(id)),binaryRequest={protocolVersion:1 as const,clientId:two.connection.context!.clientId,editorSchemaVersion:1,stateVector:'AA'};await secondSession.pull(binaryRequest);
    const post=(client:typeof one,kind:string,body:object|string)=>client.auth.authorized((authorization,signal)=>fetch(`${apiUrl}/v1/workspaces/${client.connection.context!.workspaceId}/pages/${id}/metadata/${kind}`,{method:'POST',headers:{authorization,'content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body),signal}));
    const query=async(client:typeof one,port:ReturnType<NativeWorkspaceStore['title']>)=>{const request={protocolVersion:1,clientId:client.connection.context!.clientId,afterConflict:null,limit:100},response=await post(client,'read',request);expect(response.status).toBe(200);const body=await response.json();await port.receive(request,body);return body;};
    const send=async(client:typeof one,port:ReturnType<NativeWorkspaceStore['title']>,lose=false)=>{const prepared=await port.prepare();expect(prepared).not.toBeNull();const response=await post(client,'rename',prepared!.wire);expect(response.status).toBe(200);const body=await response.json();if(!lose)await port.acknowledge(prepared,body);return{prepared:prepared!,body};};
    const left=one.store.title(id),right=two.store.title(id);await query(one,left);await query(two,right);const structured=await one.store.structuredSnapshot();const initialBinary=(await pool.query(`SELECT server_order,digest,encode(update,'hex') AS bytes FROM "${schema}".private_page_updates`)).rows;
    const firstId=newId(),secondId=newId();await left.enqueue({operationId:firstId,title:'first offline'});const lost=await send(one,left,true);await left.enqueue({operationId:secondId,title:'second offline'});await one.store.close();await one.registry.close('SIGKILL');const reopened=await NativeWorkspaceStore.open(one.connection,one.registry.invoke);stores.push(reopened);const fresh=reopened.title(id);expect(await fresh.prepare()).toEqual(lost.prepared);expect((await fresh.load()).localTitle).toBe('second offline');const retried=await send(one,fresh);expect(retried.body).toEqual(lost.body);expect(JSON.parse((await fresh.prepare())!.wire).baseVersion).toBe(1);await send(one,fresh);expect((await fresh.load()).base?.version).toBe(2);
    await right.enqueue({operationId:newId(),title:'peer offline'});const collided=await send(two,right);expect(collided.body.result.status).toBe('conflict');const cf=collided.body.result.conflict;expect(cf).toMatchObject({base:'base',local:'peer offline',remote:'second offline'});expect((await right.load()).conflicts[0]?.record).toEqual(cf);const resolvedId=newId();await right.enqueue({operationId:resolvedId,title:cf.local,resolution:{conflictId:cf.id,choice:'local'}});await send(two,right);expect((await right.load()).conflicts[0]?.resolvedBy).toBe(resolvedId);await query(one,fresh);expect((await fresh.load()).localTitle).toBe('peer offline');
    // A retry of the original creation now returns the current title. Its ACK
    // still confirms binary identity and cannot replace the managed title base.
    const seed=new Y.Doc({gc:false});Y.applyUpdate(seed,emptyPageUpdate());const vector=Buffer.from(Y.encodeStateVector(seed)).toString('base64url');seed.destroy();const reopenedPage=reopened.page(id),reopenedSession=one.connection.openPage(id,reopenedPage);await reopenedSession.push(creation!);await reopenedPage.receive({...one.connection.context!,pageId:id,documentName:'page:'+id,editorSchemaVersion:1},{...binaryRequest,clientId:one.connection.context!.clientId},{protocolVersion:1,workspaceId:one.connection.context!.workspaceId,pageId:id,documentName:'page:'+id,editorSchemaVersion:1,metadata:{...collided.body.metadata,title:'old body title'},headOrder:'1',update:Buffer.from(emptyPageUpdate()).toString('base64url'),digest:initialBinary[0]!.digest,stateVector:vector},emptyPageUpdate());expect((await fresh.load()).localTitle).toBe('peer offline');expect((await reopenedPage.load()).page.metadata.title).toBe('peer offline');expect(await reopened.structuredSnapshot()).toEqual(structured);expect((await pool.query(`SELECT server_order,digest,encode(update,'hex') AS bytes FROM "${schema}".private_page_updates`)).rows).toEqual(initialBinary);
    await fresh.enqueue({operationId:newId(),title:'retained after refresh'});const pending=await fresh.prepare();await one.auth.refresh();await reopened.close();await expect(fresh.load()).rejects.toMatchObject({stage:'closed'});await one.connection.bootstrap();const afterRefresh=await NativeWorkspaceStore.open(one.connection,one.registry.invoke);stores.push(afterRefresh);expect(await afterRefresh.title(id).prepare()).toEqual(pending);await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[one.connection.context!.clientId]);expect((await post(one,'rename',pending!.wire)).status).toBe(403);expect((await afterRefresh.title(id).load()).pending).toBe(1);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_title_operations WHERE operation_id=$1`,[firstId])).rows[0].n).toBe(1);
  }finally{for(const store of stores)try{await store.close();}catch{/* closed retained store */}for(const connection of connections)connection.close();for(const auth of auths)auth.close();for(const registry of registries)await registry.close();try{await app?.close();await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();rmSync(directory,{recursive:true,force:true});}}
});
