import {it,expect,vi} from 'vitest';
import pg from 'pg';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';
import {databaseSourceSchema} from '@greiva/domain';
import {PrivateWorkspaceAccessDenied} from '@greiva/application';
import {privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
import {privateDatabaseViewCatalogResponseSchema} from '@greiva/protocol/private-database-view-catalog';
import {installPrivateWorkspaceSchema,verifyPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {PostgresPrivateDatabaseViewStore} from '../../apps/api/src/private-database-view-store.js';
import {PostgresPrivateDatabaseViewCatalogStore} from '../../apps/api/src/private-database-view-catalog-store.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';
import {PrivateTransactionInvalidRequest,PrivateTransactionUnavailable} from '../../apps/api/src/private-transactions.js';
import {SessionVerificationError} from '../../apps/api/src/session-verifier.js';
import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
const actor=()=>({subjectId:'view-catalog-owner',issuer:'https://project.fixture.invalid/auth/v1',expiresAt:Math.floor(Date.now()/1000)+300});
async function isolated(run:(pool:pg.Pool,schema:string)=>Promise<void>,upgrade=true){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_vcat_'+newId().replaceAll('-','');try{await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await installPrivatePageMetadataSchema(pool,schema);await installPrivatePageChangesSchema(pool,schema);await installPrivateDatabaseSourceSchema(pool,schema);await installPrivateDatabaseRecordSchema(pool,schema);await installPrivateDatabaseRecordCatalogSchema(pool,schema);await installPrivateDatabaseViewSchema(pool,schema);if(upgrade)await installPrivateDatabaseViewCatalogSchema(pool,schema);await run(pool,schema);}finally{try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function fixture(pool:pg.Pool,schema:string){const owner=actor(),bootstrap=new PostgresPrivateBootstrapStore(pool,schema),binding=await bootstrap.bootstrap(owner,{clientId:newId()}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),store=new PostgresPrivateDatabaseViewStore(pool,schema),catalogs=new PostgresPrivateDatabaseViewCatalogStore(pool,schema),nameId=newId(),source=databaseSourceSchema.parse({id:newId(),workspaceId:binding.workspaceId,name:'Views',schemaVersion:1,properties:[{id:nameId,name:'Name',type:'name'}]});await sources.create(owner,binding.workspaceId,{protocolVersion:1,clientId:binding.clientId,operationId:newId(),source});const prepare=(viewId=newId())=>({protocolVersion:1 as const,clientId:binding.clientId,operationId:newId(),intent:{kind:'create' as const,sourceId:source.id,schemaVersion:1,viewId,baseVersion:null,settings:{name:'Table',layout:'table' as const,visiblePropertyIds:[nameId],filter:null,sorts:[]}}}),write=async(request:unknown)=>privateDatabaseViewWriteResponseSchema.parse(await store.write(owner,binding.workspaceId,source.id,request)),create=async()=>{const request=prepare();return{request,receipt:await write(request)};},catalog=async(cursor:string|null=null,limit=100)=>privateDatabaseViewCatalogResponseSchema.parse(await catalogs.catalog(owner,binding.workspaceId,source.id,{protocolVersion:1,clientId:binding.clientId,cursor,limit}));return{owner,bootstrap,binding,sources,store,catalogs,nameId,source,prepare,write,create,catalog};}
async function head(pool:pg.Pool,schema:string,sourceId:string){return(await pool.query(`SELECT head_order::text FROM "${schema}".private_database_view_heads WHERE source_id=$1`,[sourceId])).rows[0]?.head_order??'0';}
function interceptedPool(pool:pg.Pool,intercept:(sql:string)=>Promise<void>){const connect=pool.connect.bind(pool);return{connect:async()=>{const client=await connect(),query=client.query.bind(client);client.query=(async(...args:unknown[])=>{await intercept(typeof args[0]==='string'?args[0]:'');return(query as (...args:unknown[])=>unknown)(...args);}) as typeof client.query;const release=client.release.bind(client);client.release=(...args:Parameters<typeof release>)=>{client.query=query;client.release=release;release(...args);};return client;}} as unknown as pg.Pool;}
real('DB-VIEW-CATALOG-PG: explicit nine to ten seeds ID order and preserves original snapshots/history/receipts/key',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=f.prepare(),b=f.prepare(),second=await f.write(b),first=await f.write(a),saved=(await pool.query(`SELECT request,result FROM "${schema}".private_database_view_operations ORDER BY operation_id`)).rows,key=(await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0]!.secret;await installPrivateDatabaseViewCatalogSchema(pool,schema);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(10);expect((await f.catalog()).views.map(view=>view.id)).toEqual([a.intent.viewId,b.intent.viewId].sort());expect((await f.catalog()).views.map(view=>view.creationOrder)).toEqual(['1','2']);expect(await f.write(a)).toEqual(first);expect(await f.write(b)).toEqual(second);expect((await pool.query(`SELECT request,result FROM "${schema}".private_database_view_operations ORDER BY operation_id`)).rows).toEqual(saved);expect((await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0]!.secret).toEqual(key);expect(await f.sources.read(f.owner,f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:f.binding.clientId})).toMatchObject({snapshot:{source:f.source}});await expect(installPrivateDatabaseViewCatalogSchema(pool,schema)).rejects.toThrow();await pool.query(`ALTER TABLE "${schema}".private_database_view_heads RENAME COLUMN head_order TO broken`);await expect(verifyPrivateWorkspaceSchema(pool,schema)).rejects.toThrow();},false);});
real('DB-VIEW-CATALOG-PG: invalid seed/DDL collision rollback all new columns and do not repair history',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),created=await f.create();await pool.query(`UPDATE "${schema}".private_database_view_history SET snapshot=jsonb_set(snapshot,'{view,name}','"bad history"')`);await expect(installPrivateDatabaseViewCatalogSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(9);await pool.query(`UPDATE "${schema}".private_database_view_history SET snapshot=$1`,[JSON.stringify(created.receipt.snapshot)]);await pool.query(`CREATE TABLE "${schema}".private_database_view_heads(fixture integer)`);await expect(installPrivateDatabaseViewCatalogSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(9);expect((await pool.query(`SELECT count(*)::int AS n FROM information_schema.columns WHERE table_schema=$1 AND table_name='private_database_views' AND column_name='creation_order'`,[schema])).rows[0]!.n).toBe(0);},false);});
real('DB-VIEW-CATALOG-PG: 101 numeric positions paginate at100, freeze membership head and observe current labels/versions',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),created=[];for(let i=0;i<101;i++)created.push(await f.create());const first=await f.catalog();expect(first.views).toHaveLength(100);expect(first.views.map(item=>item.creationOrder)).toEqual(Array.from({length:100},(_v,i)=>String(i+1)));expect(first).toMatchObject({headOrder:'101',throughOrder:'100',hasMore:true});const last=created[100]!,newer=await f.create();await f.write({protocolVersion:1,clientId:f.binding.clientId,operationId:newId(),intent:{kind:'update',sourceId:f.source.id,schemaVersion:1,viewId:last.request.intent.viewId,baseVersion:1,patch:{name:'Current List',layout:'list'}}});const second=await f.catalog(first.cursor);expect(second).toMatchObject({headOrder:'101',throughOrder:'101',hasMore:false,cursor:null});expect(second.views).toEqual([{id:last.request.intent.viewId,workspaceId:f.binding.workspaceId,sourceId:f.source.id,version:2,name:'Current List',layout:'list',creationOrder:'101'}]);const fresh=await f.catalog(),tail=await f.catalog(fresh.cursor);expect(tail.views.at(-1)?.id).toBe(newer.request.intent.viewId);expect(first.views.every(item=>!('filter' in item)&&!('sorts' in item)&&!('values' in item))).toBe(true);expect(first.views.every(item=>item.version===1&&item.name==='Table')).toBe(true);});});
real('DB-VIEW-CATALOG-PG: deleted raw windows advance without delete ACK or consuming operations',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=await f.create(),b=await f.create(),c=await f.create();await pool.query(`UPDATE "${schema}".private_database_views SET deleted=true WHERE id=ANY($1::uuid[])`,[[a.request.intent.viewId,b.request.intent.viewId]]);const first=await f.catalog(null,2);expect(first).toMatchObject({views:[],afterOrder:'0',throughOrder:'2',headOrder:'3',hasMore:true});const second=await f.catalog(first.cursor,2);expect(second.views.map(item=>item.id)).toEqual([c.request.intent.viewId]);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_view_operations`)).rows[0]!.n).toBe(3);expect(await head(pool,schema,f.source.id)).toBe('3');});});
real('DB-VIEW-CATALOG-PG: lookahead header/head corruption fails closed and catalog never repairs a missing head',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();const b=await f.create();await pool.query(`UPDATE "${schema}".private_database_views SET snapshot=jsonb_set(snapshot,'{view,layout}','"board"') WHERE id=$1`,[b.request.intent.viewId]);await expect(f.catalog(null,1)).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await pool.query(`UPDATE "${schema}".private_database_views SET snapshot=$2 WHERE id=$1`,[b.request.intent.viewId,JSON.stringify(b.receipt.snapshot)]);await pool.query(`UPDATE "${schema}".private_database_view_heads SET head_order=3 WHERE source_id=$1`,[f.source.id]);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await pool.query(`DELETE FROM "${schema}".private_database_view_heads WHERE source_id=$1`,[f.source.id]);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect(await head(pool,schema,f.source.id)).toBe('0');await expect(f.create()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect(await head(pool,schema,f.source.id)).toBe('0');});});
real('DB-VIEW-CATALOG-PG: new empty Source has no read-side head and failed ledger rolls back head/current/history',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);expect(await f.catalog()).toMatchObject({views:[],headOrder:'0',hasMore:false});expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_view_heads WHERE source_id=$1`,[f.source.id])).rows[0]!.n).toBe(0);const store=new PostgresPrivateDatabaseViewStore(interceptedPool(pool,async sql=>{if(sql.startsWith('INSERT INTO')&&sql.includes('.private_database_view_operations '))throw Error('fixture ledger failure');}),schema),request=f.prepare();await expect(store.write(f.owner,f.binding.workspaceId,f.source.id,request)).rejects.toThrow();expect(await head(pool,schema,f.source.id)).toBe('0');expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_views`)).rows[0]!.n).toBe(0);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_view_history`)).rows[0]!.n).toBe(0);const saved=await f.write(request);expect(await f.write(request)).toEqual(saved);expect(await head(pool,schema,f.source.id)).toBe('1');});});
real('DB-VIEW-CATALOG-PG: concurrent creates/exact replay reserve one creation position per new View',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=f.prepare(),b=f.prepare(),results=await Promise.all([f.write(a),f.write(b),f.write(a)]);expect(results[0]).toEqual(results[2]);expect(await head(pool,schema,f.source.id)).toBe('2');expect((await f.catalog()).views.map(item=>item.creationOrder)).toEqual(['1','2']);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_view_operations`)).rows[0]!.n).toBe(2);});});
real('DB-VIEW-CATALOG-PG: owner/device/Source/cursor scope deny and lock-wait expiry cannot return success',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();await f.create();const first=await f.catalog(null,1),body={protocolVersion:1,clientId:f.binding.clientId};await expect(f.catalogs.catalog({...f.owner,subjectId:'other'},f.binding.workspaceId,f.source.id,body)).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.catalogs.catalog(f.owner,f.binding.workspaceId,newId(),body)).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.catalogs.catalog(f.owner,f.binding.workspaceId,f.source.id,{...body,clientId:newId()})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.catalog(first.cursor!.slice(0,-4))).rejects.toBeInstanceOf(PrivateTransactionInvalidRequest);const device=await f.bootstrap.bootstrap(f.owner,{clientId:newId()});await expect(f.catalogs.catalog(f.owner,f.binding.workspaceId,f.source.id,{...body,clientId:device.clientId,cursor:first.cursor})).rejects.toBeInstanceOf(PrivateTransactionInvalidRequest);const locker=await pool.connect();let now=Date.now(),waiting=false;try{await locker.query('BEGIN');await locker.query(`SELECT id FROM "${schema}".private_database_sources WHERE id=$1 FOR UPDATE`,[f.source.id]);const store=new PostgresPrivateDatabaseViewCatalogStore(interceptedPool(pool,async sql=>{if(sql.includes('.private_database_sources ')&&sql.includes('FOR SHARE'))waiting=true;}),schema,()=>now),work=store.catalog(f.owner,f.binding.workspaceId,f.source.id,body),caught=expect(work).rejects.toBeInstanceOf(SessionVerificationError);await expect.poll(()=>waiting).toBe(true);now=(f.owner.expiresAt+1)*1000;await locker.query('COMMIT');await caught;}finally{await locker.query('ROLLBACK');locker.release();}await pool.query(`UPDATE "${schema}".private_database_sources SET deleted=true WHERE id=$1`,[f.source.id]);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await pool.query(`UPDATE "${schema}".private_database_sources SET deleted=false WHERE id=$1`,[f.source.id]);await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[f.binding.clientId]);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);});});
real('DB-VIEW-CATALOG-PG: signed actual schema10 runtime catalog/write/read retains Source and Record headers',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),keys=await generateKeyPair('ES256'),jwk=await exportJWK(keys.publicKey);Object.assign(jwk,{kid:'vcatalog-fixture',alg:'ES256'});const server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});try{const token=await new SignJWT({sub:f.owner.subjectId,iss:f.owner.issuer,aud:'authenticated',exp:f.owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'vcatalog-fixture'}).sign(keys.privateKey),post=(path:string,body:unknown,auth=true)=>fetch(runtime.address+path,{method:'POST',headers:{'content-type':'application/json',...(auth?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}),root='/v1/workspaces/'+f.binding.workspaceId+'/databases',path=root+'/'+f.source.id+'/views',request=f.prepare(),body={protocolVersion:1,clientId:f.binding.clientId};expect((await post(path+'/catalog',body,false)).status).toBe(401);expect((await post(path+'/write',request)).status).toBe(200);const response=await post(path+'/catalog',body);expect(response.status).toBe(200);expect(privateDatabaseViewCatalogResponseSchema.parse(await response.json()).views).toHaveLength(1);expect((await post(path+'/'+request.intent.viewId+'/read',body)).status).toBe(200);expect((await post(root+'/catalog',{...body,cursor:null})).status).toBe(200);expect((await post(root+'/'+f.source.id+'/records/catalog',body)).status).toBe(200);expect((await post(path+'/catalog',{...body,limit:101})).status).toBe(400);expect((await post(path+'/catalog',{...body,clientId:newId()})).status).toBe(403);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(10);}finally{await runtime.close();}});});
real.each(['before-commit','after-commit'] as const)('DB-VIEW-CATALOG-SIGKILL-%s: View/head/history/ledger recover together without double position',async boundary=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),request=f.prepare(),wire=JSON.stringify({owner:f.owner,workspaceId:f.binding.workspaceId,sourceId:f.source.id,request}),child=spawn(process.execPath,['tests/fixtures/private-database-view-crash.mjs',schema,boundary,wire],{env:process.env,stdio:['ignore','ignore','pipe','ipc']});child.stderr!.on('data',()=>{/* fixed output only */});const exited=new Promise<NodeJS.Signals|null>((resolve,reject)=>{child.once('exit',(_code,signal)=>resolve(signal));child.once('error',reject);});try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('View catalog boundary timeout')),7000);child.once('message',message=>{clearTimeout(timer);if((message as {event?:string;boundary?:string}).event==='boundary'&&(message as {boundary?:string}).boundary===boundary)resolve();else reject(Error('View worker failed'));});void exited.then(()=>{clearTimeout(timer);reject(Error('View worker exited before boundary'));});});child.kill('SIGKILL');expect(await exited).toBe('SIGKILL');await expect.poll(()=>head(pool,schema,f.source.id)).toBe(boundary==='before-commit'?'0':'1');const saved=await f.write(request);expect(await f.write(request)).toEqual(saved);expect(await head(pool,schema,f.source.id)).toBe('1');expect((await f.catalog()).views.map(item=>item.creationOrder)).toEqual(['1']);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_view_operations`)).rows[0]!.n).toBe(1);}finally{if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await exited;}}});});
