import {it,expect,vi} from 'vitest';
import pg from 'pg';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';
import {emptyPageUpdate} from '@greiva/sync';
import {PrivateWorkspaceAccessDenied} from '@greiva/application';
import {installPrivateWorkspaceSchema,verifyPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {PostgresPrivatePageMetadataStore} from '../../apps/api/src/private-page-metadata-store.js';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';
import {PostgresPrivateAccessStore} from '../../apps/api/src/private-access-store.js';
import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';
import {PostgresPrivateTransactions,PrivateTransactionUnavailable} from '../../apps/api/src/private-transactions.js';
import {createPrivateApp} from '../../apps/api/src/private-app.js';
import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
import {SessionVerificationError} from '../../apps/api/src/session-verifier.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
const actor=(subjectId='owner')=>({subjectId,issuer:'https://auth.fixture.invalid/auth/v1',expiresAt:Math.floor(Date.now()/1000)+300});
async function isolated(run:(pool:pg.Pool,schema:string)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,connectionTimeoutMillis:5000,statement_timeout:5000}),schema='greiva_private_'+newId().replaceAll('-','');try{await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await run(pool,schema);}finally{try{await pool.query(`DROP SCHEMA "${schema}" CASCADE`);}finally{await pool.end();}}}
async function fixture(pool:pg.Pool,schema:string,upgrade=true){const owner=actor(),bootstrap=new PostgresPrivateBootstrapStore(pool,schema),binding=await bootstrap.bootstrap(owner,{clientId:newId()}),id=newId(),pages=new PostgresPrivatePageStore(pool,schema),store=new PostgresPrivatePageMetadataStore(pool,schema),request={protocolVersion:1,clientId:binding.clientId,editorSchemaVersion:1,title:'base',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')};await pages.bootstrap(owner,binding.workspaceId,id,request);if(upgrade)await installPrivatePageMetadataSchema(pool,schema);
  const rename=(title:string,baseVersion=0,extra:Record<string,unknown>={})=>store.rename(owner,binding.workspaceId,id,{protocolVersion:1,clientId:binding.clientId,operationId:newId(),baseVersion,title,...extra});
  const read=(extra:Record<string,unknown>={})=>store.read(owner,binding.workspaceId,id,{protocolVersion:1,clientId:binding.clientId,...extra});return{owner,bootstrap,binding,id,pages,store,request,rename,read};}
async function journal(pool:pg.Pool,schema:string){return(await pool.query(`SELECT page_id,server_order,digest,encode(update,'hex') AS bytes FROM "${schema}".private_page_updates ORDER BY page_id,server_order`)).rows;}
real('TITLE-SCHEMA-PG: atomic upgrade preserves binary/key/epoch and refuses partial/reinstall/orphan',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema,false),binary=await journal(pool,schema),key=(await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0].secret;
  await pool.query(`CREATE TABLE "${schema}".private_page_title_history(unexpected boolean)`);await expect(installPrivatePageMetadataSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(3);expect((await pool.query('SELECT 1 FROM information_schema.tables WHERE table_schema=$1 AND table_name=$2',[schema,'private_page_title_state'])).rowCount).toBe(0);
  await pool.query(`DROP TABLE "${schema}".private_page_title_history`);await installPrivatePageMetadataSchema(pool,schema);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(4);await expect(installPrivatePageMetadataSchema(pool,schema)).rejects.toThrow();expect((await f.read()).version).toBe(0);expect(await journal(pool,schema)).toEqual(binary);expect((await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0].secret).toEqual(key);expect((await f.read()).workspaceEpoch).toBe(f.binding.epoch);
});await isolated(async(pool,schema)=>{const f=await fixture(pool,schema,false);await pool.query(`INSERT INTO "${schema}".private_resources VALUES('page',$1,$2,false)`,[newId(),f.binding.workspaceId]);await expect(installPrivatePageMetadataSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(3);});});
real('TITLE-RETRY-PG: immutable replies survive reopen/later edits; changed nonce never alters binary or title',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),binary=await journal(pool,schema),operationId=newId(),first=await f.rename('first',0,{operationId});expect(first).toMatchObject({version:1,metadata:{title:'first'},result:{status:'applied'}});await f.rename('second',1);
  expect(await new PostgresPrivatePageMetadataStore(pool,schema).rename(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:f.binding.clientId,operationId,baseVersion:0,title:'first'})).toEqual(first);await expect(f.rename('altered',0,{operationId})).rejects.toMatchObject({code:'operation_id_reused'});expect((await f.read()).metadata.title).toBe('second');expect(await journal(pool,schema)).toEqual(binary);
  expect((await f.pages.bootstrap(f.owner,f.binding.workspaceId,f.id,f.request)).metadata.title).toBe('second');expect((await f.pages.read(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:f.binding.clientId,editorSchemaVersion:1,stateVector:'AA'})).metadata.title).toBe('second');
});});
real.each(['before-commit','after-commit'] as const)('TITLE-SIGKILL-%s: title/history/receipt and conflict resolution recover atomically',async boundary=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.rename('remote');const pending=await f.rename('local');if(pending.result.status!=='conflict')throw new Error('Conflict required');const c=pending.result.conflict,binary=await journal(pool,schema),body={protocolVersion:1,clientId:f.binding.clientId,operationId:newId(),baseVersion:1,title:'local',resolution:{conflictId:c.id,choice:'local'}},wire=JSON.stringify({workspaceId:f.binding.workspaceId,pageId:f.id,body});
  const child=spawn(process.execPath,['tests/fixtures/private-page-title-crash.mjs',schema,boundary,wire],{env:process.env,stdio:['ignore','ignore','ignore','ipc']}),exited=new Promise<NodeJS.Signals|null>((resolve,reject)=>{child.once('exit',(_code,signal)=>resolve(signal));child.once('error',reject);});
  try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Title crash boundary timeout')),7000);child.once('message',message=>{clearTimeout(timer);if((message as {event?:string;boundary?:string}).event==='boundary'&&(message as {boundary?:string}).boundary===boundary)resolve();else reject(new Error('Title worker failed'));});void exited.then(()=>{clearTimeout(timer);reject(new Error('Worker exited before boundary'));});});child.kill('SIGKILL');expect(await exited).toBe('SIGKILL');
    await expect.poll(async()=>(await pool.query(`SELECT version FROM "${schema}".private_page_title_state WHERE page_id=$1`,[f.id])).rows[0].version).toBe(boundary==='before-commit'?'1':'2');expect((await pool.query(`SELECT resolved_by FROM "${schema}".private_page_title_conflicts WHERE id=$1`,[c.id])).rows[0].resolved_by).toBe(boundary==='before-commit'?null:body.operationId);
    const recovered=new PostgresPrivatePageMetadataStore(pool,schema),receipt=await recovered.rename(f.owner,f.binding.workspaceId,f.id,body);expect(receipt).toMatchObject({version:2,metadata:{title:'local'},result:{status:'applied'}});expect(await recovered.rename(f.owner,f.binding.workspaceId,f.id,body)).toEqual(receipt);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_title_operations WHERE operation_id=$1`,[body.operationId])).rows[0].n).toBe(1);expect((await f.read()).conflicts).toEqual([]);expect(await journal(pool,schema)).toEqual(binary);
  }finally{if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await exited;}}
});});
real('TITLE-CONFLICT-PG: canonical three values, no-op merges, new-operation resolution, stale/wrong choice rejections',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.rename('remote');const pending=await f.rename('local');expect(pending.result.status).toBe('conflict');if(pending.result.status!=='conflict')throw new Error('Conflict required');const c=pending.result.conflict;expect(c).toMatchObject({base:'base',local:'local',remote:'remote',baseVersion:0,remoteVersion:1});expect((await f.read()).metadata.title).toBe('remote');expect((await f.rename('base')).version).toBe(1);expect((await f.rename('remote')).version).toBe(1);
  expect((await f.rename('invented',1,{resolution:{conflictId:c.id,choice:'local'}})).result).toEqual({status:'rejected',code:'resolution_invalid'});await f.rename('new remote',1);expect((await f.rename('local',1,{resolution:{conflictId:c.id,choice:'local'}})).result).toEqual({status:'rejected',code:'resolution_stale'});expect((await f.read()).conflicts).toEqual([c]);
  const operationId=newId();expect(await f.rename('local',2,{operationId,resolution:{conflictId:c.id,choice:'local'}})).toMatchObject({version:3,metadata:{title:'local'},result:{status:'applied'}});expect((await f.read()).conflicts).toEqual([]);expect((await pool.query(`SELECT record,resolved_by FROM "${schema}".private_page_title_conflicts`)).rows[0]).toEqual({record:c,resolved_by:operationId});expect((await f.rename('remote',3,{resolution:{conflictId:c.id,choice:'remote'}})).result).toEqual({status:'rejected',code:'resolution_invalid'});
});});
real('TITLE-PAGINATION-PG: bounded keyset survives reopen, omits resolved conflicts and preserves remote-choice no-op',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.rename('remote');for(let i=0;i<3;i++)await f.rename('local'+i);const first=await f.read({limit:1}),second=await f.store.read(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:f.binding.clientId,limit:1,afterConflict:first.nextAfter}),last=await f.read({limit:1,afterConflict:second.nextAfter});expect([first.conflicts[0]!.id,second.conflicts[0]!.id,last.conflicts[0]!.id]).toEqual((await f.read()).conflicts.map(c=>c.id));expect(last.nextAfter).toBeNull();const c=second.conflicts[0]!;await f.rename(c.remote,1,{resolution:{conflictId:c.id,choice:'remote'}});expect((await f.read()).version).toBe(1);expect((await f.read()).conflicts).toHaveLength(2);
});});
real('TITLE-CONCURRENT-PG: same-base renames retain alternatives; cross-Page nonce collision rolls back losing transaction',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),results=await Promise.all(Array.from({length:6},(_,i)=>f.rename('peer'+i)));expect(results.filter(r=>r.result.status==='applied')).toHaveLength(1);expect(results.filter(r=>r.result.status==='conflict')).toHaveLength(5);expect((await f.read()).version).toBe(1);expect((await f.read()).conflicts).toHaveLength(5);
  const other=newId();await f.pages.bootstrap(f.owner,f.binding.workspaceId,other,f.request);const operationId=newId(),body={protocolVersion:1,clientId:f.binding.clientId,operationId,baseVersion:0,title:'same nonce'},outcomes=await Promise.allSettled([f.store.rename(f.owner,f.binding.workspaceId,f.id,body),f.store.rename(f.owner,f.binding.workspaceId,other,body)]);expect(outcomes.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(outcomes.filter(r=>r.status==='rejected')).toHaveLength(1);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_title_operations WHERE operation_id=$1`,[operationId])).rows[0].n).toBe(1);
  const winner=outcomes[0]!.status==='fulfilled'?f.id:other,loser=winner===other?f.id:other;expect((await f.store.read(f.owner,f.binding.workspaceId,loser,{protocolVersion:1,clientId:f.binding.clientId})).metadata.title).toBe(loser===other?'base':results.find(r=>r.result.status==='applied')!.metadata.title);expect((await f.store.read(f.owner,f.binding.workspaceId,loser,{protocolVersion:1,clientId:f.binding.clientId})).conflicts).toHaveLength(loser===other?0:5);
});});
real('TITLE-CORRUPTION-PG: unknown base is immutable rejection; corrupt state/receipt/lookahead refuse partial success',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),operationId=newId(),rejected=await f.rename('future',99,{operationId});expect(rejected.result).toEqual({status:'rejected',code:'base_unknown'});expect(await f.rename('future',99,{operationId})).toEqual(rejected);await expect(f.rename('x',0,{owner:'spoof'})).rejects.toMatchObject({code:'invalid_request'});
  await pool.query(`UPDATE "${schema}".private_page_title_history SET title='corrupt' WHERE page_id=$1 AND version=0`,[f.id]);await expect(f.read()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await expect(f.rename('x')).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect((await pool.query(`SELECT metadata->>'title' AS title FROM "${schema}".private_page_documents`)).rows[0].title).toBe('base');
  await pool.query(`UPDATE "${schema}".private_page_title_history SET title='base' WHERE page_id=$1`,[f.id]);await pool.query(`UPDATE "${schema}".private_page_title_operations SET result=jsonb_set(result,'{pageId}',to_jsonb($1::text))`,[newId()]);await expect(f.rename('future',99,{operationId})).rejects.toBeInstanceOf(PrivateTransactionUnavailable);
  await f.rename('remote');await f.rename('one');await f.rename('two');const all=await f.read();await pool.query(`UPDATE "${schema}".private_page_title_conflicts SET record=jsonb_set(record,'{id}',to_jsonb($2::text)) WHERE id=$1`,[all.conflicts[1]!.id,newId()]);await expect(f.read({limit:1})).rejects.toBeInstanceOf(PrivateTransactionUnavailable);
});});
real('TITLE-PERMISSIONS-PG: foreign/revoked/deleted resources cannot read or rename',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),other=await f.bootstrap.bootstrap(actor('other'),{clientId:newId()}),body={protocolVersion:1,clientId:other.clientId,operationId:newId(),baseVersion:0,title:'foreign'};await expect(f.store.rename(actor('other'),f.binding.workspaceId,f.id,body)).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.store.rename(actor('other'),other.workspaceId,f.id,body)).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.store.read(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:other.clientId})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);
  await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[f.binding.clientId]);await expect(f.read()).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.rename('x')).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);const peer=await f.bootstrap.bootstrap(f.owner,{clientId:newId()});await pool.query(`UPDATE "${schema}".private_resources SET deleted=true WHERE id=$1`,[f.id]);await expect(f.store.read(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:peer.clientId})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_title_operations`)).rows[0].n).toBe(0);
});});
real('TITLE-EXPIRY-PG: expiry during Page lock wait rolls back every title/operation write',async()=>{await isolated(async(pool,schema)=>{let time=Date.now();const clock=vi.spyOn(Date,'now').mockImplementation(()=>time),f=await fixture(pool,schema),blocker=await pool.connect();let pending:ReturnType<typeof f.rename>|undefined;try{await blocker.query('BEGIN');await blocker.query(`SELECT page_id FROM "${schema}".private_page_documents WHERE page_id=$1 FOR UPDATE`,[f.id]);pending=f.rename('queued');void pending.catch(()=>{});await expect.poll(async()=>(await pool.query("SELECT 1 FROM pg_stat_activity WHERE query LIKE $1 AND wait_event_type='Lock'",[`SELECT metadata%"${schema}".private_page_documents%FOR UPDATE`])).rowCount).toBe(1);time+=301000;await blocker.query('COMMIT');await expect(pending).rejects.toBeInstanceOf(SessionVerificationError);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_title_operations`)).rows[0].n).toBe(0);expect((await pool.query(`SELECT version FROM "${schema}".private_page_title_state`)).rows[0].version).toBe('0');
  }finally{await blocker.query('ROLLBACK');if(pending)await Promise.allSettled([pending]);blocker.release();clock.mockRestore();}});});
real('TITLE-HTTP-PG: protected routes map fixed errors and preserve Page/structured compatibility',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),app=await createPrivateApp({verify:async authorization=>{if(authorization!=='Bearer fixture')throw new SessionVerificationError('invalid_session');return f.owner;}},new PostgresPrivateAccessStore(pool,schema),f.bootstrap,new PostgresPrivateTransactions(pool,schema),new PostgresPrivateStructuredStore(pool,schema),f.pages,f.store);try{const url=`/v1/workspaces/${f.binding.workspaceId}/pages/${f.id}/metadata/rename`,payload={protocolVersion:1,clientId:f.binding.clientId,operationId:newId(),baseVersion:0,title:'HTTP private title'},request=(body:object,authorization='Bearer fixture')=>app.inject({method:'POST',url,headers:{authorization},payload:body});expect((await request(payload,'Bearer invalid')).statusCode).toBe(401);expect((await request({...payload,email:'private@example.invalid'})).statusCode).toBe(400);expect((await request(payload)).statusCode).toBe(200);const reused=await request({...payload,title:'different private title'});expect(reused.statusCode).toBe(409);expect(reused.json()).toEqual({error:'operation_id_reused'});
  expect((await app.inject({method:'POST',url:`/v1/workspaces/${f.binding.workspaceId}/sync/pull`,headers:{authorization:'Bearer fixture'},payload:{protocolVersion:1,workspaceId:f.binding.workspaceId,clientId:f.binding.clientId,cursor:null,limit:100}})).statusCode).toBe(200);const id=newId();await f.pages.bootstrap(f.owner,f.binding.workspaceId,id,f.request);expect((await f.store.read(f.owner,f.binding.workspaceId,id,{protocolVersion:1,clientId:f.binding.clientId})).version).toBe(0);await f.pages.append(f.owner,f.binding.workspaceId,f.id,{protocolVersion:1,clientId:f.binding.clientId,editorSchemaVersion:1,update:Buffer.from([0,0]).toString('base64url')});expect((await f.read()).metadata.title).toBe(payload.title);
  await pool.query(`DROP TABLE "${schema}".private_page_title_history`);const unavailable=await request({...payload,operationId:newId()});expect(unavailable.statusCode).toBe(503);expect(unavailable.json()).toEqual({error:'transaction_unavailable'});
}finally{await app.close();}});});
real('TITLE-RUNTIME-PG: explicit CLI upgrade, signed HTTP owner isolation and missing-table startup refusal',async()=>{await isolated(async(pool,schema)=>{
  const f=await fixture(pool,schema,false),listener=createServer();await new Promise<void>(resolve=>listener.listen(0,'127.0.0.1',resolve));const address=listener.address();if(!address||typeof address==='string')throw new Error('No fixture port');await new Promise<void>((resolve,reject)=>listener.close(error=>error?reject(error):resolve()));
  const config={projectUrl:'https://auth.fixture.invalid',algorithm:'ES256' as const,databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1' as const,port:address.port},path=`/v1/workspaces/${f.binding.workspaceId}/pages/${f.id}/metadata/`,options={method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({protocolVersion:1,clientId:f.binding.clientId})};
  const keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'fixture',alg:'ES256'},ports={fetchJwks:async()=>new Response(JSON.stringify({keys:[jwk]}))},token=async(sub:string)=>new SignJWT({sub,iss:config.projectUrl+'/auth/v1',aud:'authenticated',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(keys.privateKey);
  let runtime=await startPrivateApi(config,ports);try{expect((await fetch(runtime.address+path+'read',options)).status).toBe(404);}finally{await runtime.close();}
  const cli=()=>spawnSync(process.execPath,['apps/api/dist/init-private.js','--page-metadata'],{encoding:'utf8',env:{...process.env,GREIVA_PRIVATE_SCHEMA:schema}});const installed=cli();expect(installed.status).toBe(0);expect(JSON.parse(installed.stdout).event).toBe('page_metadata_schema_installed');expect(cli().status).toBe(1);runtime=await startPrivateApi(config,ports);try{
    expect((await fetch(runtime.address+path+'read',options)).status).toBe(401);const authorization='Bearer '+await token('owner'),post=(kind:string,body:object,auth=authorization)=>fetch(runtime.address+path+kind,{...options,headers:{...options.headers,authorization:auth},body:JSON.stringify(body)}),readBody={protocolVersion:1,clientId:f.binding.clientId};
    expect((await post('read',readBody,'Bearer '+await token('foreign'))).status).toBe(403);expect((await post('read',readBody,'Bearer invalid')).status).toBe(401);const receipt=await post('rename',{...readBody,operationId:newId(),baseVersion:0,title:'signed HTTP title'});expect(receipt.status).toBe(200);expect(await receipt.json()).toMatchObject({version:1,metadata:{title:'signed HTTP title'}});const read=await post('read',readBody);expect(read.status).toBe(200);expect(await read.json()).toMatchObject({version:1,metadata:{title:'signed HTTP title'}});
  }finally{await runtime.close();}await pool.query(`DROP TABLE "${schema}".private_page_title_state`);await expect(startPrivateApi(config,ports)).rejects.toMatchObject({stage:'schema'});expect((await pool.query(`SELECT version FROM "${schema}".private_schema_version`)).rows[0].version).toBe(4);
});});
