import {PrivateDatabaseSourceWriteSession} from '../../apps/client/src/workspace/private-database-source-write-session.js';
import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
real('DB-SOURCE-WRITE-PG: denied device closes generation without losing unsent local Source; renewed bootstrap can reconcile exact pending operation',async()=>{await isolated(async f=>{const runtime=await f.runtime(),intent={operationId:newId(),source:f.source};await runtime.enqueue(intent);await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=true WHERE id=$1`,[f.context.clientId]);await expect(runtime.send()).rejects.toMatchObject({stage:'closed'});expect(runtime.snapshot).toMatchObject({phase:'closed',data:null,retryAck:false});await expect(f.store.databaseSourceQueue()).rejects.toMatchObject({stage:'closed'});expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_sources`)).rows[0].n).toBe('0');await f.pool.query(`UPDATE "${f.schema}".private_devices SET revoked=false WHERE id=$1`,[f.context.clientId]);await f.reconnect();expect((await f.store.databaseSourceQueue()).pending).toBe(1);const recovery=await f.runtime();expect((await recovery.send())?.operationId).toBe(intent.operationId);expect((await f.store.databaseSourceQueue()).pending).toBe(0);await recovery.close();});});
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_swrite_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-source-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'source-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'source-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'source-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit=false,lostHttp=false,failEnqueue=false;const bodies:string[]=[];const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));if(String(input).endsWith('/create'))bodies.push(String(init?.body));const result=await fetch(input,init);if(lostHttp&&String(input).endsWith('/create')){lostHttp=false;throw Error('fixture lost HTTP response');}if(hold&&String(input).endsWith('/create')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_source_ack'){failCommit=false;throw Error('fixture commit result unknown');}if(failEnqueue&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_source_enqueue'){failEnqueue=false;throw Error('fixture lost enqueue response');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema);
 return{pool,schema,source,sources,context,auth,owner,bodies,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:()=>{failCommit=true;},unknownEnqueue:()=>{failEnqueue=true;},lostNextHttp:()=>{lostHttp=true;},runtime:()=>PrivateDatabaseSourceWriteSession.open(connection,store),blockCreate:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
real('DB-SOURCE-WRITE-PG: offline durable enqueue, lost server HTTP and unknown native ACK retry preserve original operation and proof across restart',async()=>{await isolated(async f=>{let runtime=await f.runtime();const calls=f.calls.length,intent={operationId:newId(),source:f.source};f.unknownEnqueue();await expect(runtime.enqueue(intent)).rejects.toMatchObject({stage:'storage'});expect(f.calls).toHaveLength(calls);expect(runtime.snapshot.retryEnqueue).toBe(true);await runtime.reload();expect(runtime.snapshot).toMatchObject({retryEnqueue:true,data:{pending:1}});await runtime.retryEnqueue();expect((await f.store.databaseSourceLoad(f.source.id)).snapshot).toBeNull();await runtime.close();await f.reopen();runtime=await f.runtime();f.lostNextHttp();await expect(runtime.send()).rejects.toMatchObject({stage:'transport'});expect(runtime.snapshot.retryAck).toBe(false);expect((await f.store.databaseSourceQueue()).pending).toBe(1);expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_sources`)).rows[0].n).toBe('1');await runtime.close();await f.reopen();runtime=await f.runtime();f.unknownNextCommit();await expect(runtime.send()).rejects.toMatchObject({stage:'storage'});expect(runtime.snapshot.retryAck).toBe(true);expect(f.bodies).toHaveLength(2);expect(f.bodies[0]).toBe(f.bodies[1]);expect(JSON.parse(f.bodies[0]!).operationId).toBe(intent.operationId);const count=f.calls.length;await runtime.reload();expect(runtime.snapshot).toMatchObject({retryAck:true,data:{pending:0}});await runtime.retryAck();expect(f.calls).toHaveLength(count);expect(runtime.snapshot).toMatchObject({retryAck:false,catalogFresh:true,data:{pending:0}});const original=(await f.store.databaseSourceQueue()).operations[0]!.response;expect(original).toMatchObject({operationId:intent.operationId,snapshot:{source:f.source,version:1},result:{status:'created'}});await runtime.close();await f.reopen();expect((await f.store.databaseSourceLoad(f.source.id)).snapshot).toEqual(original!.snapshot);expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_source_operations`)).rows[0].n).toBe('1');const saved=JSON.stringify((await f.pool.query(`SELECT request,result FROM "${f.schema}".private_database_source_operations`)).rows);expect(saved).not.toContain('auth-only@example.invalid');expect(saved).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);});});
real('DB-SOURCE-WRITE-PG: replacement, Auth refresh and native close discard late committed HTTP; original saved bytes reconcile through a new session',async()=>{await isolated(async f=>{for(const boundary of ['replacement','refresh','native-close'] as const){const runtime=await f.runtime(),source={...f.source,id:newId()},intent={operationId:newId(),source};await runtime.enqueue(intent);const block=f.blockCreate(),work=runtime.send();await block.entered;if(boundary==='replacement')f.store.databaseSourceWrites();if(boundary==='refresh'){await f.auth.refresh();await f.connection.bootstrap();}if(boundary==='native-close')await f.store.close();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(runtime.snapshot).toMatchObject({phase:'closed',data:null});await f.reopen();expect((await f.store.databaseSourceLoad(source.id)).snapshot).toBeNull();expect((await f.store.databaseSourceQueue()).pending).toBe(1);const recovery=await f.runtime();expect((await recovery.send())?.snapshot.source).toEqual(source);expect(f.bodies.at(-1)).toBe(f.bodies.at(-2));expect((await f.store.databaseSourceQueue()).pending).toBe(0);await recovery.close();}expect((await f.pool.query(`SELECT count(*) AS n FROM "${f.schema}".private_database_sources`)).rows[0].n).toBe('3');});});
