import {it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import pg from 'pg';import * as Y from 'yjs';import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {emptyPageUpdate,supabaseAuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {createSupabasePrivateApp} from '../../apps/api/src/supabase-private-app.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';import {PostgresPrivateAccessStore} from '../../apps/api/src/private-access-store.js';import {PostgresPrivateTransactions} from '../../apps/api/src/private-transactions.js';import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {WorkspaceDevice,workspacePagePort} from '../support/workspace-device.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {NativeWorkspaceStore} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivatePageEditorSession} from '../../apps/client/src/editor/private-page-session.js';
import {nativeWorkspaceDevice} from '../../apps/client/src/workspace/native-workspace-device.js';
it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1')('PRIVATE-PAGE-CLIENT-PG: signed fixture HTTP and two actual SQLite stores recover lost ACKs, offline restart, concurrent edits and revoked pending without duplicate binary',async()=>{
  const directory=mkdtempSync(join(tmpdir(),'greiva-private-page-client-')),schema='greiva_private_'+newId().replaceAll('-',''),pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),projectUrl='https://project.fixture.invalid',keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'fixture',alg:'ES256'};
  const registries:WorkspaceRegistryDevice[]=[],devices:WorkspaceDevice[]=[],auths:ReturnType<typeof supabaseAuthSession>[]=[],docs:Y.Doc[]=[];let app:Awaited<ReturnType<typeof createSupabasePrivateApp>>|undefined;
  try{
    await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);app=await createSupabasePrivateApp({projectUrl,algorithm:'ES256'},new PostgresPrivateAccessStore(pool,schema),new PostgresPrivateBootstrapStore(pool,schema),async()=>new Response(JSON.stringify({keys:[jwk]})),new PostgresPrivateTransactions(pool,schema),new PostgresPrivateStructuredStore(pool,schema),new PostgresPrivatePageStore(pool,schema));await app.listen(0,'127.0.0.1');const apiUrl=await app.getUrl();
    const auth=async()=>{const session=supabaseAuthSession({projectUrl,algorithm:'ES256',publishableKey:'sb_publishable_fixture',apiUrl},async(input,init)=>{if(new URL(String(input)).origin!==projectUrl)return fetch(input,init);const token=await new SignJWT({sub:'owner',iss:projectUrl+'/auth/v1',aud:'authenticated',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(keys.privateKey);return new Response(JSON.stringify({access_token:token,refresh_token:'fixture-refresh',token_type:'bearer',user:{id:'owner'}}));});auths.push(session);await session.login('fixture@example.invalid','fixture-password');return session;};
    const registry=new WorkspaceRegistryDevice(join(directory,'native-registry'));registries.push(registry);
    const oneAuth=await auth(),twoAuth=await auth(),clientId=await twoAuth.authorized((_authorization,signal,identity)=>nativeWorkspaceDevice(identity,signal,registry.invoke)),oneConnection=new PrivateWorkspaceConnection(oneAuth,{apiUrl,clientId:newId()}),twoConnection=new PrivateWorkspaceConnection(twoAuth,{apiUrl,clientId}),one=await oneConnection.bootstrap(),two=await twoConnection.bootstrap(),device=new WorkspaceDevice(join(directory,'one.sqlite'),one),peer=new WorkspaceDevice(join(directory,'two.sqlite'),two);devices.push(device,peer);const id=newId(),path=`/v1/workspaces/${one.workspaceId}/pages/${id}/document/`;
    const post=(session:typeof oneAuth,kind:string,body:unknown)=>session.authorized((authorization,signal)=>fetch(apiUrl+path+kind,{method:'POST',headers:{authorization,'content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body),signal}));
    async function send(target:WorkspaceDevice,session:typeof oneAuth,lose=false){const prepared=await target.request('page_prepare',{pageId:id});expect(prepared).not.toBeNull();const response=await post(session,prepared.kind,prepared.wire);expect(response.status).toBe(200);const value=await response.json();if(lose)return prepared;await target.request('page_ack',{...prepared,response:value});return prepared;}
    async function restore(target:WorkspaceDevice){const doc=new Y.Doc({gc:false});docs.push(doc);for(const bytes of (await target.request('page_load',{pageId:id})).page.updates)Y.applyUpdate(doc,Uint8Array.from(bytes));return doc;}
    async function pull(target:WorkspaceDevice,session:typeof oneAuth,context:typeof one,vector='AA'){const response=await post(session,'read',{protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,stateVector:vector});expect(response.status).toBe(200);await target.request('page_receive',{pageId:id,response:await response.json()});}
    const original=new Y.Doc({gc:false});docs.push(original);Y.applyUpdate(original,emptyPageUpdate());(original.getXmlFragment('body').get(0) as Y.XmlElement).insert(0,[new Y.XmlText('日本語')]);await device.request('page_create',{pageId:id,title:'private binary',update:Array.from(Y.encodeStateAsUpdate(original))});const first=await send(device,oneAuth,true);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(first);await send(device,oneAuth);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(1);await pull(peer,twoAuth,two);
    const local=await restore(device),remote=await restore(peer);const edit=(doc:Y.Doc,text:string)=>{let update:Uint8Array|undefined;const capture=(value:Uint8Array)=>{update=value;};doc.on('update',capture);((doc.getXmlFragment('body').get(0) as Y.XmlElement).get(0) as Y.XmlText).insert(0,text);doc.off('update',capture);return update!;};
    await device.request('page_append',{pageId:id,update:Array.from(edit(local,'one '))});await peer.request('page_append',{pageId:id,update:Array.from(edit(remote,'two '))});await device.close('SIGKILL');const durable=await device.request('page_prepare',{pageId:id});const [lost]=await Promise.all([send(device,oneAuth,true),send(peer,twoAuth)]);expect(lost).toEqual(durable);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(durable);await send(device,oneAuth);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(3);
    await Promise.all([pull(device,oneAuth,one,Buffer.from(Y.encodeStateVector(local)).toString('base64url')),pull(peer,twoAuth,two,Buffer.from(Y.encodeStateVector(remote)).toString('base64url'))]);const a=await restore(device),b=await restore(peer);expect(a.getXmlFragment('body').toString()).toBe(b.getXmlFragment('body').toString());expect(a.getXmlFragment('body').toString()).toContain('one ');expect(a.getXmlFragment('body').toString()).toContain('two ');expect(Buffer.from(Y.encodeStateVector(a))).toEqual(Buffer.from(Y.encodeStateVector(b)));expect(await device.request('page_prepare',{pageId:id})).toBeNull();expect(await peer.request('page_prepare',{pageId:id})).toBeNull();

    const oneSession=oneConnection.openPage(id,workspacePagePort(device,id)),twoSession=twoConnection.openPage(id,workspacePagePort(peer,id));
    const catalog=await twoConnection.queryPages({protocolVersion:1,clientId:two.clientId,limit:1});expect(catalog.pages).toHaveLength(1);expect(catalog.pages[0]).toMatchObject({id,title:'private binary',yDocId:'page:'+id});expect(catalog.hasMore).toBe(false);
    const catalogUrl=apiUrl+'/v1/workspaces/'+one.workspaceId+'/pages/query';expect((await fetch(catalogUrl,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).status).toBe(401);
    const invalidCursor=await twoAuth.authorized((authorization,signal)=>fetch(catalogUrl,{method:'POST',headers:{authorization,'content-type':'application/json'},body:JSON.stringify({protocolVersion:1,clientId:two.clientId,cursor:'invalid'}),signal}));expect(invalidCursor.status).toBe(400);expect(await invalidCursor.json()).toEqual({error:'invalid_cursor'});
    await device.request('page_append',{pageId:id,update:Array.from(edit(a,'session '))});await oneSession.push(await device.request('page_prepare',{pageId:id}));
    await twoSession.pull({protocolVersion:1,clientId:two.clientId,editorSchemaVersion:1,stateVector:Buffer.from(Y.encodeStateVector(b)).toString('base64url')});expect((await restore(peer)).getXmlFragment('body').toString()).toContain('session ');
    await oneAuth.refresh();await expect(oneSession.pull({protocolVersion:1,clientId:one.clientId,editorSchemaVersion:1,stateVector:'AA'})).rejects.toMatchObject({stage:'closed'});expect(await oneConnection.bootstrap()).toEqual(one);const refreshed=oneConnection.openPage(id,workspacePagePort(device,id));

    const native=await NativeWorkspaceStore.open(twoConnection,registry.invoke),nativePage=native.page(id),nativeSession=twoConnection.openPage(id,nativePage);
    await nativeSession.pull({protocolVersion:1,clientId:two.clientId,editorSchemaVersion:1,stateVector:'AA'});const nativeDoc=new Y.Doc({gc:false});docs.push(nativeDoc);for(const update of (await nativePage.load()).page.updates)Y.applyUpdate(nativeDoc,Uint8Array.from(update));expect(nativeDoc.getXmlFragment('body').toString()).toContain('session ');
    await nativePage.append(edit(nativeDoc,'registry '));await nativeSession.push(await nativePage.prepare());expect(await nativePage.prepare()).toBeNull();
    await twoAuth.refresh();await native.close();await expect(nativePage.load()).rejects.toMatchObject({stage:'closed'});await twoConnection.bootstrap();const nativeFresh=await NativeWorkspaceStore.open(twoConnection,registry.invoke);expect((await nativeFresh.page(id).load()).pending).toBe(0);await nativeFresh.close();
    await device.request('page_append',{pageId:id,update:Array.from(edit(a,'retained '))});const pending=await device.request('page_prepare',{pageId:id});await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[one.clientId]);await expect(refreshed.push(pending)).rejects.toMatchObject({stage:'closed'});expect(oneConnection.context).toBeNull();expect((await post(oneAuth,'append',pending.wire)).status).toBe(403);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(pending);expect((await restore(device)).getXmlFragment('body').toString()).toContain('retained ');expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(5);
    const editorStore=await NativeWorkspaceStore.open(twoConnection,registry.invoke);
    const editor=await PrivatePageEditorSession.open(twoConnection,editorStore,id,{kind:'local'});
    expect(editor.snapshot).toMatchObject({pending:0,synced:false});edit(editor.document,'editor ');
    await editor.durable();expect((await editorStore.page(id).load()).pending).toBe(1);
    await editor.sync();expect(editor.snapshot).toMatchObject({pending:0,synced:true});
    expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(6);
    await twoAuth.refresh();expect(editor.snapshot.phase).toBe('closed');await editor.close();await editorStore.close();
    await registry.close();await twoConnection.bootstrap();
    const reopenedStore=await NativeWorkspaceStore.open(twoConnection,registry.invoke);
    const reopened=await PrivatePageEditorSession.open(twoConnection,reopenedStore,id,{kind:'local'});
    expect(reopened.document.getXmlFragment('body').toString()).toContain('editor ');
    expect(reopened.snapshot).toMatchObject({pending:0,synced:false});
    await reopened.sync();expect(reopened.snapshot.synced).toBe(true);
    edit(reopened.document,'relogin ');await reopened.durable();const retained=await reopenedStore.page(id).prepare();expect(retained?.kind).toBe('append');
    await reopened.close();await twoAuth.logout();await reopenedStore.close();await registry.close('SIGKILL');
    const nextAuth=await auth(),nextId=await nextAuth.authorized((_authorization,signal,identity)=>nativeWorkspaceDevice(identity,signal,registry.invoke));expect(nextId).toBe(clientId);
    const nextConnection=new PrivateWorkspaceConnection(nextAuth,{apiUrl,clientId:nextId});expect(await nextConnection.bootstrap()).toEqual(two);
    const nextStore=await NativeWorkspaceStore.open(nextConnection,registry.invoke),nextEditor=await PrivatePageEditorSession.open(nextConnection,nextStore,id,{kind:'local'});
    expect(nextEditor.snapshot).toMatchObject({pending:1,synced:false});expect(await nextStore.page(id).prepare()).toEqual(retained);expect(nextEditor.document.getXmlFragment('body').toString()).toContain('relogin ');
    await nextEditor.sync();expect(nextEditor.snapshot).toMatchObject({pending:0,synced:true});expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_devices`)).rows[0].n).toBe(2);
    await nextEditor.close();await nextStore.close();nextConnection.close();
  }finally{for(const auth of auths)auth.close();for(const doc of docs)doc.destroy();for(const device of devices)await device.close();for(const registry of registries)await registry.close();await app?.close();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();rmSync(directory,{recursive:true,force:true});}}
});
