import {it,expect,vi} from 'vitest';
import pg from 'pg';
import {createServer} from 'node:net';
import {spawn} from 'node:child_process';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';
import {databaseSourceSchema} from '@greiva/domain';
import {PrivateWorkspaceAccessDenied} from '@greiva/application';
import {emptyPageUpdate} from '@greiva/sync';
import {privateDatabaseRecordCatalogResponseSchema} from '@greiva/protocol/private-database-record-catalog';
import {privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {installPrivateWorkspaceSchema,verifyPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';
import {PostgresPrivateDatabaseRecordStore} from '../../apps/api/src/private-database-record-store.js';
import {PostgresPrivateDatabaseRecordCatalogStore} from '../../apps/api/src/private-database-record-catalog-store.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {PrivateTransactionUnavailable,PrivateTransactionInvalidRequest} from '../../apps/api/src/private-transactions.js';
import {SessionVerificationError} from '../../apps/api/src/session-verifier.js';
import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
const owner=()=>({subjectId:'catalog-owner',issuer:'https://project.fixture.invalid/auth/v1',expiresAt:Math.floor(Date.now()/1000)+300});
async function isolated(run:(pool:pg.Pool,schema:string)=>Promise<void>,upgrade=true){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_catalog_'+newId().replaceAll('-','');try{await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await installPrivatePageMetadataSchema(pool,schema);await installPrivatePageChangesSchema(pool,schema);await installPrivateDatabaseSourceSchema(pool,schema);await installPrivateDatabaseRecordSchema(pool,schema);if(upgrade)await installPrivateDatabaseRecordCatalogSchema(pool,schema);await run(pool,schema);}finally{try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function fixture(pool:pg.Pool,schema:string){const actor=owner(),bootstrap=new PostgresPrivateBootstrapStore(pool,schema),binding=await bootstrap.bootstrap(actor,{clientId:newId()}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),records=new PostgresPrivateDatabaseRecordStore(pool,schema),pages=new PostgresPrivatePageStore(pool,schema),catalogs=new PostgresPrivateDatabaseRecordCatalogStore(pool,schema),textId=newId(),source=databaseSourceSchema.parse({id:newId(),workspaceId:binding.workspaceId,name:'DB',schemaVersion:1,properties:[{id:newId(),type:'name',name:'Name'},{id:textId,type:'text',name:'Text'}]});await sources.create(actor,binding.workspaceId,{protocolVersion:1,clientId:binding.clientId,operationId:newId(),source});const prepare=async(recordId=newId())=>{const pageId=newId();await pages.bootstrap(actor,binding.workspaceId,pageId,{protocolVersion:1,clientId:binding.clientId,editorSchemaVersion:1,title:'not in record headers',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')});return{protocolVersion:1 as const,clientId:binding.clientId,operationId:newId(),intent:{kind:'create' as const,sourceId:source.id,schemaVersion:1,recordId,pageId,baseVersion:null,values:{[textId]:'private fixture text'}}};};const write=async(request:Awaited<ReturnType<typeof prepare>>)=>privateDatabaseRecordWriteResponseSchema.parse(await records.write(actor,binding.workspaceId,source.id,request)),create=async()=>{const request=await prepare();return{request,receipt:await write(request)};},catalog=async(cursor:string|null=null,limit=100)=>privateDatabaseRecordCatalogResponseSchema.parse(await catalogs.catalog(actor,binding.workspaceId,source.id,{protocolVersion:1,clientId:binding.clientId,cursor,limit}));return{actor,bootstrap,binding,sources,records,pages,catalogs,textId,source,prepare,write,create,catalog};}
async function head(pool:pg.Pool,schema:string,sourceId:string){return(await pool.query(`SELECT head_order::text FROM "${schema}".private_database_record_heads WHERE source_id=$1`,[sourceId])).rows[0]?.head_order??'0';}
real('DB-RECORD-CATALOG-PG: explicit seven to eight seeds ID order and preserves original records/history/receipts/key',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=await f.prepare(),b=await f.prepare(),second=await f.write(b),first=await f.write(a),saved=(await pool.query(`SELECT request,result FROM "${schema}".private_database_record_operations ORDER BY operation_id`)).rows,key=(await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0]!.secret;await installPrivateDatabaseRecordCatalogSchema(pool,schema);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(8);const rows=(await f.catalog()).records;expect(rows.map(row=>row.id)).toEqual([a.intent.recordId,b.intent.recordId].sort());expect(rows.map(row=>row.creationOrder)).toEqual(['1','2']);expect(await f.write(a)).toEqual(first);expect(await f.write(b)).toEqual(second);expect((await pool.query(`SELECT request,result FROM "${schema}".private_database_record_operations ORDER BY operation_id`)).rows).toEqual(saved);expect((await pool.query(`SELECT secret FROM "${schema}".private_structured_config`)).rows[0]!.secret).toEqual(key);await expect(installPrivateDatabaseRecordCatalogSchema(pool,schema)).rejects.toThrow();await pool.query(`ALTER TABLE "${schema}".private_database_record_heads RENAME COLUMN head_order TO broken`);await expect(verifyPrivateWorkspaceSchema(pool,schema)).rejects.toThrow();},false);});
real('DB-RECORD-CATALOG-PG: invalid seed or DDL conflict rolls back every schema change without repair',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),created=await f.create();await pool.query(`UPDATE "${schema}".private_database_record_history SET snapshot=jsonb_set(snapshot,'{pageId}',$1::jsonb)`,[JSON.stringify(newId())]);await expect(installPrivateDatabaseRecordCatalogSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(7);await pool.query(`UPDATE "${schema}".private_database_record_history SET snapshot=$1`,[JSON.stringify(created.receipt.record)]);await pool.query(`CREATE TABLE "${schema}".private_database_record_heads(fixture integer)`);await expect(installPrivateDatabaseRecordCatalogSchema(pool,schema)).rejects.toThrow();expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(7);expect((await pool.query(`SELECT count(*)::int AS n FROM information_schema.columns WHERE table_schema=$1 AND table_name='private_database_records' AND column_name='creation_order'`,[schema])).rows[0]!.n).toBe(0);},false);});
real('DB-RECORD-CATALOG-PG: 101 headers use numeric order/fixed head and omit values/title/body; updates are fresh observations',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),created=[];for(let i=0;i<101;i++)created.push(await f.create());const first=await f.catalog();expect(first.records).toHaveLength(100);expect(first).toMatchObject({afterOrder:'0',throughOrder:'100',headOrder:'101',hasMore:true});expect(first.records.map(row=>row.creationOrder)).toEqual(Array.from({length:100},(_,i)=>String(i+1)));expect(JSON.stringify(first)).not.toContain('private fixture text');expect(JSON.stringify(first)).not.toContain('not in record headers');await f.create();const last=await f.catalog(first.cursor);expect(last.records.map(row=>row.creationOrder)).toEqual(['101']);expect(last).toMatchObject({headOrder:'101',hasMore:false,cursor:null});expect((await f.catalog()).headOrder).toBe('102');const old=created[0]!,updated=privateDatabaseRecordWriteResponseSchema.parse(await f.records.write(f.actor,f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:f.binding.clientId,operationId:newId(),intent:{...old.request.intent,kind:'update',baseVersion:1,values:{[f.textId]:'new observed value'}}}));expect(updated.record.version).toBe(2);expect((await f.catalog()).records[0]!.version).toBe(2);expect(first.records[0]!.version).toBe(1);const peer=await f.bootstrap.bootstrap(f.actor,{clientId:newId()});await expect(f.catalogs.catalog(f.actor,f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:peer.clientId,cursor:first.cursor})).rejects.toBeInstanceOf(PrivateTransactionInvalidRequest);await expect(f.catalog(first.cursor+'x')).rejects.toBeInstanceOf(PrivateTransactionInvalidRequest);});});
real('DB-RECORD-CATALOG-PG: filtered Page/deleted records advance raw windows without deletion ACK or resurrection',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=await f.create(),b=await f.create(),c=await f.create();await pool.query(`UPDATE "${schema}".private_resources SET deleted=true WHERE id=$1`,[a.request.intent.pageId]);await pool.query(`UPDATE "${schema}".private_database_records SET deleted=true WHERE id=$1`,[b.request.intent.recordId]);const first=await f.catalog(null,2);expect(first).toMatchObject({records:[],throughOrder:'2',headOrder:'3',hasMore:true});const last=await f.catalog(first.cursor,2);expect(last.records.map(row=>row.id)).toEqual([c.request.intent.recordId]);expect(last.hasMore).toBe(false);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_record_operations`)).rows[0]!.n).toBe(3);});});
real('DB-RECORD-CATALOG-PG: head/header/lookahead corruption fails closed and catalog never repairs missing state',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=await f.create(),b=await f.create();await pool.query(`UPDATE "${schema}".private_database_record_heads SET head_order=3`);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await pool.query(`UPDATE "${schema}".private_database_record_heads SET head_order=2`);await pool.query(`UPDATE "${schema}".private_database_records SET snapshot=jsonb_set(snapshot,'{version}','"1"'::jsonb) WHERE id=$1`,[b.request.intent.recordId]);await expect(f.catalog(null,1)).rejects.toBeInstanceOf(PrivateTransactionUnavailable);await pool.query(`UPDATE "${schema}".private_database_records SET snapshot=$2 WHERE id=$1`,[b.request.intent.recordId,JSON.stringify(b.receipt.record)]);await pool.query(`DELETE FROM "${schema}".private_database_record_heads`);await expect(f.catalog()).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_record_heads`)).rows[0]!.n).toBe(0);expect(a.receipt.record.version).toBe(1);});});
real('DB-RECORD-CATALOG-PG: Source/owner/device/cursor boundaries and lock-wait expiry deny without writes',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema);await f.create();await expect(f.catalogs.catalog({...f.actor,subjectId:'other'},f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:f.binding.clientId})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.catalogs.catalog(f.actor,f.binding.workspaceId,newId(),{protocolVersion:1,clientId:f.binding.clientId})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);await expect(f.catalogs.catalog(f.actor,f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:newId()})).rejects.toBeInstanceOf(PrivateWorkspaceAccessDenied);let clock=Date.now();const expired=new PostgresPrivateDatabaseRecordCatalogStore(pool,schema,()=>clock),blocker=await pool.connect();try{await blocker.query('BEGIN');await blocker.query(`SELECT id FROM "${schema}".private_database_sources WHERE id=$1 FOR UPDATE`,[f.source.id]);const work=expired.catalog(f.actor,f.binding.workspaceId,f.source.id,{protocolVersion:1,clientId:f.binding.clientId}).catch(error=>error);await vi.waitFor(async()=>expect((await pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND position($1 in query)>0 AND query LIKE '%private_database_sources%'`,[schema])).rows[0]!.n).toBeGreaterThan(0));clock=(f.actor.expiresAt+1)*1000;await blocker.query('COMMIT');expect(await work).toBeInstanceOf(SessionVerificationError);expect(await head(pool,schema,f.source.id)).toBe('1');}finally{try{await blocker.query('ROLLBACK');}finally{blocker.release();}}});});
real('DB-RECORD-CATALOG-PG: create head is atomic with ledger, exact retry never consumes a second position',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),request=await f.prepare(),connect=pool.connect.bind(pool);let fail=true;const faulty={connect:async()=>{const client=await connect(),query=client.query.bind(client),release=client.release.bind(client);client.query=(async(...args:unknown[])=>{if(fail&&String(args[0]).includes('private_database_record_operations VALUES'))throw Error('fixture ledger fault');return(query as (...args:unknown[])=>unknown)(...args);}) as typeof client.query;client.release=(...args:Parameters<typeof release>)=>{client.query=query;client.release=release;release(...args);};return client;}} as unknown as pg.Pool,store=new PostgresPrivateDatabaseRecordStore(faulty,schema);await expect(store.write(f.actor,f.binding.workspaceId,f.source.id,request)).rejects.toBeInstanceOf(PrivateTransactionUnavailable);expect(await head(pool,schema,f.source.id)).toBe('0');expect((await f.catalog()).records).toEqual([]);fail=false;const first=await store.write(f.actor,f.binding.workspaceId,f.source.id,request);expect(await store.write(f.actor,f.binding.workspaceId,f.source.id,request)).toEqual(first);expect((await f.catalog()).records[0]!.creationOrder).toBe('1');});});
real('DB-RECORD-CATALOG-PG: concurrent creates/replay commit positions under Source lock, independent of client ID time',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),a=await f.prepare(),b=await f.prepare(),blocker=await pool.connect();try{await blocker.query('BEGIN');await blocker.query(`SELECT id FROM "${schema}".private_database_sources WHERE id=$1 FOR UPDATE`,[f.source.id]);const work=Promise.all([f.write(b),f.write(a),f.write(structuredClone(b))]);await vi.waitFor(async()=>expect((await pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND position($1 in query)>0 AND query LIKE '%private_database_sources%'`,[schema])).rows[0]!.n).toBeGreaterThan(0));await blocker.query('COMMIT');const replies=await work;expect(replies[2]).toEqual(replies[0]);expect((await f.catalog()).records.map(row=>row.creationOrder)).toEqual(['1','2']);expect(await head(pool,schema,f.source.id)).toBe('2');}finally{try{await blocker.query('ROLLBACK');}finally{blocker.release();}}});});
real('DB-RECORD-CATALOG-PG: signed protected runtime mounts schema-eight catalog and retains create/read routes',async()=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'catalog-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:async()=>new Response(JSON.stringify({keys:[jwk]}))});try{const token=await new SignJWT({sub:f.actor.subjectId,iss:f.actor.issuer,aud:'authenticated',exp:f.actor.expiresAt}).setProtectedHeader({alg:'ES256',kid:'catalog-fixture'}).sign(keys.privateKey),post=(path:string,body:unknown,authorized=true)=>fetch(runtime.address+path,{method:'POST',headers:{'content-type':'application/json',...(authorized?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}),path='/v1/workspaces/'+f.binding.workspaceId+'/databases/'+f.source.id+'/records',request=await f.prepare();expect((await post(path+'/catalog',{protocolVersion:1,clientId:f.binding.clientId},false)).status).toBe(401);expect((await post(path+'/write',request)).status).toBe(200);const response=await post(path+'/catalog',{protocolVersion:1,clientId:f.binding.clientId});expect(response.status).toBe(200);expect(privateDatabaseRecordCatalogResponseSchema.parse(await response.json())).toMatchObject({headOrder:'1',records:[{id:request.intent.recordId}]});expect((await post(path+'/'+request.intent.recordId+'/read',{protocolVersion:1,clientId:f.binding.clientId,pageId:request.intent.pageId})).status).toBe(200);expect((await post(path+'/catalog',{protocolVersion:1,clientId:newId()})).status).toBe(403);expect((await post(path+'/catalog',{protocolVersion:1,clientId:f.binding.clientId,cursor:'invalid'})).status).toBe(400);expect(await verifyPrivateWorkspaceSchema(pool,schema)).toBe(8);}finally{await runtime.close();}});});

real.each(['before-commit','after-commit'] as const)('DB-RECORD-CATALOG-SIGKILL-%s: record and creation head recover together after real worker death',async boundary=>{await isolated(async(pool,schema)=>{const f=await fixture(pool,schema),request=await f.prepare(),wire=JSON.stringify({owner:f.actor,workspaceId:f.binding.workspaceId,sourceId:f.source.id,request}),child=spawn(process.execPath,['tests/fixtures/private-database-record-crash.mjs',schema,boundary,wire],{env:process.env,stdio:['ignore','ignore','pipe','ipc']});child.stderr!.on('data',()=>{/* no private cause output */});const exited=new Promise<NodeJS.Signals|null>((resolve,reject)=>{child.once('exit',(_code,signal)=>resolve(signal));child.once('error',reject);});try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Catalog crash boundary timeout')),7000);child.once('message',message=>{clearTimeout(timer);if((message as {event?:string;boundary?:string}).event==='boundary'&&(message as {boundary?:string}).boundary===boundary)resolve();else reject(Error('Catalog worker failed'));});void exited.then(()=>{clearTimeout(timer);reject(Error('Catalog worker exited before boundary'));});});child.kill('SIGKILL');expect(await exited).toBe('SIGKILL');await expect.poll(async()=>await head(pool,schema,f.source.id)).toBe(boundary==='before-commit'?'0':'1');const first=await f.write(request);expect(await f.write(request)).toEqual(first);expect(await head(pool,schema,f.source.id)).toBe('1');expect((await f.catalog()).records.map(row=>row.creationOrder)).toEqual(['1']);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_database_record_operations`)).rows[0]!.n).toBe(1);}finally{if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await exited;}}});});
