import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_sclient_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-source-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'source-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'source-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'source-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit=false;const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));const result=await fetch(input,init);if(hold&&String(input).endsWith('/read')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_source_receive'){failCommit=false;throw Error('fixture commit result unknown');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),created=await sources.create(owner,context.workspaceId,{protocolVersion:1,clientId:context.clientId,operationId:newId(),source});
 return{pool,schema,source,created,context,auth,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:()=>{failCommit=true;},blockRead:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
real('DB-SOURCE-CLIENT-PG: signed actual HTTP catalog/read commits six-type native cache, unknown result retries same response without network and server denies retain local data',async()=>{await isolated(async f=>{const before=f.calls.length,session=f.store.databaseSources();expect(f.calls).toHaveLength(before);expect((await f.store.databaseSourceList()).sources).toEqual([]);const catalog=await session.catalog();expect(catalog.sources.map(item=>item.id)).toEqual([f.source.id]);expect((await f.store.databaseSourceList()).sources).toEqual([]);f.unknownNextCommit();await expect(session.read(f.source.id)).rejects.toMatchObject({stage:'storage'});expect(session.retryReceive).toBe(true);const reads=f.calls.filter(url=>url.endsWith('/read')).length;await expect(session.catalog()).rejects.toMatchObject({stage:'busy'});expect((await session.retry()).snapshot.source).toEqual(f.source);expect(f.calls.filter(url=>url.endsWith('/read'))).toHaveLength(reads);await f.reopen();expect((await f.store.databaseSourceLoad(f.source.id)).snapshot?.source).toEqual(f.source);const fresh=f.store.databaseSources();await fresh.read(f.source.id);await f.pool.query(`UPDATE "${f.schema}".private_database_sources SET deleted=true WHERE id=$1`,[f.source.id]);await expect(fresh.read(f.source.id)).rejects.toMatchObject({stage:'closed'});expect(fresh.retryReceive).toBe(false);await expect(f.store.databaseSourceLoad(f.source.id)).rejects.toMatchObject({stage:'closed'});await f.reconnect();expect((await f.store.databaseSourceLoad(f.source.id)).snapshot?.source).toEqual(f.source);const saved=JSON.stringify((await f.pool.query(`SELECT request,result FROM "${f.schema}".private_database_source_operations`)).rows);expect(saved).not.toContain('auth-only@example.invalid');expect(saved).not.toMatch(/Bearer |eyJ[A-Za-z0-9_-]+\./);});});
real('DB-SOURCE-CLIENT-PG: replacement and Auth refresh discard late signed HTTP before native cache, close blocks new calls',async()=>{await isolated(async f=>{let session=f.store.databaseSources(),block=f.blockRead(),work=session.read(f.source.id);await block.entered;const replacement=f.store.databaseSources();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect((await f.store.databaseSourceLoad(f.source.id)).snapshot).toBeNull();session=replacement;block=f.blockRead();work=session.read(f.source.id);await block.entered;await f.auth.refresh();await f.connection.bootstrap();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});await expect(f.store.databaseSourceLoad(f.source.id)).rejects.toMatchObject({stage:'closed'});await f.reopen();expect((await f.store.databaseSourceLoad(f.source.id)).snapshot).toBeNull();const final=f.store.databaseSources();await final.read(f.source.id);f.connection.close();const count=f.calls.length;await expect(final.read(f.source.id)).rejects.toMatchObject({stage:'closed'});expect(f.calls).toHaveLength(count);});});
