import {it,expect} from 'vitest';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {newId} from '@greiva/shared';import {AuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivateChangesSession} from '../../apps/client/src/workspace/private-changes-session.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';import {pageChangesCursor} from '../../apps/api/src/private-page-changes-cursor.js';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
async function fixture(){const directory=mkdtempSync(join(tmpdir(),'greiva-changes-runtime-')),device=new WorkspaceRegistryDevice(directory),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},token={access_token:'fixture.access.signature',refresh_token:'fixture-refresh',token_type:'bearer',user:{id:context.subjectId}},auth=new AuthSession(context.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>({issuer:context.issuer,subjectId:context.subjectId,expiresAt:200}),revoke:async()=>{}},()=>100),sign=pageChangesCursor(context.workspaceId,context.streamEpoch,Buffer.alloc(32,7)),requests:any[]=[],faults={receiveThrow:false,loadThrowAfterCommit:false,receiveWait:null as ReturnType<typeof deferred<void>>|null,networkWait:null as ReturnType<typeof deferred<void>>|null},events:any[]=[],scope={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch};
 const event=(order:string,pageId=newId(),title='remote',version=0)=>({order,pageId,metadata:{id:pageId,title,yDocId:'page:'+pageId,createdAt:'2026-10-08T00:00:00.000Z',updatedAt:'2026-10-08T00:00:00.000Z'},version,conflict:null});
 const connection=new PrivateWorkspaceConnection(auth,{apiUrl:'http://127.0.0.1:3001',clientId:context.clientId},async(input,init)=>{if(String(input).endsWith('/bootstrap'))return Response.json({protocolVersion:1,workspaceId:context.workspaceId,clientId:context.clientId,epoch:context.streamEpoch});const request=JSON.parse(String(init?.body));requests.push({request,url:String(input),init});const after=sign.decode(request.cursor,String(events.length)),read=BigInt(events.length)>after+BigInt(request.limit)?after+BigInt(request.limit):BigInt(events.length),response={...scope,afterOrder:String(after),readOrder:String(read),headOrder:String(events.length),events:events.slice(Number(after),Number(read)),hasMore:read<BigInt(events.length),cursor:sign.encode(String(read))};if(faults.networkWait)await faults.networkWait.promise;return Response.json(response);});
 let failLoad=false;const invoke:NativeWorkspaceInvoke=async(command,args)=>{const kind=(args?.request as {command?:string}|undefined)?.command;if(kind==='changes_load'&&failLoad){failLoad=false;throw Error('fixture lost local read');}const value=await device.invoke(command,args);if(kind==='changes_receive'){if(faults.loadThrowAfterCommit){faults.loadThrowAfterCommit=false;failLoad=true;}if(faults.receiveWait)await faults.receiveWait.promise;if(faults.receiveThrow){faults.receiveThrow=false;throw Error('fixture lost native commit response');}}return value;};
 await auth.login('fixture@example.invalid','fixture');await connection.bootstrap();let store=await NativeWorkspaceStore.open(connection,invoke),runtime=await PrivateChangesSession.open(connection,store);const runtimes=[runtime],stores=[store];
 return{auth,connection,context,device,events,event,requests,faults,get store(){return store;},get runtime(){return runtime;},replace:async()=>{runtime=await PrivateChangesSession.open(connection,store);runtimes.push(runtime);return runtime;},refresh:async()=>{await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);stores.push(store);runtime=await PrivateChangesSession.open(connection,store);runtimes.push(runtime);return runtime;},cleanup:async()=>{for(const r of runtimes)await r.close();for(const s of stores)await s.close().catch(()=>{});connection.close();auth.close();await device.close();rmSync(directory,{recursive:true,force:true});}};
}
it('CHANGES-RUNTIME: local open is network-free; bounded cycles preserve durable progress and separate metadata-only Pages',async()=>{const f=await fixture();try{expect(f.requests).toHaveLength(0);expect(f.runtime.snapshot).toMatchObject({phase:'ready',readComplete:false,data:{received:false,pages:[]}});f.events.push(...Array.from({length:101},(_,i)=>f.event(String(i+1))));await f.runtime.sync();expect(f.runtime.snapshot).toMatchObject({readComplete:false,hasMoreRemote:true,data:{order:'100',received:true}});expect(f.requests).toHaveLength(1);expect((await f.store.listPages()).pages).toEqual([]);await f.runtime.sync();expect(f.runtime.snapshot).toMatchObject({readComplete:true,hasMoreRemote:false,hasMoreLocal:true,data:{order:'101'}});await f.runtime.catalog(true);expect(f.runtime.snapshot.data?.pages).toHaveLength(1);expect(f.runtime.snapshot.hasMoreLocal).toBe(false);expect(f.requests).toHaveLength(2);const previous=f.runtime,replaced=await f.replace();expect(previous.snapshot).toMatchObject({phase:'closed',data:null});expect(replaced.snapshot).toMatchObject({readComplete:false,data:{order:'101',received:true}});}finally{await f.cleanup();}});
it('CHANGES-RUNTIME: native COMMIT response loss blocks network and retries exact saved receipt before new changes',async()=>{const f=await fixture();try{const e=f.event('1');f.events.push(e);f.faults.receiveThrow=true;await expect(f.runtime.sync()).rejects.toMatchObject({stage:'storage'});expect(f.runtime.snapshot).toMatchObject({error:'storage',retryReceive:true,readComplete:false,data:{order:'0'}});expect((await f.store.changesLoad()).order).toBe('1');const cursor=(await f.store.changesLoad()).cursor;f.events.push(f.event('2',e.pageId,'newer',1));await expect(f.runtime.sync()).rejects.toMatchObject({stage:'busy'});await f.runtime.retryReceive();expect(f.requests).toHaveLength(1);expect(f.runtime.snapshot).toMatchObject({retryReceive:false,readComplete:true,data:{order:'1',pages:[{metadata:{title:'remote'}}]}});await f.runtime.sync();expect(f.requests.at(-1)?.request.cursor).toBe(cursor);expect(f.runtime.snapshot.data?.pages[0]?.metadata.title).toBe('newer');}finally{await f.cleanup();}});
it('CHANGES-RUNTIME: post-commit read failure resumes from durable cursor instead of applying a newer reply to stale base',async()=>{const f=await fixture();try{const e=f.event('1');f.events.push(e);f.faults.loadThrowAfterCommit=true;await expect(f.runtime.sync()).rejects.toMatchObject({stage:'storage'});expect(f.runtime.snapshot).toMatchObject({error:'storage',retryReceive:false,data:{order:'0'},readComplete:false});const cursor=(await f.store.changesLoad()).cursor;f.events.push(f.event('2',e.pageId,'next',1));await f.runtime.sync();expect(f.requests.at(-1)?.request.cursor).toBe(cursor);expect(f.runtime.snapshot).toMatchObject({error:null,readComplete:true,data:{order:'2'}});}finally{await f.cleanup();}});
it('CHANGES-RUNTIME: refresh cancels late network, clears displayed data and a new generation starts from saved progress',async()=>{const f=await fixture();try{f.events.push(f.event('1'));const wait=deferred<void>();f.faults.networkWait=wait;const old=f.runtime,work=old.sync();await expect.poll(()=>f.requests.length).toBe(1);await f.auth.refresh();expect(old.snapshot).toMatchObject({phase:'closed',data:null,retryReceive:false});wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});f.faults.networkWait=null;await f.refresh();expect(f.runtime.snapshot.data?.order).toBe('0');await f.runtime.sync();expect(f.runtime.snapshot.data?.order).toBe('1');}finally{await f.cleanup();}});
it('CHANGES-RUNTIME: admitted old-store commit finishes after close; no success/rollback claim and replacement sees durable result',async()=>{const f=await fixture();try{f.events.push(f.event('1'));const wait=deferred<void>();f.faults.receiveWait=wait;const old=f.runtime,work=old.sync();await expect.poll(async()=>(await f.store.changesLoad()).order).toBe('1');const close=old.close();expect(old.snapshot).toMatchObject({phase:'closed',data:null,retryReceive:false});wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});await close;f.faults.receiveWait=null;const replacement=await f.replace();expect(replacement.snapshot).toMatchObject({data:{order:'1',received:true},readComplete:false});expect(f.requests).toHaveLength(1);}finally{await f.cleanup();}});
