import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema,prepareDatabaseResolution,prepareDatabaseViewResolution} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
import {PostgresPrivateDatabaseRecordStore} from '../../apps/api/src/private-database-record-store.js';
import {PostgresPrivateDatabaseViewStore} from '../../apps/api/src/private-database-view-store.js';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_dclient_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-content-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'content-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'content-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'content-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit:'record'|'view'|'changes'|null=null;const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));const result=await fetch(input,init);if(hold&&String(input).endsWith('/pull')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_'+failCommit+'_receive'){failCommit=null;throw Error('fixture commit result unknown');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),created=await sources.create(owner,context.workspaceId,{protocolVersion:1,clientId:context.clientId,operationId:newId(),source});
 const option=(source.properties.find(p=>p.type==='select') as {options:{id:string}[]}).options[0]!.id,pageId=newId(),recordId=newId(),viewId=newId(),pages=new PostgresPrivatePageStore(pool,schema),records=new PostgresPrivateDatabaseRecordStore(pool,schema),views=new PostgresPrivateDatabaseViewStore(pool,schema),writeRecord=async(intent:unknown)=>privateDatabaseRecordWriteResponseSchema.parse(await records.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent})),writeView=async(intent:unknown)=>privateDatabaseViewWriteResponseSchema.parse(await views.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent}));
 await pages.bootstrap(owner,context.workspaceId,pageId,{protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,title:'Page Name',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')});
 const recordBase={sourceId:source.id,schemaVersion:1,recordId,pageId},viewBase={sourceId:source.id,schemaVersion:1,viewId},initialRecord=await writeRecord({...recordBase,kind:'create',baseVersion:null,values:{[ids.text]:'base',[ids.number]:0,[ids.checkbox]:false,[ids.select]:option,[ids.date]:'2026-10-09'}}),initialView=await writeView({...viewBase,kind:'create',baseVersion:null,settings:{name:'base',layout:'table',visiblePropertyIds:[ids.name,ids.text,ids.number,ids.checkbox,ids.select,ids.date],filter:{kind:'predicate',propertyId:ids.number,operator:'gte',value:0},sorts:[{propertyId:ids.date,direction:'asc'},{propertyId:ids.text,direction:'desc'}]}});
 return{apiUrl:runtime.address,pool,schema,source,created,context,auth,owner,ids,pageId,recordId,viewId,recordBase,viewBase,initialRecord,initialView,writeRecord,writeView,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:(kind:'record'|'view'|'changes')=>{failCommit=kind;},blockPull:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
real('DB-CHANGES-CLIENT-PG: captured signed HTTP resumes two actual SQLite replicas; lost commit return retries exact response without HTTP and restart retains cursor/cache',async()=>{await isolated(async f=>{
 const calls=f.calls.length;await expect(f.store.databaseChanges(f.source.id)).rejects.toMatchObject({stage:'protocol'});expect(f.calls).toHaveLength(calls);await f.store.databaseSources().read(f.source.id);let session=await f.store.databaseChanges(f.source.id),before=f.calls.length;expect((await session.progress()).received).toBe(false);expect(f.calls).toHaveLength(before);
 f.unknownNextCommit('changes');await expect(session.pull(1)).rejects.toMatchObject({stage:'storage'});expect(session.retryReceive).toBe(true);before=f.calls.length;await expect(session.pull()).rejects.toMatchObject({stage:'busy'});const first=await session.retry();expect(first.progress).toMatchObject({order:'1',headOrder:'2',hasMore:true});expect(f.calls).toHaveLength(before);expect(first.response.events[0]!.kind).toBe('record');expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toEqual(f.initialRecord.record);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toBeNull();
 await f.reopen();expect(session.signal.aborted).toBe(true);session=await f.store.databaseChanges(f.source.id);expect((await session.pull(1)).progress).toMatchObject({order:'2',hasMore:false});expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toEqual(f.initialView.snapshot);expect(await f.store.hasPage(f.pageId)).toBe(false);
 const directory=mkdtempSync(join(tmpdir(),'greiva-dbchanges-second-')),device=new WorkspaceRegistryDevice(join(directory,'native')),connection=new PrivateWorkspaceConnection(f.auth,{apiUrl:f.apiUrl,clientId:newId()}),context=await connection.bootstrap();let store:NativeWorkspaceStore|undefined;
 try{store=await NativeWorkspaceStore.open(connection,device.invoke);await store.databaseSources().read(f.source.id);const second=await store.databaseChanges(f.source.id);expect((await second.pull()).progress).toMatchObject({order:'2',context:{clientId:context.clientId}});expect(context.clientId).not.toBe(f.context.clientId);expect((await store.databaseRecordLoad(f.source.id,f.recordId)).record).toEqual(f.initialRecord.record);expect((await store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toEqual(f.initialView.snapshot);await store.close();await device.close();store=await NativeWorkspaceStore.open(connection,device.invoke);expect((await store.databaseChangesLoad(f.source.id)).order).toBe('2');}finally{await store?.close().catch(()=>{});connection.close();await device.close();rmSync(directory,{recursive:true,force:true});}
 expect(f.calls.filter(path=>path.endsWith('/changes/pull'))).toHaveLength(2);
});});
real('DB-CHANGES-CLIENT-PG: read-ahead snapshots retain versions while delta fills histories/candidates; remote resolution survives stale read/restart and progress never rewinds',async()=>{await isolated(async f=>{
 await f.store.databaseSources().read(f.source.id);const contents=await f.store.databaseContents(f.source.id),request={protocolVersion:1,clientId:f.context.clientId,pageId:f.pageId};await f.writeRecord({...f.recordBase,kind:'update',baseVersion:1,values:{[f.ids.text]:'remote'}});await f.writeView({...f.viewBase,kind:'update',baseVersion:1,patch:{name:'remote'}});const r=await f.writeRecord({...f.recordBase,kind:'update',baseVersion:1,values:{[f.ids.text]:'local'}}),v=await f.writeView({...f.viewBase,kind:'update',baseVersion:1,patch:{name:'local'}});if(r.result.status!=='conflict'||v.result.status!=='conflict')throw Error('Fixture candidate missing');const rc=r.result.conflicts[0]!,vc=v.result.conflicts[0]!;const staleRecord=await contents.readRecord(f.recordId,request),staleView=await contents.readView(f.viewId);let session=await f.store.databaseChanges(f.source.id);expect((await session.pull()).progress).toMatchObject({order:'6',hasMore:false});expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record?.version).toBe(2);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot?.version).toBe(2);
 const rr=await f.writeRecord(prepareDatabaseResolution(f.source,r.record,rc,'remote')),vr=await f.writeView(prepareDatabaseViewResolution(f.source,v.snapshot,vc,'remote'));expect((await session.pull()).progress.order).toBe('8');await f.store.databaseRecordReceive(f.source.id,f.recordId,request,staleRecord);await f.store.databaseViewReceive(f.source.id,f.viewId,{protocolVersion:1,clientId:f.context.clientId},staleView);await f.reopen();session=await f.store.databaseChanges(f.source.id);expect((await session.progress()).order).toBe('8');expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).conflicts).toEqual([{...rc,resolvedBy:rr.operationId}]);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).conflicts).toEqual([{...vc,resolvedBy:vr.operationId}]);expect((await session.pull()).response.events).toEqual([]);expect((await f.store.databaseChangesLoad(f.source.id)).order).toBe('8');
});});
real('DB-CHANGES-CLIENT-PG: filtered empty windows advance without deleting cached entities; denied Source closes old sessions and reconnect retains cursor/data',async()=>{await isolated(async f=>{
 await f.store.databaseSources().read(f.source.id);let session=await f.store.databaseChanges(f.source.id);await session.pull();await f.writeRecord({...f.recordBase,kind:'update',baseVersion:1,values:{[f.ids.text]:'filtered'}});await f.writeView({...f.viewBase,kind:'update',baseVersion:1,patch:{name:'filtered'}});await f.pool.query(`UPDATE "${f.schema}".private_resources SET deleted=true WHERE id=$1`,[f.pageId]);await f.pool.query(`UPDATE "${f.schema}".private_database_views SET deleted=true WHERE id=$1`,[f.viewId]);const result=await session.pull(2);expect(result.response.events).toEqual([]);expect(result.progress).toMatchObject({order:'4',hasMore:false});expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toEqual(f.initialRecord.record);expect((await f.store.databaseViewLoad(f.source.id,f.viewId)).snapshot).toEqual(f.initialView.snapshot);await f.pool.query(`UPDATE "${f.schema}".private_database_sources SET deleted=true WHERE id=$1`,[f.source.id]);await expect(session.pull()).rejects.toMatchObject({stage:'closed'});expect(session.retryReceive).toBe(false);await expect(f.store.databaseChangesLoad(f.source.id)).rejects.toMatchObject({stage:'closed'});await f.reconnect();expect((await f.store.databaseChangesLoad(f.source.id)).order).toBe('4');expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record?.version).toBe(1);
});});
real('DB-CHANGES-CLIENT-PG: replacement/refresh/native-close exclude late signed pulls; invalid replacement keeps old session; local opening never fetches changes',async()=>{await isolated(async f=>{
 await f.store.databaseSources().read(f.source.id);let session=await f.store.databaseChanges(f.source.id);expect(()=>f.connection.openDatabaseChanges({...f.source,workspaceId:newId()},{load:async()=>null,receive:async()=>{}})).toThrow('Private workspace connection configuration');expect(session.signal.aborted).toBe(false);let block=f.blockPull(),work=session.pull();await block.entered;let replacement=await f.store.databaseChanges(f.source.id);block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect((await f.store.databaseChangesLoad(f.source.id)).received).toBe(false);
 session=replacement;block=f.blockPull();work=session.pull();await block.entered;await f.auth.refresh();await f.connection.bootstrap();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});await f.reopen();expect((await f.store.databaseChangesLoad(f.source.id)).received).toBe(false);
 session=await f.store.databaseChanges(f.source.id);const contents=await f.store.databaseContents(f.source.id),sources=f.store.databaseSources();block=f.blockPull();work=session.pull();await block.entered;await f.store.close();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(contents.signal.aborted).toBe(true);expect(sources.signal.aborted).toBe(true);const calls=f.calls.length;await expect(session.pull()).rejects.toMatchObject({stage:'closed'});expect(f.calls).toHaveLength(calls);await f.reopen();replacement=await f.store.databaseChanges(f.source.id);expect((await replacement.pull()).progress.order).toBe('2');f.connection.close();await expect(replacement.progress()).rejects.toMatchObject({stage:'closed'});
});});
