import {it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import pg from 'pg';import * as Y from 'yjs';import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {emptyPageUpdate,supabaseAuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {createSupabasePrivateApp} from '../../apps/api/src/supabase-private-app.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';import {PostgresPrivateAccessStore} from '../../apps/api/src/private-access-store.js';import {PostgresPrivateTransactions} from '../../apps/api/src/private-transactions.js';import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {WorkspaceDevice} from '../support/workspace-device.js';
it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1')('PRIVATE-PAGE-CLIENT-PG: signed fixture HTTP and two actual SQLite stores recover lost ACKs, offline restart, concurrent edits and revoked pending without duplicate binary',async()=>{
  const directory=mkdtempSync(join(tmpdir(),'greiva-private-page-client-')),schema='greiva_private_'+newId().replaceAll('-',''),pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),projectUrl='https://project.fixture.invalid',keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'fixture',alg:'ES256'};
  const devices:WorkspaceDevice[]=[],auths:ReturnType<typeof supabaseAuthSession>[]=[],docs:Y.Doc[]=[];let app:Awaited<ReturnType<typeof createSupabasePrivateApp>>|undefined;
  try{
    await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);app=await createSupabasePrivateApp({projectUrl,algorithm:'ES256'},new PostgresPrivateAccessStore(pool,schema),new PostgresPrivateBootstrapStore(pool,schema),async()=>new Response(JSON.stringify({keys:[jwk]})),new PostgresPrivateTransactions(pool,schema),new PostgresPrivateStructuredStore(pool,schema),new PostgresPrivatePageStore(pool,schema));await app.listen(0,'127.0.0.1');const apiUrl=await app.getUrl();
    const auth=async()=>{const session=supabaseAuthSession({projectUrl,algorithm:'ES256',publishableKey:'sb_publishable_fixture',apiUrl},async(input,init)=>{if(new URL(String(input)).origin!==projectUrl)return fetch(input,init);const token=await new SignJWT({sub:'owner',iss:projectUrl+'/auth/v1',aud:'authenticated',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(keys.privateKey);return new Response(JSON.stringify({access_token:token,refresh_token:'fixture-refresh',token_type:'bearer',user:{id:'owner'}}));});auths.push(session);await session.login('fixture@example.invalid','fixture-password');return session;};
    const oneAuth=await auth(),twoAuth=await auth(),one=await new PrivateWorkspaceConnection(oneAuth,{apiUrl,clientId:newId()}).bootstrap(),two=await new PrivateWorkspaceConnection(twoAuth,{apiUrl,clientId:newId()}).bootstrap(),device=new WorkspaceDevice(join(directory,'one.sqlite'),one),peer=new WorkspaceDevice(join(directory,'two.sqlite'),two);devices.push(device,peer);const id=newId(),path=`/v1/workspaces/${one.workspaceId}/pages/${id}/document/`;
    const post=(session:typeof oneAuth,kind:string,body:unknown)=>session.authorized((authorization,signal)=>fetch(apiUrl+path+kind,{method:'POST',headers:{authorization,'content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body),signal}));
    async function send(target:WorkspaceDevice,session:typeof oneAuth,lose=false){const prepared=await target.request('page_prepare',{pageId:id});expect(prepared).not.toBeNull();const response=await post(session,prepared.kind,prepared.wire);expect(response.status).toBe(200);const value=await response.json();if(lose)return prepared;await target.request('page_ack',{...prepared,response:value});return prepared;}
    async function restore(target:WorkspaceDevice){const doc=new Y.Doc({gc:false});docs.push(doc);for(const bytes of (await target.request('page_load',{pageId:id})).page.updates)Y.applyUpdate(doc,Uint8Array.from(bytes));return doc;}
    async function pull(target:WorkspaceDevice,session:typeof oneAuth,context:typeof one,vector='AA'){const response=await post(session,'read',{protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,stateVector:vector});expect(response.status).toBe(200);await target.request('page_receive',{pageId:id,response:await response.json()});}
    const original=new Y.Doc({gc:false});docs.push(original);Y.applyUpdate(original,emptyPageUpdate());(original.getXmlFragment('body').get(0) as Y.XmlElement).insert(0,[new Y.XmlText('日本語')]);await device.request('page_create',{pageId:id,title:'private binary',update:Array.from(Y.encodeStateAsUpdate(original))});const first=await send(device,oneAuth,true);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(first);await send(device,oneAuth);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(1);await pull(peer,twoAuth,two);
    const local=await restore(device),remote=await restore(peer);const edit=(doc:Y.Doc,text:string)=>{let update:Uint8Array|undefined;const capture=(value:Uint8Array)=>{update=value;};doc.on('update',capture);((doc.getXmlFragment('body').get(0) as Y.XmlElement).get(0) as Y.XmlText).insert(0,text);doc.off('update',capture);return update!;};
    await device.request('page_append',{pageId:id,update:Array.from(edit(local,'one '))});await peer.request('page_append',{pageId:id,update:Array.from(edit(remote,'two '))});await device.close('SIGKILL');const durable=await device.request('page_prepare',{pageId:id});const [lost]=await Promise.all([send(device,oneAuth,true),send(peer,twoAuth)]);expect(lost).toEqual(durable);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(durable);await send(device,oneAuth);expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(3);
    await Promise.all([pull(device,oneAuth,one,Buffer.from(Y.encodeStateVector(local)).toString('base64url')),pull(peer,twoAuth,two,Buffer.from(Y.encodeStateVector(remote)).toString('base64url'))]);const a=await restore(device),b=await restore(peer);expect(a.getXmlFragment('body').toString()).toBe(b.getXmlFragment('body').toString());expect(a.getXmlFragment('body').toString()).toContain('one ');expect(a.getXmlFragment('body').toString()).toContain('two ');expect(Buffer.from(Y.encodeStateVector(a))).toEqual(Buffer.from(Y.encodeStateVector(b)));expect(await device.request('page_prepare',{pageId:id})).toBeNull();expect(await peer.request('page_prepare',{pageId:id})).toBeNull();
    await device.request('page_append',{pageId:id,update:Array.from(edit(a,'retained '))});const pending=await device.request('page_prepare',{pageId:id});await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[one.clientId]);expect((await post(oneAuth,'append',pending.wire)).status).toBe(403);await device.close('SIGKILL');expect(await device.request('page_prepare',{pageId:id})).toEqual(pending);expect((await restore(device)).getXmlFragment('body').toString()).toContain('retained ');expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(3);
  }finally{for(const auth of auths)auth.close();for(const doc of docs)doc.destroy();for(const device of devices)await device.close();await app?.close();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();rmSync(directory,{recursive:true,force:true});}}
});
