import {it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {newId} from '@greiva/shared';import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivateTitleSession} from '../../apps/client/src/workspace/private-title-session.js';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
async function fixture(known=true){
 const directory=mkdtempSync(join(tmpdir(),'greiva-title-runtime-')),registry=new WorkspaceRegistryDevice(join(directory,'store')),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},pageId=newId(),time='2026-10-08T00:00:00.000Z',metadata={id:pageId,title:'base',yDocId:'page:'+pageId,createdAt:time,updatedAt:time},scope={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,pageId};
 const token={access_token:'fixture.access.signature',refresh_token:'fixture-refresh',token_type:'bearer',user:{id:context.subjectId}},auth=new AuthSession(context.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>({issuer:context.issuer,subjectId:context.subjectId,expiresAt:200}),revoke:async()=>{}},()=>100);
 const state={version:0,title:'base',conflicts:[] as any[],queries:[] as any[],wires:[] as string[],loseMutation:false,failLoad:false,loseRename:false,query:null as null|((body:any)=>Promise<unknown>),beforeEnqueue:null as null|(()=>Promise<void>)};
 const ledger=new Map<string,unknown>(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const request=args?.request as {command?:string}|undefined;if(request?.command==='title_enqueue')await state.beforeEnqueue?.();if(request?.command==='title_load'&&state.failLoad){state.failLoad=false;throw Error('private email/path');}const value=await registry.invoke(command,args);if(request?.command==='title_enqueue'&&state.loseMutation){state.loseMutation=false;throw Error('private committed reply');}return value;};
 const connection=new PrivateWorkspaceConnection(auth,{apiUrl:'http://127.0.0.1:3001',clientId:context.clientId},async(input,init)=>{
   if(String(input).endsWith('/bootstrap'))return Response.json({protocolVersion:1,workspaceId:context.workspaceId,clientId:context.clientId,epoch:context.streamEpoch});
   const body=JSON.parse(String(init?.body));if(String(input).endsWith('/rename')){state.wires.push(String(init?.body));if(!ledger.has(body.operationId)){if(state.title!==body.title)++state.version;state.title=body.title;ledger.set(body.operationId,{...scope,metadata:{...metadata,title:state.title},version:state.version,operationId:body.operationId,result:{status:'applied'}});}if(state.loseRename){state.loseRename=false;throw Error('private lost ACK');}return Response.json(ledger.get(body.operationId));}
   state.queries.push(body);if(state.query)return Response.json(await state.query(body));const records=state.conflicts.filter(cf=>body.afterConflict===null||cf.id>body.afterConflict);return Response.json({...scope,metadata:{...metadata,title:state.title},version:state.version,conflicts:records.slice(0,body.limit),nextAfter:records.length>body.limit?records[body.limit-1].id:null});
 });
 await auth.login('fixture@example.invalid','fixture-password');await connection.bootstrap();let store=await NativeWorkspaceStore.open(connection,invoke);const page=store.page(pageId);await page.create('base',emptyPageUpdate());const prepared=(await page.prepare())!;await page.acknowledge({...context,pageId,documentName:'page:'+pageId,editorSchemaVersion:1},prepared,{protocolVersion:1,workspaceId:context.workspaceId,pageId,documentName:'page:'+pageId,editorSchemaVersion:1,metadata,initialDigest:prepared.digest});
 if(known)await store.title(pageId).receive({protocolVersion:1,clientId:context.clientId,afterConflict:null,limit:100},{...scope,metadata,version:0,conflicts:[],nextAfter:null});let session=await PrivateTitleSession.open(connection,store,pageId);
 return{directory,registry,context,pageId,metadata,scope,state,auth,connection,get store(){return store;},get session(){return session;},
  async reopen(){await session.close();await store.close();await registry.close('SIGKILL');store=await NativeWorkspaceStore.open(connection,invoke);session=await PrivateTitleSession.open(connection,store,pageId);},
  async cleanup(){await session.close();await store.close().catch(()=>{});connection.close();auth.close();await registry.close();rmSync(directory,{recursive:true,force:true});}};
}
it('TITLE-RUNTIME: local open performs no query or creation; unknown baseline becomes known only on explicit sync',async()=>{const f=await fixture(false);try{expect(f.session.snapshot).toMatchObject({phase:'ready',data:{base:null},pending:0,queryComplete:false});expect(f.state.queries).toHaveLength(0);await expect(f.session.mutate({operationId:newId(),title:'unknown'})).rejects.toMatchObject({stage:'protocol'});expect(f.session.snapshot.retryMutation).toBe(false);await f.session.sync();expect(f.session.snapshot).toMatchObject({data:{base:{version:0}},queryComplete:true});await f.session.mutate({operationId:newId(),title:'offline'});expect(f.session.snapshot).toMatchObject({data:{localTitle:'offline'},pending:1,queryComplete:false});expect(f.state.wires).toHaveLength(0);}finally{await f.cleanup();}});
it('TITLE-RUNTIME: offline chain and exact prepared request survive lost HTTP ACK and registry SIGKILL; own receipt advances descendant',async()=>{const f=await fixture();try{await f.session.mutate({operationId:newId(),title:'first'});await f.session.mutate({operationId:newId(),title:'second'});const prepared=await f.store.title(f.pageId).prepare();f.state.loseRename=true;await expect(f.session.sync()).rejects.toThrow('Private title transport');expect(f.session.snapshot).toMatchObject({pending:2,error:'transport',data:{localTitle:'second'}});await f.reopen();expect(await f.store.title(f.pageId).prepare()).toEqual(prepared);expect(f.session.snapshot.queryComplete).toBe(false);await f.session.sync();expect(f.state.wires[0]).toBe(f.state.wires[1]);expect(JSON.parse(f.state.wires[2]!).baseVersion).toBe(1);expect(f.session.snapshot).toMatchObject({pending:0,data:{localTitle:'second',base:{version:2}},queryComplete:true});expect('synced' in f.session.snapshot).toBe(false);}finally{await f.cleanup();}});
it('TITLE-RUNTIME: unknown local commit/read results retain exact intent and refuse another mutation until same-ID retry',async()=>{for(const fault of ['loseMutation','failLoad'] as const){const f=await fixture();try{const intent={operationId:newId(),title:'retained'};f.state[fault]=true;await expect(f.session.mutate(intent)).rejects.toThrow('Private title storage');expect(f.session.snapshot.retryMutation).toBe(true);await expect(f.session.mutate({operationId:newId(),title:'other'})).rejects.toMatchObject({stage:'busy'});await expect(f.session.sync()).rejects.toMatchObject({stage:'busy'});intent.title='caller changed';await f.session.retryMutation();expect(f.session.snapshot).toMatchObject({pending:1,retryMutation:false,data:{localTitle:'retained'}});expect((await f.store.title(f.pageId).load()).operations).toHaveLength(1);}finally{await f.cleanup();}}});
it('TITLE-RUNTIME: bounded remote keysets continue only after durable query/local read; omitted candidates and histories remain',async()=>{const f=await fixture();try{f.state.version=1;f.state.title='remote';f.state.conflicts=Array.from({length:101},()=>({id:newId(),operationId:newId(),baseVersion:0,remoteVersion:1,base:'base',local:'alternative',remote:'remote'})).sort((a,b)=>a.id.localeCompare(b.id));await f.session.sync();expect(f.session.snapshot).toMatchObject({hasMoreRemote:true,queryComplete:false});const after=f.state.conflicts[99].id;f.state.failLoad=true;await expect(f.session.sync()).rejects.toThrow();expect(f.session.snapshot.hasMoreRemote).toBe(true);await f.session.sync();expect(f.state.queries.at(-1).afterConflict).toBe(after);expect(f.session.snapshot).toMatchObject({hasMoreRemote:false,queryComplete:true,hasMoreLocal:true});f.state.conflicts=[];await f.session.sync();expect((await f.store.title(f.pageId).load()).conflicts).toHaveLength(50);expect((await f.store.title(f.pageId).load({limit:100})).nextConflict).not.toBeNull();}finally{await f.cleanup();}});
it('TITLE-RUNTIME: failed read after query commit retries unchanged keyset rather than advancing past lost local result',async()=>{const f=await fixture();try{let seen=0;f.state.query=async()=>{++seen;f.state.failLoad=true;return {...f.scope,metadata:f.metadata,version:0,conflicts:[],nextAfter:null};};await expect(f.session.sync()).rejects.toThrow('Private title storage');expect(seen).toBe(1);expect(f.session.snapshot.queryComplete).toBe(false);f.state.query=null;await f.session.sync();expect(f.state.queries.map(query=>query.afterConflict)).toEqual([null,null]);expect(f.session.snapshot.queryComplete).toBe(true);}finally{await f.cleanup();}});
it('TITLE-RUNTIME: close/replacement/refresh ignore late queries; title replacement leaves independent body session active',async()=>{for(const action of ['close','replace','refresh'] as const){const f=await fixture(),wait=deferred<unknown>();try{const body=f.connection.openPage(f.pageId,f.store.page(f.pageId));f.state.query=()=>wait.promise;const work=f.session.sync();await expect.poll(()=>f.state.queries.length).toBe(1);if(action==='close')void f.session.close();if(action==='replace'){const replacement=await PrivateTitleSession.open(f.connection,f.store,f.pageId);expect(body.signal.aborted).toBe(false);await replacement.close();}if(action==='refresh')await f.auth.refresh();wait.resolve({...f.scope,metadata:{...f.metadata,title:'late'},version:1,conflicts:[],nextAfter:null});await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.session.snapshot).toMatchObject({phase:'closed',data:null});if(action!=='refresh')expect((await f.store.title(f.pageId).load()).base?.version).toBe(0);}finally{wait.resolve(null);await f.cleanup();}}});
it('TITLE-RUNTIME: admitted enqueue finishes on captured Page after close; observers and invalid intent cannot interrupt or redirect it',async()=>{const f=await fixture(),wait=deferred<void>();try{await expect(f.session.mutate({operationId:newId(),title:'bad',email:'private'})).rejects.toMatchObject({stage:'protocol'});f.session.subscribe(()=>{throw Error('observer');});f.state.beforeEnqueue=()=>wait.promise;const intent={operationId:newId(),title:'admitted'},work=f.session.mutate(intent);await expect.poll(()=>f.session.snapshot.busy).toBe(true);void f.session.close();intent.title='changed';wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});expect((await f.store.title(f.pageId).load()).localTitle).toBe('admitted');expect((await f.store.title(f.pageId).load()).pending).toBe(1);}finally{wait.resolve();await f.cleanup();}});
it('TITLE-RUNTIME: one explicit cycle sends at most100 intents; bounded local history advances and restarts without consuming remaining pending',async()=>{const f=await fixture();try{for(let n=0;n<101;++n)await f.store.title(f.pageId).enqueue({operationId:newId(),title:'edit '+n});await f.session.sync();expect(f.state.wires).toHaveLength(100);expect(f.session.snapshot).toMatchObject({pending:1,hasMoreLocal:true});expect('synced' in f.session.snapshot).toBe(false);await f.session.history(true);expect(f.session.snapshot.data?.operations).toHaveLength(1);expect(f.session.snapshot.data?.operations[0]?.intent.title).toBe('edit 100');expect(f.session.snapshot.pending).toBe(1);await f.session.history();expect(f.session.snapshot.data?.operations).toHaveLength(100);const records=Array.from({length:201},()=>({id:newId(),operationId:newId(),baseVersion:0,remoteVersion:1,base:'base',local:'alternative',remote:'past remote'})).sort((a,b)=>a.id.localeCompare(b.id));for(let start=0;start<records.length;start+=100){const batch=records.slice(start,start+100),afterConflict=start?records[start-1]!.id:null;await f.store.title(f.pageId).receive({protocolVersion:1,clientId:f.context.clientId,afterConflict,limit:100},{...f.scope,metadata:{...f.metadata,title:f.state.title},version:f.state.version,conflicts:batch,nextAfter:start+100<records.length?batch.at(-1)!.id:null});}await f.session.history();await f.session.history(true);expect(f.session.snapshot.data?.operations).toHaveLength(1);expect(f.session.snapshot.data?.conflicts).toHaveLength(100);f.state.failLoad=true;await expect(f.session.history(true)).rejects.toMatchObject({stage:'storage'});await f.session.history(true);expect(f.session.snapshot.data?.operations).toHaveLength(0);expect(f.session.snapshot.data?.conflicts).toHaveLength(1);expect(f.session.snapshot).toMatchObject({hasMoreLocal:false,pending:1});await f.session.history(true);expect(f.session.snapshot.data?.operations).toHaveLength(0);expect(f.session.snapshot.data?.conflicts).toHaveLength(0);await f.session.sync();expect(f.session.snapshot.pending).toBe(0);}finally{await f.cleanup();}});
it('TITLE-RUNTIME: close from state observer before admission prevents storage and clears uncertain state',async()=>{const f=await fixture();try{f.session.subscribe(state=>{if(state.busy)void f.session.close();});await expect(f.session.mutate({operationId:newId(),title:'not admitted'})).rejects.toMatchObject({stage:'closed'});expect(f.session.snapshot).toMatchObject({phase:'closed',data:null,retryMutation:false});expect((await f.store.title(f.pageId).load()).pending).toBe(0);}finally{await f.cleanup();}});
