import {PrivateDatabaseChangesSession} from '../../apps/client/src/workspace/private-database-changes-session.js';
import {it,expect,vi} from 'vitest';import pg from 'pg';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {databaseSourceSchema,prepareDatabaseResolution,prepareDatabaseViewResolution} from '@greiva/domain';
import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';
import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';
import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';
import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';
import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {installPrivateDatabaseSourceSchema} from '../../apps/api/src/private-database-source-schema.js';
import {installPrivateDatabaseRecordSchema} from '../../apps/api/src/private-database-record-schema.js';
import {installPrivateDatabaseRecordCatalogSchema} from '../../apps/api/src/private-database-record-catalog-schema.js';
import {installPrivateDatabaseViewSchema} from '../../apps/api/src/private-database-view-schema.js';
import {installPrivateDatabaseViewCatalogSchema} from '../../apps/api/src/private-database-view-catalog-schema.js';
import {installPrivateDatabaseChangesSchema} from '../../apps/api/src/private-database-changes-schema.js';
import {PostgresPrivateDatabaseSourceStore} from '../../apps/api/src/private-database-source-store.js';import {startPrivateApi} from '../../apps/api/src/private-runtime.js';
import {PostgresPrivateDatabaseRecordStore} from '../../apps/api/src/private-database-record-store.js';
import {PostgresPrivateDatabaseViewStore} from '../../apps/api/src/private-database-view-store.js';
import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';
import {privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
const real=it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1');
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function isolated(run:(f:Awaited<ReturnType<typeof setup>>)=>Promise<void>){const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8,statement_timeout:10000}),schema='greiva_private_drun_'+newId().replaceAll('-','');let f:Awaited<ReturnType<typeof setup>>|undefined;try{for(const install of [installPrivateWorkspaceSchema,installPrivateStructuredSchema,installPrivatePageSchema,installPrivatePageMetadataSchema,installPrivatePageChangesSchema,installPrivateDatabaseSourceSchema,installPrivateDatabaseRecordSchema,installPrivateDatabaseRecordCatalogSchema,installPrivateDatabaseViewSchema,installPrivateDatabaseViewCatalogSchema,installPrivateDatabaseChangesSchema])await install(pool,schema);f=await setup(pool,schema);await run(f);}finally{await f?.cleanup();try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}}
async function setup(pool:pg.Pool,schema:string){
 const directory=mkdtempSync(join(tmpdir(),'greiva-content-http-')),device=new WorkspaceRegistryDevice(join(directory,'native')),keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'content-client-fixture',alg:'ES256'},server=createServer();await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));const runtime=await startPrivateApi({projectUrl:'https://project.fixture.invalid',algorithm:'ES256',databaseUrl:process.env.DATABASE_URL!,schema,host:'127.0.0.1',port},{fetchJwks:vi.fn(async()=>new Response(JSON.stringify({keys:[jwk]}))) as typeof fetch});
 const owner={issuer:'https://project.fixture.invalid/auth/v1',subjectId:'content-client-owner',expiresAt:Math.floor(Date.now()/1000)+300},signed=await new SignJWT({sub:owner.subjectId,iss:owner.issuer,aud:'authenticated',email:'auth-only@example.invalid',exp:owner.expiresAt}).setProtectedHeader({alg:'ES256',kid:'content-client-fixture'}).sign(keys.privateKey),token={access_token:signed,refresh_token:'fixture-only-refresh',token_type:'bearer',user:{id:owner.subjectId}},auth=new AuthSession(owner.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>owner,revoke:async()=>{}});
 let hold:ReturnType<typeof deferred<void>>|null=null,entered:ReturnType<typeof deferred<void>>|null=null,failCommit:'record'|'view'|'changes'|null=null;let offline=false;const calls:string[]=[],fetchPort:typeof fetch=async(input,init)=>{calls.push(String(input));if(offline)throw Error('fixture offline');const result=await fetch(input,init);if(hold&&String(input).endsWith('/pull')){entered?.resolve();await hold.promise;}return result;};let connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:newId()},fetchPort);await auth.login('auth-only@example.invalid','fixture');const context=await connection.bootstrap(),invoke:NativeWorkspaceInvoke=async(command,args)=>{const result=await device.invoke(command,args);if(failCommit&&command==='workspace_execute'&&(args?.request as {command?:string})?.command==='database_'+failCommit+'_receive'){failCommit=null;throw Error('fixture commit result unknown');}return result;};let store=await NativeWorkspaceStore.open(connection,invoke);
 const ids={name:newId(),text:newId(),number:newId(),checkbox:newId(),select:newId(),date:newId()},source=databaseSourceSchema.parse({id:newId(),workspaceId:context.workspaceId,name:'Server definition',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type,...(type==='select'?{options:[{id:newId(),name:'Choice'}]}:{})}))}),sources=new PostgresPrivateDatabaseSourceStore(pool,schema),created=await sources.create(owner,context.workspaceId,{protocolVersion:1,clientId:context.clientId,operationId:newId(),source});
 const option=(source.properties.find(p=>p.type==='select') as {options:{id:string}[]}).options[0]!.id,pageId=newId(),recordId=newId(),viewId=newId(),pages=new PostgresPrivatePageStore(pool,schema),records=new PostgresPrivateDatabaseRecordStore(pool,schema),views=new PostgresPrivateDatabaseViewStore(pool,schema),writeRecord=async(intent:unknown)=>privateDatabaseRecordWriteResponseSchema.parse(await records.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent})),writeView=async(intent:unknown)=>privateDatabaseViewWriteResponseSchema.parse(await views.write(owner,context.workspaceId,source.id,{protocolVersion:1,clientId:context.clientId,operationId:newId(),intent}));
 await pages.bootstrap(owner,context.workspaceId,pageId,{protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,title:'Page Name',initialUpdate:Buffer.from(emptyPageUpdate()).toString('base64url')});
 const recordBase={sourceId:source.id,schemaVersion:1,recordId,pageId},viewBase={sourceId:source.id,schemaVersion:1,viewId},initialRecord=await writeRecord({...recordBase,kind:'create',baseVersion:null,values:{[ids.text]:'base',[ids.number]:0,[ids.checkbox]:false,[ids.select]:option,[ids.date]:'2026-10-09'}}),initialView=await writeView({...viewBase,kind:'create',baseVersion:null,settings:{name:'base',layout:'table',visiblePropertyIds:[ids.name,ids.text,ids.number,ids.checkbox,ids.select,ids.date],filter:{kind:'predicate',propertyId:ids.number,operator:'gte',value:0},sorts:[{propertyId:ids.date,direction:'asc'},{propertyId:ids.text,direction:'desc'}]}});
 return{offline:(value:boolean)=>{offline=value;},apiUrl:runtime.address,pool,schema,source,created,context,auth,owner,ids,pageId,recordId,viewId,recordBase,viewBase,initialRecord,initialView,writeRecord,writeView,get connection(){return connection;},calls,get store(){return store;},unknownNextCommit:(kind:'record'|'view'|'changes')=>{failCommit=kind;},blockPull:()=>{hold=deferred<void>();entered=deferred<void>();return{entered:entered.promise,release:()=>{hold?.resolve();hold=null;}};},reopen:async()=>{await store.close().catch(()=>{});await device.close();store=await NativeWorkspaceStore.open(connection,invoke);},reconnect:async()=>{await store.close().catch(()=>{});await device.close();connection.close();connection=new PrivateWorkspaceConnection(auth,{apiUrl:runtime.address,clientId:context.clientId},fetchPort);await connection.bootstrap();store=await NativeWorkspaceStore.open(connection,invoke);},cleanup:async()=>{hold?.resolve();await store.close().catch(()=>{});connection.close();await device.close();await runtime.close();rmSync(directory,{recursive:true,force:true});}};
}
real('DB-CHANGES-RUNTIME-PG: offline local opening/reload never fetch; one explicit sync is max100 and observed head changes do not imply full sync or consume Page pending',async()=>{await isolated(async f=>{
 await f.store.databaseSources().read(f.source.id);f.offline(true);const before=f.calls.length,runtime=await PrivateDatabaseChangesSession.open(f.connection,f.store,f.source.id);expect(runtime.snapshot).toMatchObject({phase:'ready',data:{received:false},observedHead:false});await runtime.reload();expect(f.calls).toHaveLength(before);await expect(runtime.sync()).rejects.toMatchObject({stage:'transport'});expect(runtime.snapshot).toMatchObject({error:'transport',data:{order:'0'},observedHead:false,retryReceive:false});f.offline(false);
 for(let i=1;i<=101;i++)await f.writeRecord({...f.recordBase,kind:'update',baseVersion:i,values:{[f.ids.text]:'row-'+i}});
 const deltaBefore=f.calls.filter(path=>path.endsWith('/changes/pull')).length;await runtime.sync();expect(runtime.snapshot).toMatchObject({data:{order:'100',headOrder:'103',hasMore:true},observedHead:false});expect(f.calls.filter(path=>path.endsWith('/changes/pull'))).toHaveLength(deltaBefore+1);await f.writeRecord({...f.recordBase,kind:'update',baseVersion:102,values:{[f.ids.text]:'late-head'}});await runtime.sync();expect(runtime.snapshot).toMatchObject({data:{order:'104',headOrder:'104',hasMore:false},observedHead:true});expect((await f.store.databaseRecordLoad(f.source.id,f.recordId)).record).toMatchObject({version:103,values:{[f.ids.text]:'late-head'}});
 const page=newId();await f.store.page(page).create('offline body',emptyPageUpdate());await runtime.reload();expect(runtime.snapshot.observedHead).toBe(false);await runtime.close();expect(runtime.snapshot).toMatchObject({phase:'closed',data:null});expect((await f.store.page(page).load()).pending).toBe(1);expect((await f.store.databaseChangesLoad(f.source.id)).order).toBe('104');
});});
real('DB-CHANGES-RUNTIME-PG: lost native return remains unknown across local reload; exact retry/restart retains progress and Auth or native close cancels late HTTP',async()=>{await isolated(async f=>{
 await f.store.databaseSources().read(f.source.id);let runtime=await PrivateDatabaseChangesSession.open(f.connection,f.store,f.source.id);f.unknownNextCommit('changes');await expect(runtime.sync()).rejects.toMatchObject({stage:'storage'});expect(runtime.snapshot).toMatchObject({error:'storage',retryReceive:true,observedHead:false});await expect(runtime.sync()).rejects.toMatchObject({stage:'busy'});await runtime.reload();expect(runtime.snapshot).toMatchObject({data:{order:'2'},retryReceive:true,observedHead:false});const calls=f.calls.length;await runtime.retryReceive();expect(f.calls).toHaveLength(calls);expect(runtime.snapshot).toMatchObject({data:{order:'2'},retryReceive:false,observedHead:true});await f.reopen();expect(runtime.snapshot.phase).toBe('closed');runtime=await PrivateDatabaseChangesSession.open(f.connection,f.store,f.source.id);expect(runtime.snapshot).toMatchObject({data:{order:'2'},observedHead:false});
 let block=f.blockPull(),work=runtime.sync();await block.entered;await f.auth.refresh();await f.connection.bootstrap();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});expect(runtime.snapshot).toMatchObject({phase:'closed',data:null});await f.reopen();runtime=await PrivateDatabaseChangesSession.open(f.connection,f.store,f.source.id);block=f.blockPull();work=runtime.sync();await block.entered;await f.store.close();block.release();await expect(work).rejects.toMatchObject({stage:'closed'});await runtime.close();expect(runtime.snapshot.phase).toBe('closed');await f.reopen();expect((await f.store.databaseChangesLoad(f.source.id)).order).toBe('2');
});});
