import {it,expect} from 'vitest';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import pg from 'pg';import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {newId} from '@greiva/shared';import {emptyPageUpdate,supabaseAuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivateChangesSession} from '../../apps/client/src/workspace/private-changes-session.js';
import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
import {installPrivateWorkspaceSchema} from '../../apps/api/src/private-workspace-schema.js';import {installPrivateStructuredSchema} from '../../apps/api/src/private-structured-schema.js';import {installPrivatePageSchema} from '../../apps/api/src/private-page-schema.js';import {installPrivatePageMetadataSchema} from '../../apps/api/src/private-page-metadata-schema.js';import {installPrivatePageChangesSchema} from '../../apps/api/src/private-page-changes-schema.js';
import {createSupabasePrivateApp} from '../../apps/api/src/supabase-private-app.js';import {PostgresPrivateAccessStore} from '../../apps/api/src/private-access-store.js';import {PostgresPrivateBootstrapStore} from '../../apps/api/src/private-bootstrap-store.js';import {PostgresPrivateTransactions} from '../../apps/api/src/private-transactions.js';import {PostgresPrivateStructuredStore} from '../../apps/api/src/private-structured-store.js';import {PostgresPrivatePageStore} from '../../apps/api/src/private-page-store.js';import {PostgresPrivatePageMetadataStore} from '../../apps/api/src/private-page-metadata-store.js';import {PostgresPrivatePageChangesStore} from '../../apps/api/src/private-page-changes-store.js';

it.skipIf(process.env.GREIVA_TEST_POSTGRES!=='1')('CHANGES-CLIENT-PG: signed HTTP/two actual SQLite stores preserve catalog, pending/conflicts, no-op resolution, restart, filtered progress and revoked cancellation',async()=>{
 const directory=mkdtempSync(join(tmpdir(),'greiva-changes-client-')),schema='greiva_private_'+newId().replaceAll('-',''),pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),projectUrl='https://project.fixture.invalid',keys=await generateKeyPair('ES256'),jwk={...await exportJWK(keys.publicKey),kid:'fixture',alg:'ES256'};
 const registries:WorkspaceRegistryDevice[]=[],auths:ReturnType<typeof supabaseAuthSession>[]=[],connections:PrivateWorkspaceConnection[]=[],stores:NativeWorkspaceStore[]=[],runtimes:PrivateChangesSession[]=[];let app:Awaited<ReturnType<typeof createSupabasePrivateApp>>|undefined;
 try{
  await installPrivateWorkspaceSchema(pool,schema);await installPrivateStructuredSchema(pool,schema);await installPrivatePageSchema(pool,schema);await installPrivatePageMetadataSchema(pool,schema);await installPrivatePageChangesSchema(pool,schema);
  app=await createSupabasePrivateApp({projectUrl,algorithm:'ES256'},new PostgresPrivateAccessStore(pool,schema),new PostgresPrivateBootstrapStore(pool,schema),async()=>Response.json({keys:[jwk]}),new PostgresPrivateTransactions(pool,schema),new PostgresPrivateStructuredStore(pool,schema),new PostgresPrivatePageStore(pool,schema),new PostgresPrivatePageMetadataStore(pool,schema),new PostgresPrivatePageChangesStore(pool,schema));await app.listen(0,'127.0.0.1');const apiUrl=await app.getUrl();
  const client=async(name:string)=>{const pulls:{url:string;request:any;reply:any;authorization:string|null;credentials?:RequestCredentials;redirect?:RequestRedirect;cache?:RequestCache}[]=[],faults={lostPull:false};const auth=supabaseAuthSession({projectUrl,algorithm:'ES256',publishableKey:'sb_publishable_fixture',apiUrl},async(input,init)=>{if(new URL(String(input)).origin!==projectUrl)return fetch(input,init);const token=await new SignJWT({sub:'owner',iss:projectUrl+'/auth/v1',aud:'authenticated',exp:Math.floor(Date.now()/1000)+300}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(keys.privateKey);return Response.json({access_token:token,refresh_token:'fixture-refresh',token_type:'bearer',user:{id:'owner'}});});auths.push(auth);await auth.login('fixture@example.invalid','fixture-password');const connection=new PrivateWorkspaceConnection(auth,{apiUrl,clientId:newId()},async(input,init)=>{const reply=await fetch(input,init);if(String(input).endsWith('/pages/metadata/pull')){const value=await reply.clone().json();pulls.push({url:String(input),request:JSON.parse(String(init?.body)),reply:value,authorization:new Headers(init?.headers).get('authorization'),...(init?.credentials?{credentials:init.credentials}:{}),...(init?.redirect?{redirect:init.redirect}:{}),...(init?.cache?{cache:init.cache}:{})});if(faults.lostPull){faults.lostPull=false;throw Error('fixture lost pull response');}}return reply;});connections.push(connection);await connection.bootstrap();const registry=new WorkspaceRegistryDevice(join(directory,name));registries.push(registry);const store=await NativeWorkspaceStore.open(connection,registry.invoke);stores.push(store);return{auth,connection,registry,store,pulls,faults};};
  const open=async(peer:Awaited<ReturnType<typeof client>>,store=peer.store)=>{const runtime=await PrivateChangesSession.open(peer.connection,store);runtimes.push(runtime);return runtime;};
  const one=await client('one'),two=await client('two'),id=newId(),page=one.store.page(id);await page.create('base',emptyPageUpdate());await one.connection.openPage(id,page).push((await page.prepare())!);const leftRuntime=await open(one),firstRight=await open(two);expect(one.pulls).toHaveLength(0);expect(two.pulls).toHaveLength(0);await leftRuntime.sync();await firstRight.sync();expect(await two.store.hasPage(id)).toBe(false);expect(firstRight.snapshot.data?.pages[0]?.metadata.title).toBe('base');
  await firstRight.close();await two.store.close();await two.registry.close('SIGKILL');const rightStore=await NativeWorkspaceStore.open(two.connection,two.registry.invoke);stores.push(rightStore);const rightRuntime=await open(two,rightStore);expect(rightRuntime.snapshot).toMatchObject({readComplete:false,data:{order:'1',pages:[{metadata:{title:'base'}}]}});await two.connection.openPage(id,rightStore.page(id)).pull({protocolVersion:1,clientId:two.connection.context!.clientId,editorSchemaVersion:1,stateVector:'AA'});
  const left=one.store.title(id),right=rightStore.title(id),body=(await rightStore.page(id).load()).page.updates;expect(await right.load()).toMatchObject({base:{version:0},localTitle:'base'});await left.enqueue({operationId:newId(),title:'left offline'});await right.enqueue({operationId:newId(),title:'right offline'});const wire=await right.prepare();await one.connection.openTitle(id,left).push((await left.prepare())!);await rightRuntime.sync();expect(await right.load()).toMatchObject({localTitle:'right offline',pending:1,base:{version:1}});expect(await right.prepare()).toEqual(wire);
  const conflict=await two.connection.openTitle(id,right).push(wire!);if(conflict.result.status!=='conflict')throw Error('Conflict required');const record=conflict.result.conflict;await leftRuntime.sync();expect((await left.load()).conflicts[0]?.record).toEqual(record);const resolutionId=newId();await right.enqueue({operationId:resolutionId,title:record.remote,resolution:{conflictId:record.id,choice:'remote'}});const resolved=await two.connection.openTitle(id,right).push((await right.prepare())!);expect(resolved.version).toBe(1);await leftRuntime.sync();expect((await left.load()).conflicts[0]?.resolvedBy).toBe(resolutionId);expect((await rightStore.page(id).load()).page.updates).toEqual(body);
  const secondId=newId(),second=one.store.page(secondId);await second.create('metadata only',emptyPageUpdate());await one.connection.openPage(secondId,second).push((await second.prepare())!);two.faults.lostPull=true;const before=(await rightStore.changesLoad()).order;await expect(rightRuntime.sync()).rejects.toMatchObject({stage:'transport'});expect((await rightStore.changesLoad()).order).toBe(before);expect(rightRuntime.snapshot.retryReceive).toBe(false);await rightRuntime.sync();expect(await rightStore.hasPage(secondId)).toBe(false);expect(rightRuntime.snapshot.data?.pages.some(row=>row.metadata.id===secondId)).toBe(true);
  // A deleted resource's later event is filtered, while the saved raw order
  // advances. Cached metadata is retained; this is not tombstone replication.
  await leftRuntime.sync();const secondTitle=one.store.title(secondId);await secondTitle.enqueue({operationId:newId(),title:'hidden later'});await one.connection.openTitle(secondId,secondTitle).push((await secondTitle.prepare())!);await pool.query(`UPDATE "${schema}".private_resources SET deleted=true WHERE id=$1`,[secondId]);await rightRuntime.sync();expect(two.pulls.at(-1)?.reply.events).toEqual([]);expect(rightRuntime.snapshot).toMatchObject({readComplete:true,data:{order:'6'}});expect(rightRuntime.snapshot.data?.pages.find(row=>row.metadata.id===secondId)?.metadata.title).toBe('metadata only');
  expect(two.pulls[0]).toMatchObject({url:apiUrl+'/v1/workspaces/'+two.connection.context!.workspaceId+'/pages/metadata/pull',credentials:'omit',redirect:'error',cache:'no-store'});expect(two.pulls[0]?.authorization?.startsWith('Bearer ')).toBe(true);
  await right.enqueue({operationId:newId(),title:'keep after revocation'});const pending=await right.prepare(),savedContext={...two.connection.context!};await pool.query(`UPDATE "${schema}".private_devices SET revoked=true WHERE id=$1`,[savedContext.clientId]);await expect(rightRuntime.sync()).rejects.toMatchObject({stage:'closed'});expect(rightRuntime.snapshot).toMatchObject({phase:'closed',data:null,retryReceive:false});const raw=await two.registry.request('open',{context:savedContext}),saved=await two.registry.request('execute',{handle:raw.handle,request:{command:'title_load',pageId:id,afterOperation:null,afterConflict:null,limit:100}});expect(saved.pending).toBe(1);expect(saved.operations.at(-1).wire).toBe(pending!.wire);await two.registry.request('close',{handle:raw.handle});expect((await pool.query(`SELECT count(*)::int AS n FROM "${schema}".private_page_updates`)).rows[0].n).toBe(2);
 }finally{for(const runtime of runtimes)await runtime.close();for(const store of stores)await store.close().catch(()=>{});for(const connection of connections)connection.close();for(const auth of auths)auth.close();for(const registry of registries)await registry.close();try{await app?.close();await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();rmSync(directory,{recursive:true,force:true});}}
});
