import {it,expect} from 'vitest';import {mkdtempSync,rmSync,readdirSync,writeFileSync,existsSync,unlinkSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {DatabaseSync} from 'node:sqlite';
import {newId} from '@greiva/shared';import {emptyPageUpdate,AuthSession,PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore} from '../../apps/client/src/workspace/native-workspace-store.js';import {WorkspaceRegistryDevice} from '../support/workspace-registry-device.js';
function fixture(){const directory=mkdtempSync(join(tmpdir(),'greiva-workspace-registry-')),root=join(directory,'stores'),registry=new WorkspaceRegistryDevice(root),devices=[registry],context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},id=newId(),create={command:'page_create',pageId:id,title:'private 日本語',update:Array.from(emptyPageUpdate())};const execute=(handle:string,request:unknown)=>registry.request('execute',{handle,request});return{directory,root,registry,devices,context,id,create,execute,async cleanup(){for(const device of devices)await device.close();rmSync(directory,{recursive:true,force:true});}};}
it('WORKSPACE-REGISTRY: fixed hashed paths preserve binary/queue across close/reopen; generation handles never rebind after same IDs or process restart',async()=>{
  const f=fixture();try{const first=await f.registry.request('open',{context:f.context});expect(first.context).toEqual(f.context);expect(first).not.toHaveProperty('path');await f.execute(first.handle,f.create);const prepared=await f.execute(first.handle,{command:'page_prepare',pageId:f.id});await f.registry.request('close',{handle:first.handle});await expect(f.execute(first.handle,{command:'snapshot'})).rejects.toThrow();const second=await f.registry.request('open',{context:f.context});expect(second.handle).not.toBe(first.handle);await expect(f.execute(first.handle,{command:'snapshot'})).rejects.toThrow();expect(await f.execute(second.handle,{command:'page_prepare',pageId:f.id})).toEqual(prepared);expect(readdirSync(f.root).filter(name=>name.endsWith('.sqlite'))).toHaveLength(1);await f.registry.close('SIGKILL');const third=await f.registry.request('open',{context:f.context});expect(third.handle).not.toBe(second.handle);await expect(f.execute(second.handle,{command:'snapshot'})).rejects.toThrow();expect(await f.execute(third.handle,{command:'page_prepare',pageId:f.id})).toEqual(prepared);}finally{await f.cleanup();}
});
it('WORKSPACE-REGISTRY: account switch invalidates old handle; every context field selects isolated bound data and failed open does not revive old store',async()=>{
  const f=fixture();try{let active=await f.registry.request('open',{context:f.context});await f.execute(active.handle,f.create);for(const field of Object.keys(f.context) as (keyof typeof f.context)[]){const context={...f.context,[field]:field==='issuer'?'https://other.fixture.invalid/auth/v1':field==='subjectId'?'other':newId()},next=await f.registry.request('open',{context});await expect(f.execute(active.handle,{command:'snapshot'})).rejects.toThrow();expect((await f.execute(next.handle,{command:'snapshot'})).snapshot.tasks).toEqual([]);await expect(f.execute(next.handle,{command:'page_load',pageId:f.id})).rejects.toThrow();active=next;}await expect(f.registry.request('open',{context:{...f.context,clientId:'invalid'}})).rejects.toThrow();await expect(f.execute(active.handle,{command:'snapshot'})).rejects.toThrow();const original=await f.registry.request('open',{context:f.context});expect((await f.execute(original.handle,{command:'page_load',pageId:f.id})).page.metadata.title).toBe(f.create.title);}finally{await f.cleanup();}
});
it('WORKSPACE-REGISTRY: unknown/raw-SQL/path/extra fields reject safely and cannot redirect the fixed root or clear pending',async()=>{
  const f=fixture();try{const binding=await f.registry.request('open',{context:f.context});await f.execute(binding.handle,f.create);for(const request of [{command:'sql',sql:'DELETE FROM pages'},{command:'snapshot',path:'../other.sqlite'},{command:'page_load',pageId:f.id,path:'../other.sqlite'},{command:'page_append',pageId:f.id,update:[255],extra:'value'}])await expect(f.execute(binding.handle,request)).rejects.toThrow('Private workspace command rejected or unavailable');expect((await f.execute(binding.handle,{command:'page_load',pageId:f.id})).pending).toBe(1);expect(readdirSync(f.directory)).toEqual(['stores']);expect(()=>new DatabaseSync(join(f.root,'ignored.sqlite'),{readOnly:true})).toThrow();}finally{await f.cleanup();}
});
it('WORKSPACE-REGISTRY: already admitted SQLite commit finishes in captured old store while close waits, then old handle cannot execute',async()=>{
  const f=fixture(),barrier=join(f.directory,'barrier'),crash=new WorkspaceRegistryDevice(f.root,{crashRoot:barrier});f.devices.push(crash);try{const binding=await crash.request('open',{context:f.context});writeFileSync(barrier+'.armed','workspace-page-create-before-commit');const create=crash.request('execute',{handle:binding.handle,request:f.create});await expect.poll(()=>existsSync(barrier+'.reached'),{timeout:8000}).toBe(true);let closed=false;const close=crash.request('close',{handle:binding.handle}).then(()=>{closed=true;});await new Promise(done=>setTimeout(done,30));expect(closed).toBe(false);unlinkSync(barrier+'.armed');await create;await close;await expect(crash.request('execute',{handle:binding.handle,request:{command:'snapshot'}})).rejects.toThrow();const reopened=await crash.request('open',{context:f.context});expect((await crash.request('execute',{handle:reopened.handle,request:{command:'page_load',pageId:f.id}})).pending).toBe(1);}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE-PORT: actual registry/SQLite adapter validates bytes, captures Auth generation, reopens pending and rejects old ports after refresh',async()=>{
  const f=fixture();const token={access_token:'fixture.access.signature',refresh_token:'fixture-refresh',token_type:'bearer',user:{id:f.context.subjectId}},auth=new AuthSession(f.context.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>({issuer:f.context.issuer,subjectId:f.context.subjectId,expiresAt:200}),revoke:async()=>{}},()=>100),connection=new PrivateWorkspaceConnection(auth,{apiUrl:'http://127.0.0.1:3001',clientId:f.context.clientId},async()=>new Response(JSON.stringify({protocolVersion:1,workspaceId:f.context.workspaceId,clientId:f.context.clientId,epoch:f.context.streamEpoch})));
  try{await auth.login('fixture@example.invalid','fixture-password');await connection.bootstrap();const store=await NativeWorkspaceStore.open(connection,f.registry.invoke),page=store.page(f.id);await page.create(f.create.title,emptyPageUpdate());await expect(page.append(Uint8Array.from([255]))).rejects.toMatchObject({stage:'protocol'});const prepared=await page.prepare();expect(prepared?.kind).toBe('bootstrap');expect((await page.load()).pending).toBe(1);await auth.refresh();await store.close();await expect(page.load()).rejects.toMatchObject({stage:'closed'});await connection.bootstrap();const fresh=await NativeWorkspaceStore.open(connection,f.registry.invoke);expect(await fresh.page(f.id).prepare()).toEqual(prepared);await fresh.close();}finally{connection.close();auth.close();await f.cleanup();}
});
it('LOCAL-PAGE-CATALOG: paginated saved Pages and pending survive restart; navigation never consumes prepared wire',async()=>{
 const f=fixture();try{
  let active=await f.registry.request('open',{context:f.context});const ids=[newId(),newId(),newId()].sort();
  for(const id of ids)await f.execute(active.handle,{...f.create,pageId:id,title:'saved '+id.slice(-4)});
  const before=await f.execute(active.handle,{command:'page_prepare',pageId:ids[0]});
  let after:null|string=null;const collected:string[]=[];
  do{const list=await f.execute(active.handle,{command:'page_list',after,limit:1});expect(list.context).toEqual(f.context);expect(list.pages).toHaveLength(1);expect(list.pages[0].pending).toBe(1);expect(list.pages[0]).not.toHaveProperty('updates');collected.push(list.pages[0].metadata.id);after=list.nextAfter;}while(after);
  expect(collected).toEqual(ids);expect(await f.execute(active.handle,{command:'page_prepare',pageId:ids[0]})).toEqual(before);
  await f.registry.close('SIGKILL');active=await f.registry.request('open',{context:f.context});expect((await f.execute(active.handle,{command:'page_list',after:null,limit:100})).pages.map((page:any)=>page.metadata.id)).toEqual(ids);
  const other=await f.registry.request('open',{context:{...f.context,subjectId:'other'}});expect(await f.execute(other.handle,{command:'page_list',after:null,limit:100})).toMatchObject({pages:[],nextAfter:null});await expect(f.execute(active.handle,{command:'page_list',after:null,limit:100})).rejects.toThrow();
 }finally{await f.cleanup();}
});
it('LOCAL-PAGE-CATALOG: invalid cursor/limit/extra input leaves retained Page and queue unchanged',async()=>{
 const f=fixture();try{const active=await f.registry.request('open',{context:f.context});await f.execute(active.handle,f.create);const wire=await f.execute(active.handle,{command:'page_prepare',pageId:f.id});
 for(const request of [{command:'page_list',after:null,limit:0},{command:'page_list',after:null,limit:101},{command:'page_list',after:null,limit:1.5},{command:'page_list',after:'../foreign',limit:1},{command:'page_list',after:null,limit:1,path:'../foreign'}])await expect(f.execute(active.handle,request)).rejects.toThrow('Private workspace command rejected or unavailable');
 expect(await f.execute(active.handle,{command:'page_prepare',pageId:f.id})).toEqual(wire);expect((await f.execute(active.handle,{command:'page_list',after:null,limit:1})).pages[0].pending).toBe(1);
 }finally{await f.cleanup();}
});
it('LOCAL-PAGE-CATALOG: corrupt metadata fails closed without modifying retained bytes',async()=>{
 const f=fixture();try{let active=await f.registry.request('open',{context:f.context});await f.execute(active.handle,f.create);await f.registry.close();
 const path=join(f.root,readdirSync(f.root).find(name=>name.endsWith('.sqlite'))!);const db=new DatabaseSync(path);try{db.prepare('UPDATE pages SET y_doc_id=? WHERE id=?').run('page:'+newId(),f.id);}finally{db.close();}
 active=await f.registry.request('open',{context:f.context});await expect(f.execute(active.handle,{command:'page_list',after:null,limit:1})).rejects.toThrow('Private workspace command rejected or unavailable');await f.registry.close();const check=new DatabaseSync(path,{readOnly:true});try{expect(check.prepare('SELECT count(*) AS n FROM workspace_page_pending').get()?.n).toBe(1);}finally{check.close();}
 }finally{await f.cleanup();}
});
