import {newId} from '@greiva/shared';
import type {Page} from '@greiva/protocol';
import type {PrivatePageTitleLocalResponse,PrivatePageTitleIntent,PrivatePageRenameResponse,PrivatePageTitleConflict,PrivatePageRenameRequest} from '@greiva/protocol/private-page-metadata';
import type {WorkspaceSyncContext} from '@greiva/sync';
type Operation=PrivatePageTitleLocalResponse['operations'][number];
const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
// UI double; actual Rust/PG durability and authentication use separate tests.
export function privateTitleFixture(context:WorkspaceSyncContext,ports:{local:(id:string)=>Page|undefined;server:(id:string)=>Page|undefined;project:(id:string,title:string)=>void;remote:(id:string,title:string)=>void;bootstrapPending:(id:string)=>boolean}){
 const local=new Map<string,{base:PrivatePageTitleLocalResponse['base'];operations:Operation[];conflicts:PrivatePageTitleLocalResponse['conflicts']}>(),server=new Map<string,{version:number;history:string[];conflicts:(PrivatePageTitleConflict&{resolvedBy:string|null})[];ledger:Map<string,PrivatePageRenameResponse>}>();let sequence=0;
 const state={storageFailure:false,loseMutation:false,loseAck:false,reject:false,sent:[] as string[],reads:[] as unknown[]};
 const saved=(id:string)=>{if(!local.has(id))local.set(id,{base:null,operations:[],conflicts:[]});return local.get(id)!;};
 const remote=(id:string)=>{if(!server.has(id))server.set(id,{version:0,history:[ports.server(id)!.title],conflicts:[],ledger:new Map()});return server.get(id)!;};
 const scope=(id:string)=>({protocolVersion:1 as const,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,pageId:id});
 function project(id:string){const entry=saved(id),pending=entry.operations.filter(row=>row.response===null),title=pending.at(-1)?.intent.title??entry.base?.metadata.title;if(title!==undefined)ports.project(id,title);}
 function receive(id:string,response:{metadata:Page;version:number;conflicts?:PrivatePageTitleConflict[]}){const entry=saved(id);if(entry.base===null||response.version>=entry.base.version)entry.base={metadata:clone(response.metadata),version:response.version};for(const record of response.conflicts??[])if(!entry.conflicts.some(row=>row.record.id===record.id))entry.conflicts.push({record:clone(record),resolvedBy:null});entry.conflicts.sort((a,b)=>a.record.id.localeCompare(b.record.id));project(id);}
 function execute(kind:string,id:string,request:Record<string,unknown>){const entry=saved(id),metadata=ports.local(id);if(!metadata)throw Error('Missing title Page');
  if(kind==='title_load'){const limit=Number(request.limit),ops=entry.operations.filter(row=>request.afterOperation===null||BigInt(row.sequence)>BigInt(String(request.afterOperation))),cfs=entry.conflicts.filter(row=>request.afterConflict===null||row.record.id>String(request.afterConflict));return clone({context,pageId:id,base:entry.base,localTitle:metadata.title,pending:entry.operations.filter(row=>row.response===null).length,operations:ops.slice(0,limit),nextOperation:ops.length>limit?ops[limit-1]!.sequence:null,conflicts:cfs.slice(0,limit),nextConflict:cfs.length>limit?cfs[limit-1]!.record.id:null});}
  if(kind==='title_enqueue'){if(state.storageFailure)throw Error('fixture-private-title storage');const intent=request.intent as PrivatePageTitleIntent,old=entry.operations.find(row=>row.intent.operationId===intent.operationId);if(old){if(JSON.stringify(old.intent)!==JSON.stringify(intent))throw Error('Nonce reused');return null;}if(!entry.base||ports.bootstrapPending(id))throw Error('Unknown base/bootstrap');const prior=entry.operations.filter(row=>row.response===null).at(-1);if(intent.resolution&&prior)throw Error('Unsettled resolution');entry.operations.push({sequence:String(++sequence),intent:clone(intent),baseVersion:prior?.baseVersion??entry.base.version,baseTitle:prior?.baseTitle??entry.base.metadata.title,predecessor:prior?.intent.operationId??null,wire:null,response:null});project(id);if(state.loseMutation){state.loseMutation=false;throw Error('fixture-private-title lost mutation reply');}return null;}
  if(kind==='title_prepare'){const row=entry.operations.find(row=>row.response===null);if(!row)return null;if(row.wire===null){const prior=entry.operations.find(value=>value.intent.operationId===row.predecessor),own=prior?.response?.result.status==='applied'&&prior.response.metadata.title===prior.intent.title;row.wire=JSON.stringify({protocolVersion:1,clientId:context.clientId,operationId:row.intent.operationId,baseVersion:own?prior!.response!.version:row.baseVersion,title:row.intent.title,...(row.intent.resolution?{resolution:row.intent.resolution}:{})});}return{pageId:id,sequence:row.sequence,operationId:row.intent.operationId,wire:row.wire};}
  if(kind==='title_ack'){const row=entry.operations.find(row=>row.sequence===request.sequence)!;if(row.wire!==request.wire)throw Error('Bad wire');const response=request.response as PrivatePageRenameResponse;if(row.response!==null)return null;row.response=clone(response);if(response.result.status==='conflict')receive(id,{...response,conflicts:[response.result.conflict]});else receive(id,response);if(response.result.status==='applied'&&row.intent.resolution){const cf=entry.conflicts.find(cf=>cf.record.id===row.intent.resolution!.conflictId);if(cf)cf.resolvedBy=row.intent.operationId;}return null;}
  if(kind==='title_receive'){receive(id,request.response as {metadata:Page;version:number;conflicts:PrivatePageTitleConflict[]});return null;}
  throw Error('Unexpected title command');
 }
 function fetch(id:string,kind:string,body:Record<string,unknown>,wire:string){if(!ports.server(id))return Response.json({error:'missing'},{status:403});const entry=remote(id);
  if(kind==='read'){state.reads.push(clone(body));const rows=entry.conflicts.filter(row=>row.resolvedBy===null&&(body.afterConflict===null||row.id>String(body.afterConflict))),limit=Number(body.limit),records=rows.slice(0,limit).map(({resolvedBy:_,...record})=>record);return Response.json({...scope(id),metadata:ports.server(id),version:entry.version,conflicts:records,nextAfter:rows.length>limit?records.at(-1)!.id:null});}
  state.sent.push(wire);const request=body as unknown as PrivatePageRenameRequest;let response=entry.ledger.get(request.operationId);if(!response){let result:PrivatePageRenameResponse['result']={status:'applied'};const base=entry.history[request.baseVersion],title=ports.server(id)!.title;
   if(base===undefined)result={status:'rejected',code:'base_unknown'};
   else if(state.reject){state.reject=false;result={status:'rejected',code:request.resolution?'resolution_stale':'base_unknown'};}
   else if(request.resolution){const cf=entry.conflicts.find(row=>row.id===request.resolution!.conflictId);if(!cf||cf.resolvedBy||cf[request.resolution.choice]!==request.title)result={status:'rejected',code:'resolution_invalid'};else if(request.baseVersion!==entry.version)result={status:'rejected',code:'resolution_stale'};else cf.resolvedBy=request.operationId;}
   else if(base!==title&&request.title!==base&&request.title!==title){const cf={id:newId(),operationId:request.operationId,baseVersion:request.baseVersion,remoteVersion:entry.version,base,local:request.title,remote:title};entry.conflicts.push({...cf,resolvedBy:null});result={status:'conflict',conflict:cf};}
   if(result.status==='applied'&&request.title!==title&&(request.resolution||request.title!==base)){++entry.version;entry.history.push(request.title);ports.remote(id,request.title);}
   response={...scope(id),metadata:clone(ports.server(id)!),version:entry.version,operationId:request.operationId,result};entry.ledger.set(request.operationId,response);
  }if(state.loseAck){state.loseAck=false;return Response.json({error:'fixture-private-title response lost'},{status:503});}return Response.json(response);
 }
 function remoteEdit(id:string,title:string){const entry=remote(id);++entry.version;entry.history.push(title);ports.remote(id,title);}
 function seedCandidates(id:string,count:number){remoteEdit(id,'remote');const entry=remote(id);for(let n=0;n<count;++n)entry.conflicts.push({id:newId(),operationId:newId(),baseVersion:0,remoteVersion:entry.version,base:entry.history[0]!,local:'candidate '+n,remote:'remote',resolvedBy:null});entry.conflicts.sort((a,b)=>a.id.localeCompare(b.id));}
 return{state,execute,fetch,remoteEdit,seedCandidates,managed:(id:string)=>Boolean(local.get(id)?.base||local.get(id)?.operations.length),snapshot:(id:string)=>clone(local.get(id)??null)};
}
