import {readFileSync,writeFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const version='0.6.17';const paths=['package.json',...['apps','packages'].flatMap(d=>readdirSync(d).map(n=>`${d}/${n}/package.json`))];const owners=new Set(paths.map(p=>JSON.parse(readFileSync(p,'utf8')).name));const lock=JSON.parse(readFileSync('package-lock.json','utf8'));const externalBefore=Object.fromEntries(Object.entries(lock.packages).filter(([p,v])=>p.startsWith('node_modules/')&&!v.link));
for(const path of paths){const pkg=JSON.parse(readFileSync(path,'utf8'));pkg.version=version;for(const section of ['dependencies','devDependencies','peerDependencies','optionalDependencies'])for(const name of Object.keys(pkg[section]??{}))if(owners.has(name))pkg[section][name]=version;writeFileSync(path,JSON.stringify(pkg,null,2)+'\n');}
lock.version=version;for(const [path,pkg] of Object.entries(lock.packages)){if(path===''||paths.includes(path+'/package.json')){pkg.version=version;for(const section of ['dependencies','devDependencies','peerDependencies','optionalDependencies'])for(const name of Object.keys(pkg[section]??{}))if(owners.has(name))pkg[section][name]=version;}}
assert.deepEqual(Object.fromEntries(Object.entries(lock.packages).filter(([p,v])=>p.startsWith('node_modules/')&&!v.link)),externalBefore);writeFileSync('package-lock.json',JSON.stringify(lock,null,2)+'\n');
const cargoPaths=['apps/client/src-tauri/Cargo.toml','apps/client/src-tauri/crates/page-store/Cargo.toml'];for(const path of cargoPaths){const text=readFileSync(path,'utf8');assert.match(text,/^version = "0\.6\.11"$/m);writeFileSync(path,text.replace(/^(version = )"0\.6\.11"/m,`$1"${version}"`));}
const cargoLockPath='apps/client/src-tauri/Cargo.lock',before=readFileSync(cargoLockPath,'utf8');const blocks=before.split('[[package]]');const after=blocks.map(block=>/^\s*name = "greiva-(?:poc|page-store)"/m.test(block)?block.replace(/^(version = )"0\.6\.11"/m,`$1"${version}"`):block).join('[[package]]');assert.deepEqual(after.split('[[package]]').filter(b=>!/^\s*name = "greiva-(?:poc|page-store)"/m.test(b)),blocks.filter(b=>!/^\s*name = "greiva-(?:poc|page-store)"/m.test(b)));writeFileSync(cargoLockPath,after);
const configPath='apps/client/src-tauri/tauri.conf.json',config=JSON.parse(readFileSync(configPath,'utf8'));config.version=version;assert.equal(config.app.windows[0].dragDropEnabled,false);writeFileSync(configPath,JSON.stringify(config,null,2)+'\n');writeFileSync('VERSION',version+'\n');
writeFileSync('/tmp/drag-version-files.json',JSON.stringify([...paths,'package-lock.json',...cargoPaths,cargoLockPath,configPath,'VERSION']));console.log(JSON.stringify({version,externalNpmEntriesUnchanged:Object.keys(externalBefore).length,externalCargoBlocksUnchanged:true,ownerNames:[...owners]}));
