use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,id as valid_id,source_value};
use super::private_database_record::{hash,cell,snapshot};
use serde_json::{json,Value};
use sqlx::{Row,Sqlite,Transaction,sqlite::SqliteRow};
const COLUMNS:&str="seq,operation_id,source_id,record_id,page_id,definition,intent,intent_hash,wire,wire_hash,response";
const WIRE_BYTES:usize=8*1024*1024;
pub(super) fn id(value:&str)->StoreResult<()> {valid_id(value)?;if value!=value.to_ascii_lowercase(){return Err("Canonical Record create ID required".into());}Ok(())}
fn sequence(raw:&str)->StoreResult<i64>{let value=raw.parse::<i64>().map_err(|_|"Invalid Record sequence")?;if value<1||value.to_string()!=raw{return Err("Invalid Record sequence".into());}Ok(value)}
pub(super) fn validate_source(c:&WorkspaceContext,source:&Value)->StoreResult<()> {source_value(c,source,text(source,"id")?)?;id(text(source,"id")?)?;id(text(source,"workspaceId")?)?;for property in source["properties"].as_array().unwrap(){id(text(property,"id")?)?;if property["type"]=="select"{for option in property["options"].as_array().unwrap(){id(text(option,"id")?)?;}}}Ok(())}
fn intent(c:&WorkspaceContext,source:&Value,value:&Value)->StoreResult<()> {validate_source(c,source)?;exact(value,&["kind","sourceId","schemaVersion","recordId","pageId","baseVersion","values"])?;if value["kind"]!="create"||!value["baseVersion"].is_null()||value["sourceId"]!=source["id"]||value["schemaVersion"]!=source["schemaVersion"]{return Err("Record create Source mismatch".into());}id(text(value,"recordId")?)?;id(text(value,"pageId")?)?;for(key,v)in value["values"].as_object().ok_or("Missing Record values")?{id(key)?;let property=source["properties"].as_array().unwrap().iter().find(|p|p["id"]==*key&&p["type"]!="name").ok_or("Unknown or Page Name property")?;cell(property,v)?;}Ok(())}
struct Operation{sequence:i64,operation_id:String,source:Value,intent:Value,wire:Option<String>,response:Option<Value>}
fn request(c:&WorkspaceContext,row:&Operation)->Value{json!({"protocolVersion":1,"clientId":c.client_id,"operationId":row.operation_id,"intent":row.intent})}
fn reply(c:&WorkspaceContext,row:&Operation,value:&Value)->StoreResult<()> {exact(value,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","operationId","record","result"])?;exact(&value["result"],&["status"])?;if value["protocolVersion"]!=1||value["workspaceId"]!=c.workspace_id||value["workspaceEpoch"]!=c.stream_epoch||value["clientId"]!=c.client_id||value["sourceId"]!=row.source["id"]||value["schemaVersion"]!=row.source["schemaVersion"]||value["operationId"]!=row.operation_id||value["result"]["status"]!="applied"||value["record"]["pageId"]!=row.intent["pageId"]||value["record"]["version"]!=1||value["record"]["values"]!=row.intent["values"]{return Err("Record create ACK mismatch".into());}snapshot(c,&row.source,text(&row.intent,"recordId")?,&value["record"])?;Ok(())}
fn operation(c:&WorkspaceContext,row:&SqliteRow)->StoreResult<Operation>{let seq=row.get::<i64,_>("seq");if seq<1{return Err("Invalid Record sequence".into());}let op=row.get::<String,_>("operation_id");id(&op)?;let source:Value=serde_json::from_str(&row.get::<String,_>("definition")).map_err(|_|"Corrupt Record Source")?;let value:Value=serde_json::from_str(&row.get::<String,_>("intent")).map_err(|_|"Corrupt Record intent")?;intent(c,&source,&value)?;if source["id"]!=row.get::<String,_>("source_id")||value["recordId"]!=row.get::<String,_>("record_id")||value["pageId"]!=row.get::<String,_>("page_id")||row.get::<String,_>("intent_hash")!=hash(&json!({"context":c,"operationId":op,"source":source,"intent":value})){return Err("Record intent/index checksum mismatch".into());}let raw=row.get::<Option<String>,_>("wire");let digest=row.get::<Option<String>,_>("wire_hash");let response=row.get::<Option<String>,_>("response").map(|raw|serde_json::from_str::<Value>(&raw).map_err(|_|"Corrupt Record ACK".to_string())).transpose()?;let value=Operation{sequence:seq,operation_id:op,source,intent:value,wire:raw,response};if let Some(raw)=&value.wire{let parsed:Value=serde_json::from_str(raw).map_err(|_|"Corrupt Record wire")?;if raw.len()>WIRE_BYTES||parsed!=request(c,&value)||digest.as_deref()!=Some(hash(&Value::String(raw.clone())).as_str()){return Err("Record wire checksum/scope mismatch".into());}}else if digest.is_some(){return Err("Record hash without wire".into());}if let Some(response)=&value.response{if value.wire.is_none(){return Err("Record ACK without wire".into());}reply(c,&value,response)?;}Ok(value)}
fn local(row:&Operation)->Value{json!({"sequence":row.sequence.to_string(),"intent":{"operationId":row.operation_id,"source":row.source,"intent":row.intent},"wire":row.wire,"response":row.response})}
pub(super) fn matching(left:&Value,right:&Value)->bool{["id","workspaceId","schemaVersion","properties"].iter().all(|key|left[*key]==right[*key])}
async fn available_source(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value)->StoreResult<bool>{let source_id=text(source,"id")?;if let Some(current)=super::private_database::load(tx,c,source_id).await?{if !matching(&current["source"],source){return Err("Record create schema changed".into());}return Ok(true);}let pending=super::private_database_source_queue::pending_definition(tx,c,source_id).await?.ok_or("Missing bound Record Source")?;if !matching(&pending,source){return Err("Record pending Source changed".into());}Ok(false)}
pub(super) async fn verify_receipt(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record_id:&str,operation_id:&str,response:&Value)->StoreResult<Value>{let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates WHERE operation_id=?")).bind(operation_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if !matching(source,&row.source)||row.intent["recordId"]!=record_id||row.response.as_ref()!=Some(response){return Err("Record cache ACK lacks create proof".into());}Ok(json!({"record":response["record"],"conflicts":[]}))}
async fn observed(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,row:&Operation)->StoreResult<()> {available_source(tx,c,&row.source).await?;if let Some(response)=&row.response{let record_id=text(&row.intent,"recordId")?;let current=super::private_database_record::current(tx,c,&row.source,record_id).await?.ok_or("Missing created Record projection")?;let first=super::private_database_record::historical(tx,c,&row.source,record_id,1).await?.ok_or("Missing created Record history")?;if first!=response["record"]||current["pageId"]!=row.intent["pageId"]{return Err("Record creation differs from cache/history".into());}}Ok(())}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()> {if [0,5,6,7,8,9,10,11,12,13].contains(&old){for sql in ["CREATE TABLE workspace_database_record_creates(seq INTEGER PRIMARY KEY AUTOINCREMENT CHECK(seq>0),operation_id TEXT NOT NULL UNIQUE,source_id TEXT NOT NULL,record_id TEXT NOT NULL UNIQUE,page_id TEXT NOT NULL,definition TEXT NOT NULL CHECK(json_valid(definition)),intent TEXT NOT NULL CHECK(json_valid(intent)),intent_hash TEXT NOT NULL,wire TEXT,wire_hash TEXT,response TEXT CHECK(response IS NULL OR json_valid(response)),UNIQUE(source_id,page_id),CHECK((wire IS NULL)=(wire_hash IS NULL)),CHECK(response IS NULL OR wire IS NOT NULL)) STRICT","PRAGMA user_version=14"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates LIMIT 0")).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())}
impl PageStore{
 pub(super) async fn database_record_create_enqueue(&self,c:&WorkspaceContext,candidate:Value)->StoreResult<()> {exact(&candidate,&["operationId","source","intent"])?;let op=text(&candidate,"operationId")?;id(op)?;intent(c,&candidate["source"],&candidate["intent"])?;let source=&candidate["source"];let value=&candidate["intent"];let source_id=text(source,"id")?;let record_id=text(value,"recordId")?;let page_id=text(value,"pageId")?;if json!({"protocolVersion":1,"clientId":c.client_id,"operationId":op,"intent":value}).to_string().len()>WIRE_BYTES{return Err("Record create wire too large".into());}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let old=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates WHERE operation_id=?")).bind(op).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let row=operation(c,&old)?;if row.source!=*source||row.intent!=*value{return Err("Record create operation ID reused".into());}observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(());}let reused:Option<String>=sqlx::query_scalar("SELECT operation_id FROM workspace_database_record_updates WHERE operation_id=?").bind(op).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if reused.is_some(){return Err("Record operation ID reused across update/create".into());}available_source(&mut tx,c,source).await?;let page:i64=sqlx::query_scalar("SELECT count(*) FROM workspace_page_documents WHERE page_id=?").bind(page_id).fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;if page!=1{return Err("Record create requires a local Page".into());}if super::private_database_record::current(&mut tx,c,source,record_id).await?.is_some(){return Err("Cannot create a confirmed Record".into());}let bound:Option<String>=sqlx::query_scalar("SELECT record_id FROM workspace_database_records WHERE source_id=? AND page_id=?").bind(source_id).bind(page_id).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if bound.is_some(){return Err("Record Page already bound".into());}sqlx::query("INSERT INTO workspace_database_record_creates(operation_id,source_id,record_id,page_id,definition,intent,intent_hash) VALUES(?,?,?,?,?,?,?)").bind(op).bind(source_id).bind(record_id).bind(page_id).bind(source.to_string()).bind(value.to_string()).bind(hash(&json!({"context":c,"operationId":op,"source":source,"intent":value}))).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-record-create-enqueue-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-create-enqueue-after-commit")}
 pub(super) async fn database_record_create_prepare(&self,c:&WorkspaceContext)->StoreResult<Value>{let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates WHERE response IS NULL ORDER BY seq LIMIT 1")).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{tx.commit().await.map_err(|e|e.to_string())?;return Ok(Value::Null);};let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;let blocked=if !available_source(&mut tx,c,&row.source).await?{Some("source")}else if !super::private_page::creation_confirmed(&mut tx,c,text(&row.intent,"pageId")?).await?{Some("page")}else{None};if let Some(reason)=blocked{tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"blocked","sequence":row.sequence.to_string(),"operationId":row.operation_id,"sourceId":row.source["id"],"recordId":row.intent["recordId"],"pageId":row.intent["pageId"],"reason":reason}));}let raw=row.wire.clone().unwrap_or_else(||request(c,&row).to_string());if raw.len()>WIRE_BYTES{return Err("Record create wire too large".into());}sqlx::query("UPDATE workspace_database_record_creates SET wire=?,wire_hash=? WHERE seq=? AND wire IS NULL").bind(&raw).bind(hash(&Value::String(raw.clone()))).bind(row.sequence).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-record-create-prepare-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-create-prepare-after-commit")?;Ok(json!({"sequence":row.sequence.to_string(),"operationId":row.operation_id,"sourceId":row.source["id"],"recordId":row.intent["recordId"],"pageId":row.intent["pageId"],"wire":raw}))}
 pub(super) async fn database_record_create_ack(&self,c:&WorkspaceContext,raw_sequence:&str,wire:&str,response:Value)->StoreResult<()> {let sequence=sequence(raw_sequence)?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates WHERE seq=?")).bind(sequence).fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if row.wire.as_deref()!=Some(wire){return Err("Record ACK differs from immutable wire".into());}reply(c,&row,&response)?;if !available_source(&mut tx,c,&row.source).await?{return Err("Record Source is unconfirmed".into());}if let Some(old)=&row.response{if *old!=response{return Err("Record creation ACK reused".into());}observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(());}if !super::private_page::creation_confirmed(&mut tx,c,text(&row.intent,"pageId")?).await?{return Err("Record Page creation is unconfirmed".into());}sqlx::query("UPDATE workspace_database_record_creates SET response=? WHERE seq=? AND response IS NULL").bind(response.to_string()).bind(sequence).execute(&mut *tx).await.map_err(|e|e.to_string())?;let request=json!({"databaseRecordCreateOperation":row.operation_id});let digest=hash(&json!({"request":request,"response":response}));sqlx::query("INSERT OR IGNORE INTO workspace_database_record_receipts VALUES(?,?,?,?,?)").bind(&digest).bind(text(&row.source,"id")?).bind(text(&row.intent,"recordId")?).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;let observed=verify_receipt(&mut tx,c,&row.source,text(&row.intent,"recordId")?,&row.operation_id,&response).await?;super::private_database_record::save(&mut tx,c,&row.source,text(&row.intent,"recordId")?,&observed,&digest).await?;let confirmed=Operation{response:Some(response),..row};self::observed(&mut tx,c,&confirmed).await?;barrier("workspace-database-record-create-ack-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-create-ack-after-commit")}
 pub(super) async fn database_record_create_queue(&self,c:&WorkspaceContext,after:Option<&str>,limit:usize,pending_only:bool)->StoreResult<Value>{if !(1..=100).contains(&limit){return Err("Invalid Record create limit".into());}let after=after.map(sequence).transpose()?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let rows=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_creates WHERE (?=0 OR response IS NULL) AND (? IS NULL OR seq>?) ORDER BY seq LIMIT ?")).bind(pending_only).bind(after).bind(after).bind((limit+1)as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let more=rows.len()>limit;let mut operations=Vec::new();for row in rows{let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;operations.push(local(&row));}operations.truncate(limit);let next=if more{operations.last().unwrap()["sequence"].clone()}else{Value::Null};let pending:i64=sqlx::query_scalar("SELECT count(*) FROM workspace_database_record_creates WHERE response IS NULL").fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;if pending>9007199254740991{return Err("Record pending count overflow".into());}tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"pending":pending,"operations":operations,"nextAfter":next}))}
}
