use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_page::{metadata,decode,encode};
use super::structured::uuid_v7;
use serde_json::{json,Value};
use sha2::{Digest,Sha256};
use sqlx::{Row,Sqlite,Transaction};
fn exact(v:&Value,keys:&[&str])->StoreResult<()>{let o=v.as_object().ok_or("Expected changes object")?;if o.len()!=keys.len()||keys.iter().any(|k|!o.contains_key(*k)){return Err("Unexpected changes fields".into());}Ok(())}
fn text<'a>(v:&'a Value,k:&str)->StoreResult<&'a str>{v[k].as_str().ok_or("Expected changes text".into())}
fn order(v:&str)->StoreResult<i64>{let n=v.parse::<i64>().map_err(|_|"Invalid changes order")?;if n<0||n.to_string()!=v{return Err("Invalid changes order".into());}Ok(n)}
fn version(v:&Value)->StoreResult<i64>{v["version"].as_i64().filter(|n|(0..=9007199254740991).contains(n)).ok_or("Invalid changes version".into())}
fn id(v:&str)->StoreResult<()>{if !uuid_v7(v){return Err("Invalid changes ID".into());}Ok(())}
fn cursor(value:&str,c:&WorkspaceContext,at:i64)->StoreResult<()>{if value.len()>1024{return Err("Changes cursor too long".into());}let parts:Vec<_>=value.split('.').collect();if parts.len()!=3||parts[0]!="gpm1"||decode(parts[2])?.len()!=32{return Err("Invalid changes cursor envelope".into());}let bytes=decode(parts[1])?;let v:Value=serde_json::from_slice(&bytes).map_err(|_|"Invalid changes cursor payload")?;if v!=json!([c.workspace_id,"page-metadata",c.stream_epoch,at.to_string()])||encode(v.to_string().as_bytes())!=parts[1]{return Err("Changes cursor binding mismatch".into());}Ok(())}
fn event(v:&Value)->StoreResult<()>{exact(v,&["order","pageId","metadata","version","conflict"])?;if order(text(v,"order")?)?==0{return Err("Invalid event zero".into());}let page=text(v,"pageId")?;id(page)?;metadata(&v["metadata"],page)?;let ver=version(v)?;if !v["conflict"].is_null(){let cf=&v["conflict"];exact(cf,&["record","resolvedBy"])?;super::private_title::conflict(&cf["record"])?;if cf["record"]["remoteVersion"].as_i64().ok_or("Invalid conflict version")?>ver{return Err("Conflict newer than event".into());}if !cf["resolvedBy"].is_null(){id(text(cf,"resolvedBy")?)?;}}Ok(())}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()>{
    if [0,5,6,7].contains(&old){for sql in [
        "ALTER TABLE workspace_title_conflicts RENAME TO workspace_title_conflicts_v7",
        "CREATE TABLE workspace_title_conflicts(page_id TEXT NOT NULL REFERENCES workspace_page_documents(page_id),id TEXT NOT NULL,record TEXT NOT NULL CHECK(json_valid(record)),resolved_by TEXT,PRIMARY KEY(page_id,id)) STRICT",
        "INSERT INTO workspace_title_conflicts SELECT page_id,id,record,resolved_by FROM workspace_title_conflicts_v7",
        "DROP TABLE workspace_title_conflicts_v7",
        "CREATE TABLE workspace_metadata_progress(singleton INTEGER PRIMARY KEY CHECK(singleton=1),server_order INTEGER NOT NULL CHECK(server_order>=0),cursor TEXT,head_order INTEGER NOT NULL CHECK(head_order>=server_order),has_more INTEGER NOT NULL CHECK(has_more IN(0,1))) STRICT",
        "INSERT INTO workspace_metadata_progress VALUES(1,0,NULL,0,0)",
        "CREATE TABLE workspace_metadata_events(server_order INTEGER PRIMARY KEY CHECK(server_order>0),event TEXT NOT NULL CHECK(json_valid(event))) STRICT",
        "CREATE TABLE workspace_metadata_receipts(digest TEXT PRIMARY KEY NOT NULL,after_order INTEGER NOT NULL,read_order INTEGER NOT NULL) STRICT",
        "CREATE TABLE workspace_metadata_catalog(page_id TEXT PRIMARY KEY NOT NULL,version INTEGER NOT NULL CHECK(version BETWEEN 0 AND 9007199254740991),last_order INTEGER NOT NULL CHECK(last_order>0),metadata TEXT NOT NULL CHECK(json_valid(metadata))) STRICT",
        "CREATE TABLE workspace_metadata_conflicts(page_id TEXT NOT NULL REFERENCES workspace_metadata_catalog(page_id),id TEXT NOT NULL,record TEXT NOT NULL CHECK(json_valid(record)),resolved_by TEXT,PRIMARY KEY(page_id,id)) STRICT",
        "PRAGMA user_version=8"
    ]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}
    for sql in ["SELECT server_order,cursor,head_order,has_more FROM workspace_metadata_progress LIMIT 0","SELECT server_order,event FROM workspace_metadata_events LIMIT 0","SELECT digest,after_order,read_order FROM workspace_metadata_receipts LIMIT 0","SELECT page_id,version,last_order,metadata FROM workspace_metadata_catalog LIMIT 0","SELECT page_id,id,record,resolved_by FROM workspace_metadata_conflicts LIMIT 0"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}Ok(())
}
async fn apply(tx:&mut Transaction<'_,Sqlite>,v:&Value)->StoreResult<()>{
    event(v)?;let page=text(v,"pageId")?;let ver=version(v)?;let at=order(text(v,"order")?)?;let previous=sqlx::query("SELECT version,last_order,metadata FROM workspace_metadata_catalog WHERE page_id=?").bind(page).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;
    let mut meta=v["metadata"].clone();if let Some(old)=previous{let stored:Value=serde_json::from_str(&old.get::<String,_>("metadata")).map_err(|_|"Corrupt changes metadata")?;metadata(&stored,page)?;let previous_version:i64=old.get("version");if old.get::<i64,_>("last_order")>=at||previous_version>ver||stored["createdAt"]!=meta["createdAt"]||(previous_version==ver&&stored["title"]!=meta["title"]){return Err("Changes metadata regressed".into());}if text(&stored,"updatedAt")?>text(&meta,"updatedAt")?{meta["updatedAt"]=stored["updatedAt"].clone();}}
    sqlx::query("INSERT INTO workspace_metadata_catalog VALUES(?,?,?,?) ON CONFLICT(page_id) DO UPDATE SET version=excluded.version,last_order=excluded.last_order,metadata=excluded.metadata").bind(page).bind(ver).bind(at).bind(meta.to_string()).execute(&mut **tx).await.map_err(|e|e.to_string())?;
    if !v["conflict"].is_null(){let cf=&v["conflict"];let key=text(&cf["record"],"id")?;let resolved=cf["resolvedBy"].as_str();let old=sqlx::query("SELECT record,resolved_by FROM workspace_metadata_conflicts WHERE page_id=? AND id=?").bind(page).bind(key).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let record:Value=serde_json::from_str(&old.get::<String,_>("record")).map_err(|_|"Corrupt changes conflict")?;if record!=cf["record"]||old.get::<Option<String>,_>("resolved_by").as_ref().is_some_and(|prior|resolved.is_some_and(|next|prior!=next)){return Err("Immutable changes conflict changed".into());}}
        sqlx::query("INSERT INTO workspace_metadata_conflicts VALUES(?,?,?,?) ON CONFLICT(page_id,id) DO UPDATE SET resolved_by=coalesce(workspace_metadata_conflicts.resolved_by,excluded.resolved_by)").bind(page).bind(key).bind(cf["record"].to_string()).bind(resolved).execute(&mut **tx).await.map_err(|e|e.to_string())?;
    }super::private_title::receive_change(tx,page,v).await
}
pub(super) async fn adopt(tx:&mut Transaction<'_,Sqlite>,page:&str)->StoreResult<()>{
    let row=sqlx::query("SELECT version,last_order,metadata FROM workspace_metadata_catalog WHERE page_id=?").bind(page).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{return Ok(());};let meta:Value=serde_json::from_str(&row.get::<String,_>("metadata")).map_err(|_|"Corrupt cached metadata")?;metadata(&meta,page)?;let mut value=json!({"order":row.get::<i64,_>("last_order").to_string(),"pageId":page,"metadata":meta,"version":row.get::<i64,_>("version"),"conflict":null});event(&value)?;super::private_title::receive_change(tx,page,&value).await?;
    let mut after=String::new();loop{let rows=sqlx::query("SELECT id,record,resolved_by FROM workspace_metadata_conflicts WHERE page_id=? AND id>? ORDER BY id LIMIT 100").bind(page).bind(&after).fetch_all(&mut **tx).await.map_err(|e|e.to_string())?;if rows.is_empty(){break;}for row in rows{after=row.get("id");let record:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt cached conflict")?;if record["id"]!=after{return Err("Cached conflict identity changed".into());}value["conflict"]=json!({"record":record,"resolvedBy":row.get::<Option<String>,_>("resolved_by")});event(&value)?;super::private_title::receive_change(tx,page,&value).await?;}}Ok(())
}
impl PageStore{
    pub(super) async fn changes_receive(&self,c:&WorkspaceContext,request:Value,response:Value)->StoreResult<()>{
        exact(&request,&["protocolVersion","clientId","cursor","limit"])?;exact(&response,&["protocolVersion","workspaceId","workspaceEpoch","afterOrder","readOrder","headOrder","events","hasMore","cursor"])?;if request["protocolVersion"]!=1||request["clientId"]!=c.client_id||response["protocolVersion"]!=1||response["workspaceId"]!=c.workspace_id||response["workspaceEpoch"]!=c.stream_epoch{return Err("Changes scope mismatch".into());}
        let limit=request["limit"].as_u64().filter(|n|(1..=100).contains(n)).ok_or("Invalid changes limit")? as usize;let after=order(text(&response,"afterOrder")?)?;let read=order(text(&response,"readOrder")?)?;let head=order(text(&response,"headOrder")?)?;let more=response["hasMore"].as_bool().ok_or("Invalid changes continuation")?;
        let target=text(&response,"cursor")?;cursor(target,c,read)?;if request["cursor"].is_null(){if after!=0{return Err("Invalid initial changes order".into());}}else{cursor(text(&request,"cursor")?,c,after)?;}
        if after>read||read>head||(more&&(read<=after||read>=head))||(!more&&read!=head){return Err("Invalid changes progress".into());}let events=response["events"].as_array().filter(|v|v.len()<=limit).ok_or("Invalid changes events")?;let mut prior=after;for item in events{event(item)?;let at=order(text(item,"order")?)?;if at<=prior||at>read{return Err("Invalid changes event order".into());}prior=at;}
        let receipt=format!("{:x}",Sha256::digest(format!("{}\n{}",request,response).as_bytes()));let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;
        let old=sqlx::query("SELECT after_order,read_order FROM workspace_metadata_receipts WHERE digest=?").bind(&receipt).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{if old.get::<i64,_>("after_order")!=after||old.get::<i64,_>("read_order")!=read{return Err("Corrupt changes receipt".into());}return Ok(());}
        let progress=sqlx::query("SELECT server_order,cursor FROM workspace_metadata_progress WHERE singleton=1").fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;if progress.get::<i64,_>("server_order")!=after||progress.get::<Option<String>,_>("cursor")!=request["cursor"].as_str().map(String::from){return Err("Changes receipt base mismatch".into());}
        for item in events{let at=order(text(item,"order")?)?;let old:Option<String>=sqlx::query_scalar("SELECT event FROM workspace_metadata_events WHERE server_order=?").bind(at).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if old.is_some(){return Err("Changes event order reused".into());}sqlx::query("INSERT INTO workspace_metadata_events VALUES(?,?)").bind(at).bind(item.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;apply(&mut tx,item).await?;}
        sqlx::query("UPDATE workspace_metadata_progress SET server_order=?,cursor=?,head_order=?,has_more=? WHERE singleton=1").bind(read).bind(target).bind(head).bind(more).execute(&mut *tx).await.map_err(|e|e.to_string())?;sqlx::query("INSERT INTO workspace_metadata_receipts VALUES(?,?,?)").bind(receipt).bind(after).bind(read).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-changes-receive-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-changes-receive-after-commit")
    }
    pub(super) async fn changes_load(&self,c:&WorkspaceContext,after:Option<&str>,limit:usize)->StoreResult<Value>{
        if !(1..=100).contains(&limit){return Err("Invalid changes load limit".into());}if let Some(after)=after{id(after)?;}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let progress=sqlx::query("SELECT server_order,cursor,head_order,has_more FROM workspace_metadata_progress WHERE singleton=1").fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;let at:i64=progress.get("server_order");let head:i64=progress.get("head_order");let token:Option<String>=progress.get("cursor");let more:bool=progress.get("has_more");if at<0||head<at||(more&&at>=head)||(!more&&at!=head)||token.is_none()&&(at!=0||head!=0||more){return Err("Corrupt changes progress".into());}if let Some(token)=&token{cursor(token,c,at)?;}
        let rows=sqlx::query("SELECT c.page_id,c.version,c.last_order,c.metadata,e.event AS source_event FROM workspace_metadata_catalog c LEFT JOIN workspace_metadata_events e ON e.server_order=c.last_order WHERE (? IS NULL OR c.page_id>?) ORDER BY c.page_id LIMIT ?").bind(after).bind(after).bind((limit+1) as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let has_more=rows.len()>limit;let mut pages=Vec::new();for row in rows{let page:String=row.get("page_id");id(&page)?;let meta:Value=serde_json::from_str(&row.get::<String,_>("metadata")).map_err(|_|"Corrupt catalog metadata")?;metadata(&meta,&page)?;let ver:i64=row.get("version");let last:i64=row.get("last_order");if !(0..=9007199254740991).contains(&ver)||last<1||last>at{return Err("Corrupt catalog progress".into());}let source=row.get::<Option<String>,_>("source_event").ok_or("Missing catalog source event")?;let source:Value=serde_json::from_str(&source).map_err(|_|"Corrupt catalog source event")?;event(&source)?;if source["order"]!=last.to_string()||source["pageId"]!=page||source["version"]!=ver||source["metadata"]["createdAt"]!=meta["createdAt"]||source["metadata"]["title"]!=meta["title"]||text(&source["metadata"],"updatedAt")?>text(&meta,"updatedAt")?{return Err("Catalog projection differs from source".into());}pages.push(json!({"metadata":meta,"version":ver,"lastOrder":last.to_string()}));}pages.truncate(limit);let next=if has_more{pages.last().unwrap()["metadata"]["id"].clone()}else{Value::Null};tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"order":at.to_string(),"cursor":token,"headOrder":head.to_string(),"received":token.is_some(),"hasMore":more,"pages":pages,"nextAfter":next}))
    }
}
