use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,id,version,source_definition};
use serde_json::{json,Value};
use sha2::{Digest,Sha256};
use sqlx::{Row,Sqlite,Transaction};
fn canonical(value:&Value)->Value{match value{Value::Array(items)=>Value::Array(items.iter().map(canonical).collect()),Value::Object(items)=>{let mut keys:Vec<_>=items.keys().collect();keys.sort();let mut out=serde_json::Map::new();for key in keys{out.insert(key.clone(),canonical(&items[key]));}Value::Object(out)},_=>value.clone()}}
fn hash(value:&Value)->String{Sha256::digest(canonical(value).to_string().as_bytes()).iter().map(|b|format!("{b:02x}")).collect()}
fn date(value:&str)->bool{let bytes=value.as_bytes();if bytes.len()!=10||bytes[4]!=b'-'||bytes[7]!=b'-'||bytes.iter().enumerate().any(|(i,b)|i!=4&&i!=7&&!b.is_ascii_digit()){return false;}let Ok(y)=value[..4].parse::<u32>() else{return false;};let Ok(m)=value[5..7].parse::<usize>() else{return false;};let Ok(d)=value[8..].parse::<u32>() else{return false;};if y==0||!(1..=12).contains(&m){return false;}let days=[31,if y%4==0&&(y%100!=0||y%400==0){29}else{28},31,30,31,30,31,31,30,31,30,31];d>0&&d<=days[m-1]}
fn property<'a>(source:&'a Value,key:&str)->StoreResult<&'a Value>{id(key)?;source["properties"].as_array().ok_or("Missing properties")?.iter().find(|p|p["id"]==key&&p["type"]!="name").ok_or("Unknown or Page Name property".into())}
pub(super) fn cell(property:&Value,value:&Value)->StoreResult<()> {if value.is_null(){return Ok(());}let valid=match text(property,"type")?{"text"=>value.as_str().is_some_and(|v|v.chars().count()<=65536),"number"=>value.as_f64().is_some_and(f64::is_finite),"checkbox"=>value.is_boolean(),"date"=>value.as_str().is_some_and(date),"select"=>value.as_str().is_some_and(|v|id(v).is_ok()&&property["options"].as_array().is_some_and(|options|options.iter().any(|o|o["id"]==v))),_=>false};if !valid{return Err("Invalid typed database value".into());}Ok(())}
pub(super) fn snapshot(c:&WorkspaceContext,source:&Value,record_id:&str,record:&Value)->StoreResult<i64>{id(record_id)?;exact(record,&["id","workspaceId","sourceId","pageId","version","values"])?;if record["id"]!=record_id||record["workspaceId"]!=c.workspace_id||record["sourceId"]!=source["id"]{return Err("Record snapshot scope mismatch".into());}id(text(record,"pageId")?)?;let ver=version(&record["version"])?;for (key,value) in record["values"].as_object().ok_or("Expected Record values")?{cell(property(source,key)?,value)?;}Ok(ver)}
fn conflict(c:&WorkspaceContext,source:&Value,record:&Value,value:&Value)->StoreResult<()> {exact(value,&["id","workspaceId","sourceId","schemaVersion","recordId","pageId","propertyId","baseVersion","remoteVersion","base","local","remote","resolvedBy"])?;id(text(value,"id")?)?;if value["workspaceId"]!=c.workspace_id||value["sourceId"]!=source["id"]||value["schemaVersion"]!=source["schemaVersion"]||value["recordId"]!=record["id"]||value["pageId"]!=record["pageId"]||!value["resolvedBy"].is_null(){return Err("Record candidate scope mismatch".into());}let base=version(&value["baseVersion"])?;let remote=version(&value["remoteVersion"])?;if base>=remote||remote>version(&record["version"])?{return Err("Invalid candidate versions".into());}let p=property(source,text(value,"propertyId")?)?;for key in ["base","local","remote"]{let state=&value[key];exact(state,&["present","value"])?;let present=state["present"].as_bool().ok_or("Expected presence")?;if !present&&!state["value"].is_null(){return Err("Missing field has a value".into());}cell(p,&state["value"])?;}if value["local"]["present"]!=true||value["base"]["value"]==value["remote"]["value"]||value["local"]["value"]==value["base"]["value"]||value["local"]["value"]==value["remote"]["value"]{return Err("Invalid Record triad".into());}Ok(())}
fn pair(c:&WorkspaceContext,source:&Value,record_id:&str,request:&Value,reply:&Value)->StoreResult<i64>{exact(request,&["protocolVersion","clientId","pageId","afterConflict","limit"])?;if request["protocolVersion"]!=1||request["clientId"]!=c.client_id{return Err("Record request context mismatch".into());}id(text(request,"pageId")?)?;let limit=request["limit"].as_u64().filter(|n|(1..=20).contains(n)).ok_or("Invalid candidate limit")?;let mut previous=if request["afterConflict"].is_null(){""}else{let v=text(request,"afterConflict")?;id(v)?;v};exact(reply,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","record","conflicts","nextAfter"])?;if reply["protocolVersion"]!=1||reply["workspaceId"]!=c.workspace_id||reply["workspaceEpoch"]!=c.stream_epoch||reply["clientId"]!=c.client_id||reply["sourceId"]!=source["id"]||reply["schemaVersion"]!=source["schemaVersion"]||reply["record"]["pageId"]!=request["pageId"]{return Err("Record response context mismatch".into());}let ver=snapshot(c,source,record_id,&reply["record"])?;let rows=reply["conflicts"].as_array().ok_or("Expected candidates")?;if rows.len()>limit as usize{return Err("Too many candidates".into());}for value in rows{conflict(c,source,&reply["record"],value)?;let next=text(value,"id")?;if next<=previous{return Err("Invalid candidate order".into());}previous=next;}if !reply["nextAfter"].is_null()&&(rows.is_empty()||reply["nextAfter"]!=previous){return Err("Invalid candidate continuation".into());}Ok(ver)}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()> {if [0,5,6,7,8,9].contains(&old){for sql in [
 "CREATE TABLE workspace_database_record_receipts(id TEXT PRIMARY KEY NOT NULL,source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),record_id TEXT NOT NULL,request TEXT NOT NULL CHECK(json_valid(request)),response TEXT NOT NULL CHECK(json_valid(response))) STRICT",
 "CREATE TABLE workspace_database_record_history(record_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1 AND version<=9007199254740991),snapshot TEXT NOT NULL CHECK(json_valid(snapshot)),receipt_id TEXT NOT NULL REFERENCES workspace_database_record_receipts(id),PRIMARY KEY(record_id,version)) STRICT",
 "CREATE TABLE workspace_database_records(record_id TEXT PRIMARY KEY NOT NULL,source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),page_id TEXT NOT NULL,version INTEGER NOT NULL,UNIQUE(source_id,page_id),FOREIGN KEY(record_id,version) REFERENCES workspace_database_record_history(record_id,version)) STRICT",
 "CREATE TABLE workspace_database_record_conflicts(record_id TEXT NOT NULL REFERENCES workspace_database_records(record_id),id TEXT NOT NULL,record TEXT NOT NULL CHECK(json_valid(record)),receipt_id TEXT NOT NULL REFERENCES workspace_database_record_receipts(id),PRIMARY KEY(record_id,id)) STRICT",
 "CREATE INDEX workspace_database_record_candidate_base ON workspace_database_record_conflicts(record_id,json_extract(record,'$.baseVersion'),id)",
 "CREATE INDEX workspace_database_record_candidate_remote ON workspace_database_record_conflicts(record_id,json_extract(record,'$.remoteVersion'),id)",
 "PRAGMA user_version=10"
 ]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}for sql in ["SELECT id,source_id,record_id,request,response FROM workspace_database_record_receipts LIMIT 0","SELECT record_id,version,snapshot,receipt_id FROM workspace_database_record_history LIMIT 0","SELECT record_id,source_id,page_id,version FROM workspace_database_records LIMIT 0","SELECT record_id,id,record,receipt_id FROM workspace_database_record_conflicts LIMIT 0"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}Ok(())}
async fn receipt(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record_id:&str,receipt_id:&str)->StoreResult<Value>{let row=sqlx::query("SELECT source_id,record_id,request,response FROM workspace_database_record_receipts WHERE id=?").bind(receipt_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let request:Value=serde_json::from_str(&row.get::<String,_>("request")).map_err(|_|"Corrupt Record request")?;let response:Value=serde_json::from_str(&row.get::<String,_>("response")).map_err(|_|"Corrupt Record response")?;pair(c,source,record_id,&request,&response)?;if row.get::<String,_>("source_id")!=text(source,"id")?||row.get::<String,_>("record_id")!=record_id||hash(&json!({"request":request,"response":response}))!=receipt_id{return Err("Record receipt provenance mismatch".into());}Ok(response)}
async fn historical(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record_id:&str,ver:i64)->StoreResult<Option<Value>>{let row=sqlx::query("SELECT snapshot,receipt_id FROM workspace_database_record_history WHERE record_id=? AND version=?").bind(record_id).bind(ver).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{return Ok(None);};let value:Value=serde_json::from_str(&row.get::<String,_>("snapshot")).map_err(|_|"Corrupt Record history")?;if snapshot(c,source,record_id,&value)?!=ver||receipt(tx,c,source,record_id,&row.get::<String,_>("receipt_id")).await?["record"]!=value{return Err("Record history differs from receipt".into());}Ok(Some(value))}
async fn current(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record_id:&str)->StoreResult<Option<Value>>{let row=sqlx::query("SELECT source_id,page_id,version,(SELECT max(version) FROM workspace_database_record_history WHERE record_id=r.record_id) AS latest FROM workspace_database_records r WHERE record_id=?").bind(record_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{let existing:Option<i64>=sqlx::query_scalar("SELECT 1 FROM workspace_database_record_history WHERE record_id=? LIMIT 1").bind(record_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;if existing.is_some(){return Err("Missing Record projection".into());}return Ok(None);};let ver=row.get::<i64,_>("version");let record=historical(tx,c,source,record_id,ver).await?.ok_or("Missing Record history")?;if row.get::<String,_>("source_id")!=text(source,"id")?||row.get::<String,_>("page_id")!=text(&record,"pageId")?||row.get::<Option<i64>,_>("latest")!=Some(ver){return Err("Record projection mismatch".into());}Ok(Some(record))}
async fn known_fields(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record:&Value,candidate:&Value)->StoreResult<()> {let record_id=text(record,"id")?;let field=text(candidate,"propertyId")?;for key in ["base","remote"]{let ver=version(&candidate[format!("{key}Version")])?;if let Some(snapshot)=historical(tx,c,source,record_id,ver).await?{let values=snapshot["values"].as_object().ok_or("Invalid history values")?;let observed=json!({"present":values.contains_key(field),"value":values.get(field).unwrap_or(&Value::Null)});if candidate[key]!=observed||snapshot["pageId"]!=record["pageId"]{return Err("Candidate differs from known history".into());}}}Ok(())}
impl PageStore {
 pub(super) async fn database_record_receive(&self,c:&WorkspaceContext,source_id:&str,record_id:&str,request:Value,response:Value)->StoreResult<()> {let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let ver=pair(c,&source,record_id,&request,&response)?;let before=current(&mut tx,c,&source,record_id).await?;if before.as_ref().is_some_and(|record|record["pageId"]!=response["record"]["pageId"]){return Err("Record Page binding changed".into());}let hash=hash(&json!({"request":request,"response":response}));let old:Option<String>=sqlx::query_scalar("SELECT id FROM workspace_database_record_receipts WHERE id=?").bind(&hash).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if old.is_some(){if receipt(&mut tx,c,&source,record_id,&hash).await?!=response{return Err("Record receipt reused".into());}}else{sqlx::query("INSERT INTO workspace_database_record_receipts VALUES(?,?,?,?,?)").bind(&hash).bind(source_id).bind(record_id).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;}
  if let Some(old)=historical(&mut tx,c,&source,record_id,ver).await?{if old!=response["record"]{return Err("Record version reused".into());}}else{sqlx::query("INSERT INTO workspace_database_record_history VALUES(?,?,?,?)").bind(record_id).bind(ver).bind(response["record"].to_string()).bind(&hash).execute(&mut *tx).await.map_err(|e|e.to_string())?;}
  if before.as_ref().is_none_or(|record|record["version"].as_i64().unwrap()<ver){sqlx::query("INSERT INTO workspace_database_records VALUES(?,?,?,?) ON CONFLICT(record_id) DO UPDATE SET version=excluded.version").bind(record_id).bind(source_id).bind(text(&response["record"],"pageId")?).bind(ver).execute(&mut *tx).await.map_err(|e|e.to_string())?;}
  for candidate in response["conflicts"].as_array().unwrap(){known_fields(&mut tx,c,&source,&response["record"],candidate).await?;let old:Option<String>=sqlx::query_scalar("SELECT record FROM workspace_database_record_conflicts WHERE record_id=? AND id=?").bind(record_id).bind(text(candidate,"id")?).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let old:Value=serde_json::from_str(&old).map_err(|_|"Corrupt candidate")?;if old!=*candidate{return Err("Candidate ID reused".into());}}else{sqlx::query("INSERT INTO workspace_database_record_conflicts VALUES(?,?,?,?)").bind(record_id).bind(text(candidate,"id")?).bind(candidate.to_string()).bind(&hash).execute(&mut *tx).await.map_err(|e|e.to_string())?;}}
  // A newly observed older baseline can corroborate or contradict candidates
  // already cached from a seed snapshot. Check affected rows in bounded pages
  // before admitting the new historical observation, without inventing history.
  let projected=if before.as_ref().is_some_and(|record|record["version"].as_i64().unwrap()>ver){before.as_ref().unwrap()}else{&response["record"]};let mut after=String::new();loop{let rows=sqlx::query("SELECT id,record,receipt_id FROM workspace_database_record_conflicts WHERE record_id=? AND (json_extract(record,'$.baseVersion')=? OR json_extract(record,'$.remoteVersion')=?) AND id>? ORDER BY id LIMIT 100").bind(record_id).bind(ver).bind(ver).bind(&after).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;if rows.is_empty(){break;}for row in rows{let candidate:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt known candidate")?;conflict(c,&source,projected,&candidate)?;let saved=receipt(&mut tx,c,&source,record_id,&row.get::<String,_>("receipt_id")).await?;if candidate["id"]!=row.get::<String,_>("id")||!saved["conflicts"].as_array().unwrap().contains(&candidate){return Err("Known candidate provenance mismatch".into());}known_fields(&mut tx,c,&source,projected,&candidate).await?;after=text(&candidate,"id")?.into();}}
  barrier("workspace-database-record-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-after-commit")
 }
 pub(super) async fn database_record_load(&self,c:&WorkspaceContext,source_id:&str,record_id:&str,after:Option<&str>,limit:usize)->StoreResult<Value>{id(record_id)?;if !(1..=20).contains(&limit){return Err("Invalid cached candidate limit".into());}if let Some(value)=after{id(value)?;}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let record=current(&mut tx,c,&source,record_id).await?;let rows=sqlx::query("SELECT id,record,receipt_id FROM workspace_database_record_conflicts WHERE record_id=? AND (? IS NULL OR id>?) ORDER BY id LIMIT ?").bind(record_id).bind(after).bind(after).bind((limit+1) as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let more=rows.len()>limit;let mut conflicts=Vec::new();for row in rows{let candidate:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt cached candidate")?;let record=record.as_ref().ok_or("Candidate without Record")?;conflict(c,&source,record,&candidate)?;if candidate["id"]!=row.get::<String,_>("id"){return Err("Candidate identity mismatch".into());}let saved=receipt(&mut tx,c,&source,record_id,&row.get::<String,_>("receipt_id")).await?;if !saved["conflicts"].as_array().unwrap().contains(&candidate){return Err("Candidate lacks receipt provenance".into());}known_fields(&mut tx,c,&source,record,&candidate).await?;conflicts.push(candidate);}conflicts.truncate(limit);let next=if more{conflicts.last().unwrap()["id"].clone()}else{Value::Null};tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"record":record,"conflicts":conflicts,"nextAfter":next}))}
 pub(super) async fn database_record_list(&self,c:&WorkspaceContext,source_id:&str,after:Option<&str>,limit:usize)->StoreResult<Value>{if !(1..=100).contains(&limit){return Err("Invalid local Record limit".into());}if let Some(value)=after{id(value)?;}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let ids:Vec<String>=sqlx::query_scalar("SELECT record_id FROM workspace_database_records WHERE source_id=? AND (? IS NULL OR record_id>?) ORDER BY record_id LIMIT ?").bind(source_id).bind(after).bind(after).bind((limit+1) as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let more=ids.len()>limit;let mut records=Vec::new();for record_id in ids{let value=current(&mut tx,c,&source,&record_id).await?.ok_or("Missing listed Record")?;records.push(json!({"id":record_id,"pageId":value["pageId"],"version":value["version"]}));}records.truncate(limit);let next=if more{records.last().unwrap()["id"].clone()}else{Value::Null};tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"records":records,"nextAfter":next}))}
}
