use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,version};
use super::private_database_record::{hash,cell,snapshot,conflict};
use super::private_database_record_create::{id,matching,validate_source};
use serde_json::{json,Value};
use sqlx::{Row,Sqlite,Transaction,sqlite::SqliteRow};
const COLUMNS:&str="seq,operation_id,source_id,record_id,page_id,definition,intent,base,candidate,intent_hash,wire,wire_hash,response";
const WIRE_BYTES:usize=8*1024*1024;
const WINDOW_BYTES:usize=32*1024*1024;
const ROW_BYTES:usize=128*1024*1024;
fn sequence(raw:&str)->StoreResult<i64>{let n=raw.parse::<i64>().map_err(|_|"Invalid Record update sequence")?;if n<1||n.to_string()!=raw{return Err("Invalid Record update sequence".into());}Ok(n)}
fn state(record:&Value,field:&str)->Value{let values=record["values"].as_object().unwrap();json!({"present":values.contains_key(field),"value":values.get(field).unwrap_or(&Value::Null)})}
fn input(c:&WorkspaceContext,source:&Value,intent:&Value,base:&Value,candidate:&Value)->StoreResult<()> {
 validate_source(c,source)?;let resolving=intent.get("resolution").is_some();if resolving{exact(intent,&["kind","sourceId","schemaVersion","recordId","pageId","baseVersion","values","resolution"])?;}else{exact(intent,&["kind","sourceId","schemaVersion","recordId","pageId","baseVersion","values"])?;}
 id(text(intent,"recordId")?)?;id(text(intent,"pageId")?)?;if intent["kind"]!="update"||intent["sourceId"]!=source["id"]||intent["schemaVersion"]!=source["schemaVersion"]||intent["pageId"]!=base["pageId"]||snapshot(c,source,text(intent,"recordId")?,base)?!=version(&intent["baseVersion"])?{return Err("Record update baseline mismatch".into());}
 let values=intent["values"].as_object().filter(|v|!v.is_empty()).ok_or("Empty Record update")?;for(key,value)in values{id(key)?;let property=source["properties"].as_array().unwrap().iter().find(|p|p["id"]==*key&&p["type"]!="name").ok_or("Unknown or Page Name property")?;cell(property,value)?;}
 if resolving{let resolution=&intent["resolution"];exact(resolution,&["conflictId","propertyId","remoteVersion","choice"])?;id(text(resolution,"conflictId")?)?;id(text(resolution,"propertyId")?)?;let choice=text(resolution,"choice")?;if !["local","remote"].contains(&choice){return Err("Unknown Record resolution choice".into());}conflict(c,source,base,candidate)?;if values.len()!=1||!values.contains_key(text(resolution,"propertyId")?)||candidate["id"]!=resolution["conflictId"]||candidate["propertyId"]!=resolution["propertyId"]||candidate["remoteVersion"]!=resolution["remoteVersion"]||candidate[choice]["value"]!=intent["values"][text(resolution,"propertyId")?]||state(base,text(resolution,"propertyId")?)!=candidate["remote"]{return Err("Record resolution choice/baseline mismatch".into());}}
 else if !candidate.is_null(){return Err("Candidate without resolution intent".into());}Ok(())
}
struct Operation{sequence:i64,operation_id:String,source:Value,intent:Value,base:Value,candidate:Value,wire:Option<String>,response:Option<Value>}
fn request(c:&WorkspaceContext,row:&Operation)->Value{json!({"protocolVersion":1,"clientId":c.client_id,"operationId":row.operation_id,"intent":row.intent})}
fn reply(c:&WorkspaceContext,row:&Operation,value:&Value)->StoreResult<()> {
 exact(value,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","operationId","record","result"])?;if value["protocolVersion"]!=1||value["workspaceId"]!=c.workspace_id||value["workspaceEpoch"]!=c.stream_epoch||value["clientId"]!=c.client_id||value["sourceId"]!=row.source["id"]||value["schemaVersion"]!=row.source["schemaVersion"]||value["operationId"]!=row.operation_id||value["record"]["pageId"]!=row.intent["pageId"]||snapshot(c,&row.source,text(&row.intent,"recordId")?,&value["record"])?<version(&row.intent["baseVersion"])?{return Err("Record update ACK scope/version mismatch".into());}
 let result=&value["result"];let status=text(result,"status")?;let mut fields=std::collections::HashSet::new();match status{
  "applied"=>{exact(result,&["status"])?;},
  "rejected"=>{exact(result,&["status","code"])?;if !["base_unknown","resolution_invalid","resolution_stale"].contains(&text(result,"code")?){return Err("Invalid Record rejection".into());}},
  "conflict"=>{exact(result,&["status","conflicts"])?;if !row.candidate.is_null(){return Err("Resolution ACK cannot produce a new conflict".into());}let items=result["conflicts"].as_array().filter(|v|!v.is_empty()&&v.len()<=63).ok_or("Invalid Record ACK candidates")?;let mut ids=std::collections::HashSet::new();for candidate in items{conflict(c,&row.source,&value["record"],candidate)?;id(text(candidate,"id")?)?;let field=text(candidate,"propertyId")?;if !fields.insert(field.to_string())||!ids.insert(text(candidate,"id")?)||candidate["baseVersion"]!=row.intent["baseVersion"]||!row.intent["values"].as_object().unwrap().contains_key(field)||candidate["base"]!=state(&row.base,field)||candidate["local"]!=json!({"present":true,"value":row.intent["values"][field]})||candidate["remote"]!=state(&value["record"],field){return Err("Record ACK candidate differs from intent/baseline".into());}}},
  _=>return Err("Unknown Record ACK outcome".into())
 }
 if status=="applied"&&!row.candidate.is_null(){let field=text(&row.candidate,"propertyId")?;if state(&value["record"],field)["value"]!=row.intent["values"][field]{return Err("Record resolution ACK differs from selected value".into());}}
 if status!="rejected"{for(field,local)in row.intent["values"].as_object().unwrap(){if !fields.contains(field)&&row.candidate.is_null()&&local.is_null()&&state(&row.base,field)["present"]==false&&!value["record"]["values"].as_object().unwrap().contains_key(field){return Err("Record explicit null ACK lost its field".into());}if !fields.contains(field)&&*local!=state(&row.base,field)["value"]&&value["record"]["values"][field]!=*local{return Err("Record applied field differs from intent".into());}if status=="applied"&&value["record"]["version"]==row.base["version"]&&(*local!=state(&row.base,field)["value"]||(row.candidate.is_null()&&local.is_null()&&state(&row.base,field)["present"]==false)){return Err("Record changed fields lack a new version".into());}}}
 Ok(())
}
fn operation(c:&WorkspaceContext,row:&SqliteRow)->StoreResult<Operation>{
 let seq=row.get::<i64,_>("seq");if seq<1{return Err("Invalid Record update sequence".into());}let op=row.get::<String,_>("operation_id");id(&op)?;let source:Value=serde_json::from_str(&row.get::<String,_>("definition")).map_err(|_|"Corrupt Record update Source")?;let intent:Value=serde_json::from_str(&row.get::<String,_>("intent")).map_err(|_|"Corrupt Record update intent")?;let base:Value=serde_json::from_str(&row.get::<String,_>("base")).map_err(|_|"Corrupt Record update base")?;let candidate:Value=serde_json::from_str(&row.get::<String,_>("candidate")).map_err(|_|"Corrupt Record update candidate")?;input(c,&source,&intent,&base,&candidate)?;if source["id"]!=row.get::<String,_>("source_id")||intent["recordId"]!=row.get::<String,_>("record_id")||intent["pageId"]!=row.get::<String,_>("page_id")||row.get::<String,_>("intent_hash")!=hash(&json!({"context":c,"operationId":op,"source":source,"intent":intent,"base":base,"candidate":candidate})){return Err("Record update index/checksum mismatch".into());}
 let raw=row.get::<Option<String>,_>("wire");let digest=row.get::<Option<String>,_>("wire_hash");let response=row.get::<Option<String>,_>("response").map(|raw|serde_json::from_str::<Value>(&raw).map_err(|_|"Corrupt Record update ACK".to_string())).transpose()?;let value=Operation{sequence:seq,operation_id:op,source,intent,base,candidate,wire:raw,response};if let Some(raw)=&value.wire{let parsed:Value=serde_json::from_str(raw).map_err(|_|"Corrupt Record update wire")?;if raw.len()>WIRE_BYTES||parsed!=request(c,&value)||digest.as_deref()!=Some(hash(&Value::String(raw.clone())).as_str()){return Err("Record update wire changed".into());}}else if digest.is_some(){return Err("Record update digest without wire".into());}if let Some(response)=&value.response{if value.wire.is_none(){return Err("Record update ACK without wire".into());}reply(c,&value,response)?;}Ok(value)
}
fn observed_reply(row:&Operation,response:&Value)->Value{let mut conflicts=if response["result"]["status"]=="conflict"{response["result"]["conflicts"].as_array().unwrap().clone()}else{vec![]};let mut resolved=Value::Null;if !row.candidate.is_null()&&response["result"]["status"]=="applied"{conflicts.push(row.candidate.clone());resolved=json!(row.operation_id);}json!({"record":response["record"],"conflicts":conflicts,"_resolution":resolved})}
pub(super) async fn verify_receipt(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,record_id:&str,operation_id:&str,response:&Value)->StoreResult<Value>{let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE operation_id=?")).bind(operation_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if !matching(source,&row.source)||row.intent["recordId"]!=record_id||row.response.as_ref()!=Some(response){return Err("Record cache ACK lacks update proof".into());}Ok(observed_reply(&row,response))}
async fn confirmed_source(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value)->StoreResult<()> {let saved=super::private_database::load(tx,c,text(source,"id")?).await?.ok_or("Record update Source is unconfirmed")?;if !matching(&saved["source"],source){return Err("Record update schema changed".into());}Ok(())}
async fn observed(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,row:&Operation)->StoreResult<()> {
 confirmed_source(tx,c,&row.source).await?;let entity=text(&row.intent,"recordId")?;let original=super::private_database_record::historical(tx,c,&row.source,entity,version(&row.intent["baseVersion"])?).await?.ok_or("Missing original Record update baseline")?;if original!=row.base{return Err("Record update baseline changed".into());}let current=super::private_database_record::current(tx,c,&row.source,entity).await?.ok_or("Missing updated Record projection")?;if current["pageId"]!=row.intent["pageId"]{return Err("Record update binding changed".into());}
 if !row.candidate.is_null(){let candidate=super::private_database_record::checked_candidate(tx,c,&row.source,entity,text(&row.candidate,"id")?).await?;let mut core=candidate.clone();core["resolvedBy"]=Value::Null;if core!=row.candidate{return Err("Original update resolution candidate changed".into());}if row.response.as_ref().is_some_and(|value|value["result"]["status"]=="applied")&&candidate["resolvedBy"]!=row.operation_id{return Err("Applied Record resolution missing".into());}}
 if let Some(response)=&row.response{let saved=super::private_database_record::historical(tx,c,&row.source,entity,version(&response["record"]["version"])?).await?.ok_or("Missing acknowledged Record update history")?;if saved!=response["record"]{return Err("Record update ACK history changed".into());}if response["result"]["status"]=="conflict"{for expected in response["result"]["conflicts"].as_array().unwrap(){let mut saved=super::private_database_record::checked_candidate(tx,c,&row.source,entity,text(expected,"id")?).await?;saved["resolvedBy"]=Value::Null;if saved!=*expected{return Err("Acknowledged Record candidate changed".into());}}}}
 Ok(())
}
fn local(row:&Operation)->Value{json!({"sequence":row.sequence.to_string(),"intent":{"operationId":row.operation_id,"source":row.source,"intent":row.intent},"base":row.base,"candidate":row.candidate,"wire":row.wire,"response":row.response})}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()> {if [0,5,6,7,8,9,10,11,12,13,14].contains(&old){for sql in ["CREATE TABLE workspace_database_record_updates(seq INTEGER PRIMARY KEY AUTOINCREMENT CHECK(seq>0),operation_id TEXT NOT NULL UNIQUE,source_id TEXT NOT NULL,record_id TEXT NOT NULL,page_id TEXT NOT NULL,definition TEXT NOT NULL CHECK(json_valid(definition)),intent TEXT NOT NULL CHECK(json_valid(intent)),base TEXT NOT NULL CHECK(json_valid(base)),candidate TEXT NOT NULL CHECK(json_valid(candidate)),intent_hash TEXT NOT NULL,wire TEXT,wire_hash TEXT,response TEXT CHECK(response IS NULL OR json_valid(response)),CHECK((wire IS NULL)=(wire_hash IS NULL)),CHECK(response IS NULL OR wire IS NOT NULL)) STRICT","CREATE UNIQUE INDEX workspace_database_record_pending_update ON workspace_database_record_updates(record_id) WHERE response IS NULL","PRAGMA user_version=15"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates LIMIT 0")).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())}
impl PageStore {
 pub(super) async fn database_record_update_enqueue(&self,c:&WorkspaceContext,value:Value)->StoreResult<Value>{
  exact(&value,&["operationId","source","intent"])?;let op=text(&value,"operationId")?;id(op)?;let source=&value["source"];validate_source(c,source)?;let intent=&value["intent"];let entity=text(intent,"recordId")?;id(entity)?;let base_version=version(&intent["baseVersion"])?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;confirmed_source(&mut tx,c,source).await?;
  let old=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE operation_id=?")).bind(op).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let row=operation(c,&old)?;if row.source!=*source||row.intent!=*intent{return Err("Record update operation ID reused".into());}observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"queued","operationId":op,"recordId":entity}));}
  let used:Option<String>=sqlx::query_scalar("SELECT operation_id FROM workspace_database_record_creates WHERE operation_id=?").bind(op).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if used.is_some(){return Err("Record operation ID reused across create/update".into());}
  let current=super::private_database_record::current(&mut tx,c,source,entity).await?.ok_or("Record update requires confirmation")?;let base=super::private_database_record::historical(&mut tx,c,source,entity,base_version).await?.ok_or("Record update baseline unknown")?;if base_version>version(&current["version"])?{return Err("Record update baseline exceeds current".into());}let candidate=if let Some(resolution)=intent.get("resolution"){let candidate=super::private_database_record::checked_candidate(&mut tx,c,source,entity,text(resolution,"conflictId")?).await?;if candidate["resolvedBy"]!=Value::Null||current["version"]!=intent["baseVersion"]{return Err("Record resolution is stale or resolved".into());}candidate}else{Value::Null};input(c,source,intent,&base,&candidate)?;
  if json!({"protocolVersion":1,"clientId":c.client_id,"operationId":op,"intent":intent}).to_string().len()>WIRE_BYTES{return Err("Record update wire too large".into());}
  let pending=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE record_id=? AND response IS NULL")).bind(entity).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(pending)=pending{let row=operation(c,&pending)?;observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"busy","operationId":row.operation_id,"recordId":entity}));}
  sqlx::query("INSERT INTO workspace_database_record_updates(operation_id,source_id,record_id,page_id,definition,intent,base,candidate,intent_hash) VALUES(?,?,?,?,?,?,?,?,?)").bind(op).bind(text(source,"id")?).bind(entity).bind(text(intent,"pageId")?).bind(source.to_string()).bind(intent.to_string()).bind(base.to_string()).bind(candidate.to_string()).bind(hash(&json!({"context":c,"operationId":op,"source":source,"intent":intent,"base":base,"candidate":candidate}))).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-record-update-enqueue-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-update-enqueue-after-commit")?;Ok(json!({"status":"queued","operationId":op,"recordId":entity}))
 }
 pub(super) async fn database_record_update_prepare(&self,c:&WorkspaceContext)->StoreResult<Value>{let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE response IS NULL ORDER BY seq LIMIT 1")).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{tx.commit().await.map_err(|e|e.to_string())?;return Ok(Value::Null);};let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;let raw=row.wire.clone().unwrap_or_else(||request(c,&row).to_string());if raw.len()>WIRE_BYTES{return Err("Record update wire too large".into());}sqlx::query("UPDATE workspace_database_record_updates SET wire=?,wire_hash=? WHERE seq=? AND wire IS NULL").bind(&raw).bind(hash(&Value::String(raw.clone()))).bind(row.sequence).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-record-update-prepare-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-update-prepare-after-commit")?;Ok(json!({"sequence":row.sequence.to_string(),"operationId":row.operation_id,"sourceId":row.source["id"],"recordId":row.intent["recordId"],"pageId":row.intent["pageId"],"wire":raw}))}
 pub(super) async fn database_record_update_ack(&self,c:&WorkspaceContext,raw_sequence:&str,wire:&str,response:Value)->StoreResult<()> {
  let sequence=sequence(raw_sequence)?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE seq=?")).bind(sequence).fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if row.wire.as_deref()!=Some(wire){return Err("Record update ACK wire changed".into());}reply(c,&row,&response)?;observed(&mut tx,c,&row).await?;
  if let Some(old)=&row.response{if *old!=response{return Err("Record update ACK reused".into());}tx.commit().await.map_err(|e|e.to_string())?;return Ok(());}
  sqlx::query("UPDATE workspace_database_record_updates SET response=? WHERE seq=? AND response IS NULL").bind(response.to_string()).bind(sequence).execute(&mut *tx).await.map_err(|e|e.to_string())?;let request=json!({"databaseRecordUpdateOperation":row.operation_id});let digest=hash(&json!({"request":request,"response":response}));sqlx::query("INSERT OR IGNORE INTO workspace_database_record_receipts VALUES(?,?,?,?,?)").bind(&digest).bind(text(&row.source,"id")?).bind(text(&row.intent,"recordId")?).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;let projected=verify_receipt(&mut tx,c,&row.source,text(&row.intent,"recordId")?,&row.operation_id,&response).await?;super::private_database_record::save(&mut tx,c,&row.source,text(&row.intent,"recordId")?,&projected,&digest).await?;
  if !row.candidate.is_null()&&response["result"]["status"]=="applied"{super::private_database_record::confirm_resolution(&mut tx,c,&row.source,text(&row.intent,"recordId")?,&row.candidate,&row.operation_id,&digest).await?;}
  let confirmed=Operation{response:Some(response),..row};observed(&mut tx,c,&confirmed).await?;barrier("workspace-database-record-update-ack-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-record-update-ack-after-commit")
 }
 pub(super) async fn database_record_update_queue(&self,c:&WorkspaceContext,after:Option<&str>,limit:usize,pending_only:bool)->StoreResult<Value>{
  if !(1..=100).contains(&limit){return Err("Invalid Record update limit".into());}let mut position=after.map(sequence).transpose()?.unwrap_or(0);let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let mut values=Vec::new();let mut bytes=0usize;let mut more=false;
  loop{let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_record_updates WHERE (?=0 OR response IS NULL) AND seq>? ORDER BY seq LIMIT 1")).bind(pending_only).bind(position).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{break;};let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;let value=local(&row);let size=value.to_string().len();if size>ROW_BYTES{return Err("Record update entry exceeds byte bound".into());}if values.len()==limit||(!values.is_empty()&&bytes+size>WINDOW_BYTES){more=true;break;}bytes+=size;position=row.sequence;values.push(value);}
  let next=if more{json!(position.to_string())}else{Value::Null};let pending:i64=sqlx::query_scalar("SELECT count(*) FROM workspace_database_record_updates WHERE response IS NULL").fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;if pending>9007199254740991{return Err("Record update pending overflow".into());}tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"pending":pending,"operations":values,"nextAfter":next}))
 }
}
