use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,version};
use super::private_database_record_create::{id,matching,validate_source,available_source};
use super::private_database_view::{hash,snapshot,conflict};
use serde_json::{json,Value};
use sqlx::{Row,Sqlite,Transaction,sqlite::SqliteRow};
const COLUMNS:&str="seq,operation_id,source_id,view_id,kind,definition,intent,base,candidate,intent_hash,wire,wire_hash,response";
const WIRE_BYTES:usize=8*1024*1024;
const WINDOW_BYTES:usize=32*1024*1024;
const ROW_BYTES:usize=256*1024*1024;
const FIELDS:[&str;5]=["name","layout","visiblePropertyIds","filter","sorts"];
fn sequence(raw:&str)->StoreResult<i64>{let n=raw.parse::<i64>().map_err(|_|"Invalid View sequence")?;if n<1||n.to_string()!=raw{return Err("Invalid View sequence".into());}Ok(n)}
fn refs(value:&Value)->StoreResult<()>{match value{Value::Array(items)=>{for item in items{refs(item)?;}},Value::Object(items)=>{for(key,item)in items{if ["id","sourceId","viewId","propertyId","conflictId","workspaceId","resolvedBy"].contains(&key.as_str())&&!item.is_null(){id(item.as_str().ok_or("Expected View reference")?)?;}if key=="visiblePropertyIds"{for item in item.as_array().ok_or("Expected View columns")?{id(item.as_str().ok_or("Expected column reference")?)?;}}refs(item)?;}},_=>{}}Ok(())}
fn field(source:&Value,key:&str,value:&Value)->StoreResult<()>{refs(value)?;if key=="visiblePropertyIds"{for item in value.as_array().ok_or("Expected View columns")?{id(item.as_str().ok_or("Expected column reference")?)?;}}super::private_database_view::field(source,key,value)}
fn checked_snapshot(c:&WorkspaceContext,source:&Value,entity:&str,value:&Value)->StoreResult<i64>{refs(value)?;for key in FIELDS{field(source,key,&value["view"][key])?;}snapshot(c,source,entity,value)}
fn checked_candidate(c:&WorkspaceContext,source:&Value,current:&Value,value:&Value)->StoreResult<()>{refs(value)?;conflict(c,source,current,value)?;for key in ["base","local","remote"]{field(source,text(value,"field")?,&value[key])?;}Ok(())}
fn input(c:&WorkspaceContext,source:&Value,intent:&Value,base:&Value,candidate:&Value)->StoreResult<()> {
 validate_source(c,source)?;refs(intent)?;let entity=text(intent,"viewId")?;id(entity)?;if intent["sourceId"]!=source["id"]||intent["schemaVersion"]!=source["schemaVersion"]{return Err("View Source/schema mismatch".into());}
 match text(intent,"kind")?{
 "create"=>{exact(intent,&["kind","sourceId","schemaVersion","viewId","baseVersion","settings"])?;if !intent["baseVersion"].is_null()||!base.is_null()||!candidate.is_null(){return Err("View creation has a fake baseline".into());}exact(&intent["settings"],&FIELDS)?;for key in FIELDS{field(source,key,&intent["settings"][key])?;}},
 "update"=>{if intent.get("resolution").is_some(){exact(intent,&["kind","sourceId","schemaVersion","viewId","baseVersion","patch","resolution"])?;}else{exact(intent,&["kind","sourceId","schemaVersion","viewId","baseVersion","patch"])?;}if checked_snapshot(c,source,entity,base)?!=version(&intent["baseVersion"])?{return Err("View update baseline mismatch".into());}let patch=intent["patch"].as_object().filter(|v|!v.is_empty()).ok_or("Empty View patch")?;for(key,value)in patch{field(source,key,value)?;}if let Some(resolution)=intent.get("resolution"){exact(resolution,&["conflictId","field","remoteVersion","choice"])?;let key=text(resolution,"field")?;let choice=text(resolution,"choice")?;if !["local","remote"].contains(&choice){return Err("Unknown View choice".into());}checked_candidate(c,source,base,candidate)?;if patch.len()!=1||!patch.contains_key(key)||candidate["id"]!=resolution["conflictId"]||candidate["field"]!=resolution["field"]||candidate["remoteVersion"]!=resolution["remoteVersion"]||candidate[choice]!=intent["patch"][key]||base["view"][key]!=candidate["remote"]{return Err("View resolution choice/baseline mismatch".into());}}else if !candidate.is_null(){return Err("Candidate without View resolution".into());}},
 _=>return Err("Unknown View intent".into())
 }Ok(())
}
struct Operation{sequence:i64,operation_id:String,source:Value,intent:Value,base:Value,candidate:Value,wire:Option<String>,response:Option<Value>}
fn request(c:&WorkspaceContext,row:&Operation)->Value{json!({"protocolVersion":1,"clientId":c.client_id,"operationId":row.operation_id,"intent":row.intent})}
fn reply(c:&WorkspaceContext,row:&Operation,value:&Value)->StoreResult<()> {
 exact(value,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","operationId","snapshot","result"])?;if value["protocolVersion"]!=1||value["workspaceId"]!=c.workspace_id||value["workspaceEpoch"]!=c.stream_epoch||value["clientId"]!=c.client_id||value["sourceId"]!=row.source["id"]||value["schemaVersion"]!=row.source["schemaVersion"]||value["operationId"]!=row.operation_id{return Err("View ACK scope mismatch".into());}let ver=checked_snapshot(c,&row.source,text(&row.intent,"viewId")?,&value["snapshot"])?;let result=&value["result"];
 if row.intent["kind"]=="create"{exact(result,&["status"])?;let expected=json!({"id":row.intent["viewId"],"sourceId":row.source["id"],"name":row.intent["settings"]["name"],"layout":row.intent["settings"]["layout"],"visiblePropertyIds":row.intent["settings"]["visiblePropertyIds"],"filter":row.intent["settings"]["filter"],"sorts":row.intent["settings"]["sorts"]});if result["status"]!="applied"||ver!=1||value["snapshot"]["view"]!=expected{return Err("View create ACK differs from intent".into());}return Ok(());}
 if ver<version(&row.intent["baseVersion"])?{return Err("View ACK precedes baseline".into());}let status=text(result,"status")?;let mut fields=std::collections::HashSet::new();match status{
 "applied"=>exact(result,&["status"])?,
 "rejected"=>{exact(result,&["status","code"])?;if !["base_unknown","resolution_invalid","resolution_stale"].contains(&text(result,"code")?){return Err("Invalid View rejection".into());}},
 "conflict"=>{exact(result,&["status","conflicts"])?;if !row.candidate.is_null(){return Err("View resolution cannot produce another conflict".into());}let items=result["conflicts"].as_array().filter(|v|!v.is_empty()&&v.len()<=5).ok_or("Invalid View ACK candidates")?;let mut ids=std::collections::HashSet::new();for candidate in items{checked_candidate(c,&row.source,&value["snapshot"],candidate)?;let key=text(candidate,"field")?;if !fields.insert(key.to_string())||!ids.insert(text(candidate,"id")?)||candidate["baseVersion"]!=row.intent["baseVersion"]||!row.intent["patch"].as_object().unwrap().contains_key(key)||candidate["base"]!=row.base["view"][key]||candidate["local"]!=row.intent["patch"][key]||candidate["remote"]!=value["snapshot"]["view"][key]{return Err("View candidate differs from original patch/baseline/reply".into());}}},
 _=>return Err("Unknown View outcome".into())
 }
 if status!="rejected"{for(key,local)in row.intent["patch"].as_object().unwrap(){if !fields.contains(key)&&*local!=row.base["view"][key]&&value["snapshot"]["view"][key]!=*local{return Err("View applied field differs from intent".into());}if status=="applied"&&value["snapshot"]["version"]==row.base["version"]&&*local!=row.base["view"][key]{return Err("Changed View lacks a new version".into());}}}Ok(())
}
fn operation(c:&WorkspaceContext,row:&SqliteRow)->StoreResult<Operation>{let seq=row.get::<i64,_>("seq");if seq<1{return Err("Invalid View sequence".into());}let op=row.get::<String,_>("operation_id");id(&op)?;let source:Value=serde_json::from_str(&row.get::<String,_>("definition")).map_err(|_|"Corrupt View Source")?;let intent:Value=serde_json::from_str(&row.get::<String,_>("intent")).map_err(|_|"Corrupt View intent")?;let base:Value=serde_json::from_str(&row.get::<String,_>("base")).map_err(|_|"Corrupt View base")?;let candidate:Value=serde_json::from_str(&row.get::<String,_>("candidate")).map_err(|_|"Corrupt View candidate")?;input(c,&source,&intent,&base,&candidate)?;if source["id"]!=row.get::<String,_>("source_id")||intent["viewId"]!=row.get::<String,_>("view_id")||intent["kind"]!=row.get::<String,_>("kind")||row.get::<String,_>("intent_hash")!=hash(&json!({"context":c,"operationId":op,"source":source,"intent":intent,"base":base,"candidate":candidate})){return Err("View index/checksum mismatch".into());}let raw=row.get::<Option<String>,_>("wire");let digest=row.get::<Option<String>,_>("wire_hash");let response=row.get::<Option<String>,_>("response").map(|raw|serde_json::from_str::<Value>(&raw).map_err(|_|"Corrupt View ACK".to_string())).transpose()?;let value=Operation{sequence:seq,operation_id:op,source,intent,base,candidate,wire:raw,response};if let Some(raw)=&value.wire{let parsed:Value=serde_json::from_str(raw).map_err(|_|"Corrupt View wire")?;if raw.len()>WIRE_BYTES||parsed!=request(c,&value)||digest.as_deref()!=Some(hash(&Value::String(raw.clone())).as_str()){return Err("View immutable wire changed".into());}}else if digest.is_some(){return Err("View digest without wire".into());}if let Some(response)=&value.response{if value.wire.is_none(){return Err("View ACK without wire".into());}reply(c,&value,response)?;}Ok(value)}
fn observed_reply(row:&Operation,response:&Value)->Value{let mut conflicts=if response["result"]["status"]=="conflict"{response["result"]["conflicts"].as_array().unwrap().clone()}else{vec![]};let mut resolved=Value::Null;if !row.candidate.is_null()&&response["result"]["status"]=="applied"{conflicts.push(row.candidate.clone());resolved=json!(row.operation_id);}json!({"snapshot":response["snapshot"],"conflicts":conflicts,"_resolution":resolved})}
pub(super) async fn verify_receipt(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,operation_id:&str,response:&Value)->StoreResult<Value>{let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE operation_id=?")).bind(operation_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if !matching(source,&row.source)||row.intent["viewId"]!=view_id||row.response.as_ref()!=Some(response){return Err("View cache ACK lacks original queue proof".into());}Ok(observed_reply(&row,response))}
async fn observed(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,row:&Operation)->StoreResult<()> {available_source(tx,c,&row.source).await?;let entity=text(&row.intent,"viewId")?;let current=super::private_database_view::current(tx,c,&row.source,entity).await?;if row.intent["kind"]=="update"{current.as_ref().ok_or("Missing updated View projection")?;let original=super::private_database_view::historical(tx,c,&row.source,entity,version(&row.intent["baseVersion"])?).await?.ok_or("Missing original View baseline")?;if original!=row.base{return Err("Original View base changed".into());}}
 if !row.candidate.is_null(){let candidate=super::private_database_view::checked_candidate(tx,c,&row.source,entity,text(&row.candidate,"id")?).await?;let mut core=candidate.clone();core["resolvedBy"]=Value::Null;if core!=row.candidate{return Err("Original View candidate changed".into());}if row.response.as_ref().is_some_and(|value|value["result"]["status"]=="applied")&&candidate["resolvedBy"]!=row.operation_id{return Err("Applied View resolution missing".into());}}
 if let Some(response)=&row.response{current.as_ref().ok_or("Missing acknowledged View projection")?;let saved=super::private_database_view::historical(tx,c,&row.source,entity,version(&response["snapshot"]["version"])?).await?.ok_or("Missing acknowledged View history")?;if saved!=response["snapshot"]{return Err("View ACK history changed".into());}if response["result"]["status"]=="conflict"{for expected in response["result"]["conflicts"].as_array().unwrap(){let mut saved=super::private_database_view::checked_candidate(tx,c,&row.source,entity,text(expected,"id")?).await?;saved["resolvedBy"]=Value::Null;if saved!=*expected{return Err("Acknowledged View candidate changed".into());}}}}Ok(())}
fn local(row:&Operation)->Value{json!({"sequence":row.sequence.to_string(),"intent":{"operationId":row.operation_id,"source":row.source,"intent":row.intent},"base":row.base,"candidate":row.candidate,"wire":row.wire,"response":row.response})}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()> {if [0,5,6,7,8,9,10,11,12,13,14,15].contains(&old){for sql in ["CREATE TABLE workspace_database_view_operations(seq INTEGER PRIMARY KEY AUTOINCREMENT CHECK(seq>0),operation_id TEXT NOT NULL UNIQUE,source_id TEXT NOT NULL,view_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN('create','update')),definition TEXT NOT NULL CHECK(json_valid(definition)),intent TEXT NOT NULL CHECK(json_valid(intent)),base TEXT NOT NULL CHECK(json_valid(base)),candidate TEXT NOT NULL CHECK(json_valid(candidate)),intent_hash TEXT NOT NULL,wire TEXT,wire_hash TEXT,response TEXT CHECK(response IS NULL OR json_valid(response)),CHECK((wire IS NULL)=(wire_hash IS NULL)),CHECK(response IS NULL OR wire IS NOT NULL)) STRICT","CREATE UNIQUE INDEX workspace_database_view_pending ON workspace_database_view_operations(view_id) WHERE response IS NULL","CREATE UNIQUE INDEX workspace_database_view_created ON workspace_database_view_operations(view_id) WHERE kind='create'","PRAGMA user_version=16"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations LIMIT 0")).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())}
impl PageStore {
 pub(super) async fn database_view_enqueue(&self,c:&WorkspaceContext,value:Value)->StoreResult<Value>{exact(&value,&["operationId","source","intent"])?;let op=text(&value,"operationId")?;id(op)?;let source=&value["source"];validate_source(c,source)?;let intent=&value["intent"];refs(intent)?;let entity=text(intent,"viewId")?;id(entity)?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let ready=available_source(&mut tx,c,source).await?;
  let old=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE operation_id=?")).bind(op).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let row=operation(c,&old)?;if row.source!=*source||row.intent!=*intent{return Err("View operation ID reused".into());}observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"queued","operationId":op,"viewId":entity}));}
  let current=super::private_database_view::current(&mut tx,c,source,entity).await?;let (base,candidate)=match text(intent,"kind")?{"create"=>{if current.is_some(){return Err("Cannot create confirmed View".into());}(Value::Null,Value::Null)},"update"=>{if !ready{return Err("View update Source is unconfirmed".into());}let current=current.as_ref().ok_or("View update requires confirmation")?;let ver=version(&intent["baseVersion"])?;if ver>version(&current["version"])?{return Err("View baseline exceeds current".into());}let base=super::private_database_view::historical(&mut tx,c,source,entity,ver).await?.ok_or("View baseline unknown")?;let candidate=if let Some(resolution)=intent.get("resolution"){let candidate=super::private_database_view::checked_candidate(&mut tx,c,source,entity,text(resolution,"conflictId")?).await?;if !candidate["resolvedBy"].is_null()||current["version"]!=intent["baseVersion"]{return Err("View choice is stale/resolved".into());}candidate}else{Value::Null};(base,candidate)},_=>return Err("Unknown View intent".into())};input(c,source,intent,&base,&candidate)?;
  if json!({"protocolVersion":1,"clientId":c.client_id,"operationId":op,"intent":intent}).to_string().len()>WIRE_BYTES{return Err("View wire too large".into());}
  let pending=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE view_id=? AND response IS NULL")).bind(entity).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if let Some(pending)=pending{let row=operation(c,&pending)?;observed(&mut tx,c,&row).await?;tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"busy","operationId":row.operation_id,"viewId":entity}));}
  let capture=json!({"context":c,"operationId":op,"source":source,"intent":intent,"base":base,"candidate":candidate});sqlx::query("INSERT INTO workspace_database_view_operations(operation_id,source_id,view_id,kind,definition,intent,base,candidate,intent_hash) VALUES(?,?,?,?,?,?,?,?,?)").bind(op).bind(text(source,"id")?).bind(entity).bind(text(intent,"kind")?).bind(source.to_string()).bind(intent.to_string()).bind(base.to_string()).bind(candidate.to_string()).bind(hash(&capture)).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-view-enqueue-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-view-enqueue-after-commit")?;Ok(json!({"status":"queued","operationId":op,"viewId":entity}))
 }
 pub(super) async fn database_view_prepare(&self,c:&WorkspaceContext)->StoreResult<Value>{let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE response IS NULL ORDER BY seq LIMIT 1")).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{tx.commit().await.map_err(|e|e.to_string())?;return Ok(Value::Null);};let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;if !available_source(&mut tx,c,&row.source).await?{tx.commit().await.map_err(|e|e.to_string())?;return Ok(json!({"status":"blocked","reason":"source","sequence":row.sequence.to_string(),"operationId":row.operation_id,"sourceId":row.source["id"],"viewId":row.intent["viewId"]}));}let raw=row.wire.clone().unwrap_or_else(||request(c,&row).to_string());if raw.len()>WIRE_BYTES{return Err("View wire too large".into());}sqlx::query("UPDATE workspace_database_view_operations SET wire=?,wire_hash=? WHERE seq=? AND wire IS NULL").bind(&raw).bind(hash(&Value::String(raw.clone()))).bind(row.sequence).execute(&mut *tx).await.map_err(|e|e.to_string())?;barrier("workspace-database-view-prepare-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-view-prepare-after-commit")?;Ok(json!({"sequence":row.sequence.to_string(),"operationId":row.operation_id,"sourceId":row.source["id"],"viewId":row.intent["viewId"],"wire":raw}))}
 pub(super) async fn database_view_ack(&self,c:&WorkspaceContext,raw_sequence:&str,wire:&str,response:Value)->StoreResult<()> {let seq=sequence(raw_sequence)?;let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE seq=?")).bind(seq).fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;let row=operation(c,&row)?;if row.wire.as_deref()!=Some(wire)||!available_source(&mut tx,c,&row.source).await?{return Err("View ACK wire/Source differs".into());}reply(c,&row,&response)?;observed(&mut tx,c,&row).await?;if let Some(old)=&row.response{if *old!=response{return Err("View ACK reused".into());}tx.commit().await.map_err(|e|e.to_string())?;return Ok(());}
  sqlx::query("UPDATE workspace_database_view_operations SET response=? WHERE seq=? AND response IS NULL").bind(response.to_string()).bind(seq).execute(&mut *tx).await.map_err(|e|e.to_string())?;let request=json!({"databaseViewOperation":row.operation_id});let digest=hash(&json!({"request":request,"response":response}));sqlx::query("INSERT OR IGNORE INTO workspace_database_view_receipts VALUES(?,?,?,?,?)").bind(&digest).bind(text(&row.source,"id")?).bind(text(&row.intent,"viewId")?).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;let projected=verify_receipt(&mut tx,c,&row.source,text(&row.intent,"viewId")?,&row.operation_id,&response).await?;super::private_database_view::save(&mut tx,c,&row.source,text(&row.intent,"viewId")?,&projected,&digest).await?;if !row.candidate.is_null()&&response["result"]["status"]=="applied"{super::private_database_view::confirm_resolution(&mut tx,c,&row.source,text(&row.intent,"viewId")?,&row.candidate,&row.operation_id,&digest).await?;}let confirmed=Operation{response:Some(response),..row};observed(&mut tx,c,&confirmed).await?;barrier("workspace-database-view-ack-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-view-ack-after-commit")
 }
 pub(super) async fn database_view_queue(&self,c:&WorkspaceContext,after:Option<&str>,limit:usize,pending_only:bool)->StoreResult<Value>{if !(1..=100).contains(&limit){return Err("Invalid View queue limit".into());}let mut position=after.map(sequence).transpose()?.unwrap_or(0);let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let mut values=Vec::new();let mut bytes=0usize;let mut more=false;loop{let row=sqlx::query(&format!("SELECT {COLUMNS} FROM workspace_database_view_operations WHERE (?=0 OR response IS NULL) AND seq>? ORDER BY seq LIMIT 1")).bind(pending_only).bind(position).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{break;};let row=operation(c,&row)?;observed(&mut tx,c,&row).await?;let value=local(&row);let size=value.to_string().len();if size>ROW_BYTES{return Err("View queue entry exceeds byte bound".into());}if values.len()==limit||(!values.is_empty()&&bytes+size>WINDOW_BYTES){more=true;break;}bytes+=size;position=row.sequence;values.push(value);}let next=if more{json!(position.to_string())}else{Value::Null};let pending:i64=sqlx::query_scalar("SELECT count(*) FROM workspace_database_view_operations WHERE response IS NULL").fetch_one(&mut *tx).await.map_err(|e|e.to_string())?;if pending>9007199254740991{return Err("View pending overflow".into());}tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"pending":pending,"operations":values,"nextAfter":next}))}
}
