use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,id,version,label,source_definition};
use serde_json::{json,Value};
use sha2::{Digest,Sha256};
use sqlx::{Row,Sqlite,Transaction};
use std::collections::HashSet;
fn canonical(value:&Value)->Value{match value{Value::Array(items)=>Value::Array(items.iter().map(canonical).collect()),Value::Object(items)=>{let mut keys:Vec<_>=items.keys().collect();keys.sort();let mut out=serde_json::Map::new();for key in keys{out.insert(key.clone(),canonical(&items[key]));}Value::Object(out)},_=>value.clone()}}
pub(super) fn hash(value:&Value)->String{Sha256::digest(canonical(value).to_string().as_bytes()).iter().map(|b|format!("{b:02x}")).collect()}
fn property<'a>(source:&'a Value,key:&str)->StoreResult<&'a Value>{id(key)?;source["properties"].as_array().ok_or("Missing properties")?.iter().find(|p|p["id"]==key).ok_or("Unknown View property".into())}
fn value(property:&Value,v:&Value)->StoreResult<()>{let mut p=property.clone();if p["type"]=="name"{p["type"]=json!("text");}super::private_database_record::cell(&p,v)}
fn filter(source:&Value,node:&Value,depth:usize,predicates:&mut usize)->StoreResult<()>{
 if node["kind"]=="predicate"{*predicates+=1;if *predicates>100{return Err("Too many View predicates".into());}let p=property(source,text(node,"propertyId")?)?;let op=text(node,"operator")?;match op{
 "is_set"|"is_unset"=>exact(node,&["kind","propertyId","operator"]),
 "eq"|"not_eq"|"contains"|"lt"|"lte"|"gt"|"gte"=>{exact(node,&["kind","propertyId","operator","value"])?;let kind=text(p,"type")?;if op=="contains"&&(!["name","text"].contains(&kind)||!node["value"].is_string()){return Err("Invalid contains predicate".into());}if ["lt","lte","gt","gte"].contains(&op)&&(!["number","date"].contains(&kind)||node["value"].is_null()){return Err("Invalid range predicate".into());}value(p,&node["value"])},_=>Err("Unknown predicate operator".into())}
 }else{exact(node,&["kind","children"])?;if !["and","or"].contains(&text(node,"kind")?)||depth>=3{return Err("Invalid filter depth".into());}let children=node["children"].as_array().ok_or("Expected filter children")?;if !(1..=20).contains(&children.len()){return Err("Invalid filter children".into());}for child in children{filter(source,child,depth+1,predicates)?;}Ok(())}
}
pub(super) fn field(source:&Value,key:&str,v:&Value)->StoreResult<()>{match key{
 "name"=>label(v),"layout"=>{if v=="table"||v=="list"{Ok(())}else{Err("Invalid View layout".into())}},
 "visiblePropertyIds"=>{let refs=v.as_array().ok_or("Expected visible columns")?;if !(1..=64).contains(&refs.len()){return Err("Invalid column count".into());}let mut seen=HashSet::new();let mut name=false;for item in refs{let key=item.as_str().ok_or("Expected column ID")?;let p=property(source,key)?;if !seen.insert(key){return Err("Duplicate visible column".into());}name|=p["type"]=="name";}if !name{return Err("Name must remain visible".into());}Ok(())},
 "filter"=>{if v.is_null(){Ok(())}else{filter(source,v,0,&mut 0)}},
 "sorts"=>{let sorts=v.as_array().ok_or("Expected View sorts")?;if sorts.len()>8{return Err("Too many View sorts".into());}let mut seen=HashSet::new();for sort in sorts{exact(sort,&["propertyId","direction"])?;let key=text(sort,"propertyId")?;property(source,key)?;if !seen.insert(key)||!["asc","desc"].contains(&text(sort,"direction")?){return Err("Invalid or duplicate View sort".into());}}Ok(())},_=>Err("Unknown View field".into())}}
pub(super) fn snapshot(_c:&WorkspaceContext,source:&Value,view_id:&str,snapshot:&Value)->StoreResult<i64>{id(view_id)?;exact(snapshot,&["view","version"])?;let view=&snapshot["view"];exact(view,&["id","sourceId","name","layout","visiblePropertyIds","filter","sorts"])?;if view["id"]!=view_id||view["sourceId"]!=source["id"]{return Err("View snapshot scope mismatch".into());}for key in ["name","layout","visiblePropertyIds","filter","sorts"]{field(source,key,&view[key])?;}version(&snapshot["version"])}
pub(super) fn conflict(c:&WorkspaceContext,source:&Value,snapshot:&Value,v:&Value)->StoreResult<()>{exact(v,&["id","workspaceId","sourceId","schemaVersion","viewId","field","baseVersion","remoteVersion","base","local","remote","resolvedBy"])?;id(text(v,"id")?)?;if v["workspaceId"]!=c.workspace_id||v["sourceId"]!=source["id"]||v["schemaVersion"]!=source["schemaVersion"]||v["viewId"]!=snapshot["view"]["id"]||!v["resolvedBy"].is_null(){return Err("View candidate scope mismatch".into());}let base=version(&v["baseVersion"])?;let remote=version(&v["remoteVersion"])?;if base>=remote||remote>version(&snapshot["version"])?{return Err("Invalid View candidate versions".into());}for key in ["base","local","remote"]{field(source,text(v,"field")?,&v[key])?;}if v["base"]==v["local"]||v["base"]==v["remote"]||v["local"]==v["remote"]{return Err("Invalid View triad".into());}Ok(())}
fn pair(c:&WorkspaceContext,source:&Value,view_id:&str,request:&Value,reply:&Value)->StoreResult<i64>{exact(request,&["protocolVersion","clientId","afterConflict","limit"])?;if request["protocolVersion"]!=1||request["clientId"]!=c.client_id{return Err("View request context mismatch".into());}let limit=request["limit"].as_u64().filter(|n|(1..=20).contains(n)).ok_or("Invalid candidate limit")?;let mut previous=if request["afterConflict"].is_null(){""}else{let v=text(request,"afterConflict")?;id(v)?;v};exact(reply,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","snapshot","conflicts","nextAfter"])?;if reply["protocolVersion"]!=1||reply["workspaceId"]!=c.workspace_id||reply["workspaceEpoch"]!=c.stream_epoch||reply["clientId"]!=c.client_id||reply["sourceId"]!=source["id"]||reply["schemaVersion"]!=source["schemaVersion"]{return Err("View response context mismatch".into());}let ver=snapshot(c,source,view_id,&reply["snapshot"])?;let rows=reply["conflicts"].as_array().ok_or("Expected candidates")?;if rows.len()>limit as usize{return Err("Too many candidates".into());}for value in rows{conflict(c,source,&reply["snapshot"],value)?;let next=text(value,"id")?;if next<=previous{return Err("Invalid candidate order".into());}previous=next;}if !reply["nextAfter"].is_null()&&(rows.is_empty()||reply["nextAfter"]!=previous){return Err("Invalid candidate continuation".into());}Ok(ver)}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()> {if [0,5,6,7,8,9,10].contains(&old){for sql in [
 "CREATE TABLE workspace_database_view_receipts(id TEXT PRIMARY KEY NOT NULL,source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),view_id TEXT NOT NULL,request TEXT NOT NULL CHECK(json_valid(request)),response TEXT NOT NULL CHECK(json_valid(response))) STRICT",
 "CREATE TABLE workspace_database_view_history(view_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1 AND version<=9007199254740991),snapshot TEXT NOT NULL CHECK(json_valid(snapshot)),receipt_id TEXT NOT NULL REFERENCES workspace_database_view_receipts(id),PRIMARY KEY(view_id,version)) STRICT",
 "CREATE TABLE workspace_database_views(view_id TEXT PRIMARY KEY NOT NULL,source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),version INTEGER NOT NULL,FOREIGN KEY(view_id,version) REFERENCES workspace_database_view_history(view_id,version)) STRICT",
 "CREATE TABLE workspace_database_view_conflicts(view_id TEXT NOT NULL REFERENCES workspace_database_views(view_id),id TEXT NOT NULL,record TEXT NOT NULL CHECK(json_valid(record)),receipt_id TEXT NOT NULL REFERENCES workspace_database_view_receipts(id),PRIMARY KEY(view_id,id)) STRICT",
 "CREATE INDEX workspace_database_view_candidate_base ON workspace_database_view_conflicts(view_id,json_extract(record,'$.baseVersion'),id)",
 "CREATE INDEX workspace_database_view_candidate_remote ON workspace_database_view_conflicts(view_id,json_extract(record,'$.remoteVersion'),id)",
 "PRAGMA user_version=11"
 ]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}for sql in ["SELECT id,source_id,view_id,request,response FROM workspace_database_view_receipts LIMIT 0","SELECT view_id,version,snapshot,receipt_id FROM workspace_database_view_history LIMIT 0","SELECT view_id,source_id,version FROM workspace_database_views LIMIT 0","SELECT view_id,id,record,receipt_id FROM workspace_database_view_conflicts LIMIT 0"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}Ok(())}
async fn receipt(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,receipt_id:&str)->StoreResult<Value>{let row=sqlx::query("SELECT source_id,view_id,request,response FROM workspace_database_view_receipts WHERE id=?").bind(receipt_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let request:Value=serde_json::from_str(&row.get::<String,_>("request")).map_err(|_|"Corrupt View request")?;let response:Value=serde_json::from_str(&row.get::<String,_>("response")).map_err(|_|"Corrupt View response")?;let observed=if request.get("databaseChangeReceipt").is_some(){exact(&request,&["databaseChangeReceipt","eventOrder"])?;let event=super::private_database_changes::observed_event(tx,c,source,text(&request,"databaseChangeReceipt")?,text(&request,"eventOrder")?).await?;if response!=event||event["kind"]!="view"||event["snapshot"]["view"]["id"]!=view_id{return Err("Database observation provenance mismatch".into());}let mut conflicts=Vec::new();if !event["conflict"].is_null(){let mut core=event["conflict"].clone();core["resolvedBy"]=Value::Null;conflicts.push(core);}json!({"snapshot":event["snapshot"],"conflicts":conflicts,"_resolution":event["conflict"]["resolvedBy"]})}else if request.get("databaseViewOperation").is_some(){exact(&request,&["databaseViewOperation"])?;super::private_database_view_queue::verify_receipt(tx,c,source,view_id,text(&request,"databaseViewOperation")?,&response).await?}else{pair(c,source,view_id,&request,&response)?;response.clone()};if row.get::<String,_>("source_id")!=text(source,"id")?||row.get::<String,_>("view_id")!=view_id||hash(&json!({"request":request,"response":response}))!=receipt_id{return Err("View receipt provenance mismatch".into());}Ok(observed)}
pub(super) async fn historical(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,ver:i64)->StoreResult<Option<Value>>{let row=sqlx::query("SELECT snapshot,receipt_id FROM workspace_database_view_history WHERE view_id=? AND version=?").bind(view_id).bind(ver).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{return Ok(None);};let value:Value=serde_json::from_str(&row.get::<String,_>("snapshot")).map_err(|_|"Corrupt View history")?;if snapshot(c,source,view_id,&value)?!=ver||receipt(tx,c,source,view_id,&row.get::<String,_>("receipt_id")).await?["snapshot"]!=value{return Err("View history differs from receipt".into());}Ok(Some(value))}
pub(super) async fn current(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str)->StoreResult<Option<Value>>{let row=sqlx::query("SELECT source_id,version,(SELECT max(version) FROM workspace_database_view_history WHERE view_id=r.view_id) AS latest FROM workspace_database_views r WHERE view_id=?").bind(view_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;let Some(row)=row else{let existing:Option<i64>=sqlx::query_scalar("SELECT 1 FROM workspace_database_view_history WHERE view_id=? LIMIT 1").bind(view_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;if existing.is_some(){return Err("Missing View projection".into());}return Ok(None);};let ver=row.get::<i64,_>("version");let record=historical(tx,c,source,view_id,ver).await?.ok_or("Missing View history")?;if row.get::<String,_>("source_id")!=text(source,"id")?||row.get::<Option<i64>,_>("latest")!=Some(ver){return Err("View projection mismatch".into());}Ok(Some(record))}
async fn known_fields(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,snapshot:&Value,candidate:&Value)->StoreResult<()> {let view_id=text(&snapshot["view"],"id")?;let key=text(candidate,"field")?;for state in ["base","remote"]{let ver=version(&candidate[format!("{state}Version")])?;if let Some(saved)=historical(tx,c,source,view_id,ver).await?{if candidate[state]!=saved["view"][key]{return Err("View candidate differs from known history".into());}}}Ok(())}
async fn resolution(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,core:&Value,resolved:&Option<String>,proof:&Option<String>)->StoreResult<()> {match (resolved,proof){(None,None)=>Ok(()),(Some(value),Some(proof))=>{id(value)?;let saved=receipt(tx,c,source,view_id,proof).await?;if saved["_resolution"]!=*value||!saved["conflicts"].as_array().ok_or("Missing resolution candidate")?.contains(core){return Err("Candidate resolution provenance mismatch".into());}Ok(())},_=>Err("Partial candidate resolution".into())}}
pub(super) async fn checked_candidate(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,candidate_id:&str)->StoreResult<Value>{id(candidate_id)?;let current=current(tx,c,source,view_id).await?.ok_or("Missing candidate View")?;let row=sqlx::query("SELECT record,receipt_id,resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts WHERE view_id=? AND id=?").bind(view_id).bind(candidate_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let mut core:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt View candidate")?;conflict(c,source,&current,&core)?;if core["id"]!=candidate_id{return Err("View candidate index mismatch".into());}let origin=receipt(tx,c,source,view_id,&row.get::<String,_>("receipt_id")).await?;if !origin["conflicts"].as_array().ok_or("Missing candidate provenance")?.contains(&core){return Err("View candidate lacks original proof".into());}known_fields(tx,c,source,&current,&core).await?;let resolved=row.get::<Option<String>,_>("resolved_by");resolution(tx,c,source,view_id,&core,&resolved,&row.get::<Option<String>,_>("resolution_receipt_id")).await?;if let Some(value)=resolved{core["resolvedBy"]=json!(value);}Ok(core)}
pub(super) async fn confirm_resolution(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,candidate:&Value,operation_id:&str,proof:&str)->StoreResult<()> {id(operation_id)?;let observed=checked_candidate(tx,c,source,view_id,text(candidate,"id")?).await?;let mut core=observed.clone();core["resolvedBy"]=Value::Null;if core!=*candidate||observed["resolvedBy"].as_str().is_some_and(|value|value!=operation_id){return Err("View resolution changed".into());}sqlx::query("UPDATE workspace_database_view_conflicts SET resolved_by=coalesce(resolved_by,?),resolution_receipt_id=coalesce(resolution_receipt_id,?) WHERE view_id=? AND id=?").bind(operation_id).bind(proof).bind(view_id).bind(text(candidate,"id")?).execute(&mut **tx).await.map_err(|e|e.to_string())?;if checked_candidate(tx,c,source,view_id,text(candidate,"id")?).await?["resolvedBy"]!=operation_id{return Err("View resolution missing".into());}Ok(())}
 pub(super) async fn apply_change(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,book:&str,event:&Value)->StoreResult<()> {let entity=text(&event["snapshot"]["view"],"id")?;let request=json!({"databaseChangeReceipt":book,"eventOrder":event["order"]});let digest=hash(&json!({"request":request,"response":event}));sqlx::query("INSERT OR IGNORE INTO workspace_database_view_receipts VALUES(?,?,?,?,?)").bind(&digest).bind(text(source,"id")?).bind(entity).bind(request.to_string()).bind(event.to_string()).execute(&mut **tx).await.map_err(|e|e.to_string())?;let observed=receipt(tx,c,source,entity,&digest).await?;save(tx,c,source,entity,&observed,&digest).await?;
 if !event["conflict"].is_null(){let key=text(&event["conflict"],"id")?;let row=sqlx::query("SELECT record,resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts WHERE view_id=? AND id=?").bind(entity).bind(key).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let core:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt candidate core")?;let resolved=row.get::<Option<String>,_>("resolved_by");let proof=row.get::<Option<String>,_>("resolution_receipt_id");resolution(tx,c,source,entity,&core,&resolved,&proof).await?;if let Some(value)=event["conflict"]["resolvedBy"].as_str(){id(value)?;if resolved.as_ref().is_some_and(|old|old!=value){return Err("Candidate resolution changed".into());}sqlx::query("UPDATE workspace_database_view_conflicts SET resolved_by=coalesce(resolved_by,?),resolution_receipt_id=coalesce(resolution_receipt_id,?) WHERE view_id=? AND id=?").bind(value).bind(&digest).bind(entity).bind(key).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}Ok(())}
pub(super) async fn verify_change(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,book:&str,event:&Value)->StoreResult<()> {let entity=text(&event["snapshot"]["view"],"id")?;let request=json!({"databaseChangeReceipt":book,"eventOrder":event["order"]});let digest=hash(&json!({"request":request,"response":event}));let observed=receipt(tx,c,source,entity,&digest).await?;let saved=historical(tx,c,source,entity,version(&event["snapshot"]["version"])?).await?.ok_or("Missing applied database history")?;if saved!=observed["snapshot"]{return Err("Applied database history changed".into());}let latest=current(tx,c,source,entity).await?.ok_or("Missing applied database projection")?;if !event["conflict"].is_null(){let key=text(&event["conflict"],"id")?;let row=sqlx::query("SELECT record,receipt_id,resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts WHERE view_id=? AND id=?").bind(entity).bind(key).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let core:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt applied candidate")?;let mut expected=event["conflict"].clone();expected["resolvedBy"]=Value::Null;if core!=expected{return Err("Applied database candidate changed".into());}conflict(c,source,&latest,&core)?;let provenance=receipt(tx,c,source,entity,&row.get::<String,_>("receipt_id")).await?;if !provenance["conflicts"].as_array().ok_or("Missing candidate receipt")?.contains(&core){return Err("Applied candidate lacks provenance".into());}known_fields(tx,c,source,&latest,&core).await?;let resolved=row.get::<Option<String>,_>("resolved_by");resolution(tx,c,source,entity,&core,&resolved,&row.get::<Option<String>,_>("resolution_receipt_id")).await?;if !event["conflict"]["resolvedBy"].is_null()&&resolved.as_deref()!=event["conflict"]["resolvedBy"].as_str(){return Err("Applied resolution missing".into());}}Ok(())}
pub(super) async fn save(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,view_id:&str,response:&Value,receipt_id:&str)->StoreResult<()> {let source_id=text(source,"id")?;let ver=snapshot(c,source,view_id,&response["snapshot"])?;let before=current(tx,c,&source,view_id).await?;
  if let Some(old)=historical(tx,c,&source,view_id,ver).await?{if old!=response["snapshot"]{return Err("View version reused".into());}}else{sqlx::query("INSERT INTO workspace_database_view_history VALUES(?,?,?,?)").bind(view_id).bind(ver).bind(response["snapshot"].to_string()).bind(receipt_id).execute(&mut **tx).await.map_err(|e|e.to_string())?;}
  if before.as_ref().is_none_or(|record|record["version"].as_i64().unwrap()<ver){sqlx::query("INSERT INTO workspace_database_views VALUES(?,?,?) ON CONFLICT(view_id) DO UPDATE SET version=excluded.version").bind(view_id).bind(source_id).bind(ver).execute(&mut **tx).await.map_err(|e|e.to_string())?;}
  for candidate in response["conflicts"].as_array().unwrap(){known_fields(tx,c,&source,&response["snapshot"],candidate).await?;let old:Option<String>=sqlx::query_scalar("SELECT record FROM workspace_database_view_conflicts WHERE view_id=? AND id=?").bind(view_id).bind(text(candidate,"id")?).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;if let Some(old)=old{let old:Value=serde_json::from_str(&old).map_err(|_|"Corrupt candidate")?;if old!=*candidate{return Err("Candidate ID reused".into());}}else{sqlx::query("INSERT INTO workspace_database_view_conflicts(view_id,id,record,receipt_id) VALUES(?,?,?,?)").bind(view_id).bind(text(candidate,"id")?).bind(candidate.to_string()).bind(receipt_id).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}
  // A newly observed older baseline can corroborate or contradict candidates
  // already cached from a seed snapshot. Check affected rows in bounded pages
  // before admitting the new historical observation, without inventing history.
  let projected=if before.as_ref().is_some_and(|record|record["version"].as_i64().unwrap()>ver){before.as_ref().unwrap()}else{&response["snapshot"]};let mut after=String::new();loop{let rows=sqlx::query("SELECT id,record,receipt_id,resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts WHERE view_id=? AND (json_extract(record,'$.baseVersion')=? OR json_extract(record,'$.remoteVersion')=?) AND id>? ORDER BY id LIMIT 100").bind(view_id).bind(ver).bind(ver).bind(&after).fetch_all(&mut **tx).await.map_err(|e|e.to_string())?;if rows.is_empty(){break;}for row in rows{let candidate:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt known candidate")?;conflict(c,&source,projected,&candidate)?;let saved=receipt(tx,c,&source,view_id,&row.get::<String,_>("receipt_id")).await?;if candidate["id"]!=row.get::<String,_>("id")||!saved["conflicts"].as_array().unwrap().contains(&candidate){return Err("Known candidate provenance mismatch".into());}resolution(tx,c,&source,view_id,&candidate,&row.get::<Option<String>,_>("resolved_by"),&row.get::<Option<String>,_>("resolution_receipt_id")).await?;known_fields(tx,c,&source,projected,&candidate).await?;after=text(&candidate,"id")?.into();}}

Ok(())}
impl PageStore {
 pub(super) async fn database_view_receive(&self,c:&WorkspaceContext,source_id:&str,view_id:&str,request:Value,response:Value)->StoreResult<()> {let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;pair(c,&source,view_id,&request,&response)?;let hash=hash(&json!({"request":request,"response":response}));let old:Option<String>=sqlx::query_scalar("SELECT id FROM workspace_database_view_receipts WHERE id=?").bind(&hash).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;if old.is_some(){if receipt(&mut tx,c,&source,view_id,&hash).await?!=response{return Err("View receipt reused".into());}}else{sqlx::query("INSERT INTO workspace_database_view_receipts VALUES(?,?,?,?,?)").bind(&hash).bind(source_id).bind(view_id).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;}
  save(&mut tx,c,&source,view_id,&response,&hash).await?;
  barrier("workspace-database-view-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-view-after-commit")
 }
 pub(super) async fn database_view_load(&self,c:&WorkspaceContext,source_id:&str,view_id:&str,after:Option<&str>,limit:usize)->StoreResult<Value>{id(view_id)?;if !(1..=20).contains(&limit){return Err("Invalid cached candidate limit".into());}if let Some(value)=after{id(value)?;}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let record=current(&mut tx,c,&source,view_id).await?;let rows=sqlx::query("SELECT id,record,receipt_id,resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts WHERE view_id=? AND (? IS NULL OR id>?) ORDER BY id LIMIT ?").bind(view_id).bind(after).bind(after).bind((limit+1) as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let more=rows.len()>limit;let mut conflicts=Vec::new();for row in rows{let candidate:Value=serde_json::from_str(&row.get::<String,_>("record")).map_err(|_|"Corrupt cached candidate")?;let record=record.as_ref().ok_or("Candidate without View")?;conflict(c,&source,record,&candidate)?;if candidate["id"]!=row.get::<String,_>("id"){return Err("Candidate identity mismatch".into());}let saved=receipt(&mut tx,c,&source,view_id,&row.get::<String,_>("receipt_id")).await?;if !saved["conflicts"].as_array().unwrap().contains(&candidate){return Err("Candidate lacks receipt provenance".into());}known_fields(&mut tx,c,&source,record,&candidate).await?;let resolved=row.get::<Option<String>,_>("resolved_by");resolution(&mut tx,c,&source,view_id,&candidate,&resolved,&row.get::<Option<String>,_>("resolution_receipt_id")).await?;let mut candidate=candidate;if let Some(value)=resolved{candidate["resolvedBy"]=json!(value);}conflicts.push(candidate);}conflicts.truncate(limit);let next=if more{conflicts.last().unwrap()["id"].clone()}else{Value::Null};tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"snapshot":record,"conflicts":conflicts,"nextAfter":next}))}
 pub(super) async fn database_view_list(&self,c:&WorkspaceContext,source_id:&str,after:Option<&str>,limit:usize)->StoreResult<Value>{if !(1..=100).contains(&limit){return Err("Invalid local View limit".into());}if let Some(value)=after{id(value)?;}let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let ids:Vec<String>=sqlx::query_scalar("SELECT view_id FROM workspace_database_views WHERE source_id=? AND (? IS NULL OR view_id>?) ORDER BY view_id LIMIT ?").bind(source_id).bind(after).bind(after).bind((limit+1) as i64).fetch_all(&mut *tx).await.map_err(|e|e.to_string())?;let more=ids.len()>limit;let mut records=Vec::new();for view_id in ids{let value=current(&mut tx,c,&source,&view_id).await?.ok_or("Missing listed View")?;records.push(json!({"id":view_id,"name":value["view"]["name"],"layout":value["view"]["layout"],"version":value["version"]}));}records.truncate(limit);let next=if more{records.last().unwrap()["id"].clone()}else{Value::Null};tx.commit().await.map_err(|e|e.to_string())?;Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"views":records,"nextAfter":next}))}
}
