use super::{PageStore,StoreResult,WorkspaceContext};
use super::private_database::{exact,text,id,version,source_definition};
use super::private_database_record::hash;
use super::private_page::{decode,encode};
use serde_json::{json,Value};
use sqlx::{Row,Sqlite,Transaction};
const EVENT_BYTES:usize=64*1024*1024;
fn order(raw:&str)->StoreResult<i64>{let n=raw.parse::<i64>().map_err(|_|"Invalid database order")?;if n<0||n.to_string()!=raw{return Err("Invalid database order".into());}Ok(n)}
fn cursor(raw:&str,c:&WorkspaceContext,source:&Value,epoch:&str,at:i64)->StoreResult<()>{if raw.len()>1024{return Err("Database cursor too long".into());}let parts:Vec<_>=raw.split('.').collect();if parts.len()!=3||parts[0]!="gdb1"||decode(parts[2])?.len()!=32{return Err("Invalid database cursor envelope".into());}let bytes=decode(parts[1])?;let value:Value=serde_json::from_slice(&bytes).map_err(|_|"Invalid database cursor payload")?;if value!=json!([c.workspace_id,c.stream_epoch,c.client_id,source["id"],epoch,at.to_string()])||encode(value.to_string().as_bytes())!=parts[1]{return Err("Database cursor scope mismatch".into());}Ok(())}
fn event(c:&WorkspaceContext,source:&Value,v:&Value)->StoreResult<()>{if order(text(v,"order")?)?==0{return Err("Database event zero".into());}let kind=text(v,"kind")?;let cf=&v["conflict"];let mut core=cf.clone();if !cf.is_null(){if !cf.as_object().is_some_and(|o|o.contains_key("resolvedBy")){return Err("Invalid database candidate object".into());}if !cf["resolvedBy"].is_null(){id(text(cf,"resolvedBy")?)?;}core["resolvedBy"]=Value::Null;}
 match kind{"record"=>{exact(v,&["kind","order","record","conflict"])?;super::private_database_record::snapshot(c,source,text(&v["record"],"id")?,&v["record"])?;if !cf.is_null(){super::private_database_record::conflict(c,source,&v["record"],&core)?;}},"view"=>{exact(v,&["kind","order","snapshot","conflict"])?;super::private_database_view::snapshot(c,source,text(&v["snapshot"]["view"],"id")?,&v["snapshot"])?;if !cf.is_null(){super::private_database_view::conflict(c,source,&v["snapshot"],&core)?;}},_=>return Err("Invalid database event kind".into())}Ok(())}
struct Packet{after:i64,read:i64,head:i64,more:bool}
fn packet(c:&WorkspaceContext,source:&Value,request:&Value,response:&Value)->StoreResult<Packet>{exact(request,&["protocolVersion","clientId","cursor","limit"])?;exact(response,&["protocolVersion","workspaceId","workspaceEpoch","clientId","sourceId","schemaVersion","journalEpoch","afterOrder","readOrder","headOrder","events","hasMore","cursor"])?;
 if request["protocolVersion"]!=1||request["clientId"]!=c.client_id||response["protocolVersion"]!=1||response["workspaceId"]!=c.workspace_id||response["workspaceEpoch"]!=c.stream_epoch||response["clientId"]!=c.client_id||response["sourceId"]!=source["id"]||response["schemaVersion"]!=source["schemaVersion"]{return Err("Database packet scope mismatch".into());}version(&response["schemaVersion"])?;
 let limit=request["limit"].as_u64().filter(|n|(1..=100).contains(n)).ok_or("Invalid database window limit")?;let after=order(text(response,"afterOrder")?)?;let read=order(text(response,"readOrder")?)?;let head=order(text(response,"headOrder")?)?;let more=response["hasMore"].as_bool().ok_or("Invalid database continuation")?;if after>read||read>head||more!=(read<head)||(more&&read==after)||(read-after) as u64>limit{return Err("Invalid database window progress".into());}
 let epoch=text(response,"journalEpoch")?;id(epoch)?;cursor(text(response,"cursor")?,c,source,epoch,read)?;if request["cursor"].is_null(){if after!=0{return Err("Invalid initial database order".into());}}else{cursor(text(request,"cursor")?,c,source,epoch,after)?;}
 let events=response["events"].as_array().filter(|rows|rows.len()<=limit as usize).ok_or("Invalid database event count")?;let mut previous=after;let mut bytes=0usize;for item in events{event(c,source,item)?;let at=order(text(item,"order")?)?;if at<=previous||at>read{return Err("Invalid database event order".into());}previous=at;bytes=bytes.checked_add(item.to_string().len()).ok_or("Database event byte overflow")?;if bytes>EVENT_BYTES{return Err("Database event byte limit".into());}}Ok(Packet{after,read,head,more})}
#[cfg(feature="crash-test-hooks")]
fn barrier(stage:&str)->StoreResult<()>{super::structured_sync::crash_barrier(stage)}
#[cfg(not(feature="crash-test-hooks"))]
fn barrier(_stage:&str)->StoreResult<()>{Ok(())}
pub(super) async fn initialize(tx:&mut Transaction<'_,Sqlite>,old:i64)->StoreResult<()>{if [0,5,6,7,8,9,10,11].contains(&old){for sql in [
 "CREATE TABLE workspace_database_change_receipts(id TEXT PRIMARY KEY NOT NULL,source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),after_order INTEGER NOT NULL CHECK(after_order>=0),read_order INTEGER NOT NULL CHECK(read_order>=after_order),request TEXT NOT NULL CHECK(json_valid(request)),response TEXT NOT NULL CHECK(json_valid(response))) STRICT",
 "CREATE TABLE workspace_database_change_events(source_id TEXT NOT NULL REFERENCES workspace_database_sources(source_id),server_order INTEGER NOT NULL CHECK(server_order>0),event TEXT NOT NULL CHECK(json_valid(event)),receipt_id TEXT NOT NULL REFERENCES workspace_database_change_receipts(id),PRIMARY KEY(source_id,server_order)) STRICT",
 "CREATE TABLE workspace_database_progress(source_id TEXT PRIMARY KEY NOT NULL REFERENCES workspace_database_sources(source_id),journal_epoch TEXT NOT NULL,server_order INTEGER NOT NULL CHECK(server_order>=0),cursor TEXT NOT NULL,head_order INTEGER NOT NULL CHECK(head_order>=server_order),has_more INTEGER NOT NULL CHECK(has_more IN(0,1)),receipt_id TEXT NOT NULL REFERENCES workspace_database_change_receipts(id)) STRICT",
 "ALTER TABLE workspace_database_record_conflicts ADD COLUMN resolved_by TEXT",
 "ALTER TABLE workspace_database_record_conflicts ADD COLUMN resolution_receipt_id TEXT REFERENCES workspace_database_record_receipts(id)",
 "ALTER TABLE workspace_database_view_conflicts ADD COLUMN resolved_by TEXT",
 "ALTER TABLE workspace_database_view_conflicts ADD COLUMN resolution_receipt_id TEXT REFERENCES workspace_database_view_receipts(id)",
 "CREATE INDEX workspace_database_change_receipt_source ON workspace_database_change_receipts(source_id,read_order)",
 "PRAGMA user_version=12"
 ]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}}
 for sql in ["SELECT id,source_id,after_order,read_order,request,response FROM workspace_database_change_receipts LIMIT 0","SELECT source_id,server_order,event,receipt_id FROM workspace_database_change_events LIMIT 0","SELECT source_id,journal_epoch,server_order,cursor,head_order,has_more,receipt_id FROM workspace_database_progress LIMIT 0","SELECT resolved_by,resolution_receipt_id FROM workspace_database_record_conflicts LIMIT 0","SELECT resolved_by,resolution_receipt_id FROM workspace_database_view_conflicts LIMIT 0"]{sqlx::query(sql).execute(&mut **tx).await.map_err(|e|e.to_string())?;}Ok(())}
async fn book(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,digest:&str)->StoreResult<Value>{let row=sqlx::query("SELECT source_id,after_order,read_order,request,response FROM workspace_database_change_receipts WHERE id=?").bind(digest).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let request:Value=serde_json::from_str(&row.get::<String,_>("request")).map_err(|_|"Corrupt database change request")?;let response:Value=serde_json::from_str(&row.get::<String,_>("response")).map_err(|_|"Corrupt database change response")?;let p=packet(c,source,&request,&response)?;if row.get::<String,_>("source_id")!=text(source,"id")?||row.get::<i64,_>("after_order")!=p.after||row.get::<i64,_>("read_order")!=p.read||hash(&json!({"request":request,"response":response}))!=digest{return Err("Database change receipt provenance mismatch".into());}Ok(response)}
async fn stored_events(tx:&mut Transaction<'_,Sqlite>,source:&Value,digest:&str,response:&Value)->StoreResult<()>{for expected in response["events"].as_array().ok_or("Missing database events")?{let row=sqlx::query("SELECT event,receipt_id FROM workspace_database_change_events WHERE source_id=? AND server_order=?").bind(text(source,"id")?).bind(order(text(expected,"order")?)?).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;let value:Value=serde_json::from_str(&row.get::<String,_>("event")).map_err(|_|"Corrupt database event")?;if value!=*expected||row.get::<String,_>("receipt_id")!=digest{return Err("Database event differs from receipt".into());}}Ok(())}
async fn progress(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value)->StoreResult<Value>{let source_id=text(source,"id")?;let row=sqlx::query("SELECT journal_epoch,server_order,cursor,head_order,has_more,receipt_id FROM workspace_database_progress WHERE source_id=?").bind(source_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;
 let Some(row)=row else{let orphan:Option<i64>=sqlx::query_scalar("SELECT 1 FROM workspace_database_change_receipts WHERE source_id=? LIMIT 1").bind(source_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?;if orphan.is_some(){return Err("Missing database progress".into());}return Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"journalEpoch":null,"order":"0","cursor":null,"headOrder":"0","hasMore":false,"received":false}));};
 let digest=row.get::<String,_>("receipt_id");let response=book(tx,c,source,&digest).await?;stored_events(tx,source,&digest,&response).await?;let at=row.get::<i64,_>("server_order");let latest:Option<i64>=sqlx::query_scalar("SELECT max(read_order) FROM workspace_database_change_receipts WHERE source_id=?").bind(source_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;
 if response["journalEpoch"]!=row.get::<String,_>("journal_epoch")||response["readOrder"]!=at.to_string()||response["cursor"]!=row.get::<String,_>("cursor")||response["headOrder"]!=row.get::<i64,_>("head_order").to_string()||response["hasMore"]!=row.get::<bool,_>("has_more")||latest!=Some(at){return Err("Database progress differs from receipt".into());}Ok(json!({"context":c,"sourceId":source_id,"schemaVersion":source["schemaVersion"],"journalEpoch":response["journalEpoch"],"order":response["readOrder"],"cursor":response["cursor"],"headOrder":response["headOrder"],"hasMore":response["hasMore"],"received":true}))}
pub(super) async fn observed_event(tx:&mut Transaction<'_,Sqlite>,c:&WorkspaceContext,source:&Value,digest:&str,raw_order:&str)->StoreResult<Value>{let at=order(raw_order)?;if at==0{return Err("Invalid observed event order".into());}let response=book(tx,c,source,digest).await?;stored_events(tx,source,digest,&response).await?;let saved=progress(tx,c,source).await?;if saved["journalEpoch"]!=response["journalEpoch"]||at>order(text(&saved,"order")?)?{return Err("Database observation beyond progress".into());}let found=response["events"].as_array().unwrap().iter().find(|event|event["order"]==raw_order).ok_or("Database event absent from receipt")?;Ok(found.clone())}
impl PageStore{
 pub(super) async fn database_changes_load(&self,c:&WorkspaceContext,source_id:&str)->StoreResult<Value>{let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let saved=progress(&mut tx,c,&source).await?;tx.commit().await.map_err(|e|e.to_string())?;Ok(saved)}
 pub(super) async fn database_changes_receive(&self,c:&WorkspaceContext,source_id:&str,request:Value,response:Value)->StoreResult<()> {let mut tx=self.pool.begin().await.map_err(|e|e.to_string())?;let source=source_definition(&mut tx,c,source_id).await?;let p=packet(c,&source,&request,&response)?;let saved=progress(&mut tx,c,&source).await?;let digest=hash(&json!({"request":request,"response":response}));let old:Option<String>=sqlx::query_scalar("SELECT id FROM workspace_database_change_receipts WHERE id=?").bind(&digest).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;
 if old.is_some(){if book(&mut tx,c,&source,&digest).await?!=response{return Err("Database change receipt reused".into());}for item in response["events"].as_array().unwrap(){observed_event(&mut tx,c,&source,&digest,text(item,"order")?).await?;if item["kind"]=="record"{super::private_database_record::verify_change(&mut tx,c,&source,&digest,item).await?;}else{super::private_database_view::verify_change(&mut tx,c,&source,&digest,item).await?;}}tx.commit().await.map_err(|e|e.to_string())?;return Ok(());}
 if saved["order"]!=p.after.to_string()||saved["cursor"]!=request["cursor"]||(saved["received"]==true&&saved["journalEpoch"]!=response["journalEpoch"]){return Err("Database change base mismatch".into());}
 sqlx::query("INSERT INTO workspace_database_change_receipts VALUES(?,?,?,?,?,?)").bind(&digest).bind(source_id).bind(p.after).bind(p.read).bind(request.to_string()).bind(response.to_string()).execute(&mut *tx).await.map_err(|e|e.to_string())?;
 for item in response["events"].as_array().unwrap(){sqlx::query("INSERT INTO workspace_database_change_events VALUES(?,?,?,?)").bind(source_id).bind(order(text(item,"order")?)?).bind(item.to_string()).bind(&digest).execute(&mut *tx).await.map_err(|e|e.to_string())?;}
 // Publish progress inside this transaction before verifying event provenance;
 // every projection/candidate below must succeed before this can commit.
 sqlx::query("INSERT INTO workspace_database_progress VALUES(?,?,?,?,?,?,?) ON CONFLICT(source_id) DO UPDATE SET journal_epoch=excluded.journal_epoch,server_order=excluded.server_order,cursor=excluded.cursor,head_order=excluded.head_order,has_more=excluded.has_more,receipt_id=excluded.receipt_id").bind(source_id).bind(text(&response,"journalEpoch")?).bind(p.read).bind(text(&response,"cursor")?).bind(p.head).bind(p.more).bind(&digest).execute(&mut *tx).await.map_err(|e|e.to_string())?;
 for item in response["events"].as_array().unwrap(){if item["kind"]=="record"{super::private_database_record::apply_change(&mut tx,c,&source,&digest,item).await?;}else{super::private_database_view::apply_change(&mut tx,c,&source,&digest,item).await?;}}
 progress(&mut tx,c,&source).await?;barrier("workspace-database-changes-before-commit")?;tx.commit().await.map_err(|e|e.to_string())?;barrier("workspace-database-changes-after-commit")
 }
}
