import {useEffect,useState,useRef} from 'react';
import {newId} from '@greiva/shared';
import type {Page,PushOperation,Task,Relation,Conflict} from '@greiva/protocol';
import type {PrivateStructuredSession} from './private-structured-session';
type TaskDraft={id:string|null;base:number|null;title:string;status:Task['status'];due:string};
type RelationDraft={id:string|null;base:number|null;from:string;to:string};
const emptyTask=():TaskDraft=>({id:null,base:null,title:'',status:'todo',due:''});
const emptyRelation=():RelationDraft=>({id:null,base:null,from:'',to:''});
const statusLabels={todo:'未着手',in_progress:'進行中',done:'完了'};
const fieldLabels={title:'タイトル',status:'状態',due:'期限',fromType:'元の種類',fromId:'元の参照先',toType:'先の種類',toId:'先の参照先'};
function display(value:unknown){return value===null?'未設定':typeof value==='string'?value:JSON.stringify(value);}
export function PrivateStructuredPanel({session,pages,onDraftChange}:{session:PrivateStructuredSession;pages:readonly Pick<Page,'id'|'title'>[];onDraftChange:(blocked:boolean)=>void}){
 const [state,setState]=useState(session.snapshot),[task,setTask]=useState(emptyTask),[relation,setRelation]=useState(emptyRelation),[taskDirty,setTaskDirty]=useState(false),[relationDirty,setRelationDirty]=useState(false),[composing,setComposing]=useState(false),[formError,setFormError]=useState(false);
 const taskInput=useRef<HTMLInputElement>(null),relationInput=useRef<HTMLSelectElement>(null);
 useEffect(()=>session.subscribe(setState),[session]);
 useEffect(()=>{onDraftChange(taskDirty||relationDirty||composing);return()=>onDraftChange(false);},[onDraftChange,taskDirty,relationDirty,composing]);
 useEffect(()=>{if(task.id)taskInput.current?.focus();},[task.id]);useEffect(()=>{if(relation.id)relationInput.current?.focus();},[relation.id]);
 if(state.phase!=='ready'||!state.data)return null;
 const locked=state.busy||state.retryMutation,otherBlocked=locked||taskDirty||relationDirty||composing;
 const tasks=state.data.tasks.filter(row=>!row.deletedAt),relations=state.data.relations.filter(row=>!row.deletedAt),conflicts=state.data.conflicts.filter(row=>row.status==='open');
 const endpoints=[...pages.map(row=>({value:'page:'+row.id,label:'Page: '+(row.title||'無題')})),...tasks.map(row=>({value:'task:'+row.id,label:'Task: '+(row.title||'無題')}))];
 const endpointLabel=(type:string,id:string)=>endpoints.find(row=>row.value===type+':'+id)?.label??`${type}: ${id}`;
 const entityLabel=(type:'task'|'relation',id:string)=>{if(type==='task')return endpointLabel('task',id);const row=state.data!.relations.find(value=>value.id===id);return row?endpointLabel(row.fromType,row.fromId)+' → '+endpointLabel(row.toType,row.toId):'Relation';};
 const conflictValue=(conflict:Conflict,value:unknown)=>{if(conflict.field==='status'&&typeof value==='string'&&Object.hasOwn(statusLabels,value))return statusLabels[value as Task['status']];if((conflict.field==='fromId'||conflict.field==='toId')&&typeof value==='string')return endpoints.find(row=>row.value.slice(5)===value)?.label??value;return display(value);};
 function operation(entityType:PushOperation['entityType'],entityId:string,kind:PushOperation['kind'],baseVersion:number|null,payload:unknown):PushOperation{return {operationId:newId(),clientId:state.data!.clientId!,entityType,entityId,kind,baseVersion,payload};}
 async function mutate(value:PushOperation,done:()=>void=()=>{}){if(composing||locked)return;setFormError(false);try{await session.mutate(value);done();}catch{setFormError(true);}}
 function reset(){setTask(emptyTask());setRelation(emptyRelation());setTaskDirty(false);setRelationDirty(false);setFormError(false);}
 async function resolve(conflict:Conflict,choice:'local'|'remote'){const rows=conflict.entityType==='task'?state.data!.tasks:state.data!.relations,row=rows.find(entity=>entity.id===conflict.entityId);if(!row||row.deletedAt){setFormError(true);return;}const value=operation(conflict.entityType,conflict.entityId,'update',row.version,{[conflict.field]:conflict[choice]});value.resolution={conflictIds:[conflict.id],choice};await mutate(value);}
 const syncLabel=composing?'入力変換中…':state.busy?'保存・同期処理中…':state.retryMutation?'端末の保存結果を再確認してください':taskDirty||relationDirty?'入力内容はまだ保存していません':state.error?'同期を確認できませんでした':state.rejected?'拒否された更新があります':state.conflicts?'競合を確認してください':state.pending?`未確認の更新 ${state.pending}件`:state.hasMore?'サーバーに続きの更新があります':state.synced?'取得した更新まで同期済み':'同期はまだ確認していません';
 return <section aria-label="TaskとRelation" className="private-structured" onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)}>
  <h2>TaskとRelation</h2><output aria-label="TaskとRelationの同期状態" aria-live="polite">{syncLabel}</output>
  <div className="connection-tools"><button type="button" disabled={otherBlocked} onClick={()=>{void session.sync().catch(()=>{});}}>{state.hasMore?'続きの更新を取得':'TaskとRelationを同期'}</button>
   {state.retryMutation&&<button type="button" disabled={state.busy||composing} onClick={()=>{void session.retryMutation().then(reset,()=>setFormError(true));}}>同じ更新の保存を再確認</button>}
  </div>
  {(taskDirty||relationDirty)&&<p role="status">入力中の内容があります。保存または入力を取り消してから接続を切り替えてください。</p>}
  {(formError||state.error)&&<p role="alert">{state.retryMutation?'保存結果を確認できませんでした。入力をコピーできる状態で保持しています。同じ更新の保存を再確認してください。':state.error==='transport'?'接続できませんでした。端末の更新は保持しています。':'更新を確認できませんでした。入力内容と端末の保存状態を確認してください。'}</p>}
  <div className="structured-forms"><form aria-label="Task編集" onSubmit={event=>{event.preventDefault();if(composing||locked)return;const current=task.id?state.data!.tasks.find(row=>row.id===task.id):null;if(task.id&&(!current||current.deletedAt||current.version!==task.base)){setFormError(true);return;}void mutate(operation('task',task.id??newId(),task.id?'update':'create',task.base,{title:task.title,status:task.status,due:task.due||null}),()=>{setTask(emptyTask());setTaskDirty(false);});}}>
   <h3>{task.id?'Taskを編集':'Taskを作成'}</h3><label>Taskタイトル<input ref={taskInput} value={task.title} readOnly={locked} onChange={event=>{setTask({...task,title:event.target.value});setTaskDirty(true);}}/></label>
   <label>Task状態<select value={task.status} disabled={locked} onChange={event=>{setTask({...task,status:event.target.value as Task['status']});setTaskDirty(true);}}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
   <label>Task期限<input type="date" min="0001-01-01" max="9999-12-31" value={task.due} readOnly={locked} onChange={event=>{setTask({...task,due:event.target.value});setTaskDirty(true);}}/></label>
   <button disabled={locked||composing||relationDirty}>{task.id?'Taskの変更を保存':'Taskを端末に保存'}</button><button type="button" disabled={locked||composing} onClick={()=>{setTask(emptyTask());setTaskDirty(false);setFormError(false);}}>Task入力を取り消す</button>
  </form><form aria-label="Relation編集" onSubmit={event=>{event.preventDefault();if(composing||locked||!relation.from||!relation.to)return;const current=relation.id?state.data!.relations.find(row=>row.id===relation.id):null;if(relation.id&&(!current||current.deletedAt||current.version!==relation.base)){setFormError(true);return;}const [fromType,fromId]=relation.from.split(':'),[toType,toId]=relation.to.split(':');void mutate(operation('relation',relation.id??newId(),relation.id?'update':'create',relation.base,{fromType,fromId,toType,toId}),()=>{setRelation(emptyRelation());setRelationDirty(false);});}}>
   <h3>{relation.id?'Relationを編集':'Relationを作成'}</h3>{(['from','to'] as const).map(field=><label key={field}>{field==='from'?'Relationの元':'Relationの先'}<select ref={field==='from'?relationInput:undefined} value={relation[field]} disabled={locked} required onChange={event=>{setRelation({...relation,[field]:event.target.value});setRelationDirty(true);}}><option value="">選択してください</option>{relation[field]&&!endpoints.some(row=>row.value===relation[field])&&<option value={relation[field]}>保存済みの参照: {relation[field]}</option>}{endpoints.map(row=><option key={row.value} value={row.value}>{row.label}</option>)}</select></label>)}
   <p className="editor-hint">参照先もサーバーに保存されている必要があります。未送信のPageは本文の同期後に関連付けてください。</p>
   <button disabled={locked||composing||taskDirty||!relation.from||!relation.to}>{relation.id?'Relationの変更を保存':'Relationを端末に保存'}</button><button type="button" disabled={locked||composing} onClick={()=>{setRelation(emptyRelation());setRelationDirty(false);setFormError(false);}}>Relation入力を取り消す</button>
  </form></div>
  <h3>Task一覧</h3>{!tasks.length&&<p>Taskはありません。</p>}<ul>{tasks.map(row=><li key={row.id}><strong>{row.title||'無題のTask'}</strong><span>{statusLabels[row.status]}{row.due?' / '+row.due:''}</span><div className="connection-tools"><button type="button" aria-label={'Taskを編集: '+(row.title||'無題')} disabled={otherBlocked} onClick={()=>{setTask({id:row.id,base:row.version,title:row.title,status:row.status,due:row.due??''});}}>編集</button><button type="button" aria-label={'Taskを削除: '+(row.title||'無題')} disabled={otherBlocked} onClick={()=>{void mutate(operation('task',row.id,'delete',row.version,{}));}}>削除</button></div></li>)}</ul>
  <h3>Relation一覧</h3>{!relations.length&&<p>Relationはありません。</p>}<ul>{relations.map(row=><li key={row.id}><span>{endpointLabel(row.fromType,row.fromId)} → {endpointLabel(row.toType,row.toId)}</span><div className="connection-tools"><button type="button" aria-label={'Relationを編集: '+row.id} disabled={otherBlocked} onClick={()=>setRelation({id:row.id,base:row.version,from:row.fromType+':'+row.fromId,to:row.toType+':'+row.toId})}>編集</button><button type="button" aria-label={'Relationを削除: '+row.id} disabled={otherBlocked} onClick={()=>{void mutate(operation('relation',row.id,'delete',row.version,{}));}}>削除</button></div></li>)}</ul>
  {!!conflicts.length&&<section aria-label="TaskとRelationの競合"><h3>競合</h3>{conflicts.map(conflict=><article key={conflict.id}><h4>{entityLabel(conflict.entityType,conflict.entityId)} / {fieldLabels[conflict.field]}</h4><dl><dt>編集前</dt><dd>{conflictValue(conflict,conflict.base)}</dd><dt>この端末</dt><dd>{conflictValue(conflict,conflict.local)}</dd><dt>サーバー</dt><dd>{conflictValue(conflict,conflict.remote)}</dd></dl>{(['local','remote'] as const).map(choice=><button key={choice} type="button" disabled={otherBlocked||state.data!.operations.some(row=>row.entityId===conflict.entityId&&row.entityType===conflict.entityType&&row.status==='pending')} onClick={()=>{void resolve(conflict,choice);}}>{choice==='local'?'この端末の値を選ぶ':'サーバーの値を選ぶ'}</button>)}</article>)}</section>}
  {state.rejected>0&&<section aria-label="拒否された更新"><h3>拒否された更新</h3><p>送信した更新は採用されませんでした。端末の記録を保持しています。</p><ul>{state.data.operations.filter(row=>row.status==='rejected').map(row=><li key={row.operationId}>{row.entityType==='task'?'Task: '+(state.data!.tasks.find(task=>task.id===row.entityId)?.title||'無題'):'Relation'} / {{create:'作成',update:'変更',delete:'削除'}[row.kind]}が拒否されました</li>)}</ul></section>}
 </section>;
}
