import {idSchema,newId} from '@greiva/shared';
import {parseDatabaseRecord,parseDatabaseRecordIntent,parseDatabaseRecordConflict,parseDatabaseViewSnapshot,parseDatabaseViewIntent,parseDatabaseViewConflict,type DatabaseSource,type DatabaseViewField} from '@greiva/domain';
import {isDeepStrictEqual} from 'node:util';
import {privateDatabaseRecordWriteRequestSchema,privateDatabaseRecordWriteResponseSchema} from '@greiva/protocol/private-database-record';
import {privateDatabaseViewWriteRequestSchema,privateDatabaseViewWriteResponseSchema} from '@greiva/protocol/private-database-view';
import {parsePrivateDatabaseChange,type PrivateDatabaseChange} from '@greiva/protocol/private-database-changes';
import {structuredOrderSchema} from '@greiva/protocol/workspace';
import {PrivateTransactionUnavailable,type PrivateTransaction} from './private-transactions.js';
export type DatabaseChangePayload={ [Kind in PrivateDatabaseChange['kind']]:Omit<Extract<PrivateDatabaseChange,{kind:Kind}>,'order'> }[PrivateDatabaseChange['kind']];
export async function initializeDatabaseJournal(tx:PrivateTransaction,schema:string,source:DatabaseSource){
 if(source.workspaceId!==tx.context.workspaceId)throw new PrivateTransactionUnavailable();
 await tx.query(`INSERT INTO "${schema}".private_database_change_heads(source_id,workspace_id,journal_epoch,head_order) VALUES($1,$2,$3,0)`,[source.id,source.workspaceId,newId()]);
}
// Caller holds Source UPDATE. Exact operation replay returns before this helper.
export async function appendDatabaseChange(tx:PrivateTransaction,schema:string,source:DatabaseSource,value:DatabaseChangePayload){
 const gate=await tx.query(`SELECT version FROM "${schema}".private_schema_version WHERE singleton=true`);if(gate.rowCount!==1||gate.rows[0]!.version>11)throw new PrivateTransactionUnavailable();if(gate.rows[0]!.version<11)return;
 const heads=await tx.query(`SELECT workspace_id,journal_epoch,head_order::text FROM "${schema}".private_database_change_heads WHERE source_id=$1 FOR UPDATE`,[source.id]);if(heads.rowCount!==1||heads.rows[0]!.workspace_id!==tx.context.workspaceId||source.workspaceId!==tx.context.workspaceId)throw new PrivateTransactionUnavailable();const head=heads.rows[0]!,epoch=idSchema.safeParse(head.journal_epoch);if(!epoch.success||epoch.data!==epoch.data.toLowerCase())throw new PrivateTransactionUnavailable();structuredOrderSchema.parse(head.head_order);
 const last=await tx.query(`SELECT server_order::text FROM "${schema}".private_database_change_events WHERE source_id=$1 ORDER BY private_database_change_events.server_order DESC LIMIT 1`,[source.id]);if((last.rows[0]?.server_order??'0')!==head.head_order)throw new PrivateTransactionUnavailable();
 const next=await tx.query(`UPDATE "${schema}".private_database_change_heads SET head_order=head_order+1 WHERE source_id=$1 AND head_order<9223372036854775807 RETURNING head_order::text`,[source.id]);if(next.rowCount!==1)throw new PrivateTransactionUnavailable();const event=parsePrivateDatabaseChange(source,{...value,order:next.rows[0]!.head_order}),entityId=event.kind==='record'?event.record.id:event.snapshot.view.id;
 await tx.query(`INSERT INTO "${schema}".private_database_change_events(workspace_id,source_id,server_order,kind,entity_id,event) VALUES($1,$2,$3,$4,$5,$6)`,[source.workspaceId,source.id,event.order,event.kind,entityId,JSON.stringify(event)]);
}
// Both a read-only installer and authenticated pull can check the same immutable
// candidate/history/ledger graph. This does not grant access or settle a client ACK.
export async function verifyDatabaseChangeCandidate(port:Pick<PrivateTransaction,'query'>,schema:string,source:DatabaseSource,workspaceEpoch:string,event:PrivateDatabaseChange){
 if(!event.conflict)return;
 const entityId=event.kind==='record'?event.record.id:event.snapshot.view.id,kind=event.kind,field=event.kind==='record'?(event.conflict as Extract<PrivateDatabaseChange,{kind:'record'}>['conflict'])!.propertyId:(event.conflict as Extract<PrivateDatabaseChange,{kind:'view'}>['conflict'])!.field,immutable={...event.conflict,resolvedBy:null};
 const rows=await port.query(`SELECT operation_id,record,resolved_by FROM "${schema}".private_database_${kind}_conflicts WHERE workspace_id=$1 AND ${kind}_id=$2 AND id=$3`,[source.workspaceId,entityId,immutable.id]);if(rows.rowCount!==1||!isDeepStrictEqual(rows.rows[0]!.record,immutable))throw new PrivateTransactionUnavailable();const row=rows.rows[0]!;
 const snapshot=async(version:number)=>{const history=await port.query(`SELECT snapshot FROM "${schema}".private_database_${kind}_history WHERE ${kind}_id=$1 AND version=$2`,[entityId,version]);if(history.rowCount!==1)throw new PrivateTransactionUnavailable();const value=history.rows[0]!.snapshot;
  if(event.kind==='record'){const record=parseDatabaseRecord(source,value);if(record.id!==entityId||record.pageId!==event.record.pageId||record.version!==version)throw new PrivateTransactionUnavailable();return{value:record,field:{present:Object.hasOwn(record.values,field),value:record.values[field]??null}};}
  const view=parseDatabaseViewSnapshot(source,value);if(view.view.id!==entityId||view.version!==version)throw new PrivateTransactionUnavailable();return{value:view,field:view.view[field as DatabaseViewField]};
 };
 if(!isDeepStrictEqual((await snapshot(immutable.baseVersion)).field,immutable.base)||!isDeepStrictEqual((await snapshot(immutable.remoteVersion)).field,immutable.remote))throw new PrivateTransactionUnavailable();
 const original=await port.query(`SELECT client_id,request,result FROM "${schema}".private_database_${kind}_operations WHERE workspace_id=$1 AND ${kind}_id=$2 AND operation_id=$3`,[source.workspaceId,entityId,row.operation_id]);if(original.rowCount!==1)throw new PrivateTransactionUnavailable();const op=original.rows[0]!;
 if(event.kind==='record'){
  const request=privateDatabaseRecordWriteRequestSchema.parse(op.request),intent=parseDatabaseRecordIntent(source,request.intent),receipt=privateDatabaseRecordWriteResponseSchema.parse(op.result),candidate=parseDatabaseRecordConflict(source,immutable);
  if(intent.kind!=='update'||intent.recordId!==entityId||intent.pageId!==event.record.pageId||intent.baseVersion!==candidate.baseVersion||!Object.hasOwn(intent.values,field)||intent.values[field]!==candidate.local.value||request.operationId!==row.operation_id||request.clientId!==op.client_id||receipt.clientId!==request.clientId||receipt.operationId!==row.operation_id||receipt.workspaceId!==source.workspaceId||receipt.workspaceEpoch!==workspaceEpoch||receipt.sourceId!==source.id||receipt.schemaVersion!==source.schemaVersion||receipt.record.id!==entityId||receipt.result.status!=='conflict'||!receipt.result.conflicts.some(item=>isDeepStrictEqual(item,immutable))||!isDeepStrictEqual((await snapshot(receipt.record.version)).value,receipt.record))throw new PrivateTransactionUnavailable();
 }else{
  const request=privateDatabaseViewWriteRequestSchema.parse(op.request),intent=parseDatabaseViewIntent(source,request.intent),receipt=privateDatabaseViewWriteResponseSchema.parse(op.result),candidate=parseDatabaseViewConflict(source,immutable);
  if(intent.kind!=='update'||intent.viewId!==entityId||intent.baseVersion!==candidate.baseVersion||!isDeepStrictEqual(intent.patch[candidate.field],candidate.local)||request.operationId!==row.operation_id||request.clientId!==op.client_id||receipt.clientId!==request.clientId||receipt.operationId!==row.operation_id||receipt.workspaceId!==source.workspaceId||receipt.workspaceEpoch!==workspaceEpoch||receipt.sourceId!==source.id||receipt.schemaVersion!==source.schemaVersion||receipt.snapshot.view.id!==entityId||receipt.result.status!=='conflict'||!receipt.result.conflicts.some(item=>isDeepStrictEqual(item,immutable))||!isDeepStrictEqual((await snapshot(receipt.snapshot.version)).value,receipt.snapshot))throw new PrivateTransactionUnavailable();
 }
 if(event.conflict.resolvedBy===null)return;
 if(row.resolved_by!==event.conflict.resolvedBy)throw new PrivateTransactionUnavailable();
 const resolved=await port.query(`SELECT client_id,request,result FROM "${schema}".private_database_${kind}_operations WHERE workspace_id=$1 AND ${kind}_id=$2 AND operation_id=$3`,[source.workspaceId,entityId,event.conflict.resolvedBy]);if(resolved.rowCount!==1)throw new PrivateTransactionUnavailable();const resolution=resolved.rows[0]!;
 if(event.kind==='record'){
  const request=privateDatabaseRecordWriteRequestSchema.parse(resolution.request),intent=parseDatabaseRecordIntent(source,request.intent),receipt=privateDatabaseRecordWriteResponseSchema.parse(resolution.result),candidate=parseDatabaseRecordConflict(source,immutable);
  if(intent.kind!=='update'||!intent.resolution||intent.recordId!==entityId||intent.pageId!==event.record.pageId||intent.resolution.conflictId!==candidate.id||intent.resolution.propertyId!==field||intent.resolution.remoteVersion!==candidate.remoteVersion||request.operationId!==event.conflict.resolvedBy||request.clientId!==resolution.client_id||receipt.clientId!==request.clientId||receipt.operationId!==request.operationId||receipt.workspaceId!==source.workspaceId||receipt.workspaceEpoch!==workspaceEpoch||receipt.sourceId!==source.id||receipt.schemaVersion!==source.schemaVersion||receipt.record.id!==entityId||receipt.result.status!=='applied'||intent.values[field]!==candidate[intent.resolution.choice].value||!isDeepStrictEqual((await snapshot(intent.baseVersion)).field,candidate.remote)||!isDeepStrictEqual((await snapshot(receipt.record.version)).value,receipt.record)||!isDeepStrictEqual((await snapshot(receipt.record.version)).field,candidate[intent.resolution.choice]))throw new PrivateTransactionUnavailable();
 }else{
  const request=privateDatabaseViewWriteRequestSchema.parse(resolution.request),intent=parseDatabaseViewIntent(source,request.intent),receipt=privateDatabaseViewWriteResponseSchema.parse(resolution.result),candidate=parseDatabaseViewConflict(source,immutable);
  if(intent.kind!=='update'||!intent.resolution||intent.viewId!==entityId||intent.resolution.conflictId!==candidate.id||intent.resolution.field!==field||intent.resolution.remoteVersion!==candidate.remoteVersion||request.operationId!==event.conflict.resolvedBy||request.clientId!==resolution.client_id||receipt.clientId!==request.clientId||receipt.operationId!==request.operationId||receipt.workspaceId!==source.workspaceId||receipt.workspaceEpoch!==workspaceEpoch||receipt.sourceId!==source.id||receipt.schemaVersion!==source.schemaVersion||receipt.snapshot.view.id!==entityId||receipt.result.status!=='applied'||!isDeepStrictEqual(intent.patch[candidate.field],candidate[intent.resolution.choice])||!isDeepStrictEqual((await snapshot(intent.baseVersion)).field,candidate.remote)||!isDeepStrictEqual((await snapshot(receipt.snapshot.version)).value,receipt.snapshot)||!isDeepStrictEqual((await snapshot(receipt.snapshot.version)).field,candidate[intent.resolution.choice]))throw new PrivateTransactionUnavailable();
 }
}
