import type {PrivateDatabaseChangesResponse} from '@greiva/protocol/private-database-changes';
import {it,expect,vi} from 'vitest';
import {newId} from '@greiva/shared';
import {DatabaseChangesSyncSession,type DatabaseChangesStore} from '@greiva/sync';
function values(reply:PrivateDatabaseChangesResponse){const event=reply.events[0];if(event?.kind!=='record')throw Error('Fixture Record event missing');return event.record.values;}
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){
 const context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},ids={name:newId(),text:newId(),number:newId()},source={id:newId(),workspaceId:context.workspaceId,name:'DB',schemaVersion:1,properties:Object.entries(ids).map(([type,id])=>({id,type,name:type}))},epoch=newId(),record={id:newId(),workspaceId:context.workspaceId,sourceId:source.id,pageId:newId(),version:1,values:{[ids.text]:'base'}};
 const response={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,clientId:context.clientId,sourceId:source.id,schemaVersion:1,journalEpoch:epoch,afterOrder:'0',readOrder:'1',headOrder:'2',events:[{kind:'record',order:'1',record,conflict:null}],hasMore:true,cursor:'cursor-1'};
 const initial={context:structuredClone(context),sourceId:source.id,schemaVersion:1,journalEpoch:null,order:'0',cursor:null,headOrder:'0',hasMore:false,received:false};let saved:unknown=structuredClone(initial);
 const transport={pull:vi.fn(async(..._args:unknown[]):Promise<unknown>=>response)},store={load:vi.fn(async()=>saved),receive:vi.fn<DatabaseChangesStore['receive']>(async(_request,reply)=>{saved={...initial,journalEpoch:reply.journalEpoch,order:reply.readOrder,cursor:reply.cursor,headOrder:reply.headOrder,hasMore:reply.hasMore,received:true};})},session=new DatabaseChangesSyncSession(context,source,{transport,store});
 return{context,source,ids,epoch,record,response,initial,transport,store,session,setSaved:(value:unknown)=>{saved=structuredClone(value);}};
}
it('DB-CHANGES-SESSION: immutable scope/ports and explicit durable-progress pull save typed response; opening/local progress never starts HTTP',async()=>{const f=fixture(),context=structuredClone(f.context),source=structuredClone(f.source),load=f.store.load,receive=f.store.receive;f.context.subjectId='changed';f.source.name='changed';f.store.load=vi.fn(async()=>{throw Error();});f.store.receive=vi.fn(async()=>{});expect(await f.session.progress()).toEqual(f.initial);expect(f.transport.pull).not.toHaveBeenCalled();expect(f.session.context).toEqual(context);expect(f.session.source).toEqual(source);expect(Object.isFrozen(f.session.source.properties)).toBe(true);const result=await f.session.pull(1);expect(result.response).toEqual(f.response);expect(result.progress.order).toBe('1');expect(f.transport.pull).toHaveBeenCalledWith({protocolVersion:1,clientId:context.clientId,cursor:null,limit:1},f.session.signal);expect(receive).toHaveBeenCalledTimes(1);expect(load).toHaveBeenCalledTimes(3);expect(Object.isFrozen(values(result.response))).toBe(true);expect(f.session.retryReceive).toBe(false);});
it('DB-CHANGES-SESSION: scope/source/schema/journal/raw-range/type and looping response reject before receive',async()=>{const f=fixture(),base=f.response;for(const reply of [{...base,workspaceEpoch:newId()},{...base,clientId:newId()},{...base,sourceId:newId()},{...base,schemaVersion:2},{...base,afterOrder:'1',readOrder:'2',headOrder:'2',hasMore:false,events:[]},{...base,readOrder:'2'},{...base,email:'private@example.invalid'},{...base,events:[{...base.events[0]!,record:{...f.record,values:{[f.ids.number]:'bad'}}}]}]){f.transport.pull.mockResolvedValueOnce(reply);await expect(f.session.pull(1)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.receive).not.toHaveBeenCalled();expect(f.session.retryReceive).toBe(false);await f.session.pull(1);f.transport.pull.mockResolvedValueOnce({...base,journalEpoch:newId(),afterOrder:'1',readOrder:'2',events:[],hasMore:false});await expect(f.session.pull(1)).rejects.toMatchObject({stage:'protocol'});f.transport.pull.mockResolvedValueOnce({...base,afterOrder:'1',readOrder:'2',events:[],hasMore:false,cursor:'cursor-1'});await expect(f.session.pull(1)).rejects.toMatchObject({stage:'protocol'});expect(f.store.receive).toHaveBeenCalledTimes(1);});
it('DB-CHANGES-SESSION: corrupt/foreign saved progress and invalid limits fail before network without empty fallback',async()=>{const f=fixture();for(const limit of [0,101,1.5,'1',null,{limit:1}])await expect(f.session.pull(limit)).rejects.toMatchObject({stage:'protocol'});expect(f.store.load).not.toHaveBeenCalled();for(const progress of [{...f.initial,context:{...f.context,subjectId:'foreign'}},{...f.initial,sourceId:newId()},{...f.initial,schemaVersion:2},{...f.initial,order:'1'},{...f.initial,email:'private@example.invalid'}]){f.setSaved(progress);await expect(f.session.pull()).rejects.toMatchObject({stage:'protocol'});}expect(f.transport.pull).not.toHaveBeenCalled();expect(f.session.retryReceive).toBe(false);});
it('DB-CHANGES-SESSION: unknown commit retains exact immutable pair; retry has no HTTP and returns actual newer durable progress',async()=>{const f=fixture(),receive=f.store.receive.getMockImplementation()!;f.store.receive.mockImplementationOnce(async(request,reply)=>{await receive(request,reply);throw Error('private body/token/path');});await expect(f.session.pull(1)).rejects.toThrow('Database changes sync storage');expect(f.session.retryReceive).toBe(true);const pair=structuredClone(f.store.receive.mock.calls[0]);f.response.events[0]!.record.values[f.ids.text]='caller changed';await expect(f.session.pull()).rejects.toMatchObject({stage:'busy'});const newer={...f.initial,journalEpoch:f.epoch,order:'3',cursor:'cursor-3',headOrder:'4',hasMore:true,received:true};f.setSaved(newer);f.store.receive.mockImplementationOnce(async()=>{});const result=await f.session.retry();expect(values(result.response)[f.ids.text]).toBe('base');expect(result.progress).toEqual(newer);expect(f.store.receive.mock.calls[1]).toEqual(pair);expect(f.transport.pull).toHaveBeenCalledTimes(1);expect(f.session.retryReceive).toBe(false);await expect(f.session.retry()).rejects.toMatchObject({stage:'protocol'});});
it('DB-CHANGES-SESSION: post-commit progress failure retains receive pair and storage retry never refetches',async()=>{const f=fixture();f.store.load.mockResolvedValueOnce(f.initial).mockRejectedValueOnce(Error('private'));await expect(f.session.pull(1)).rejects.toMatchObject({stage:'storage'});expect(f.session.retryReceive).toBe(true);expect((await f.session.retry()).progress.order).toBe('1');expect(f.transport.pull).toHaveBeenCalledTimes(1);expect(f.store.receive.mock.calls[0]).toEqual(f.store.receive.mock.calls[1]);});
it('DB-CHANGES-SESSION: false success/rewound or wrong journal progress keeps exact pair without claiming an observation',async()=>{const f=fixture();f.store.receive.mockImplementationOnce(async()=>{});await expect(f.session.pull(1)).rejects.toMatchObject({stage:'protocol'});expect(f.session.retryReceive).toBe(true);f.setSaved({...f.initial,journalEpoch:newId(),order:'1',cursor:'cursor-1',headOrder:'2',hasMore:true,received:true});f.store.receive.mockImplementationOnce(async()=>{});await expect(f.session.retry()).rejects.toMatchObject({stage:'protocol'});expect(f.transport.pull).toHaveBeenCalledTimes(1);await f.session.retry();expect(f.session.retryReceive).toBe(false);});
it('DB-CHANGES-SESSION: transport/load failures preserve private causes and never create receive retry',async()=>{const f=fixture();f.store.load.mockRejectedValueOnce(Error('private'));await expect(f.session.pull()).rejects.toThrow('Database changes sync storage');expect(f.transport.pull).not.toHaveBeenCalled();f.transport.pull.mockRejectedValueOnce(Error('private'));await expect(f.session.pull()).rejects.toThrow('Database changes sync transport');expect(f.store.receive).not.toHaveBeenCalled();expect(f.session.retryReceive).toBe(false);});
it.each(['load','transport','receive','reload'] as const)('DB-CHANGES-SESSION %s: close/busy exclude late work and do not retain a private pair',async boundary=>{const f=fixture(),wait=deferred<unknown>();if(boundary==='load')f.store.load.mockImplementationOnce(()=>wait.promise);if(boundary==='transport')f.transport.pull.mockImplementationOnce(()=>wait.promise);if(boundary==='receive')f.store.receive.mockImplementationOnce(async()=>{await wait.promise;});if(boundary==='reload')f.store.load.mockResolvedValueOnce(f.initial).mockImplementationOnce(()=>wait.promise);const work=f.session.pull(1);await expect.poll(()=>boundary==='load'?f.store.load.mock.calls.length:boundary==='transport'?f.transport.pull.mock.calls.length:boundary==='receive'?f.store.receive.mock.calls.length:f.store.load.mock.calls.length-1).toBe(1);await expect(f.session.progress()).rejects.toMatchObject({stage:'busy'});f.session.close();wait.resolve(boundary==='transport'?f.response:f.initial);await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.session.retryReceive).toBe(false);if(boundary==='load'||boundary==='transport')expect(f.store.receive).not.toHaveBeenCalled();await expect(f.session.retry()).rejects.toMatchObject({stage:'closed'});});
it('DB-CHANGES-SESSION: filtered empty bounded windows advance exact bigint progress without projecting or acknowledging entities',async()=>{const f=fixture(),base={...f.initial,journalEpoch:f.epoch,order:'9007199254740993',cursor:'big-before',headOrder:'9223372036854775807',hasMore:true,received:true};f.setSaved(base);f.transport.pull.mockResolvedValueOnce({...f.response,afterOrder:base.order,readOrder:'9007199254740994',headOrder:base.headOrder,events:[],cursor:'big-after'});const result=await f.session.pull(1);expect(result.response.events).toEqual([]);expect(result.progress.order).toBe('9007199254740994');expect(f.transport.pull.mock.calls[0]![0]).toMatchObject({cursor:'big-before',limit:1});});
it('DB-CHANGES-SESSION: constructor rejects foreign definitions/context before ports can be used',()=>{const f=fixture();for(const source of [{...f.source,workspaceId:newId()},{...f.source,properties:[]}])expect(()=>new DatabaseChangesSyncSession(f.context,source,{transport:f.transport,store:f.store})).toThrow('Database changes sync protocol');expect(()=>new DatabaseChangesSyncSession({...f.context,email:'private@example.invalid'} as any,f.source,{transport:f.transport,store:f.store})).toThrow('Database changes sync protocol');});
