import {it,expect,vi} from 'vitest';
import {newId} from '@greiva/shared';import {AuthSession,PrivateWorkspaceConnection,emptyPageUpdate} from '@greiva/sync';
import {NativeWorkspaceStore,type NativeWorkspaceInvoke} from '../../apps/client/src/workspace/native-workspace-store.js';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
const titleMetadata=(id:string)=>({id,title:'base',yDocId:'page:'+id,createdAt:'2026-10-08T00:00:00.000Z',updatedAt:'2026-10-08T00:00:00.000Z'});
async function fixture(){
  const context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},token={access_token:'fixture.access.signature',refresh_token:'fixture-refresh',token_type:'bearer',user:{id:context.subjectId}},auth=new AuthSession(context.issuer,{login:async()=>token,refresh:async()=>token,verify:async()=>({issuer:context.issuer,subjectId:context.subjectId,expiresAt:200}),revoke:async()=>{}},()=>100),connection=new PrivateWorkspaceConnection(auth,{apiUrl:'http://127.0.0.1:3001',clientId:context.clientId},async()=>new Response(JSON.stringify({protocolVersion:1,workspaceId:context.workspaceId,clientId:context.clientId,epoch:context.streamEpoch})));
  await auth.login('fixture@example.invalid','fixture-password');await connection.bootstrap();const handle='abc-123-1',invoke=vi.fn<NativeWorkspaceInvoke>(async<T>(command:string)=>({workspace_open:{handle,context},workspace_close:null,workspace_execute:{context,snapshot:{}}})[command as 'workspace_open'] as T),id=newId();
  return{context,auth,connection,handle,invoke,id,async cleanup(){connection.close();auth.close();}};
}
it('NATIVE-WORKSPACE: failed/foreign native handle never adopts another store; private errors are sanitized',async()=>{
  const f=await fixture();try{for(const response of [{handle:'../foreign',context:f.context},{handle:f.handle,context:{...f.context,subjectId:'other'}},{handle:f.handle,context:f.context,path:'private.sqlite'}]){f.invoke.mockResolvedValueOnce(response);await expect(NativeWorkspaceStore.open(f.connection,f.invoke)).rejects.toMatchObject({stage:'protocol'});}f.invoke.mockRejectedValueOnce(Error('private database path token'));await expect(NativeWorkspaceStore.open(f.connection,f.invoke)).rejects.toMatchObject({stage:'storage',message:'Native workspace storage'});}finally{await f.cleanup();}
});
it('NATIVE-TITLE: captured intent/wire and bound query reach only the owned handle; malformed or foreign values never commit',async()=>{const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),port=store.title(f.id),intent={operationId:newId(),title:'local'};await port.enqueue(intent);intent.title='mutated';expect(f.invoke).toHaveBeenLastCalledWith('workspace_execute',{handle:f.handle,request:{command:'title_enqueue',pageId:f.id,intent:{operationId:intent.operationId,title:'local'}}});
  const wire=JSON.stringify({protocolVersion:1,clientId:f.context.clientId,operationId:intent.operationId,baseVersion:0,title:'local'}),prepared={pageId:f.id,sequence:'9007199254740993',operationId:intent.operationId,wire};f.invoke.mockResolvedValueOnce(prepared);const result=await port.prepare();expect(result).toEqual(prepared);expect(Object.isFrozen(result)).toBe(true);
  const reply={protocolVersion:1,workspaceId:f.context.workspaceId,workspaceEpoch:f.context.streamEpoch,pageId:f.id,metadata:{...titleMetadata(f.id),title:'local'},version:1,operationId:intent.operationId,result:{status:'applied'}};await port.acknowledge(prepared,reply);expect(f.invoke).toHaveBeenLastCalledWith('workspace_execute',{handle:f.handle,request:{command:'title_ack',pageId:f.id,sequence:prepared.sequence,wire,response:reply}});
  const count=f.invoke.mock.calls.length;for(const bad of [{...reply,workspaceEpoch:newId()},{...reply,pageId:newId()},{...reply,operationId:newId()}])await expect(port.acknowledge(prepared,bad)).rejects.toMatchObject({stage:'protocol'});await expect(port.enqueue({operationId:newId(),title:'x',path:'../other'})).rejects.toMatchObject({stage:'protocol'});await expect(port.receive({protocolVersion:1,clientId:newId()},{...reply,conflicts:[],nextAfter:null})).rejects.toMatchObject({stage:'protocol'});expect(f.invoke).toHaveBeenCalledTimes(count);await store.close();
}finally{await f.cleanup();}});
it('NATIVE-TITLE: scoped immutable bounded snapshots reject foreign context and invalid progress',async()=>{const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),port=store.title(f.id),snapshot={context:f.context,pageId:f.id,base:{metadata:titleMetadata(f.id),version:0},localTitle:'base',pending:0,operations:[],nextOperation:null,conflicts:[],nextConflict:null};f.invoke.mockResolvedValueOnce(snapshot);const value=await port.load();expect(value).toEqual(snapshot);expect(Object.isFrozen(value.base?.metadata)).toBe(true);expect(f.invoke).toHaveBeenLastCalledWith('workspace_execute',{handle:f.handle,request:{command:'title_load',pageId:f.id,afterOperation:null,afterConflict:null,limit:50}});
  for(const bad of [{...snapshot,pageId:newId()},{...snapshot,context:{...f.context,subjectId:'foreign'}},{...snapshot,nextOperation:'1'},{...snapshot,nextConflict:newId()},{...snapshot,base:null,pending:1}]){f.invoke.mockResolvedValueOnce(bad);await expect(port.load()).rejects.toMatchObject({stage:'protocol'});}const count=f.invoke.mock.calls.length;for(const request of [{afterOperation:'bad'},{limit:101},{path:'private.sqlite'}])await expect(port.load(request)).rejects.toMatchObject({stage:'protocol'});expect(f.invoke).toHaveBeenCalledTimes(count);await store.close();
}finally{await f.cleanup();}});
it('NATIVE-TITLE: refresh during admitted write rejects late success and old title port never follows a fresh store',async()=>{const f=await fixture(),wait=deferred<unknown>();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),port=store.title(f.id);f.invoke.mockImplementationOnce(()=>wait.promise);const work=port.enqueue({operationId:newId(),title:'retained'});await f.auth.refresh();await f.connection.bootstrap();wait.resolve(null);await expect(work).rejects.toMatchObject({stage:'closed'});await expect(port.load()).rejects.toMatchObject({stage:'closed'});await store.close();const fresh=await NativeWorkspaceStore.open(f.connection,f.invoke);f.invoke.mockResolvedValueOnce(null);expect(await fresh.title(f.id).prepare()).toBeNull();await fresh.close();}finally{await f.cleanup();}});
it('NATIVE-WORKSPACE: refresh during native open closes a late handle and old generation never exposes storage',async()=>{
  const f=await fixture(),wait=deferred<unknown>();try{f.invoke.mockImplementationOnce(()=>wait.promise as Promise<never>);const work=NativeWorkspaceStore.open(f.connection,f.invoke);await f.auth.refresh();wait.resolve({handle:f.handle,context:f.context});await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.invoke).toHaveBeenLastCalledWith('workspace_close',{handle:f.handle});}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE: execute captures requests and exact handle; close during admitted work rejects late success and cleanup coalesces',async()=>{
  const f=await fixture(),wait=deferred<unknown>();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke);f.invoke.mockImplementationOnce(()=>wait.promise as Promise<never>);const request={cursor:null,protocolVersion:1,workspaceId:f.context.workspaceId,clientId:f.context.clientId,limit:1},response={protocolVersion:1 as const,workspaceId:f.context.workspaceId,streamEpoch:f.context.streamEpoch,operations:[],cursor:'same',headCursor:'same',hasMore:false,serverTime:'2026-10-05T00:00:00.000Z'};const work=store.applyPull(f.context,request,response);response.cursor='mutated';expect((f.invoke.mock.calls[1]?.[1]?.request as any).response.cursor).toBe('same');const one=store.close(),two=store.close();expect(one).toBe(two);wait.resolve(null);await expect(work).rejects.toMatchObject({stage:'closed'});await one;expect(f.invoke.mock.calls.filter(call=>call[0]==='workspace_close')).toHaveLength(1);}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE: Page methods reject malformed bytes/IDs/load/foreign response and cannot inject a path or override the captured Page',async()=>{
  const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke);expect(()=>store.page('../foreign')).toThrow('protocol');const page=store.page(f.id);await expect(page.append(Uint8Array.from([255]))).rejects.toMatchObject({stage:'protocol'});expect(f.invoke).toHaveBeenCalledTimes(1);await page.create('日本語',emptyPageUpdate());const args=f.invoke.mock.calls[1]?.[1];expect(args).toMatchObject({handle:f.handle,request:{command:'page_create',pageId:f.id,title:'日本語',update:Array.from(emptyPageUpdate())}});expect(args).not.toHaveProperty('path');f.invoke.mockResolvedValueOnce({page:{metadata:{id:newId()}},serverHead:null,pending:0});await expect(page.load()).rejects.toMatchObject({stage:'protocol'});await store.pageCommand(f.id,'page_prepare',{pageId:newId(),command:'sql'});expect(f.invoke).toHaveBeenLastCalledWith('workspace_execute',{handle:f.handle,request:{command:'page_prepare',pageId:f.id}});await store.close();}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE: Auth abort permanently closes captured store even after fresh bootstrap with identical IDs',async()=>{
  const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),page=store.page(f.id);await f.auth.refresh();await f.connection.bootstrap();await expect(store.prepare()).rejects.toMatchObject({stage:'closed'});await expect(page.create('retained',emptyPageUpdate())).rejects.toMatchObject({stage:'closed'});await store.close();const fresh=await NativeWorkspaceStore.open(f.connection,f.invoke);f.invoke.mockResolvedValueOnce(null);expect(await fresh.page(f.id).prepare()).toBeNull();await fresh.close();}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE: cleanup failure is safe and never reopens ports or deletes retained data',async()=>{
  const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke);f.invoke.mockRejectedValueOnce(Error('private path'));await expect(store.close()).rejects.toMatchObject({stage:'storage',message:'Native workspace storage'});await expect(store.snapshot()).rejects.toMatchObject({stage:'closed'});expect(f.invoke.mock.calls.map(call=>call[0])).toEqual(['workspace_open','workspace_close']);}finally{await f.cleanup();}
});
it('NATIVE-WORKSPACE: connection close aborts the native generation and starts cleanup while shared Auth remains verified',async()=>{
  const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke);f.connection.close();await expect.poll(()=>f.invoke.mock.calls.filter(call=>call[0]==='workspace_close').length).toBe(1);expect(f.auth.identity?.subjectId).toBe(f.context.subjectId);await expect(store.prepare()).rejects.toMatchObject({stage:'closed'});await store.close();}finally{await f.cleanup();}
});
it('LOCAL-PAGE-CATALOG: strict request and bound immutable response; no binary/wire or caller mutation',async()=>{
 const f=await fixture();try{
  const store=await NativeWorkspaceStore.open(f.connection,f.invoke),metadata={id:f.id,title:'local pending',yDocId:'page:'+f.id,createdAt:'2026-10-08T00:00:00.000Z',updatedAt:'2026-10-08T00:00:00.000Z'};
  const response={context:f.context,pages:[{metadata,pending:2}],nextAfter:null};f.invoke.mockResolvedValueOnce(response);
  const result=await store.listPages();expect(result.pages[0]?.pending).toBe(2);expect(Object.isFrozen(result.pages[0]?.metadata)).toBe(true);
  expect(f.invoke).toHaveBeenLastCalledWith('workspace_execute',{handle:f.handle,request:{command:'page_list',after:null,limit:50}});
  const count=f.invoke.mock.calls.length;for(const candidate of [{after:null,limit:0},{after:'../path',limit:1},{after:null,limit:101},{after:null,limit:1,sql:'delete'}])await expect(store.listPages(candidate)).rejects.toMatchObject({stage:'protocol'});expect(f.invoke).toHaveBeenCalledTimes(count);
  for(const candidate of [{...response,context:{...f.context,clientId:newId()}},{...response,nextAfter:newId()},{...response,pages:[{metadata,pending:-1}]},{...response,pages:[{metadata,pending:1,wire:'private'}]}]){f.invoke.mockResolvedValueOnce(candidate);await expect(store.listPages()).rejects.toMatchObject({stage:'protocol'});}
  f.invoke.mockResolvedValueOnce(response);await expect(store.listPages({after:f.id,limit:1})).rejects.toMatchObject({stage:'protocol'});
  await store.close();
 }finally{await f.cleanup();}
});
it('LOCAL-PAGE-CATALOG: Auth close rejects ignored-abort late result and does not adopt a current workspace',async()=>{
 const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),wait=deferred<unknown>();f.invoke.mockImplementationOnce(()=>wait.promise);const work=store.listPages();f.connection.close();wait.resolve({context:f.context,pages:[],nextAfter:null});await expect(work).rejects.toMatchObject({stage:'closed'});await store.close();}finally{await f.cleanup();}
});
it('PRIVATE-STRUCTURED-NATIVE: snapshot is strict, bound and deeply immutable, including conflict values',async()=>{
 const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),snapshot={clientId:f.context.clientId,tasks:[],relations:[],operations:[],conflicts:[],errors:[],state:{stream:'structured',cursor:null,headCursor:null,lastSuccessfulSyncAt:null}},response={context:f.context,snapshot};
  f.invoke.mockResolvedValueOnce(response);const result=await store.structuredSnapshot();expect(Object.isFrozen(result.state)).toBe(true);expect(Object.isFrozen(result.tasks)).toBe(true);
  for(const candidate of [{...response,context:{...f.context,workspaceId:newId()}},{...response,snapshot:{...snapshot,clientId:newId()}},{...response,path:'private.sqlite'},{...response,snapshot:{...snapshot,tasks:[{id:f.id}]}}]){f.invoke.mockResolvedValueOnce(candidate);await expect(store.structuredSnapshot()).rejects.toMatchObject({stage:'protocol'});}
  await store.close();
 }finally{await f.cleanup();}
});
it('PRIVATE-STRUCTURED-NATIVE: mutation captures its exact payload, rejects foreign client/response and exposes no private cause',async()=>{
 const f=await fixture();try{const store=await NativeWorkspaceStore.open(f.connection,f.invoke),wait=deferred<unknown>(),operation={operationId:newId(),clientId:f.context.clientId,entityType:'task',entityId:f.id,kind:'create',baseVersion:null,payload:{title:'captured',status:'todo',due:null}},time='2026-10-08T00:00:00.000Z',entity={id:f.id,title:'captured',status:'todo',due:null,version:0,createdAt:time,updatedAt:time,deletedAt:null};
  f.invoke.mockImplementationOnce(()=>wait.promise);const work=store.mutate(operation);operation.payload.title='changed';expect((f.invoke.mock.calls[1]?.[1]?.request as any).operation.payload.title).toBe('captured');wait.resolve(entity);await work;
  const count=f.invoke.mock.calls.length;await expect(store.mutate({...operation,clientId:newId()})).rejects.toMatchObject({stage:'protocol'});expect(f.invoke).toHaveBeenCalledTimes(count);
  f.invoke.mockResolvedValueOnce({...entity,id:newId()});await expect(store.mutate(operation)).rejects.toMatchObject({stage:'protocol'});
  f.invoke.mockRejectedValueOnce(Error('private title and path'));await expect(store.mutate(operation)).rejects.toMatchObject({stage:'storage',message:'Native workspace storage'});await store.close();
 }finally{await f.cleanup();}
});
