import {it,expect,vi} from 'vitest';import {createHash} from 'node:crypto';import * as Y from 'yjs';
import {newId,utcNow} from '@greiva/shared';import {PageSyncSession,emptyPageUpdate,type PageSessionStore} from '@greiva/sync';
const encode=(bytes:Uint8Array)=>Buffer.from(bytes).toString('base64url'),hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){
  const pageId=newId(),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId(),pageId,documentName:'page:'+pageId,editorSchemaVersion:1 as const},doc=new Y.Doc({gc:false});Y.applyUpdate(doc,emptyPageUpdate());const xml=new Y.XmlText('日本語');(doc.getXmlFragment('body').get(0) as Y.XmlElement).insert(0,[xml]);const initial=Y.encodeStateAsUpdate(doc);doc.destroy();const time=utcNow();
  const request={protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,title:'日本語 Page',initialUpdate:encode(initial)},prepared={sequence:'1',pageId,kind:'bootstrap' as 'bootstrap'|'append',digest:hash(initial),wire:JSON.stringify(request,null,2)};
  const scope={protocolVersion:1,workspaceId:context.workspaceId,pageId,documentName:context.documentName,editorSchemaVersion:1},metadata={id:pageId,title:request.title,yDocId:context.documentName,createdAt:time,updatedAt:time},bootstrap={...scope,metadata,initialDigest:prepared.digest};
  const append={...scope,serverOrder:'2',headOrder:'2',digest:prepared.digest,stateVector:'AA'},readRequest={protocolVersion:1,clientId:context.clientId,editorSchemaVersion:1,stateVector:'AA'},response={...scope,metadata,headOrder:'1',update:encode(initial),digest:hash(initial),stateVector:'AA'};
  const transport={push:vi.fn(async(_kind:unknown,_wire:string,_signal:AbortSignal):Promise<unknown>=>bootstrap),read:vi.fn(async(_request:unknown,_signal:AbortSignal):Promise<unknown>=>response)};
  const store={acknowledge:vi.fn<PageSessionStore['acknowledge']>(async()=>{}),receive:vi.fn<PageSessionStore['receive']>(async()=>{})};
  return{context,initial,request,prepared,bootstrap,append,readRequest,response,transport,store,session:new PageSyncSession(context,{transport,store})};
}
it('PAGE-SESSION: exact durable wire and immutable context are captured; validated remote bytes reach the captured commit port',async()=>{
  const f=fixture(),original={...f.context};f.context.subjectId='changed';f.context.pageId=newId();await f.session.push(f.prepared);expect(f.transport.push).toHaveBeenCalledWith('bootstrap',f.prepared.wire,expect.any(AbortSignal));expect(f.store.acknowledge).toHaveBeenCalledWith(original,f.prepared,f.bootstrap);const ack=f.store.acknowledge.mock.calls[0]!;expect(Object.isFrozen(ack[0])).toBe(true);expect(Object.isFrozen(ack[1])).toBe(true);expect(Object.isFrozen(ack[2])).toBe(true);expect(Object.isFrozen(f.bootstrap)).toBe(false);await f.session.pull(f.readRequest);expect(f.store.receive).toHaveBeenCalledWith(original,f.readRequest,f.response,Uint8Array.from(f.initial));
});
it('PAGE-SESSION: malformed/foreign/corrupt outbound binary never reaches network or storage',async()=>{
  const f=fixture();for(const prepared of [{...f.prepared,pageId:newId()},{...f.prepared,sequence:'0'},{...f.prepared,digest:'0'.repeat(64)},{...f.prepared,wire:'invalid'}, {...f.prepared,wire:JSON.stringify({...f.request,clientId:newId()})},{...f.prepared,wire:JSON.stringify({...f.request,editorSchemaVersion:2})},{...f.prepared,wire:JSON.stringify({...f.request,initialUpdate:encode(Buffer.concat([f.initial,Buffer.from([0])]))})}])await expect(f.session.push(prepared)).rejects.toMatchObject({stage:'protocol'});
  for(const request of [{...f.readRequest,clientId:newId()},{...f.readRequest,stateVector:'AA='},{...f.readRequest,stateVector:'_w'},{...f.readRequest,editorSchemaVersion:2}])await expect(f.session.pull(request)).rejects.toMatchObject({stage:'protocol'});expect(f.transport.push).not.toHaveBeenCalled();expect(f.transport.read).not.toHaveBeenCalled();expect(f.store.acknowledge).not.toHaveBeenCalled();
});
it('PAGE-SESSION: foreign binding/digest/bootstrap response cannot acknowledge prepared data',async()=>{
  const f=fixture();for(const response of [{...f.bootstrap,workspaceId:newId()},{...f.bootstrap,pageId:newId()},{...f.bootstrap,documentName:'page:foreign'},{...f.bootstrap,editorSchemaVersion:2},{...f.bootstrap,initialDigest:'0'.repeat(64)}]){f.transport.push.mockResolvedValueOnce(response);await expect(f.session.push(f.prepared)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.acknowledge).not.toHaveBeenCalled();
});
it('PAGE-SESSION: bootstrap retry accepts later mutable title while retaining creation digest and exact wire',async()=>{const f=fixture(),current={...f.bootstrap,metadata:{...f.bootstrap.metadata,title:'renamed by another device'}};f.transport.push.mockResolvedValueOnce(current);await f.session.push(f.prepared);expect(f.transport.push).toHaveBeenCalledWith('bootstrap',f.prepared.wire,expect.any(AbortSignal));expect(f.store.acknowledge).toHaveBeenCalledWith(f.context,f.prepared,current);});
it('PAGE-SESSION: append validates stable digest/order/vector and preserves latest head on duplicate receipt',async()=>{
  const f=fixture(),prepared={...f.prepared,kind:'append' as const,sequence:'9007199254740993',wire:JSON.stringify({protocolVersion:1,clientId:f.context.clientId,editorSchemaVersion:1,update:encode(f.initial)})};
  for(const response of [{...f.append,serverOrder:'0'},{...f.append,serverOrder:'3'},{...f.append,digest:'0'.repeat(64)},{...f.append,stateVector:'AA='},{...f.append,stateVector:'_w'}]){f.transport.push.mockResolvedValueOnce(response);await expect(f.session.push(prepared)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.acknowledge).not.toHaveBeenCalled();f.transport.push.mockResolvedValueOnce({...f.append,headOrder:'9223372036854775807'});await f.session.push(prepared);expect(f.store.acknowledge.mock.calls[0]?.[1].sequence).toBe(prepared.sequence);
});
it('PAGE-SESSION: wrong/malformed/corrupt read response is rejected before durable receive',async()=>{
  const f=fixture();for(const response of [{...f.response,workspaceId:newId()},{...f.response,headOrder:'0'},{...f.response,digest:'0'.repeat(64)},{...f.response,stateVector:'AA='},{...f.response,update:'_w',digest:hash(Buffer.from([255]))},{...f.response,update:encode(Buffer.concat([f.initial,Buffer.from([0])])),digest:hash(Buffer.concat([f.initial,Buffer.from([0])]))}]){f.transport.read.mockResolvedValueOnce(response);await expect(f.session.pull(f.readRequest)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.receive).not.toHaveBeenCalled();
});
it('PAGE-SESSION: combined large binary and unknown block attrs remain intact without JSON projection or input frame bound',async()=>{
  const f=fixture(),doc=new Y.Doc({gc:false});try{Y.applyUpdate(doc,f.initial);const block=new Y.XmlElement('future-block');block.setAttribute('future','保持');block.insert(0,[new Y.XmlText('x'.repeat(600000))]);doc.getXmlFragment('body').insert(1,[block]);const update=Y.encodeStateAsUpdate(doc),response={...f.response,update:encode(update),digest:hash(update),stateVector:encode(Y.encodeStateVector(doc))};f.transport.read.mockResolvedValueOnce(response);await f.session.pull(f.readRequest);expect(f.store.receive.mock.calls[0]?.[3]).toEqual(update);}finally{doc.destroy();}
});
it('PAGE-SESSION: port/caller replacement while hash/network await never redirects or mutates captured work',async()=>{
  const f=fixture(),wait=deferred<unknown>(),originalAck=f.store.acknowledge,prepared={...f.prepared},original={...prepared};f.transport.push.mockImplementationOnce(()=>wait.promise);const work=f.session.push(prepared);prepared.wire='changed';prepared.digest='0'.repeat(64);f.store.acknowledge=vi.fn();await expect.poll(()=>f.transport.push.mock.calls.length).toBe(1);wait.resolve(f.bootstrap);await work;expect(originalAck).toHaveBeenCalledWith(expect.anything(),original,f.bootstrap);expect(f.store.acknowledge).not.toHaveBeenCalled();
});
it('PAGE-SESSION: close during asynchronous validation prevents even an outbound call',async()=>{
  const f=fixture(),work=f.session.push(f.prepared);f.session.close();await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.transport.push).not.toHaveBeenCalled();expect(f.store.acknowledge).not.toHaveBeenCalled();
});
for(const direction of ['push','pull'] as const)it(`PAGE-SESSION: closed old ${direction} ignores late response while fresh identical IDs can commit`,async()=>{
  const f=fixture(),wait=deferred<unknown>();if(direction==='push')f.transport.push.mockImplementationOnce(()=>wait.promise);else f.transport.read.mockImplementationOnce(()=>wait.promise);const work=direction==='push'?f.session.push(f.prepared):f.session.pull(f.readRequest);await expect.poll(()=>(direction==='push'?f.transport.push:f.transport.read).mock.calls.length).toBe(1);f.session.close();const fresh=new PageSyncSession(f.context,{transport:{push:async()=>f.bootstrap,read:async()=>f.response},store:{acknowledge:async()=>{},receive:async()=>{}}});await (direction==='push'?fresh.push(f.prepared):fresh.pull(f.readRequest));wait.resolve(direction==='push'?f.bootstrap:f.response);await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.store.acknowledge).not.toHaveBeenCalled();expect(f.store.receive).not.toHaveBeenCalled();
});
it('PAGE-SESSION: in-flight captured commit can finish in old store but close prevents success; no fresh store redirection',async()=>{
  const f=fixture(),wait=deferred<void>();f.store.receive.mockImplementationOnce(()=>wait.promise);const work=f.session.pull(f.readRequest);await expect.poll(()=>f.store.receive.mock.calls.length).toBe(1);f.session.close();wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.store.receive).toHaveBeenCalledOnce();
});
it('PAGE-SESSION: busy serialization and sanitized transport/storage errors retain exact retry intent',async()=>{
  const f=fixture(),wait=deferred<unknown>();f.transport.push.mockImplementationOnce(()=>wait.promise);const work=f.session.push(f.prepared);await expect(f.session.pull(f.readRequest)).rejects.toMatchObject({stage:'busy'});await expect.poll(()=>f.transport.push.mock.calls.length).toBe(1);wait.resolve(f.bootstrap);await work;
  f.transport.push.mockRejectedValueOnce(Error('private token SQL'));await expect(f.session.push(f.prepared)).rejects.toMatchObject({stage:'transport',message:'Page sync transport'});f.store.acknowledge.mockRejectedValueOnce(Error('private database path'));await expect(f.session.push(f.prepared)).rejects.toMatchObject({stage:'storage',message:'Page sync storage'});await f.session.push(f.prepared);expect(f.transport.push.mock.calls.map(call=>call[1])).toEqual(Array(4).fill(f.prepared.wire));
});
