import {it,expect,vi} from 'vitest';
import {newId} from '@greiva/shared';
import {PageTitleSyncSession,type PageTitleStore} from '@greiva/sync';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){const pageId=newId(),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId(),pageId},operationId=newId(),time='2026-10-08T00:00:00.000Z';
  const request={protocolVersion:1,clientId:context.clientId,operationId,baseVersion:0,title:'日本語'},prepared={pageId,sequence:'1',operationId,wire:JSON.stringify(request,null,2)},scope={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,pageId},metadata={id:pageId,yDocId:'page:'+pageId,title:request.title,createdAt:time,updatedAt:time},receipt={...scope,metadata,version:1,operationId,result:{status:'applied'}},readRequest={protocolVersion:1,clientId:context.clientId,afterConflict:null,limit:1},response={...scope,metadata,version:1,conflicts:[],nextAfter:null};
  const transport={rename:vi.fn(async(_wire:string,_signal:AbortSignal):Promise<unknown>=>receipt),read:vi.fn(async(_request:unknown,_signal:AbortSignal):Promise<unknown>=>response)},store={acknowledge:vi.fn<PageTitleStore['acknowledge']>(async()=>{}),receive:vi.fn<PageTitleStore['receive']>(async()=>{})};
  return{context,request,prepared,scope,metadata,receipt,readRequest,response,transport,store,session:new PageTitleSyncSession(context,{transport,store})};}
it('TITLE-SESSION: captures exact wire/context/store and freezes committed replies; caller changes cannot redirect in-flight ACK',async()=>{const f=fixture(),wait=deferred<unknown>(),original={...f.prepared},ack=f.store.acknowledge;f.transport.rename.mockImplementationOnce(()=>wait.promise);const work=f.session.push(f.prepared);f.prepared.wire='changed';f.prepared.operationId=newId();f.context.subjectId='other';f.store.acknowledge=vi.fn();wait.resolve(f.receipt);expect(await work).toEqual(f.receipt);expect(f.transport.rename).toHaveBeenCalledWith(original.wire,expect.any(AbortSignal));expect(ack).toHaveBeenCalledWith(original,f.receipt);expect(Object.isFrozen(ack.mock.calls[0]![0])).toBe(true);expect(Object.isFrozen(ack.mock.calls[0]![1].metadata)).toBe(true);expect(f.store.acknowledge).not.toHaveBeenCalled();});
it('TITLE-SESSION: strict prepared/request rejects spoofed client/Page/nonce before transport',async()=>{const f=fixture();for(const bad of [{...f.prepared,pageId:newId()},{...f.prepared,sequence:'01'},{...f.prepared,wire:'bad'},{...f.prepared,wire:JSON.stringify({...f.request,clientId:newId()})},{...f.prepared,wire:JSON.stringify({...f.request,operationId:newId()})},{...f.prepared,email:'private'}])await expect(f.session.push(bad)).rejects.toMatchObject({stage:'protocol'});expect(f.transport.rename).not.toHaveBeenCalled();expect(f.store.acknowledge).not.toHaveBeenCalled();});
it('TITLE-SESSION: foreign or inconsistent receipts never reach storage; errors omit private causes',async()=>{const f=fixture();for(const bad of [{...f.receipt,workspaceEpoch:newId()},{...f.receipt,pageId:newId()},{...f.receipt,operationId:newId()},{...f.receipt,result:{status:'rejected',code:'resolution_stale'}},{...f.receipt,metadata:{...f.metadata,id:newId()}},{...f.receipt,email:'private'}]){f.transport.rename.mockResolvedValueOnce(bad);await expect(f.session.push(f.prepared)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.acknowledge).not.toHaveBeenCalled();f.transport.rename.mockRejectedValueOnce(Error('private token/path/title'));await expect(f.session.push(f.prepared)).rejects.toThrow('Page title sync transport');});
it('TITLE-SESSION: Conflict response is tied to observed request while native port verifies baseTitle',async()=>{const f=fixture(),conflict={id:newId(),operationId:f.request.operationId,baseVersion:0,remoteVersion:2,base:'base',local:f.request.title,remote:'remote'},reply={...f.receipt,metadata:{...f.metadata,title:'remote'},version:2,result:{status:'conflict',conflict}};f.transport.rename.mockResolvedValueOnce(reply);expect(await f.session.push(f.prepared)).toEqual(reply);f.store.acknowledge.mockClear();for(const changed of [{...conflict,local:'unrelated'},{...conflict,baseVersion:1}]){f.transport.rename.mockResolvedValueOnce({...reply,result:{status:'conflict',conflict:changed}});await expect(f.session.push(f.prepared)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.acknowledge).not.toHaveBeenCalled();});
it('TITLE-SESSION: keyset response bounds/progress reject before commit; valid query commits before return',async()=>{const f=fixture(),key=newId(),cf={id:key,operationId:newId(),baseVersion:0,remoteVersion:1,base:'base',local:'local',remote:f.metadata.title},after={...f.readRequest,afterConflict:key};for(const response of [{...f.response,conflicts:[cf],nextAfter:key},{...f.response,workspaceEpoch:newId()},{...f.response,nextAfter:newId()}]){f.transport.read.mockResolvedValueOnce(response);await expect(f.session.pull(after)).rejects.toMatchObject({stage:'protocol'});}expect(f.store.receive).not.toHaveBeenCalled();const blocked=deferred<void>();f.store.receive.mockImplementationOnce(()=>blocked.promise);let returned=false;const work=f.session.pull(f.readRequest).then(()=>{returned=true;});await expect.poll(()=>f.store.receive.mock.calls.length).toBe(1);expect(returned).toBe(false);blocked.resolve();await work;expect(Object.isFrozen(f.store.receive.mock.calls[0]![0])).toBe(true);});
it('TITLE-SESSION: single in-flight operation refuses overlap; closed late network result never commits',async()=>{const f=fixture(),wait=deferred<unknown>();f.transport.rename.mockImplementationOnce(()=>wait.promise);const work=f.session.push(f.prepared);await expect(f.session.pull(f.readRequest)).rejects.toMatchObject({stage:'busy'});f.session.close();wait.resolve(f.receipt);await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.store.acknowledge).not.toHaveBeenCalled();expect(f.session.signal.aborted).toBe(true);});
it('TITLE-SESSION: admitted original commit can finish after close without accepting result or adopting another store',async()=>{const f=fixture(),wait=deferred<void>();f.store.acknowledge.mockImplementationOnce(()=>wait.promise);const work=f.session.push(f.prepared);await expect.poll(()=>f.store.acknowledge.mock.calls.length).toBe(1);f.session.close();wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.store.acknowledge).toHaveBeenCalledOnce();});
it('TITLE-SESSION: failed storage never returns receipt and permits exact retry; context configuration is strict',async()=>{const f=fixture();f.store.acknowledge.mockRejectedValueOnce(Error('private body/path'));await expect(f.session.push(f.prepared)).rejects.toThrow('Page title sync storage');await f.session.push(f.prepared);expect(f.transport.rename.mock.calls.map(([wire])=>wire)).toEqual([f.prepared.wire,f.prepared.wire]);for(const context of [{...f.context,pageId:'bad'},{...f.context,issuer:''},{...f.context,token:'private'}])expect(()=>new PageTitleSyncSession(context,{transport:f.transport,store:f.store})).toThrow('Page title sync protocol');});
