import {it,expect,vi} from 'vitest';import {newId} from '@greiva/shared';
import {PageChangesSyncSession,type PageChangesStore} from '@greiva/sync';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){const context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},pageId=newId(),request={protocolVersion:1,clientId:context.clientId,cursor:null,limit:1},event={order:'1',pageId,metadata:{id:pageId,title:'日本語',yDocId:'page:'+pageId,createdAt:'2026-10-08T00:00:00.000Z',updatedAt:'2026-10-08T00:00:00.000Z'},version:0,conflict:null},response={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,afterOrder:'0',readOrder:'1',headOrder:'1',events:[event],hasMore:false,cursor:'opaque-cursor'},transport={pull:vi.fn(async(_request:unknown,_signal:AbortSignal):Promise<unknown>=>response)},store={receive:vi.fn<PageChangesStore['receive']>(async()=>{})};return{context,request,event,response,transport,store,session:new PageChangesSyncSession(context,{transport,store})};}
it('CHANGES-SESSION: captures immutable request/context/reply and original receive port through await',async()=>{const f=fixture(),wait=deferred<unknown>(),original={...f.request},receive=f.store.receive;f.transport.pull.mockImplementationOnce(()=>wait.promise);const work=f.session.pull(f.request,'0');f.request.clientId=newId();f.context.subjectId='other';f.store.receive=vi.fn();wait.resolve(f.response);expect(await work).toEqual(f.response);expect(receive).toHaveBeenCalledWith(original,f.response);expect(Object.isFrozen(receive.mock.calls[0]![0])).toBe(true);expect(Object.isFrozen(receive.mock.calls[0]![1].events[0]!.metadata)).toBe(true);expect(f.store.receive).not.toHaveBeenCalled();});
it('CHANGES-SESSION: strict request/client/after fails before transport',async()=>{const f=fixture();for(const [request,after] of [[{...f.request,clientId:newId()},'0'],[{...f.request,limit:101},'0'],[{...f.request,email:'private'},'0'],[f.request,'01'],[f.request,'1']] as const)await expect(f.session.pull(request,after)).rejects.toMatchObject({stage:'protocol'});expect(f.transport.pull).not.toHaveBeenCalled();});
it('CHANGES-SESSION: foreign scope/after, overlimit and inconsistent progress never reach storage',async()=>{const f=fixture();for(const response of [{...f.response,workspaceId:newId()},{...f.response,workspaceEpoch:newId()},{...f.response,afterOrder:'1'},{...f.response,readOrder:'2'},{...f.response,events:[f.event,{...f.event,order:'2'}],readOrder:'2',headOrder:'2'},{...f.response,hasMore:true},{...f.response,email:'private'}]){f.transport.pull.mockResolvedValueOnce(response);await expect(f.session.pull(f.request,'0')).rejects.toMatchObject({stage:'protocol'});}expect(f.store.receive).not.toHaveBeenCalled();expect(f.session.retryReceive).toBe(false);});
it('CHANGES-SESSION: storage unknown keeps exact pair, blocks new pull and retries without network',async()=>{const f=fixture();f.store.receive.mockRejectedValueOnce(Error('private body/token/path'));await expect(f.session.pull(f.request,'0')).rejects.toThrow('Page changes sync storage');expect(f.session.retryReceive).toBe(true);f.response.events[0]!.metadata.title='later mutation';await expect(f.session.pull(f.request,'0')).rejects.toMatchObject({stage:'busy'});expect((await f.session.retry()).events[0]!.metadata.title).toBe('日本語');expect(f.transport.pull).toHaveBeenCalledTimes(1);expect(f.store.receive).toHaveBeenCalledTimes(2);expect(f.store.receive.mock.calls[0]).toEqual(f.store.receive.mock.calls[1]);expect(f.session.retryReceive).toBe(false);});
it('CHANGES-SESSION: filtered empty windows, zero events and bigint after remain exact',async()=>{const f=fixture(),after='9007199254740993',response={...f.response,afterOrder:after,readOrder:'9007199254740994',headOrder:'9223372036854775807',events:[],hasMore:true,cursor:'new-cursor'};f.transport.pull.mockResolvedValueOnce(response);expect(await f.session.pull({...f.request,cursor:'old-cursor'},after)).toEqual(response);f.transport.pull.mockResolvedValueOnce({...response,readOrder:after,headOrder:after,hasMore:false,cursor:'old-cursor'});await f.session.pull({...f.request,cursor:'old-cursor'},after);expect(f.store.receive).toHaveBeenCalledTimes(2);});
it('CHANGES-SESSION: transport failure has no storage retry; busy never admits a second pull',async()=>{const f=fixture(),wait=deferred<unknown>();f.transport.pull.mockRejectedValueOnce(Error('private'));await expect(f.session.pull(f.request,'0')).rejects.toThrow('Page changes sync transport');expect(f.session.retryReceive).toBe(false);f.transport.pull.mockImplementationOnce(()=>wait.promise);const work=f.session.pull(f.request,'0');await expect(f.session.pull(f.request,'0')).rejects.toMatchObject({stage:'busy'});wait.resolve(f.response);await work;expect(f.store.receive).toHaveBeenCalledTimes(1);});
it('CHANGES-SESSION: close drops late transport before storage and clears private retry pair',async()=>{const f=fixture(),wait=deferred<unknown>();f.transport.pull.mockImplementationOnce(()=>wait.promise);const work=f.session.pull(f.request,'0');f.session.close();wait.resolve(f.response);await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.store.receive).not.toHaveBeenCalled();await expect(f.session.retry()).rejects.toMatchObject({stage:'closed'});const another=fixture();another.store.receive.mockRejectedValueOnce(Error());await expect(another.session.pull(another.request,'0')).rejects.toMatchObject({stage:'storage'});another.session.close();expect(another.session.retryReceive).toBe(false);});
it('CHANGES-SESSION: an admitted old-store commit can finish after close without success or new-store writes',async()=>{const f=fixture(),wait=deferred<void>();f.store.receive.mockImplementationOnce(()=>wait.promise);const work=f.session.pull(f.request,'0');await expect.poll(()=>f.store.receive.mock.calls.length).toBe(1);f.session.close();wait.resolve();await expect(work).rejects.toMatchObject({stage:'closed'});expect(f.session.retryReceive).toBe(false);});
