import {it,expect} from 'vitest';
import {newId} from '@greiva/shared';
import {privateDatabaseViewCatalogRequestSchema,privateDatabaseViewCatalogResponseSchema} from '@greiva/protocol/private-database-view-catalog';
import {databaseViewCatalogCursor} from '../../apps/api/src/private-database-view-catalog-cursor.js';
import {databaseRecordCatalogCursor} from '../../apps/api/src/private-database-record-catalog-cursor.js';
function fixture(){const scope=[newId(),newId(),newId(),newId()] as const,key=new Uint8Array(32).fill(7),cursor=databaseViewCatalogCursor(...scope,key),header={id:newId(),workspaceId:scope[0],sourceId:scope[3],version:1,name:'Table',layout:'table',creationOrder:'1'},response={protocolVersion:1,workspaceId:scope[0],workspaceEpoch:scope[1],clientId:scope[2],sourceId:scope[3],schemaVersion:1,afterOrder:'0',throughOrder:'1',headOrder:'1',views:[header],hasMore:false,cursor:null};return{scope,key,cursor,header,response};}
it('DB-VIEW-CATALOG: default50/max100 and bounded header names/layout exclude filter/sorts/record values',()=>{const f=fixture();expect(privateDatabaseViewCatalogRequestSchema.parse({protocolVersion:1,clientId:f.scope[2]})).toMatchObject({limit:50,cursor:null});expect(()=>privateDatabaseViewCatalogRequestSchema.parse({protocolVersion:1,clientId:f.scope[2],limit:101})).toThrow();expect(privateDatabaseViewCatalogResponseSchema.parse(f.response)).toEqual(f.response);for(const extra of [{filter:null},{sorts:[]},{values:{}},{title:'Page title'}])expect(()=>privateDatabaseViewCatalogResponseSchema.parse({...f.response,views:[{...f.header,...extra}]})).toThrow();});
it('DB-VIEW-CATALOG: exact numeric progress/header scope/order and filtered empty continuation are checked',()=>{const f=fixture();expect(privateDatabaseViewCatalogResponseSchema.parse({...f.response,views:[],headOrder:'2',hasMore:true,cursor:'opaque'})).toMatchObject({views:[],hasMore:true});for(const value of [{...f.response,hasMore:true},{...f.response,throughOrder:'2'},{...f.response,views:[f.header,f.header]},{...f.response,views:[{...f.header,sourceId:newId()}]},{...f.response,views:[{...f.header,creationOrder:'0'}]},{...f.response,views:[{...f.header,layout:'board'}]}])expect(()=>privateDatabaseViewCatalogResponseSchema.parse(value)).toThrow();});
it('DB-VIEW-CURSOR: exact bigint observed head survives growth and scope/purpose are bound',()=>{const f=fixture(),after='9007199254740993',head='9007199254740995',encoded=f.cursor.encode(after,head);expect(f.cursor.decode(encoded,'9007199254740996')).toEqual({after,head});for(let i=0;i<4;i++){const scope=[...f.scope] as [string,string,string,string];scope[i]=newId();expect(()=>databaseViewCatalogCursor(...scope,f.key).decode(encoded,head)).toThrow();}expect(()=>f.cursor.decode(databaseRecordCatalogCursor(...f.scope,f.key).encode(after,head),head)).toThrow();expect(()=>f.cursor.decode(encoded,'9007199254740994')).toThrow();});
it('DB-VIEW-CURSOR: key is captured and invalid/tampered/canonical/range inputs fail',()=>{const f=fixture(),encoded=f.cursor.encode('0','1');f.key.fill(2);expect(f.cursor.decode(encoded,'1')).toEqual({after:'0',head:'1'});expect(()=>databaseViewCatalogCursor(...f.scope,f.key).decode(encoded,'1')).toThrow();for(const candidate of [encoded+'=',encoded.replace('gdv1','gds1'),encoded.slice(0,-4),encoded.replace(/^gdv1\./,'gdv1.='),'x'.repeat(1025)])expect(()=>f.cursor.decode(candidate,'1')).toThrow();expect(()=>f.cursor.encode('2','1')).toThrow();expect(()=>f.cursor.encode('01','1')).toThrow();expect(()=>databaseViewCatalogCursor(...f.scope,new Uint8Array(31))).toThrow();});
