import {it,expect,vi} from 'vitest';
import {newId} from '@greiva/shared';
import {DatabaseSourceWriteSyncSession,type DatabaseSourceWriteStore,type PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,NativeWorkspaceError} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivateDatabaseSourceWriteSession} from '../../apps/client/src/workspace/private-database-source-write-session.js';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){
 const controller=new AbortController(),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},source={id:newId(),workspaceId:context.workspaceId,name:'DB',schemaVersion:1,properties:[{id:newId(),type:'name',name:'Name'}]},intent={operationId:newId(),source},wire=JSON.stringify({protocolVersion:1,clientId:context.clientId,...intent}),prepared={sequence:'1',operationId:intent.operationId,sourceId:source.id,wire},reply={protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,clientId:context.clientId,operationId:intent.operationId,snapshot:{source,version:1,creationOrder:'1'},result:{status:'created'}};
 let pending=false;const load=vi.fn(async(..._args:unknown[])=>({context,pending:pending?1:0,operations:pending?[{sequence:'1',intent,wire:null,response:null}]:[],nextAfter:null})),enqueue=vi.fn(async(..._args:unknown[])=>{pending=true;}),transport={create:vi.fn(async(..._args:unknown[]):Promise<unknown>=>reply)},cache={prepare:vi.fn(async():Promise<unknown>=>pending?prepared:null),acknowledge:vi.fn<DatabaseSourceWriteStore['acknowledge']>(async()=>{pending=false;})},session=new DatabaseSourceWriteSyncSession(context,{transport,store:cache}),connection={generationSignal:controller.signal} as unknown as PrivateWorkspaceConnection,assertConnection=vi.fn((candidate:PrivateWorkspaceConnection)=>{if(candidate!==connection||controller.signal.aborted)throw new NativeWorkspaceError('closed');}),close=vi.fn(async()=>{}),store={context,assertConnection,databaseSourceQueue:load,databaseSourceEnqueue:enqueue,databaseSourceWrites:()=>session,close} as unknown as NativeWorkspaceStore;
 return{controller,context,intent,prepared,reply,load,enqueue,transport,cache,session,connection,store,close,runtime:()=>PrivateDatabaseSourceWriteSession.open(connection,store)};
}
it('DB-SOURCE-WRITE-RUNTIME: opening, offline enqueue and pending-only reload start no HTTP; explicit send confirms only one saved operation',async()=>{const f=fixture(),r=await f.runtime();expect(r.snapshot).toMatchObject({phase:'ready',catalogFresh:true,data:{pending:0}});await r.enqueue(f.intent);expect(r.snapshot).toMatchObject({data:{pending:1},retryEnqueue:false});expect(f.load.mock.calls.every(call=>JSON.stringify(call[0])===JSON.stringify({pendingOnly:true,after:null,limit:100}))).toBe(true);await r.reload(true);expect(f.transport.create).not.toHaveBeenCalled();expect((await r.send())?.snapshot.source).toEqual(f.intent.source);expect(r.snapshot).toMatchObject({data:{pending:0},retryAck:false,catalogFresh:true});expect(await r.send()).toBeNull();expect(f.transport.create).toHaveBeenCalledTimes(1);await r.close();expect(f.close).not.toHaveBeenCalled();});
it.each(['enqueue','reload'] as const)('DB-SOURCE-WRITE-RUNTIME unknown %s: captured intent retries exactly without HTTP; local reload cannot clear unknown enqueue',async boundary=>{const f=fixture(),r=await f.runtime(),candidate=structuredClone(f.intent);if(boundary==='enqueue'){const write=f.enqueue.getMockImplementation()!;f.enqueue.mockImplementationOnce(async(...args)=>{await write(...args);throw new NativeWorkspaceError('storage');});}else f.load.mockRejectedValueOnce(new NativeWorkspaceError('storage'));await expect(r.enqueue(candidate)).rejects.toMatchObject({stage:'storage'});candidate.source.name='changed';candidate.operationId=newId();expect(r.snapshot).toMatchObject({retryEnqueue:true,catalogFresh:false,error:'storage'});await expect(r.enqueue(candidate)).rejects.toMatchObject({stage:'busy'});await expect(r.send()).rejects.toMatchObject({stage:'busy'});await r.reload();expect(r.snapshot).toMatchObject({retryEnqueue:true,data:{pending:1}});await r.retryEnqueue();expect(f.enqueue.mock.calls[0]).toEqual(f.enqueue.mock.calls[1]);expect(r.snapshot).toMatchObject({retryEnqueue:false,catalogFresh:true});expect(f.transport.create).not.toHaveBeenCalled();await r.close();});
it('DB-SOURCE-WRITE-RUNTIME: unknown local ACK retries exact pair without HTTP; successful ACK followed by failed catalog reload remains confirmed with stale display',async()=>{const f=fixture(),r=await f.runtime();await r.enqueue(f.intent);const ack=f.cache.acknowledge.getMockImplementation()!;f.cache.acknowledge.mockImplementationOnce(async(...args)=>{await ack(...args);throw Error('private');});await expect(r.send()).rejects.toMatchObject({stage:'storage'});expect(r.snapshot).toMatchObject({retryAck:true,catalogFresh:false,data:{pending:1}});await r.reload();expect(r.snapshot).toMatchObject({retryAck:true,data:{pending:0}});await expect(r.send()).rejects.toMatchObject({stage:'busy'});await r.retryAck();expect(f.cache.acknowledge.mock.calls[0]).toEqual(f.cache.acknowledge.mock.calls[1]);expect(f.transport.create).toHaveBeenCalledTimes(1);expect(r.snapshot.retryAck).toBe(false);await r.close();const next=fixture(),runtime=await next.runtime();await runtime.enqueue(next.intent);next.load.mockRejectedValueOnce(new NativeWorkspaceError('storage'));await expect(runtime.send()).rejects.toMatchObject({stage:'storage'});expect(runtime.snapshot).toMatchObject({retryAck:false,catalogFresh:false,data:{pending:1}});await runtime.reload();expect(runtime.snapshot).toMatchObject({data:{pending:0},catalogFresh:true,error:null});expect(next.transport.create).toHaveBeenCalledTimes(1);await runtime.close();});
it('DB-SOURCE-WRITE-RUNTIME: unknown transport retains pending definition for exact durable resend and never exposes private causes',async()=>{const f=fixture(),r=await f.runtime(),states:unknown[]=[];r.subscribe(state=>{states.push(state);throw Error('observer');});await r.enqueue(f.intent);f.transport.create.mockRejectedValueOnce(Error('private body/token/path'));await expect(r.send()).rejects.toMatchObject({stage:'transport'});expect(r.snapshot).toMatchObject({retryAck:false,retryEnqueue:false,catalogFresh:false,data:{pending:1}});await r.send();expect(f.transport.create.mock.calls[0]![0]).toBe(f.transport.create.mock.calls[1]![0]);expect(JSON.stringify(states)).not.toContain('private body/token/path');await r.close();});
it.each(['enqueue','http','reload'] as const)('DB-SOURCE-WRITE-RUNTIME %s: busy and close exclude late work, clear private state and keep shared store open',async boundary=>{const f=fixture(),r=await f.runtime(),wait=deferred<unknown>();await r.enqueue(f.intent);if(boundary==='enqueue')f.enqueue.mockImplementationOnce(async()=>{await wait.promise;});if(boundary==='http')f.transport.create.mockImplementationOnce(()=>wait.promise);if(boundary==='reload')f.load.mockImplementationOnce(async()=>{await wait.promise;return{context:f.context,pending:0,operations:[],nextAfter:null};});const work=boundary==='enqueue'?r.enqueue({...f.intent,operationId:newId(),source:{...f.intent.source,id:newId()}}):boundary==='http'?r.send():r.reload();await expect.poll(()=>boundary==='enqueue'?f.enqueue.mock.calls.length-1:boundary==='http'?f.transport.create.mock.calls.length:f.load.mock.calls.length-2).toBe(1);await expect(r.reload()).rejects.toMatchObject({stage:'busy'});const closing=r.close();expect(r.snapshot).toMatchObject({phase:'closed',data:null,retryEnqueue:false,retryAck:false,catalogFresh:false});wait.resolve(f.reply);await expect(work).rejects.toMatchObject({stage:'closed'});await closing;expect(r.close()).toBe(closing);expect(f.close).not.toHaveBeenCalled();});
it('DB-SOURCE-WRITE-RUNTIME: lease/session/observer closure cannot start HTTP or recurse; opening failure preserves no fake empty catalog',async()=>{for(const kind of ['lease','session','observer'] as const){const f=fixture(),r=await f.runtime();if(kind==='lease')f.controller.abort();if(kind==='session')f.session.close();if(kind==='observer'){r.subscribe(state=>{if(state.busy||state.phase==='closed')void r.close();});await expect(r.send()).rejects.toMatchObject({stage:'closed'});}expect(r.snapshot.phase).toBe('closed');expect(f.transport.create).not.toHaveBeenCalled();await r.close();expect(f.close).not.toHaveBeenCalled();}const f=fixture();f.load.mockRejectedValueOnce(new NativeWorkspaceError('storage'));await expect(f.runtime()).rejects.toMatchObject({stage:'storage'});expect(f.session.signal.aborted).toBe(true);expect(f.close).not.toHaveBeenCalled();});
it('DB-SOURCE-WRITE-RUNTIME: malformed/foreign intent rejects before storage; retry without unknown intent rejects explicitly',async()=>{const f=fixture(),r=await f.runtime();for(const value of [{...f.intent,email:'private@example.invalid'},{...f.intent,source:{...f.intent.source,workspaceId:newId()}}])await expect(r.enqueue(value)).rejects.toMatchObject({stage:'protocol'});expect(f.enqueue).not.toHaveBeenCalled();await expect(r.retryEnqueue()).rejects.toMatchObject({stage:'protocol'});await expect(r.retryAck()).rejects.toMatchObject({stage:'protocol'});await r.close();});
