import {it,expect,vi} from 'vitest';
import {newId} from '@greiva/shared';
import {DatabaseChangesSyncSession,type DatabaseChangesStore,type PrivateWorkspaceConnection} from '@greiva/sync';
import {NativeWorkspaceStore,NativeWorkspaceError} from '../../apps/client/src/workspace/native-workspace-store.js';
import {PrivateDatabaseChangesSession} from '../../apps/client/src/workspace/private-database-changes-session.js';
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{promise,resolve};};
function fixture(){
 const controller=new AbortController(),context={issuer:'https://auth.fixture.invalid/auth/v1',subjectId:'owner',workspaceId:newId(),clientId:newId(),streamEpoch:newId()},source={id:newId(),workspaceId:context.workspaceId,name:'DB',schemaVersion:1,properties:[{id:newId(),type:'name',name:'Name'}]},epoch=newId(),initial={context,sourceId:source.id,schemaVersion:1,journalEpoch:null,order:'0',cursor:null,headOrder:'0',hasMore:false,received:false};let saved:unknown=structuredClone(initial);
 const response=()=>{const after=(saved as typeof initial).order,read=String(BigInt(after)<3n?BigInt(after)+1n:BigInt(after));return{protocolVersion:1,workspaceId:context.workspaceId,workspaceEpoch:context.streamEpoch,clientId:context.clientId,sourceId:source.id,schemaVersion:1,journalEpoch:epoch,afterOrder:after,readOrder:read,headOrder:'3',events:[],hasMore:BigInt(read)<3n,cursor:'cursor-'+read};};
 const transport={pull:vi.fn(async(..._args:unknown[]):Promise<unknown>=>response())},cache={load:vi.fn(async()=>saved),receive:vi.fn<DatabaseChangesStore['receive']>(async(_request,reply)=>{saved={...initial,journalEpoch:reply.journalEpoch,order:reply.readOrder,cursor:reply.cursor,headOrder:reply.headOrder,hasMore:reply.hasMore,received:true};})},session=new DatabaseChangesSyncSession(context,source,{transport,store:cache});
 const connection={generationSignal:controller.signal} as unknown as PrivateWorkspaceConnection,assertConnection=vi.fn((candidate:PrivateWorkspaceConnection)=>{if(candidate!==connection||controller.signal.aborted)throw new NativeWorkspaceError('closed');}),open=vi.fn(async(id:string)=>{if(id!==source.id)throw new NativeWorkspaceError('protocol');return session;}),close=vi.fn(async()=>{}),store={assertConnection,databaseChanges:open,close} as unknown as NativeWorkspaceStore;
 return{controller,context,source,epoch,initial,response,transport,cache,session,connection,store,open,close,assertConnection,setSaved:(value:unknown)=>{saved=structuredClone(value);},runtime:()=>PrivateDatabaseChangesSession.open(connection,store,source.id)};
}
it('DB-CHANGES-RUNTIME: local opening/reload stay unreceived and send no HTTP; each explicit sync consumes one bounded window and head is an observation',async()=>{const f=fixture(),runtime=await f.runtime();expect(runtime.snapshot).toMatchObject({phase:'ready',busy:false,data:f.initial,observedHead:false});expect(f.transport.pull).not.toHaveBeenCalled();await runtime.reload();expect(f.transport.pull).not.toHaveBeenCalled();await runtime.sync();expect(runtime.snapshot).toMatchObject({data:{order:'1',hasMore:true},observedHead:false});expect(f.transport.pull.mock.calls[0]![0]).toMatchObject({limit:100,cursor:null});expect(f.transport.pull).toHaveBeenCalledTimes(1);await runtime.sync();expect(runtime.snapshot.data?.order).toBe('2');await runtime.sync();expect(runtime.snapshot).toMatchObject({data:{order:'3',hasMore:false},observedHead:true});await runtime.reload();expect(runtime.snapshot.observedHead).toBe(false);expect(f.transport.pull).toHaveBeenCalledTimes(3);await runtime.close();expect(runtime.snapshot).toMatchObject({phase:'closed',data:null,observedHead:false});expect(f.close).not.toHaveBeenCalled();});
it('DB-CHANGES-RUNTIME: result unknown blocks a new pull, local reload keeps retry pending and exact retry restores latest progress without network',async()=>{const f=fixture(),runtime=await f.runtime(),receive=f.cache.receive.getMockImplementation()!;f.cache.receive.mockImplementationOnce(async(...args)=>{await receive(...args);throw Error('private body/token/path');});await expect(runtime.sync()).rejects.toThrow('Private database changes storage');expect(runtime.snapshot).toMatchObject({error:'storage',retryReceive:true,observedHead:false});await expect(runtime.sync()).rejects.toMatchObject({stage:'busy'});await runtime.reload();expect(runtime.snapshot).toMatchObject({data:{order:'1'},retryReceive:true,observedHead:false});f.setSaved({...f.initial,journalEpoch:f.epoch,order:'3',cursor:'cursor-3',headOrder:'3',hasMore:false,received:true});f.cache.receive.mockImplementationOnce(async()=>{});await runtime.retryReceive();expect(runtime.snapshot).toMatchObject({data:{order:'3'},error:null,retryReceive:false,observedHead:true});expect(f.transport.pull).toHaveBeenCalledTimes(1);expect(f.cache.receive.mock.calls[0]).toEqual(f.cache.receive.mock.calls[1]);await runtime.close();});
it.each(['transport','storage','protocol'] as const)('DB-CHANGES-RUNTIME %s: local state remains visible on failure; observers never receive private causes',async failure=>{const f=fixture(),runtime=await f.runtime(),states:unknown[]=[];runtime.subscribe(state=>{states.push(state);throw Error('observer');});if(failure==='transport')f.transport.pull.mockRejectedValueOnce(Error('private body/token/path'));if(failure==='storage')f.cache.load.mockRejectedValueOnce(Error('private body/token/path'));if(failure==='protocol')f.transport.pull.mockResolvedValueOnce({...f.response(),sourceId:newId()});await expect(runtime.sync()).rejects.toMatchObject({stage:failure});expect(runtime.snapshot).toMatchObject({data:f.initial,error:failure,retryReceive:false,observedHead:false});expect(JSON.stringify(states)).not.toContain('private body/token/path');await runtime.sync();expect(runtime.snapshot.error).toBeNull();await runtime.close();});
it.each(['http','receive','reload'] as const)('DB-CHANGES-RUNTIME %s: busy and close discard late result, clear private state and leave shared store open',async boundary=>{const f=fixture(),runtime=await f.runtime(),wait=deferred<unknown>();if(boundary==='http')f.transport.pull.mockImplementationOnce(()=>wait.promise);if(boundary==='receive')f.cache.receive.mockImplementationOnce(async()=>{await wait.promise;});if(boundary==='reload')f.cache.load.mockImplementationOnce(()=>wait.promise);const work=boundary==='reload'?runtime.reload():runtime.sync();await expect.poll(()=>boundary==='http'?f.transport.pull.mock.calls.length:boundary==='receive'?f.cache.receive.mock.calls.length:f.cache.load.mock.calls.length-1).toBe(1);await expect(runtime.reload()).rejects.toMatchObject({stage:'busy'});const closing=runtime.close();expect(runtime.snapshot).toMatchObject({phase:'closed',data:null,busy:false,retryReceive:false});wait.resolve(boundary==='http'?f.response():f.initial);await expect(work).rejects.toMatchObject({stage:'closed'});await closing;expect(f.close).not.toHaveBeenCalled();await expect(runtime.sync()).rejects.toMatchObject({stage:'closed'});expect(runtime.close()).toBe(closing);});
it('DB-CHANGES-RUNTIME: generation/session closure cancels runtime and listener-initiated close cannot start HTTP or recurse',async()=>{for(const kind of ['lease','session','observer'] as const){const f=fixture(),runtime=await f.runtime();if(kind==='lease')f.controller.abort();if(kind==='session')f.session.close();if(kind==='observer'){runtime.subscribe(state=>{if(state.busy||state.phase==='closed')void runtime.close();});await expect(runtime.sync()).rejects.toMatchObject({stage:'closed'});}expect(runtime.snapshot.phase).toBe('closed');expect(runtime.snapshot.data).toBeNull();expect(f.transport.pull).not.toHaveBeenCalled();await runtime.close();expect(f.close).not.toHaveBeenCalled();}});
it('DB-CHANGES-RUNTIME: opening failure closes only its session and preserves no fake empty state',async()=>{const f=fixture();f.cache.load.mockRejectedValueOnce(Error('private'));await expect(f.runtime()).rejects.toThrow('Private database changes storage');expect(f.session.signal.aborted).toBe(true);expect(f.close).not.toHaveBeenCalled();const other=fixture();await expect(PrivateDatabaseChangesSession.open(other.connection,other.store,newId())).rejects.toMatchObject({stage:'protocol'});expect(other.session.signal.aborted).toBe(false);expect(other.transport.pull).not.toHaveBeenCalled();});
it('DB-CHANGES-RUNTIME: retry without an unknown pair fails explicitly and successful observed data stays frozen',async()=>{const f=fixture(),runtime=await f.runtime();await expect(runtime.retryReceive()).rejects.toMatchObject({stage:'protocol'});expect(runtime.snapshot).toMatchObject({error:'protocol',observedHead:false});await runtime.sync();expect(Object.isFrozen(runtime.snapshot.data)).toBe(true);expect(Object.isFrozen(runtime.snapshot.data?.context)).toBe(true);const states:unknown[]=[];const detach=runtime.subscribe(state=>states.push(state));detach();const count=states.length;await runtime.reload();expect(states).toHaveLength(count);await runtime.close();});
