import {it,expect} from 'vitest';
import {newId} from '@greiva/shared';
import {privateDatabaseRecordCatalogRequestSchema,privateDatabaseRecordCatalogResponseSchema,privateDatabaseRecordHeaderSchema} from '@greiva/protocol/private-database-record-catalog';
import {databaseRecordCatalogCursor} from '../../apps/api/src/private-database-record-catalog-cursor.js';
import {databaseSourceCursor} from '../../apps/api/src/private-database-source-cursor.js';
function fixture(){const scope={protocolVersion:1,workspaceId:newId(),workspaceEpoch:newId(),clientId:newId(),sourceId:newId(),schemaVersion:1},header={id:newId(),workspaceId:scope.workspaceId,sourceId:scope.sourceId,pageId:newId(),version:1,creationOrder:'9007199254740993'},key=new Uint8Array(32).fill(7),cursor=databaseRecordCatalogCursor(scope.workspaceId,scope.workspaceEpoch,scope.clientId,scope.sourceId,key);return{scope,header,key,cursor};}
it('DB-RECORD-CATALOG-WIRE: bounded request and small header do not accept values or a second title',()=>{const f=fixture();expect(privateDatabaseRecordCatalogRequestSchema.parse({protocolVersion:1,clientId:f.scope.clientId})).toMatchObject({cursor:null,limit:50});for(const limit of [0,101,1.5])expect(privateDatabaseRecordCatalogRequestSchema.safeParse({protocolVersion:1,clientId:f.scope.clientId,limit}).success).toBe(false);expect(privateDatabaseRecordHeaderSchema.parse(f.header)).toEqual(f.header);for(const header of [{...f.header,values:{}},{...f.header,title:'body'},{...f.header,creationOrder:'0'},{...f.header,id:'ABCDEFAB-CDEF-7123-8123-ABCDEFABCDEF'}])expect(privateDatabaseRecordHeaderSchema.safeParse(header).success).toBe(false);});
it('DB-RECORD-CATALOG-WIRE: exact bigint progress allows filtered empty windows and rejects duplicate/mixed bindings',()=>{const f=fixture(),reply={...f.scope,afterOrder:'9007199254740992',throughOrder:f.header.creationOrder,headOrder:'9007199254740994',records:[f.header],hasMore:true,cursor:'opaque'};expect(privateDatabaseRecordCatalogResponseSchema.parse(reply)).toEqual(reply);expect(privateDatabaseRecordCatalogResponseSchema.parse({...reply,records:[]})).toMatchObject({hasMore:true});for(const value of [{...reply,throughOrder:reply.afterOrder},{...reply,cursor:null},{...reply,records:[f.header,f.header]},{...reply,records:[{...f.header,sourceId:newId()}]},{...reply,records:[{...f.header,creationOrder:'9007199254740995'}]}])expect(privateDatabaseRecordCatalogResponseSchema.safeParse(value).success).toBe(false);});
it('DB-RECORD-CURSOR: fixes the observed head and binds workspace/epoch/device/Source/purpose/key',()=>{const f=fixture(),token=f.cursor.encode('9007199254740993','9007199254740994');expect(f.cursor.decode(token,'9007199254740995')).toEqual({after:'9007199254740993',head:'9007199254740994'});expect(f.cursor.decode(null,'10')).toEqual({after:'0',head:'10'});for(const cursor of [databaseRecordCatalogCursor(newId(),f.scope.workspaceEpoch,f.scope.clientId,f.scope.sourceId,f.key),databaseRecordCatalogCursor(f.scope.workspaceId,newId(),f.scope.clientId,f.scope.sourceId,f.key),databaseRecordCatalogCursor(f.scope.workspaceId,f.scope.workspaceEpoch,newId(),f.scope.sourceId,f.key),databaseRecordCatalogCursor(f.scope.workspaceId,f.scope.workspaceEpoch,f.scope.clientId,newId(),f.key),databaseRecordCatalogCursor(f.scope.workspaceId,f.scope.workspaceEpoch,f.scope.clientId,f.scope.sourceId,new Uint8Array(32).fill(8))])expect(()=>cursor.decode(token,'9007199254740994')).toThrow();expect(()=>f.cursor.decode(databaseSourceCursor(f.scope.workspaceId,f.scope.workspaceEpoch,f.scope.clientId,f.key).encode('0','1'),'1')).toThrow();f.key.fill(0);expect(f.cursor.decode(token,'9007199254740994').after).toBe('9007199254740993');});
it('DB-RECORD-CURSOR: malformed/noncanonical/tampered/future range cannot advance',()=>{const f=fixture(),valid=f.cursor.encode('1','2');for(const value of [undefined,{},valid+'x',valid.replace('gdr1','gds1'),'gdr1.a.b',valid.split('.').slice(0,2).join('.')+'.'+valid.split('.')[2]+'=', 'x'.repeat(1025)])expect(()=>f.cursor.decode(value,'2')).toThrow();expect(()=>f.cursor.decode(valid,'1')).toThrow();expect(()=>f.cursor.encode('2','1')).toThrow();});
