import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
import {createInterface} from 'node:readline';
import assert from 'node:assert/strict';
import * as Y from '/workspace/node_modules/yjs/dist/yjs.mjs';
import {v7} from '/workspace/node_modules/uuid/dist/index.js';
const directory='/tmp/native-release-seeded';mkdirSync(directory,{recursive:true});
const child=spawn('/workspace/.data/native-target/debug/examples/store-driver',[directory+'/greiva.sqlite']);
const replies=new Map();let sequence=0;let stderr='';child.stderr.on('data',data=>stderr+=data);createInterface({input:child.stdout}).on('line',line=>{const reply=JSON.parse(line),pending=replies.get(reply.id);replies.delete(reply.id);if(reply.error)pending.reject(Error(reply.error));else pending.resolve(reply.value);});
function rpc(command,fields={}){const id=++sequence;return new Promise((resolve,reject)=>{replies.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,command,...fields})+'\n');});}
const pageId='01a10230-0000-7000-8000-000000000001';const doc=new Y.Doc();const fragment=doc.getXmlFragment('body');const page=await rpc('load',{pageId});for(const update of page.updates)Y.applyUpdate(doc,Uint8Array.from(update));fragment.delete(0,fragment.length);await rpc('append',{pageId,update:Array.from(Y.encodeStateAsUpdate(doc))});let update;doc.on('update',value=>update=value);const started=performance.now();const rows=[];
for(let i=0;i<1000;i++){const row=`Block ${String(i).padStart(4,'0')} — saved content ${i}`;rows.push(row);const paragraph=new Y.XmlElement('paragraph'),leaf=new Y.XmlText();leaf.insert(0,row);paragraph.insert(0,[leaf]);fragment.push([paragraph]);await rpc('append',{pageId,update:Array.from(update)});}
await rpc('title',{pageId,title:'WIN611-RELEASE1000'});const pageSeedMs=performance.now()-started;const clientId=await rpc('structured-client-id',{candidate:v7()});const tasks=[],operations=[];const queueStarted=performance.now();
for(let i=0;i<250;i++){const id=v7();tasks.push({id,title:`BENCH611 edited task ${i}`,status:'done',due:'2028-02-29',version:4});for(const [kind,payload,baseVersion] of [['create',{title:`BENCH611 task ${i}`,status:'todo',due:null},null],['update',{status:'in_progress'},0],['update',{title:`BENCH611 edited task ${i}`,due:'2028-02-29'},0],['update',{status:'done'},0]]){const operation={operationId:v7(),clientId,entityId:id,entityType:'task',kind,payload,baseVersion};await rpc('structured-mutate',{operation});operations.push(operation);}}
const snapshot=await rpc('structured-snapshot');assert.equal(snapshot.operations.length,1000);assert.ok(snapshot.operations.every(op=>op.status==='pending'));assert.equal(snapshot.tasks.length,250);
writeFileSync('/tmp/native-release-seed.json',JSON.stringify({at:new Date().toISOString(),pageId,clientId,blocks:1000,pageSeedMs,queueSeedMs:performance.now()-queueStarted,rows,bodyXml:fragment.toString(),clocks:Array.from(Y.decodeStateVector(Y.encodeStateVector(doc))).sort(([a],[b])=>a-b),tasks,operations,snapshot,scope:'Dataset seeded through actual Rust repository in Docker, not native UI input. Subsequent runtime is normal Windows release with no hooks.'},null,2)+'\n');child.stdin.end();await new Promise((resolve,reject)=>child.on('exit',code=>code===0?resolve():reject(Error(stderr))));doc.destroy();console.log(JSON.stringify({blocks:1000,pending:1000,tasks:250,pageSeedMs}));
