// Docker audit of a stopped normal Windows release and its actual HTTP proxy responses.
import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,cpSync} from 'node:fs';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import * as Y from '/workspace/node_modules/yjs/dist/yjs.mjs';import pg from '/workspace/node_modules/pg/lib/index.js';
import {v7} from '/workspace/node_modules/uuid/dist/index.js';
import {StructuredDevice} from '/workspace/tests/support/structured-device.ts';import {StructuredSyncEngine,httpStructuredTransport} from '/workspace/packages/sync/dist/index.js';import {HocuspocusProvider} from '/workspace/node_modules/@hocuspocus/provider/dist/hocuspocus-provider.esm.js';
const seed=JSON.parse(readFileSync('/tmp/native-release-seed-audit.json','utf8')),input=JSON.parse(readFileSync('/tmp/native-release-input.json','utf8'));const sha=value=>createHash('sha256').update(value).digest('hex');
const db=new DatabaseSync('/tmp/native-release-final-copy/greiva.sqlite',{readOnly:true}),doc=new Y.Doc();let operations,receipts,updates;try{
 assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');updates=db.prepare('SELECT seq,update_bytes,digest FROM page_updates WHERE page_id=? ORDER BY seq').all(seed.pageId);
 for(const update of updates){assert.equal(sha(update.update_bytes),Buffer.from(update.digest).toString('hex'));Y.applyUpdate(doc,update.update_bytes);}
 operations=db.prepare('SELECT * FROM sync_operations ORDER BY seq').all();receipts=db.prepare('SELECT * FROM structured_received ORDER BY server_order').all();
}finally{db.close();}
const bodyXml=doc.getXmlFragment('body').toString(),rows=doc.getXmlFragment('body').toArray().map(p=>p.toArray().map(n=>n.toString()).join(''));
assert.equal(rows.length,1000);assert.equal(rows[0],seed.rows[0]+input.text);assert.deepEqual(rows.slice(1),seed.rows.slice(1));
cpSync('/tmp/native-release-final-copy','/tmp/native-release-final-rust',{recursive:true});const load=spawnSync('.data/native-target/debug/examples/store-driver',['/tmp/native-release-final-rust/greiva.sqlite'],{input:JSON.stringify({id:1,command:'structured-snapshot'})+'\n',encoding:'utf8',maxBuffer:16*1024*1024});assert.equal(load.status,0,load.stderr);const native=JSON.parse(load.stdout.trim()).value;
assert.equal(native.operations.length,1000);assert.ok(native.operations.every(o=>o.status==='acknowledged'));assert.equal(native.errors.length,0);assert.equal(native.state.cursor,native.state.headCursor);
assert.deepEqual(native.operations.map(o=>o.operationId),seed.operations.map(o=>o.operationId));
const ids=new Set(seed.tasks.map(t=>t.id)),bench=native.tasks.filter(t=>ids.has(t.id)).map(({id,title,status,due,version})=>({id,title,status,due,version}));assert.deepEqual(bench.sort((a,b)=>a.id.localeCompare(b.id)),seed.tasks.sort((a,b)=>a.id.localeCompare(b.id)));
const trace=readFileSync('/tmp/native-release-proxy.jsonl','utf8').trim().split('\n').map(JSON.parse),operationIds=new Set(seed.operations.map(o=>o.operationId));
const pushes=trace.filter(r=>r.path==='/sync/push'&&r.event==='upstream-response'&&r.request?.operations?.some(o=>operationIds.has(o.operationId)));
assert.equal(pushes.length,1000);assert.equal(new Set(pushes.flatMap(r=>r.request.operations.map(o=>o.operationId))).size,1000);assert.ok(pushes.every(r=>r.status===200&&r.body.results.length===1&&r.body.results[0].status==='acknowledged'));
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});let ledger;try{ledger=(await pool.query('SELECT server_order::text,operation_id,request,result FROM greiva_native_20261003_0611.server_operations ORDER BY server_order')).rows;assert.equal(ledger.length,1009);assert.equal(receipts.length,1009);for(const op of operations){const row=ledger.find(r=>r.operation_id===op.operation_id);assert.deepEqual(row.request,JSON.parse(op.prepared_wire));assert.deepEqual(row.result,JSON.parse(op.local_result));assert.deepEqual(row.result,JSON.parse(receipts.find(r=>r.operation_id===op.operation_id).result));}}finally{await pool.end();}
async function until(predicate){const end=Date.now()+30000;while(!predicate()){if(Date.now()>end)throw Error('Independent peer convergence timed out');await new Promise(done=>setTimeout(done,50));}}
const device=new StructuredDevice('/tmp/native-release-independent-peer.sqlite');let report;const engine=new StructuredSyncEngine(device,httpStructuredTransport('http://greiva-native-network-0611:3000'),r=>report=r,{pollMs:10000});let peer;
try{engine.start();await until(()=>report?.phase==='synced');engine.stop();peer=await device.snapshot();assert.deepEqual(peer.tasks,native.tasks);assert.deepEqual(peer.relations,native.relations);assert.deepEqual(peer.conflicts,native.conflicts);assert.equal(peer.state.cursor,native.state.cursor);}finally{engine.stop();await device.close();}
const peerDoc=new Y.Doc(),provider=new HocuspocusProvider({url:'ws://greiva-native-network-0611:1234?clientId='+v7(),name:'page:'+seed.pageId,document:peerDoc});const clocks=Array.from(Y.decodeStateVector(Y.encodeStateVector(doc))).sort(([a],[b])=>a-b);try{await until(()=>provider.isSynced&&peerDoc.getXmlFragment('body').toString()===bodyXml);assert.deepEqual(Array.from(Y.decodeStateVector(Y.encodeStateVector(peerDoc))).sort(([a],[b])=>a-b),clocks);}finally{provider.destroy();peerDoc.destroy();doc.destroy();}
const verification={at:new Date().toISOString(),result:'Pass',product:'0.6.11',blocks:rows.length,typedCharacters:input.characters,allSeededTextPreserved:true,allUpdateDigestsVerified:true,pageUpdates:updates.map(u=>({seq:u.seq,bytes:u.update_bytes.length,sha256:sha(u.update_bytes)})),bodyXml,clocks,nativeOperations:1000,acknowledged:1000,receipts:receipts.length,ledger:ledger.length,benchTasks:bench,cursor:native.state.cursor,headCursor:native.state.headCursor,peerTasksRelationsConflictsAndCursorMatch:true,pagePeerMatches:true,queueResponses:{firstAt:pushes[0].at,lastAt:pushes.at(-1).at,responseSpanMs:Date.parse(pushes.at(-1).at)-Date.parse(pushes[0].at),count:1000,unique:1000,scope:'First-to-last server response span, excludes time to first request and final native ACK commit. Not a native SLO.'},operationEvidence:operations.map(o=>({operationId:o.operation_id,preparedWireSha256:sha(o.prepared_wire),localResultSha256:sha(o.local_result)})),scope:'Normal Windows release native IPC engine pushed 1000 operations. Actual Rust seed/audit in Docker; no batch shortcut. Native input was literal text, not real Microsoft IME or per-key frame measurement.'};writeFileSync('/tmp/native-release-verification.json',JSON.stringify(verification,null,2)+'\n');writeFileSync('/tmp/native-release-selected-proxy.jsonl',pushes.map(r=>JSON.stringify(r)).join('\n')+'\n');console.log(JSON.stringify({...verification,pageUpdates:verification.pageUpdates.length,bodyXml:undefined,clocks:undefined,benchTasks:bench.length,operationEvidence:undefined}));
